/**
 * Deterministic Wave 4 risk evidence fixtures — no live network in CI.
 */

import type { BusinessIdentityEvidence, DigitalRiskEvidence } from './models.ts';

export const FIXTURE_BUSINESSES: readonly BusinessIdentityEvidence[] = Object.freeze([
  {
    evidenceId: 'kyb-ev:us:0000320193',
    entityId: 'sunrey:company:us:0000320193',
    legalName: 'Apple Inc.',
    tradingName: null,
    registrationNumber: '0000320193',
    jurisdiction: 'US',
    status: 'ACTIVE',
    providerNativeStatus: 'Active',
    incorporationDate: '1977-01-03',
    entityType: 'Corporation',
    registeredAddress: Object.freeze({
      line1: 'One Apple Park Way',
      city: 'Cupertino',
      region: 'CA',
      postalCode: '95014',
      country: 'US',
    }),
    officers: Object.freeze([
      Object.freeze({ name: 'Tim Cook', role: 'CEO', appointedDate: '2011-08-24' }),
    ]),
    providerId: 'sec-edgar',
    providerRecordId: '320193',
    retrievedAt: '2026-08-30T12:00:00.000Z',
    sourceUpdatedAt: '2025-11-01T16:30:00.000Z',
    freshness: 'FRESH',
    confidence: 0.95,
    authorityClass: 'authoritative_official',
    provenance: 'fixture:sec-edgar:company-profile',
  },
  {
    evidenceId: 'kyb-ev:gb:12345678',
    entityId: 'sunrey:company:gb:12345678',
    legalName: 'ABC Holdings Ltd',
    tradingName: null,
    registrationNumber: '12345678',
    jurisdiction: 'GB',
    status: 'ACTIVE',
    providerNativeStatus: 'Active',
    incorporationDate: '2010-03-15',
    entityType: 'Private Limited Company',
    registeredAddress: Object.freeze({
      line1: '1 Example Street',
      city: 'London',
      region: null,
      postalCode: 'EC1A 1BB',
      country: 'GB',
    }),
    officers: Object.freeze([
      Object.freeze({ name: 'Jane Director', role: 'Director', appointedDate: '2010-03-15' }),
    ]),
    providerId: 'fixture-identity',
    providerRecordId: 'gb-12345678',
    retrievedAt: '2026-08-30T12:00:00.000Z',
    sourceUpdatedAt: '2026-06-01T00:00:00.000Z',
    freshness: 'FRESH',
    confidence: 0.88,
    authorityClass: 'regulated_provider',
    provenance: 'fixture:fixture-identity:kyb',
  },
  {
    evidenceId: 'kyb-ev:us:99999999',
    entityId: 'sunrey:company:us:99999999',
    legalName: 'ABC Holdings Ltd',
    tradingName: null,
    registrationNumber: '99999999',
    jurisdiction: 'US',
    status: 'DISSOLVED',
    providerNativeStatus: 'Dissolved',
    incorporationDate: '2005-01-01',
    entityType: 'LLC',
    registeredAddress: null,
    officers: Object.freeze([]),
    providerId: 'fixture-identity',
    providerRecordId: 'us-99999999',
    retrievedAt: '2026-08-30T12:00:00.000Z',
    sourceUpdatedAt: '2024-12-31T00:00:00.000Z',
    freshness: 'STALE',
    confidence: 0.75,
    authorityClass: 'regulated_provider',
    provenance: 'fixture:fixture-identity:kyb-dissolved',
  },
]);

export const FIXTURE_DIGITAL_RISK: readonly DigitalRiskEvidence[] = Object.freeze([
  {
    evidenceId: 'dr-ev:ip:clean',
    sessionId: 'sess_clean',
    deviceId: 'dev_known',
    userId: 'usr_1',
    riskType: 'IP_REPUTATION',
    riskScore: 12,
    confidence: 0.9,
    providerId: 'fixture-aml',
    providerNativeClassification: 'low_risk',
    observedAt: '2026-08-30T12:00:00.000Z',
    retrievedAt: '2026-08-30T12:00:00.000Z',
    freshness: 'FRESH',
    provenance: 'fixture:fixture-aml:ip-reputation',
    ipIntelligence: Object.freeze({
      ip: null,
      asn: 'AS7922',
      isp: 'Example ISP',
      country: 'GB',
      proxy: false,
      vpn: false,
      tor: false,
      hosting: false,
      abuseFlags: Object.freeze([]),
    }),
    emailReputation: null,
  },
  {
    evidenceId: 'dr-ev:ip:vpn',
    sessionId: 'sess_vpn',
    deviceId: 'dev_new',
    userId: 'usr_2',
    riskType: 'VPN',
    riskScore: 55,
    confidence: 0.85,
    providerId: 'fixture-aml',
    providerNativeClassification: 'vpn_detected',
    observedAt: '2026-08-30T12:00:00.000Z',
    retrievedAt: '2026-08-30T12:00:00.000Z',
    freshness: 'FRESH',
    provenance: 'fixture:fixture-aml:vpn',
    ipIntelligence: Object.freeze({
      ip: null,
      asn: 'AS9009',
      isp: 'VPN Provider',
      country: 'NL',
      proxy: false,
      vpn: true,
      tor: false,
      hosting: false,
      abuseFlags: Object.freeze(['VPN_EXIT']),
    }),
    emailReputation: null,
  },
  {
    evidenceId: 'dr-ev:ip:tor',
    sessionId: 'sess_tor',
    deviceId: null,
    userId: 'usr_3',
    riskType: 'TOR',
    riskScore: 72,
    confidence: 0.92,
    providerId: 'fixture-aml',
    providerNativeClassification: 'tor_exit',
    observedAt: '2026-08-30T12:00:00.000Z',
    retrievedAt: '2026-08-30T12:00:00.000Z',
    freshness: 'FRESH',
    provenance: 'fixture:fixture-aml:tor',
    ipIntelligence: Object.freeze({
      ip: null,
      asn: null,
      isp: null,
      country: null,
      proxy: false,
      vpn: false,
      tor: true,
      hosting: false,
      abuseFlags: Object.freeze(['TOR_EXIT_NODE']),
    }),
    emailReputation: null,
  },
  {
    evidenceId: 'dr-ev:ip:proxy',
    sessionId: 'sess_proxy',
    deviceId: 'dev_proxy',
    userId: 'usr_4',
    riskType: 'PROXY',
    riskScore: 48,
    confidence: 0.8,
    providerId: 'fixture-aml',
    providerNativeClassification: 'proxy_detected',
    observedAt: '2026-08-30T12:00:00.000Z',
    retrievedAt: '2026-08-30T12:00:00.000Z',
    freshness: 'FRESH',
    provenance: 'fixture:fixture-aml:proxy',
    ipIntelligence: Object.freeze({
      ip: null,
      asn: 'AS12345',
      isp: 'Hosting Co',
      country: 'US',
      proxy: true,
      vpn: false,
      tor: false,
      hosting: true,
      abuseFlags: Object.freeze(['DATACENTER_PROXY']),
    }),
    emailReputation: null,
  },
  {
    evidenceId: 'dr-ev:email:suspicious',
    sessionId: 'sess_email',
    deviceId: null,
    userId: 'usr_5',
    riskType: 'EMAIL_REPUTATION',
    riskScore: 68,
    confidence: 0.77,
    providerId: 'fixture-aml',
    providerNativeClassification: 'suspicious',
    observedAt: '2026-08-30T12:00:00.000Z',
    retrievedAt: '2026-08-30T12:00:00.000Z',
    freshness: 'FRESH',
    provenance: 'fixture:fixture-aml:email-reputation',
    ipIntelligence: null,
    emailReputation: Object.freeze({
      reputation: 'SUSPICIOUS',
      suspicious: true,
      references: 2,
      domainAgeDays: 14,
      disposable: false,
      breachMetadata: Object.freeze(['credential_stuffing_list']),
    }),
  },
  {
    evidenceId: 'dr-ev:location:anomaly',
    sessionId: 'sess_travel',
    deviceId: 'dev_travel',
    userId: 'usr_6',
    riskType: 'LOCATION_ANOMALY',
    riskScore: 80,
    confidence: 0.7,
    providerId: 'fixture-aml',
    providerNativeClassification: 'impossible_travel',
    observedAt: '2026-08-30T12:00:00.000Z',
    retrievedAt: '2026-08-30T12:00:00.000Z',
    freshness: 'FRESH',
    provenance: 'fixture:fixture-aml:location-anomaly',
    ipIntelligence: Object.freeze({
      ip: null,
      asn: null,
      isp: null,
      country: 'JP',
      proxy: false,
      vpn: false,
      tor: false,
      hosting: false,
      abuseFlags: Object.freeze(['IMPOSSIBLE_TRAVEL']),
    }),
    emailReputation: null,
  },
]);

export const TIMEOUT_PROVIDER = 'fixture-risk-timeout';
export const RATE_LIMIT_PROVIDER = 'fixture-risk-rate-limit';
