export const HUMAN_CONTRIBUTION_ISOLATION = Object.freeze({
  owner: 'packages/human-economic-contribution',
  capability: 'sunrey-human-economic-contributions',
  boundedContext: 'HUMAN_ECONOMIC_CONTRIBUTION',
  financialStateMutation: false,
  executionAuthorityRequired: false,
  kernelAuthorizationRequired: false,
  valuationImplemented: false,
  valuationConstitutionImplemented: true,
  valuationEngineComputesSettlement: false,
  mintingImplemented: false,
  peveIsNotContributionValue: true,
  measurementIsNotSunReyQuantity: true,
  contributionIsNotHumanWorth: true,
  productionActivated: false,
  productionValuationActivated: false,
  forbiddenCompetingPackages: Object.freeze([
    'packages/human-contribution',
    'packages/human-economic-contribution-v2',
    'packages/contribution-ontology',
    'packages/human-worth',
    'packages/contribution-valuation',
    'packages/human-contribution-score',
    'packages/sunrey-contribution',
    'packages/human-contribution-registry',
    'packages/contribution-registry',
    'packages/human-economic-contribution-registry',
    'packages/human-valuation-engine',
    'packages/human-valuation',
    'packages/human-contribution-verification',
    'packages/contribution-verification',
  ]),
  mustNotImport: Object.freeze([
    'packages/kernel',
    'packages/permissions',
    'packages/ledger',
    'packages/sunrey-coin',
    'packages/platform',
    'packages/personal-economic-graph',
    'packages/information-market',
    'packages/consent',
    'packages/clean-room',
    'packages/personal-data-vault',
    'packages/sunrey-chain',
    'services/',
  ]),
});
