export const SURVEILLANCE_ALERT_KINDS = [
  'SELF_TRADING',
  'WASH_TRADING_PATTERN',
  'SPOOFING_CANDIDATE',
  'LAYERING_CANDIDATE',
  'ABNORMAL_VOLUME',
  'ORDER_CANCEL_BURST',
  'PRICE_DISLOCATION',
  'COORDINATED_ACCOUNTS_CANDIDATE',
  'CIRCULAR_TRADING_CANDIDATE',
  'ARTIFICIAL_CAPACITY_CANDIDATE',
  'DELIVERY_MANIPULATION_CANDIDATE',
  'ORACLE_CONCENTRATION_CANDIDATE',
  'REPEATED_NON_DELIVERY_CANDIDATE',
  'UNAUTHORIZED_PURPOSE_ATTEMPT',
  'CONSENT_MISMATCH_CANDIDATE',
  'REPEATED_DENIED_ACCESS',
] as const;
export type SurveillanceAlertKind = (typeof SURVEILLANCE_ALERT_KINDS)[number];

export const SURVEILLANCE_OUTPUT_CLASS = 'CANDIDATE_ALERT' as const;

export const EVIDENCE_KIND_SURVEILLANCE = 'market-surveillance';
