export {
  AI_CAN_AUTHORIZE_PRODUCTION,
  BINDING_KEYS,
  CHUNK_71_REMAINS_MONETARY_AUTHORITY,
  ECONOMIC_ACTIVATION_BLOCKER_CODES,
  ECONOMIC_ACTIVATION_DOMAINS,
  ECONOMIC_ACTIVATION_LIVE_FLAGS_CHANGED,
  ECONOMIC_ACTIVATION_MONETARY_AUTHORITY_INVOKED,
  ECONOMIC_ACTIVATION_PRODUCTION_ACTIVATED,
  ECONOMIC_ACTIVATION_STATES,
  ECONOMIC_ACTOR_KINDS,
  ENGINEERING_EVIDENCE_IS_EXTERNAL_APPROVAL,
  PARAMETER_STATUSES,
  PRODUCTION_ECONOMIC_ACTIVATION_FIREWALL_ID,
  PRODUCTION_ECONOMIC_ACTIVATION_SCHEMA_VERSION,
  PRODUCTION_ECONOMIC_ACTIVATION_TOOL_VERSION,
  PRODUCTION_PARAMETER_IDS,
  REJECTED_PARAMETER_SOURCES,
  REQUIREMENT_EVIDENCE_CLASSES,
} from './types.ts';
export type {
  ActivationEvidenceRecord,
  ActivationRequirement,
  BindingKey,
  CoverageGapSnapshot,
  DomainActivationDecision,
  EconomicActivationBlockerCode,
  EconomicActivationDomain,
  EconomicActivationState,
  EconomicActorKind,
  ExternalSecurityEvidenceSnapshot,
  HinChainAnchorReadiness,
  HinProductionGates,
  HumanAuthorizationSlot,
  LegalRegulatoryEvidenceSnapshot,
  LiveFlagSnapshot,
  OracleProductionEvidenceSnapshot,
  PolicyBindingPair,
  ProductionEconomicActivationDecision,
  ProductionEconomicActivationManifest,
  ProductionEconomicActivationReadinessReport,
  ProductionEconomicActivationSnapshot,
  ProductionParameterId,
  ProductionParameterRecord,
  ProductionParameterStatus,
  RequirementEvaluation,
  RequirementEvidenceClass,
  SupplySafetySnapshot,
  VersionBinding,
} from './types.ts';
export * as parameterPackage from './parameter-package/index.ts';
export { ACTIVATION_REQUIREMENTS, DOMAIN_TO_MAINNET, requirementById, requirementsFor } from './requirements.ts';
export {
  FIXTURE_KINDS,
  actorLooksNonHuman,
  evidenceClassSatisfies,
  humanSlotSatisfied,
  isFixtureEvidence,
  isNonHumanActor,
  partitionEvidence,
} from './evidence.ts';
export type { FixtureKind } from './evidence.ts';
export {
  PARAMETER_MANIFEST_DOMAIN,
  classifyParameter,
  currentUnconfiguredParameters,
  overallParameterStatus,
  parameterConfigured,
  parameterManifestHash,
  parameterSourceRejected,
  unconfiguredParameter,
} from './parameters.ts';
export {
  MANIFEST_DOMAIN,
  activationManifestHash,
  bindingRejectedAsLatest,
  compatiblePair,
  incompatiblePair,
  manifestFromBindings,
  policyBindingStatus,
} from './bindings.ts';
export {
  ProductionEconomicActivationFirewall,
  domainState,
  evaluateProductionEconomicActivation,
  summarizeMissingEvidence,
} from './firewall.ts';
export {
  buildProductionEconomicActivationReadinessReport,
  formatReadinessReport,
  printDomainLine,
} from './report.ts';
export {
  AI_CAN_AUTHORIZE_PRODUCTION as INVARIANT_AI_CAN_AUTHORIZE_PRODUCTION,
  CHUNK_71_REMAINS_MONETARY_AUTHORITY as INVARIANT_CHUNK_71_REMAINS_MONETARY_AUTHORITY,
  ENGINEERING_EVIDENCE_IS_EXTERNAL_APPROVAL as INVARIANT_ENGINEERING_EVIDENCE_IS_EXTERNAL_APPROVAL,
  LIVE_FLAGS_CHANGED,
  MONETARY_AUTHORITY_INVOKED,
  PRODUCTION_ACTIVATED,
  PRODUCTION_PARAMETERS_CONFIGURED_ON_MAIN,
  compiledCapabilitiesRemainSafe,
  currentLiveFlags,
  liveFlagsRemainDisabled,
} from './invariants.ts';
export {
  PRODUCTION_ECONOMIC_SOURCE_ID,
  allConfiguredParameters,
  bindingKeysComplete,
  candidateReadySnapshot,
  configuredParameter,
  currentRepositoryBindings,
  currentRepositorySnapshot,
  humanSlot,
  simulationConversionParameter,
  withSnapshot,
  withUnconfigured,
} from './fixtures.ts';
