export const MANDATE_STATES = [
  'DRAFT',
  'AWAITING_CONFIRMATION',
  'ACTIVE',
  'PAUSED',
  'SUPERSEDED',
  'REVOKED',
  'EXPIRED',
] as const;

export type MandateState = (typeof MANDATE_STATES)[number];

export const MANDATE_GOAL_KINDS = [
  'BUILD_EMERGENCY_RESERVE',
  'REDUCE_DEBT',
  'SAVE_FOR_HOME',
  'INCREASE_MONTHLY_SURPLUS',
  'REDUCE_UNNECESSARY_FEES',
  'IMPROVE_REWARD_CAPTURE',
  'INVEST_ELIGIBLE_LONG_TERM_SURPLUS_LATER',
  'MAINTAIN_TARGET_LIQUIDITY',
  'AGGRESSIVE_SHORT_HORIZON_GROWTH',
  'OTHER',
] as const;

export type MandateGoalKind = (typeof MANDATE_GOAL_KINDS)[number];

export const MANDATE_GOAL_STATUSES = [
  'DRAFT',
  'CONFIRMED',
  'ACTIVE',
  'PAUSED',
  'ACHIEVED',
  'CANCELLED',
] as const;

export type MandateGoalStatus = (typeof MANDATE_GOAL_STATUSES)[number];

export const GOAL_SOURCES = ['PEG', 'USER', 'AGENT'] as const;
export type GoalSource = (typeof GOAL_SOURCES)[number];

export const USER_CONFIRMATION_STATES = ['UNCONFIRMED', 'CONFIRMED'] as const;
export type UserConfirmationState = (typeof USER_CONFIRMATION_STATES)[number];

export const HARD_CONSTRAINT_KINDS = [
  'MINIMUM_CASH_RESERVE',
  'PROTECTED_ACCOUNTS',
  'PROTECTED_CURRENCIES',
  'NEVER_SPEND_BELOW_LIQUIDITY_FLOOR',
  'MAXIMUM_SINGLE_PROPOSED_ACTION_AMOUNT',
  'MAXIMUM_MONTHLY_ACTION_BUDGET',
  'PROHIBITED_PRODUCT_CATEGORIES',
  'PROHIBITED_ASSET_CATEGORIES',
  'PROHIBITED_JURISDICTIONS',
  'REQUIRED_CONFIRMATION_THRESHOLD',
  'ALLOWED_PROPOSAL_CATEGORIES',
  'TIME_HORIZON',
  'RISK_PREFERENCE_METADATA',
  'DEBT_MINIMUM_OBLIGATIONS',
  'RECURRING_ESSENTIAL_OBLIGATIONS',
  'KEEP_ALL_LIQUID',
  'INVEST_ALL_AVAILABLE_IMMEDIATELY',
] as const;

export type HardConstraintKind = (typeof HARD_CONSTRAINT_KINDS)[number];

export const SOFT_PREFERENCE_KINDS = [
  'PREFER_LIQUIDITY',
  'PREFER_DEBT_REDUCTION',
  'PREFER_LOWER_FEES',
  'PREFER_SIMPLER_PLAN',
  'PREFER_FASTER_GOAL_ACHIEVEMENT',
  'PREFER_LOWER_VOLATILITY_LATER',
] as const;

export type SoftPreferenceKind = (typeof SOFT_PREFERENCE_KINDS)[number];

export const COMPILER_ERROR_CODES = [
  'INVALID_CURRENCY',
  'INVALID_LIMIT',
  'CONTRADICTORY_CONSTRAINTS',
  'IMPOSSIBLE_VALUE',
  'MISSING_GOALS',
  'EXPIRED_FACTS',
  'UNSUPPORTED_PRODUCT',
  'AMBIGUOUS_PERMISSIONS',
] as const;

export type CompilerErrorCode = (typeof COMPILER_ERROR_CODES)[number];
