/**
 * Evidence requirements per activation domain.
 * Missing evidence disables the row. No permissive defaults.
 */

import type { ActivationDomain } from '../types.ts';
import type { ScopeEvidenceClass, ScopeRequirement } from './types.ts';

function req(
  requirementId: string,
  activationDomain: ActivationDomain,
  evidenceClass: ScopeEvidenceClass,
  extra: Partial<Pick<ScopeRequirement, 'hinOnly' | 'productiveUseRight' | 'corridorEndpoint'>> = {},
): ScopeRequirement {
  return Object.freeze({
    requirementId,
    activationDomain,
    evidenceClass,
    blocking: true,
    ...extra,
  });
}

export const SCOPE_REQUIREMENTS: readonly ScopeRequirement[] = Object.freeze([
  req('SUNREY_CHAIN.LICENSE', 'SUNREY_CHAIN', 'LICENSE_OR_REGISTRATION'),
  req('SUNREY_CHAIN.COUNSEL', 'SUNREY_CHAIN', 'COUNSEL_OPINION'),
  req('SUNREY_CHAIN.REGULATORY', 'SUNREY_CHAIN', 'REGULATORY_APPROVAL'),
  req('SUNREY_CHAIN.HUMAN', 'SUNREY_CHAIN', 'HUMAN_AUTHORIZATION'),

  req('SUNREY_COIN.LICENSE', 'SUNREY_COIN_NATIVE_ASSET', 'LICENSE_OR_REGISTRATION'),
  req('SUNREY_COIN.COUNSEL', 'SUNREY_COIN_NATIVE_ASSET', 'COUNSEL_OPINION'),
  req('SUNREY_COIN.REGULATORY', 'SUNREY_COIN_NATIVE_ASSET', 'REGULATORY_APPROVAL'),
  req('SUNREY_COIN.HUMAN', 'SUNREY_COIN_NATIVE_ASSET', 'HUMAN_AUTHORIZATION'),

  req('MOONREY_COIN.LICENSE', 'MOONREY_COIN_NATIVE_ASSET', 'LICENSE_OR_REGISTRATION'),
  req('MOONREY_COIN.COUNSEL', 'MOONREY_COIN_NATIVE_ASSET', 'COUNSEL_OPINION'),
  req('MOONREY_COIN.REGULATORY', 'MOONREY_COIN_NATIVE_ASSET', 'REGULATORY_APPROVAL'),
  req('MOONREY_COIN.HUMAN', 'MOONREY_COIN_NATIVE_ASSET', 'HUMAN_AUTHORIZATION'),

  req('EXCHANGE.LICENSE', 'SUNREY_EXCHANGE', 'LICENSE_OR_REGISTRATION'),
  req('EXCHANGE.COUNSEL', 'SUNREY_EXCHANGE', 'COUNSEL_OPINION'),
  req('EXCHANGE.REGULATORY', 'SUNREY_EXCHANGE', 'REGULATORY_APPROVAL'),
  req('EXCHANGE.PARTNER', 'SUNREY_EXCHANGE', 'PARTNER_AGREEMENT'),
  req('EXCHANGE.HUMAN', 'SUNREY_EXCHANGE', 'HUMAN_AUTHORIZATION'),

  req('CUSTODY.LICENSE', 'INSTITUTIONAL_CUSTODY', 'LICENSE_OR_REGISTRATION'),
  req('CUSTODY.COUNSEL', 'INSTITUTIONAL_CUSTODY', 'COUNSEL_OPINION'),
  req('CUSTODY.REGULATORY', 'INSTITUTIONAL_CUSTODY', 'REGULATORY_APPROVAL'),
  req('CUSTODY.PARTNER', 'INSTITUTIONAL_CUSTODY', 'PARTNER_AGREEMENT'),
  req('CUSTODY.HUMAN', 'INSTITUTIONAL_CUSTODY', 'HUMAN_AUTHORIZATION'),

  req('FIAT.LICENSE', 'FIAT_BANKING', 'LICENSE_OR_REGISTRATION'),
  req('FIAT.PARTNER', 'FIAT_BANKING', 'PARTNER_AGREEMENT'),
  req('FIAT.KYC', 'FIAT_BANKING', 'KYC_AML_PROGRAM'),
  req('FIAT.HUMAN', 'FIAT_BANKING', 'HUMAN_AUTHORIZATION'),

  req('RAILS.LICENSE', 'PAYMENT_RAILS', 'LICENSE_OR_REGISTRATION'),
  req('RAILS.PARTNER', 'PAYMENT_RAILS', 'PARTNER_AGREEMENT'),
  req('RAILS.KYC', 'PAYMENT_RAILS', 'KYC_AML_PROGRAM'),
  req('RAILS.SOURCE', 'PAYMENT_RAILS', 'LICENSE_OR_REGISTRATION', { corridorEndpoint: 'SOURCE' }),
  req('RAILS.DEST', 'PAYMENT_RAILS', 'LICENSE_OR_REGISTRATION', { corridorEndpoint: 'DESTINATION' }),
  req('RAILS.HUMAN', 'PAYMENT_RAILS', 'HUMAN_AUTHORIZATION'),

  req('CARDS.LICENSE', 'CARDS', 'LICENSE_OR_REGISTRATION'),
  req('CARDS.PARTNER', 'CARDS', 'PARTNER_AGREEMENT'),
  req('CARDS.HUMAN', 'CARDS', 'HUMAN_AUTHORIZATION'),

  req('INVEST.LICENSE', 'INVESTMENTS', 'LICENSE_OR_REGISTRATION'),
  req('INVEST.COUNSEL', 'INVESTMENTS', 'COUNSEL_OPINION'),
  req('INVEST.HUMAN', 'INVESTMENTS', 'HUMAN_AUTHORIZATION'),

  req('HIN.LICENSE', 'HUMAN_INFORMATION_MARKET', 'LICENSE_OR_REGISTRATION'),
  req('HIN.COUNSEL', 'HUMAN_INFORMATION_MARKET', 'COUNSEL_OPINION'),
  req('HIN.PRIVACY', 'HUMAN_INFORMATION_MARKET', 'PRIVACY_REVIEW', { hinOnly: true }),
  req('HIN.RESIDENCY', 'HUMAN_INFORMATION_MARKET', 'DATA_RESIDENCY', { hinOnly: true }),
  req('HIN.CONSENT', 'HUMAN_INFORMATION_MARKET', 'CONSENT_CONTROL', { hinOnly: true }),
  req('HIN.PURPOSE', 'HUMAN_INFORMATION_MARKET', 'PURPOSE_CONTROL', { hinOnly: true }),
  req('HIN.TERMS', 'HUMAN_INFORMATION_MARKET', 'TERMS_AGREEMENT', { hinOnly: true }),
  req('HIN.HUMAN', 'HUMAN_INFORMATION_MARKET', 'HUMAN_AUTHORIZATION'),

  req('PROD.LICENSE', 'PRODUCTIVE_CAPACITY_MARKET', 'DATA_LICENSE', { productiveUseRight: true }),
  req('PROD.CONTRACT', 'PRODUCTIVE_CAPACITY_MARKET', 'PROVIDER_CONTRACT', { productiveUseRight: true }),
  req('PROD.USE_RIGHT', 'PRODUCTIVE_CAPACITY_MARKET', 'JURISDICTIONAL_USE_RIGHT', { productiveUseRight: true }),
  req('PROD.CERT', 'PRODUCTIVE_CAPACITY_MARKET', 'SOURCE_CERTIFICATION', { productiveUseRight: true }),
  req('PROD.HUMAN', 'PRODUCTIVE_CAPACITY_MARKET', 'HUMAN_AUTHORIZATION'),

  req('INTEROP.COUNSEL', 'INTEROPERABILITY', 'COUNSEL_OPINION'),
  req('INTEROP.HUMAN', 'INTEROPERABILITY', 'HUMAN_AUTHORIZATION'),
]);

export function requirementsFor(domain: ActivationDomain): readonly ScopeRequirement[] {
  return SCOPE_REQUIREMENTS.filter((row) => row.activationDomain === domain);
}

export function reasonCodeForClass(
  evidenceClass: ScopeEvidenceClass,
): import('./types.ts').OperatingScopeReasonCode {
  switch (evidenceClass) {
    case 'LICENSE_OR_REGISTRATION':
      return 'LICENSE_EVIDENCE_MISSING';
    case 'COUNSEL_OPINION':
      return 'COUNSEL_EVIDENCE_MISSING';
    case 'REGULATORY_APPROVAL':
      return 'REGULATORY_APPROVAL_MISSING';
    case 'PARTNER_AGREEMENT':
      return 'PARTNER_AGREEMENT_MISSING';
    case 'PRIVACY_REVIEW':
      return 'PRIVACY_REVIEW_MISSING';
    case 'DATA_RESIDENCY':
      return 'DATA_RESIDENCY_EVIDENCE_MISSING';
    case 'CONSENT_CONTROL':
      return 'CONSENT_EVIDENCE_MISSING';
    case 'PURPOSE_CONTROL':
      return 'PURPOSE_CONTROL_EVIDENCE_MISSING';
    case 'TERMS_AGREEMENT':
      return 'TERMS_AGREEMENT_MISSING';
    case 'DATA_LICENSE':
    case 'JURISDICTIONAL_USE_RIGHT':
    case 'PROVIDER_CONTRACT':
      return 'DATA_RIGHTS_EVIDENCE_MISSING';
    case 'SOURCE_CERTIFICATION':
      return 'SOURCE_CERTIFICATION_MISSING';
    case 'HUMAN_AUTHORIZATION':
      return 'HUMAN_APPROVAL_REQUIRED';
    default:
      return 'PROVIDER_NOT_ELIGIBLE';
  }
}
