/**
 * Versioned, hashable economic-policy configuration.
 *
 * Missing mainnet economics stay UNRESOLVED / NOT_AUTHORIZED.
 * Values are never generated automatically. AI cannot approve.
 */

import { createHash } from 'node:crypto';

import { nativeAssetConstitution } from '../economics/constitution.ts';
import {
  PRODUCTION_PARAMETER_UNCONFIGURED,
  TICKER_STATUS_NOT_ASSIGNED,
  type MonetaryPolicyState,
  type NativeMonetaryAssetId,
} from '../economics/types.ts';

export const ECONOMIC_PARAMETER_UNRESOLVED = 'UNRESOLVED' as const;
export const ECONOMIC_PARAMETER_NOT_AUTHORIZED = 'NOT_AUTHORIZED' as const;

export type EconomicParameterState =
  | typeof PRODUCTION_PARAMETER_UNCONFIGURED
  | typeof ECONOMIC_PARAMETER_UNRESOLVED
  | typeof ECONOMIC_PARAMETER_NOT_AUTHORIZED;

export type UnresolvedEconomicParameterId =
  | 'maxSupply'
  | 'genesisSupply'
  | 'issuanceCaps'
  | 'periodCaps'
  | 'conversionSchedules'
  | 'feePolicy'
  | 'burnPolicy'
  | 'genesisAllocation'
  | 'valuationParameters'
  | 'publicTicker';

export type UnresolvedEconomicParameter = {
  readonly id: UnresolvedEconomicParameterId;
  readonly assetId: NativeMonetaryAssetId | 'BOTH';
  readonly state: EconomicParameterState;
  readonly humanDecision: true;
  readonly aiMayApprove: false;
  readonly autoGenerated: false;
};

export const UNRESOLVED_MAINNET_ECONOMICS: readonly UnresolvedEconomicParameter[] = Object.freeze([
  param('maxSupply', 'BOTH'),
  param('genesisSupply', 'BOTH'),
  param('issuanceCaps', 'BOTH'),
  param('periodCaps', 'BOTH'),
  param('conversionSchedules', 'BOTH'),
  param('feePolicy', 'SUNREY_COIN'),
  param('burnPolicy', 'BOTH'),
  param('genesisAllocation', 'BOTH'),
  param('valuationParameters', 'BOTH'),
  param('publicTicker', 'BOTH'),
]);

function param(
  id: UnresolvedEconomicParameterId,
  assetId: NativeMonetaryAssetId | 'BOTH',
): UnresolvedEconomicParameter {
  return Object.freeze({
    id,
    assetId,
    state: id === 'publicTicker' ? ECONOMIC_PARAMETER_UNRESOLVED : ECONOMIC_PARAMETER_NOT_AUTHORIZED,
    humanDecision: true,
    aiMayApprove: false,
    autoGenerated: false,
  });
}

export type VersionedEconomicPolicyDocument = {
  readonly schema: 'sunrey.native-asset.economic-policy.v1';
  readonly versionId: string;
  readonly network: 'DEVELOPMENT' | 'TESTNET' | 'MAINNET';
  readonly policyState: MonetaryPolicyState;
  readonly tickerStatus: typeof TICKER_STATUS_NOT_ASSIGNED;
  readonly mainnetEconomics: 'UNRESOLVED' | 'NOT_AUTHORIZED' | 'AUTHORIZED';
  readonly productionIssuanceActivated: false;
  readonly aiApprovalForbidden: true;
  readonly parameters: readonly UnresolvedEconomicParameter[];
  readonly constitutionId: string;
  readonly contentHash: string;
};

export function hashEconomicPolicy(document: Omit<VersionedEconomicPolicyDocument, 'contentHash'>): string {
  return createHash('sha256')
    .update(
      JSON.stringify({
        schema: document.schema,
        versionId: document.versionId,
        network: document.network,
        policyState: document.policyState,
        tickerStatus: document.tickerStatus,
        mainnetEconomics: document.mainnetEconomics,
        productionIssuanceActivated: document.productionIssuanceActivated,
        aiApprovalForbidden: document.aiApprovalForbidden,
        parameters: document.parameters,
        constitutionId: document.constitutionId,
      }),
    )
    .digest('hex');
}

export function economicPolicyDocument(input: {
  readonly network: VersionedEconomicPolicyDocument['network'];
  readonly policyState?: MonetaryPolicyState;
}): VersionedEconomicPolicyDocument {
  const policyState =
    input.policyState ??
    (input.network === 'MAINNET'
      ? 'PRODUCTION_CANDIDATE'
      : input.network === 'TESTNET'
        ? 'TESTNET_ACTIVE'
        : 'DEVELOPMENT_ACTIVE');
  const constitution = nativeAssetConstitution(policyState);
  const mainnetEconomics: VersionedEconomicPolicyDocument['mainnetEconomics'] =
    input.network === 'MAINNET' ? ECONOMIC_PARAMETER_NOT_AUTHORIZED : ECONOMIC_PARAMETER_UNRESOLVED;
  const draft = {
    schema: 'sunrey.native-asset.economic-policy.v1' as const,
    versionId: constitution.assets[0]!.policyVersion.versionId,
    network: input.network,
    policyState,
    tickerStatus: TICKER_STATUS_NOT_ASSIGNED,
    mainnetEconomics,
    productionIssuanceActivated: false as const,
    aiApprovalForbidden: true as const,
    parameters: UNRESOLVED_MAINNET_ECONOMICS,
    constitutionId: constitution.constitutionId,
  };
  return Object.freeze({
    ...draft,
    contentHash: hashEconomicPolicy(draft),
  });
}

export function mainnetEconomicsMissing(document: VersionedEconomicPolicyDocument): boolean {
  return document.network === 'MAINNET' && document.mainnetEconomics !== 'AUTHORIZED';
}
