export const ECONOMIC_ASSET_VERIFICATION_CODES = [
  'RIGHTS_REFERENCE_REQUIRED',
  'CONSENT_REFERENCE_REQUIRED',
  'PURPOSE_REFERENCE_REQUIRED',
  'LICENSE_REFERENCE_REQUIRED',
  'LEGAL_OWNERSHIP_EVIDENCE_REQUIRED',
  'PROVENANCE_REQUIRED',
  'PROVENANCE_MISMATCH',
  'SOURCE_CLASS_MISMATCH',
  'DOMAIN_MISMATCH',
  'SCHEMA_REFERENCE_REQUIRED',
  'CONTENT_COMMITMENT_REQUIRED',
  'LINEAGE_REQUIRED',
  'LINEAGE_INVALID',
  'LINEAGE_CYCLE',
  'STORAGE_SENSITIVITY_MISMATCH',
  'RETENTION_POLICY_REQUIRED',
  'JURISDICTION_UNRESOLVED',
  'FRESHNESS_INSUFFICIENT',
  'CONFIDENCE_INSUFFICIENT',
  'CHAIN_ANCHOR_INVALID',
  'FINALITY_CLAIM_INVALID',
  'RAW_DATA_FORBIDDEN',
  'MINT_AUTHORITY_FORBIDDEN',
  'SETTLEMENT_AUTHORITY_FORBIDDEN',
  'ASSET_CLASS_NOT_ELIGIBLE',
  'POLICY_NOT_ACTIVE',
  'OTHER_CLASS_FAIL_CLOSED',
  'CONTROLLER_SUBJECT_SEPARATION_REQUIRED',
  'CANONICAL_SOURCE_REQUIRED',
  'CONTRIBUTION_REFERENCE_REQUIRED',
  'CONTRIBUTION_FINGERPRINT_REQUIRED',
  'ORACLE_FACT_REFERENCE_REQUIRED',
  'OBJECT_REFERENCE_REQUIRED',
  'CLAIM_REFERENCE_REQUIRED',
  'MEASUREMENT_PERIOD_REQUIRED',
  'ATTESTING_SOURCE_REQUIRED',
  'VALIDITY_PERIOD_REQUIRED',
  'OPERATOR_REFERENCE_REQUIRED',
  'PARENT_ASSET_REQUIRED',
] as const;

export type EconomicAssetVerificationCode = (typeof ECONOMIC_ASSET_VERIFICATION_CODES)[number];

export const ADDITIONAL_EVIDENCE_CODES = Object.freeze([
  'CONSENT_REFERENCE_REQUIRED',
  'PURPOSE_REFERENCE_REQUIRED',
  'LICENSE_REFERENCE_REQUIRED',
  'FRESHNESS_INSUFFICIENT',
  'CONFIDENCE_INSUFFICIENT',
  'SCHEMA_REFERENCE_REQUIRED',
  'RETENTION_POLICY_REQUIRED',
] as const satisfies readonly EconomicAssetVerificationCode[]);

export function isEconomicAssetVerificationCode(value: string): value is EconomicAssetVerificationCode {
  return (ECONOMIC_ASSET_VERIFICATION_CODES as readonly string[]).includes(value);
}

export function requiresAdditionalEvidence(code: EconomicAssetVerificationCode): boolean {
  return (ADDITIONAL_EVIDENCE_CODES as readonly string[]).includes(code);
}
