/**
 * Deterministic sandbox fixtures. Clearly simulation.
 */

import { createResource, type ProductiveAssetRegistry } from './registry.ts';
import { simulationMethodology } from './methodology.ts';
import type { ObservationDraft, ProductiveResourceRecord, ProductiveValueMethodology } from './types.ts';

export const SANDBOX_NOW_UTC = '2026-08-23T12:00:00.000Z' as const;

export const SANDBOX_RESOURCES = Object.freeze({
  energy: createResource({
    resourceId: 'res_sandbox_energy_grid',
    category: 'ENERGY',
    subtype: 'GRID_GENERATION',
    ownerRef: 'op_sandbox_grid',
    operatorRef: 'op_sandbox_grid',
    jurisdiction: 'SIM',
    region: 'lab-west',
    publicDisclosureAllowed: true,
    unit: 'MWh',
    valuationMethodologyId: 'pvm.energy.sim',
    minimumSources: 2,
  }),
  compute: createResource({
    resourceId: 'res_sandbox_compute_cluster',
    category: 'COMPUTE',
    subtype: 'APPROVED_COMPUTE',
    jurisdiction: 'SIM',
    region: 'lab-east',
    publicDisclosureAllowed: false,
    unit: 'GPU_HOUR',
    valuationMethodologyId: 'pvm.compute.sim',
  }),
  manufacturing: createResource({
    resourceId: 'res_sandbox_factory',
    category: 'MANUFACTURING',
    subtype: 'FINISHED_UNITS',
    jurisdiction: 'SIM',
    region: 'lab-central',
    publicDisclosureAllowed: true,
    unit: 'units_produced',
    valuationMethodologyId: 'pvm.manufacturing.sim',
  }),
  agriculture: createResource({
    resourceId: 'res_sandbox_farm',
    category: 'AGRICULTURE_FOOD',
    subtype: 'HARVEST_YIELD',
    jurisdiction: 'SIM',
    region: 'lab-south',
    publicDisclosureAllowed: true,
    unit: 'kg',
    valuationMethodologyId: 'pvm.agriculture_food.sim',
  }),
  logistics: createResource({
    resourceId: 'res_sandbox_freight',
    category: 'LOGISTICS',
    subtype: 'FREIGHT_TONNE_KM',
    jurisdiction: 'SIM',
    region: 'lab-north',
    publicDisclosureAllowed: true,
    unit: 'tonne_km',
    valuationMethodologyId: 'pvm.logistics.sim',
  }),
});

export function seedSandboxResources(registry: ProductiveAssetRegistry): readonly ProductiveResourceRecord[] {
  return Object.values(SANDBOX_RESOURCES).map((row) => registry.register(row));
}

export function sandboxMethodologies(): readonly ProductiveValueMethodology[] {
  return Object.freeze([
    simulationMethodology('ENERGY', 'ENERGY_PRODUCTION'),
    simulationMethodology('COMPUTE', 'COMPUTE_USAGE'),
    simulationMethodology('MANUFACTURING', 'MANUFACTURING_OUTPUT'),
    simulationMethodology('AGRICULTURE_FOOD', 'FOOD_PRODUCTION'),
    simulationMethodology('LOGISTICS', 'DELIVERY_COMPLETION'),
  ]);
}

function draft(input: Omit<ObservationDraft, 'license' | 'sourceClass'> & {
  readonly license?: ObservationDraft['license'];
  readonly sourceClass?: ObservationDraft['sourceClass'];
}): ObservationDraft {
  return Object.freeze({
    license: input.license ?? 'SANDBOX_FIXTURE',
    sourceClass: input.sourceClass ?? 'SANDBOX_FIXTURE',
    method: 'SANDBOX_FIXTURE',
    ...input,
  });
}

export const SANDBOX_DRAFTS = Object.freeze({
  energyA: draft({
    observationId: 'obs_sandbox_energy_a',
    category: 'ENERGY',
    resourceId: SANDBOX_RESOURCES.energy.resourceId,
    metric: 'ENERGY_PRODUCTION',
    value: 120n,
    unit: 'MWh',
    timestampUtc: SANDBOX_NOW_UTC,
    source: 'fixture-oracle-a',
    provider: 'fixture-oracle-a',
    signatureValid: true,
    evidenceRef: 'ev:energy:a',
  }),
  energyB: draft({
    observationId: 'obs_sandbox_energy_b',
    category: 'ENERGY',
    resourceId: SANDBOX_RESOURCES.energy.resourceId,
    metric: 'ENERGY_PRODUCTION',
    value: 118n,
    unit: 'MWh',
    timestampUtc: SANDBOX_NOW_UTC,
    source: 'fixture-oracle-b',
    provider: 'fixture-oracle-b',
    signatureValid: true,
    evidenceRef: 'ev:energy:b',
  }),
  compute: draft({
    observationId: 'obs_sandbox_compute',
    category: 'COMPUTE',
    resourceId: SANDBOX_RESOURCES.compute.resourceId,
    metric: 'COMPUTE_USAGE',
    value: 40n,
    unit: 'GPU_HOUR',
    timestampUtc: SANDBOX_NOW_UTC,
    source: 'fixture-oracle-compute',
    provider: 'fixture-oracle-compute',
    signatureValid: true,
    evidenceRef: 'ev:compute:a',
  }),
  manufacturing: draft({
    observationId: 'obs_sandbox_mfg',
    category: 'MANUFACTURING',
    resourceId: SANDBOX_RESOURCES.manufacturing.resourceId,
    metric: 'MANUFACTURING_OUTPUT',
    value: 500n,
    unit: 'units_produced',
    timestampUtc: SANDBOX_NOW_UTC,
    source: 'fixture-oracle-mfg',
    provider: 'fixture-oracle-mfg',
    signatureValid: true,
    evidenceRef: 'ev:mfg:a',
  }),
  agriculture: draft({
    observationId: 'obs_sandbox_ag',
    category: 'AGRICULTURE_FOOD',
    resourceId: SANDBOX_RESOURCES.agriculture.resourceId,
    metric: 'FOOD_PRODUCTION',
    value: 2_000n,
    unit: 'kg',
    timestampUtc: SANDBOX_NOW_UTC,
    source: 'fixture-oracle-ag',
    provider: 'fixture-oracle-ag',
    signatureValid: true,
    evidenceRef: 'ev:ag:a',
  }),
  logistics: draft({
    observationId: 'obs_sandbox_log',
    category: 'LOGISTICS',
    resourceId: SANDBOX_RESOURCES.logistics.resourceId,
    metric: 'DELIVERY_COMPLETION',
    value: 80n,
    unit: 'tonne_km',
    timestampUtc: SANDBOX_NOW_UTC,
    source: 'fixture-oracle-log',
    provider: 'fixture-oracle-log',
    signatureValid: true,
    evidenceRef: 'ev:log:a',
  }),
  stale: draft({
    observationId: 'obs_sandbox_stale',
    category: 'ENERGY',
    resourceId: SANDBOX_RESOURCES.energy.resourceId,
    metric: 'ENERGY_PRODUCTION',
    value: 100n,
    unit: 'MWh',
    timestampUtc: '2026-01-01T00:00:00.000Z',
    source: 'fixture-oracle-stale',
    provider: 'fixture-oracle-stale',
    signatureValid: true,
    evidenceRef: 'ev:energy:stale',
  }),
  conflicting: draft({
    observationId: 'obs_sandbox_conflict',
    category: 'ENERGY',
    resourceId: SANDBOX_RESOURCES.energy.resourceId,
    metric: 'ENERGY_PRODUCTION',
    value: 9_000n,
    unit: 'MWh',
    timestampUtc: SANDBOX_NOW_UTC,
    source: 'fixture-oracle-conflict',
    provider: 'fixture-oracle-conflict',
    signatureValid: true,
    evidenceRef: 'ev:energy:conflict',
  }),
  outlier: draft({
    observationId: 'obs_sandbox_outlier',
    category: 'ENERGY',
    resourceId: SANDBOX_RESOURCES.energy.resourceId,
    metric: 'ENERGY_PRODUCTION',
    value: 50_000n,
    unit: 'MWh',
    timestampUtc: SANDBOX_NOW_UTC,
    source: 'fixture-oracle-outlier',
    provider: 'fixture-oracle-outlier',
    signatureValid: true,
    evidenceRef: 'ev:energy:outlier',
  }),
  missingSource: draft({
    observationId: 'obs_sandbox_missing_source',
    category: 'ENERGY',
    resourceId: SANDBOX_RESOURCES.energy.resourceId,
    metric: 'ENERGY_PRODUCTION',
    value: 10n,
    unit: 'MWh',
    timestampUtc: SANDBOX_NOW_UTC,
    source: '',
    provider: 'fixture-oracle-blank',
    signatureValid: true,
    evidenceRef: 'ev:energy:blank',
  }),
  invalidProvenance: draft({
    observationId: 'obs_sandbox_invalid_sig',
    category: 'ENERGY',
    resourceId: SANDBOX_RESOURCES.energy.resourceId,
    metric: 'ENERGY_PRODUCTION',
    value: 10n,
    unit: 'MWh',
    timestampUtc: SANDBOX_NOW_UTC,
    source: 'fixture-oracle-bad',
    provider: 'fixture-oracle-bad',
    signatureValid: false,
    evidenceRef: 'ev:energy:bad',
  }),
  unlabeled: draft({
    observationId: 'obs_sandbox_unlabeled',
    category: 'ENERGY',
    resourceId: SANDBOX_RESOURCES.energy.resourceId,
    value: 10n,
    unit: 'MWh',
    timestampUtc: SANDBOX_NOW_UTC,
    source: 'fixture-oracle-unlabeled',
    provider: 'fixture-oracle-unlabeled',
    signatureValid: true,
    evidenceRef: 'ev:energy:unlabeled',
  }),
  restrictedLicense: draft({
    observationId: 'obs_sandbox_restricted',
    category: 'COMPUTE',
    resourceId: SANDBOX_RESOURCES.compute.resourceId,
    metric: 'COMPUTE_USAGE',
    value: 12n,
    unit: 'GPU_HOUR',
    timestampUtc: SANDBOX_NOW_UTC,
    source: 'fixture-licensed-provider',
    provider: 'fixture-licensed-provider',
    signatureValid: true,
    evidenceRef: 'ev:compute:restricted',
    license: 'EXTERNAL_RESTRICTED',
    sourceClass: 'INSTITUTIONAL',
  }),
});
