/**
 * Machine-readable readiness dimension catalog and default evidence slots.
 */

import { collectReadinessArtifactDigests } from '../infra/artifacts.ts';
import { mainnetRcReadinessRecords } from '../release-candidate/mainnet/readiness.ts';
import type { MainnetReadinessDimension, ReadinessEvidenceRecord } from './types.ts';
import { READINESS_DIMENSIONS } from './types.ts';
import { freezeEvidence } from './evidence.ts';

type SlotDraft = Omit<ReadinessEvidenceRecord, 'verificationStatus' | 'evidenceHash' | 'evidenceReference'> & {
  readonly verificationStatus?: ReadinessEvidenceRecord['verificationStatus'];
  readonly evidenceHash?: string | null;
  readonly evidenceReference?: string | null;
};

export type EngineeringEvidenceOverlay = {
  readonly chunk76?: string;
  readonly chunk77?: string;
  readonly chunk78?: string;
  readonly chunk79?: string;
  readonly chunk80?: string;
  readonly chunk81?: string;
};

function overlayHash(draft: SlotDraft, overlay?: EngineeringEvidenceOverlay): string | null {
  if (draft.externalEvidence) {
    return draft.evidenceHash ?? null;
  }
  if (draft.chunkReference === 'CHUNK-76') {
    return overlay?.chunk76 ?? draft.evidenceHash ?? null;
  }
  if (draft.chunkReference === 'CHUNK-77') {
    return overlay?.chunk77 ?? draft.evidenceHash ?? null;
  }
  if (draft.chunkReference === 'CHUNK-78') {
    return overlay?.chunk78 ?? draft.evidenceHash ?? null;
  }
  if (draft.chunkReference === 'CHUNK-79') {
    return overlay?.chunk79 ?? draft.evidenceHash ?? null;
  }
  if (draft.chunkReference === 'CHUNK-80') {
    return overlay?.chunk80 ?? draft.evidenceHash ?? null;
  }
  if (draft.chunkReference === 'CHUNK-81') {
    return overlay?.chunk81 ?? draft.evidenceHash ?? null;
  }
  return draft.evidenceHash ?? null;
}

function slot(draft: SlotDraft, overlay?: EngineeringEvidenceOverlay): ReadinessEvidenceRecord {
  return freezeEvidence({
    ...draft,
    evidenceHash: overlayHash(draft, overlay),
    evidenceReference: draft.evidenceReference ?? null,
    verificationStatus: draft.verificationStatus ?? 'NOT_PROVIDED',
  });
}

export function defaultDimensionCatalog(
  overlay?: EngineeringEvidenceOverlay,
): readonly ReadinessEvidenceRecord[] {
  const digests = collectReadinessArtifactDigests();
  const drafts: SlotDraft[] = [
    {
      requirementId: 'REQ-PROTOCOL-001',
      dimension: 'PROTOCOL',
      description: 'Canonical transaction protocol and codec remain the Chunk 32R owner',
      scope: 'SUNREY_CHAIN',
      evidenceType: 'ENGINEERING_ARTIFACT',
      source: 'packages/sunrey-chain/src/protocol',
      authorizedVerifierRole: 'ENGINEERING',
      expirationOrReviewDateUtc: null,
      notes: 'Engineering implementation evidence. Not a production launch.',
      externalEvidence: false,
      chunkReference: 'CHUNK-32',
      verificationStatus: 'ENGINEERING_VERIFIED',
    },
    {
      requirementId: 'REQ-CONSENSUS-001',
      dimension: 'CONSENSUS',
      description: 'Development Tendermint-class BFT exists; production consensus is not activated',
      scope: 'SUNREY_CHAIN',
      evidenceType: 'SOFTWARE_TEST',
      source: 'packages/sunrey-chain/rust/crates/consensus',
      authorizedVerifierRole: 'ENGINEERING',
      expirationOrReviewDateUtc: null,
      notes: 'Development consensus only. Production BFT remains disabled.',
      externalEvidence: false,
      chunkReference: 'CHUNK-37',
      verificationStatus: 'ENGINEERING_VERIFIED',
    },
    {
      requirementId: 'REQ-FORMAL-001',
      dimension: 'FORMAL_ASSURANCE',
      description: 'Formal model versions, bounds, properties, counterexamples, report digest',
      scope: 'SUNREY_CHAIN',
      evidenceType: 'FORMAL_MODEL',
      source: 'packages/sunrey-chain/src/formal',
      authorizedVerifierRole: 'ENGINEERING',
      expirationOrReviewDateUtc: null,
      notes: 'Chunk 61 formal models are model-checked within stated bounds. Independent auditor review remains a separate slot. Formal assurance is not a substitute for implementation or security review.',
      externalEvidence: true,
      chunkReference: 'CHUNK-61',
      verificationStatus: 'ENGINEERING_VERIFIED',
      evidenceHash: digests.formalReportDigest,
      evidenceReference: `formal-report:${digests.formalReportDigest}`,
    },
    {
      requirementId: 'REQ-FORMAL-002',
      dimension: 'FORMAL_ASSURANCE',
      description: 'Independent auditor review of formal models',
      scope: 'SUNREY_CHAIN',
      evidenceType: 'EXTERNAL_AUDIT_REPORT',
      source: 'external-formal-auditor-slot',
      authorizedVerifierRole: 'EXTERNAL_AUDITOR',
      expirationOrReviewDateUtc: null,
      notes: 'Independent auditor review of Chunk 61 models is not provided.',
      externalEvidence: true,
      chunkReference: 'CHUNK-61',
      verificationStatus: 'EXTERNAL_VERIFICATION_REQUIRED',
    },
    {
      requirementId: 'REQ-SECURITY-TEST-001',
      dimension: 'SECURITY_TESTING',
      description: 'Fuzz corpus, property campaigns, and adversarial-range invariant status',
      scope: 'SUNREY_CHAIN',
      evidenceType: 'SOFTWARE_TEST',
      source: 'packages/sunrey-chain/src/assurance + packages/sunrey-range',
      authorizedVerifierRole: 'SECURITY',
      expirationOrReviewDateUtc: null,
      notes: 'Chunks 56 and 57 engineering tests. Not an independent audit.',
      externalEvidence: false,
      chunkReference: 'CHUNK-56',
      verificationStatus: 'ENGINEERING_VERIFIED',
    },
    {
      requirementId: 'REQ-EXT-SEC-001',
      dimension: 'EXTERNAL_SECURITY_REVIEW',
      description: 'Independent review organization, scope, report hash, open critical/high, retest',
      scope: 'SUNREY_CHAIN',
      evidenceType: 'EXTERNAL_AUDIT_REPORT',
      source: 'external-security-review-slot',
      authorizedVerifierRole: 'EXTERNAL_AUDITOR',
      expirationOrReviewDateUtc: null,
      notes: 'No independent auditor report exists. Do not invent one. Chunk 62 preparation and Chunk 83 remediation workflow are separate engineering slots. TEST_FIXTURE_NOT_EXTERNAL_AUDIT records never satisfy this requirement.',
      externalEvidence: true,
      chunkReference: 'CHUNK-62',
      verificationStatus: 'NOT_PROVIDED',
    },
    {
      requirementId: 'REQ-EXT-SEC-PREP',
      dimension: 'EXTERNAL_SECURITY_REVIEW',
      description: 'Chunk 62 engineering security-review preparation bundle',
      scope: 'SUNREY_CHAIN',
      evidenceType: 'ENGINEERING_ARTIFACT',
      source: 'packages/sunrey-chain/src/audit',
      authorizedVerifierRole: 'SECURITY',
      expirationOrReviewDateUtc: null,
      notes: 'Engineering preparation bundle only. Does not claim an external audit occurred or passed.',
      externalEvidence: false,
      chunkReference: 'CHUNK-62',
      verificationStatus: 'ENGINEERING_VERIFIED',
      evidenceHash: digests.auditBundleDigest,
      evidenceReference: `audit-bundle:${digests.auditBundleDigest}`,
    },
    {
      requirementId: 'REQ-EXT-SEC-REMEDIATION',
      dimension: 'EXTERNAL_SECURITY_REVIEW',
      description: 'Chunk 83 finding ingestion, remediation, retest, and risk-acceptance workflow',
      scope: 'SUNREY_CHAIN',
      evidenceType: 'ENGINEERING_ARTIFACT',
      source: 'packages/sunrey-chain/src/audit/remediation',
      authorizedVerifierRole: 'SECURITY',
      expirationOrReviewDateUtc: null,
      notes: 'Engineering audit-remediation infrastructure may be verified. Actual external review remains based on real supplied evidence. Fixtures cannot become a real audit.',
      externalEvidence: false,
      chunkReference: 'CHUNK-83',
      verificationStatus: 'ENGINEERING_VERIFIED',
      evidenceHash: digests.auditBundleDigest,
      evidenceReference: `audit-remediation:${digests.auditBundleDigest}`,
    },
    {
      requirementId: 'REQ-CRYPTO-001',
      dimension: 'CRYPTOGRAPHY',
      description: 'CryptoPolicy reflects actually supported suites and providers',
      scope: 'SUNREY_CHAIN',
      evidenceType: 'ENGINEERING_ARTIFACT',
      source: 'packages/security',
      authorizedVerifierRole: 'SECURITY',
      expirationOrReviewDateUtc: null,
      notes: 'Production consensus is not configured to require unsupported PQ/HSM combinations.',
      externalEvidence: false,
      chunkReference: 'CHUNK-60',
      verificationStatus: 'ENGINEERING_VERIFIED',
    },
    {
      requirementId: 'REQ-PQC-001',
      dimension: 'PQC',
      description: 'Record actual PQ roles and providers; production PQ/HSM remains unselected',
      scope: 'SUNREY_CHAIN',
      evidenceType: 'ENGINEERING_ARTIFACT',
      source: 'packages/security/src/pqc-library-selection.ts',
      authorizedVerifierRole: 'SECURITY',
      expirationOrReviewDateUtc: null,
      notes: 'PQC software is not production HSM PQC capability. productionStatus=NOT_SELECTED_FOR_PRODUCTION.',
      externalEvidence: false,
      chunkReference: 'CHUNK-60',
      verificationStatus: 'ENGINEERING_VERIFIED',
    },
    {
      requirementId: 'REQ-SUPPLY-001',
      dimension: 'SUPPLY_CHAIN',
      description: 'Release artifact hashes, SBOM, provenance, dependency audit, reproducibility, signature',
      scope: 'SUNREY_CHAIN',
      evidenceType: 'RELEASE_ARTIFACT',
      source: 'packages/sunrey-chain/src/supply-chain',
      authorizedVerifierRole: 'RELEASE',
      expirationOrReviewDateUtc: null,
      notes: `Chunk 59 engineering supply-chain. SBOM digest ${digests.sbomDigest}. Production cosign/HSM release key is not present.`,
      externalEvidence: false,
      chunkReference: 'CHUNK-59',
      verificationStatus: 'ENGINEERING_VERIFIED',
      evidenceHash: digests.sbomDigest,
      evidenceReference: `sbom:${digests.sbomDigest}`,
    },
    {
      requirementId: 'REQ-RELEASE-001',
      dimension: 'RELEASE',
      description: 'ReleaseAuthority signs artifacts only and does not activate protocol change',
      scope: 'SUNREY_CHAIN',
      evidenceType: 'RELEASE_ARTIFACT',
      source: 'packages/sunrey-chain/src/supply-chain/release.ts',
      authorizedVerifierRole: 'RELEASE',
      expirationOrReviewDateUtc: null,
      notes: `Software release approval is not network launch. Provenance digest ${digests.releaseProvenanceDigest}.`,
      externalEvidence: false,
      chunkReference: 'CHUNK-59',
      verificationStatus: 'ENGINEERING_VERIFIED',
      evidenceHash: digests.releaseProvenanceDigest,
      evidenceReference: `provenance:${digests.releaseProvenanceDigest}`,
    },
    {
      requirementId: 'REQ-VALOPS-001',
      dimension: 'VALIDATOR_OPERATIONS',
      description: 'Operator infrastructure, sentry, signer safety, join/exit workflows',
      scope: 'SUNREY_CHAIN',
      evidenceType: 'ENGINEERING_ARTIFACT',
      source: 'packages/sunrey-chain/src/ops',
      authorizedVerifierRole: 'OPERATIONS',
      expirationOrReviewDateUtc: null,
      notes: 'Engineering operator tooling. Not a production operations contract.',
      externalEvidence: false,
      chunkReference: 'CHUNK-54',
      verificationStatus: 'ENGINEERING_VERIFIED',
    },
    {
      requirementId: 'REQ-VALECON-001',
      dimension: 'VALIDATOR_ECONOMICS',
      description: 'Validator bond policy implemented; production bond asset remains UNCONFIGURED',
      scope: 'SUNREY_CHAIN',
      evidenceType: 'ENGINEERING_ARTIFACT',
      source: 'packages/sunrey-chain/src/validator-economics',
      authorizedVerifierRole: 'ENGINEERING',
      expirationOrReviewDateUtc: null,
      notes: 'Development/rehearsal fixtures only. Production bond asset is UNCONFIGURED.',
      externalEvidence: false,
      chunkReference: 'CHUNK-72',
      verificationStatus: 'ENGINEERING_VERIFIED',
    },
    {
      requirementId: 'REQ-VALECON-002',
      dimension: 'VALIDATOR_ECONOMICS',
      description: 'Validator reward policy implemented with integer remainder handling',
      scope: 'SUNREY_CHAIN',
      evidenceType: 'SOFTWARE_TEST',
      source: 'packages/sunrey-chain/src/validator-economics',
      authorizedVerifierRole: 'ENGINEERING',
      expirationOrReviewDateUtc: null,
      notes: 'No hidden inflation. Fee allocation enters validator reward accounting.',
      externalEvidence: false,
      chunkReference: 'CHUNK-72',
      verificationStatus: 'ENGINEERING_VERIFIED',
    },
    {
      requirementId: 'REQ-VALECON-003',
      dimension: 'VALIDATOR_ECONOMICS',
      description: 'Validator penalty policy implemented; protocol evidence required',
      scope: 'SUNREY_CHAIN',
      evidenceType: 'SOFTWARE_TEST',
      source: 'packages/sunrey-chain/src/validator-economics',
      authorizedVerifierRole: 'ENGINEERING',
      expirationOrReviewDateUtc: null,
      notes: 'Customer assets cannot be debited. Duplicate evidence cannot slash twice.',
      externalEvidence: false,
      chunkReference: 'CHUNK-72',
      verificationStatus: 'ENGINEERING_VERIFIED',
    },
    {
      requirementId: 'REQ-VALECON-004',
      dimension: 'VALIDATOR_ECONOMICS',
      description: 'Formal VALIDATOR_ECONOMICS model result within stated bounds',
      scope: 'SUNREY_CHAIN',
      evidenceType: 'FORMAL_MODEL',
      source: 'packages/sunrey-chain/src/formal/models/validator-economics.ts',
      authorizedVerifierRole: 'ENGINEERING',
      expirationOrReviewDateUtc: null,
      notes: 'Model checked within stated bounds. Not whole-system verification.',
      externalEvidence: false,
      chunkReference: 'CHUNK-72',
      verificationStatus: 'ENGINEERING_VERIFIED',
    },
    {
      requirementId: 'REQ-VALECON-005',
      dimension: 'VALIDATOR_ECONOMICS',
      description: 'Validator economics simulation result',
      scope: 'SUNREY_CHAIN',
      evidenceType: 'SOFTWARE_TEST',
      source: 'packages/sunrey-chain/src/validator-economics/simulator.ts',
      authorizedVerifierRole: 'ENGINEERING',
      expirationOrReviewDateUtc: null,
      notes: 'Engineering metrics only. Does not claim guaranteed economic security.',
      externalEvidence: false,
      chunkReference: 'CHUNK-72',
      verificationStatus: 'ENGINEERING_VERIFIED',
    },
    {
      requirementId: 'REQ-VALECON-006',
      dimension: 'HUMAN_AUTHORIZATION',
      description: 'Production bond/reward/penalty parameters configured',
      scope: 'SUNREY_CHAIN',
      evidenceType: 'HUMAN_AUTHORIZATION',
      source: 'production-validator-economics-parameters',
      authorizedVerifierRole: 'HUMAN_AUTHORITY',
      expirationOrReviewDateUtc: null,
      notes: 'Production values remain UNCONFIGURED. Incomplete until human/governance authorization.',
      externalEvidence: true,
      chunkReference: 'CHUNK-72',
      verificationStatus: 'NOT_PROVIDED',
    },
    {
      requirementId: 'REQ-VALECON-007',
      dimension: 'HUMAN_AUTHORIZATION',
      description: 'Human/governance authorization of validator economic policy',
      scope: 'SUNREY_CHAIN',
      evidenceType: 'HUMAN_AUTHORIZATION',
      source: 'external-validator-economics-authorization',
      authorizedVerifierRole: 'HUMAN_AUTHORITY',
      expirationOrReviewDateUtc: null,
      notes: 'AI cannot authorize. Software cannot mark this HUMAN_VERIFIED.',
      externalEvidence: true,
      chunkReference: 'CHUNK-72',
      verificationStatus: 'NOT_PROVIDED',
    },
    {
      requirementId: 'REQ-ROT-001',
      dimension: 'ROOT_OF_TRUST',
      description: 'Simulation rehearsal transcript; process readiness only',
      scope: 'SUNREY_CHAIN',
      evidenceType: 'CEREMONY_TRANSCRIPT',
      source: 'packages/security/src/ceremony',
      authorizedVerifierRole: 'SECURITY',
      expirationOrReviewDateUtc: null,
      notes: 'Simulation rehearsal is evidence of process readiness, not proof of real production key creation.',
      externalEvidence: true,
      chunkReference: 'CHUNK-64',
      verificationStatus: 'ENGINEERING_VERIFIED',
      evidenceHash: digests.rootOfTrustRehearsalDigest,
      evidenceReference: `ceremony-rehearsal:${digests.rootOfTrustRehearsalDigest}`,
    },
    {
      requirementId: 'REQ-ROT-002',
      dimension: 'ROOT_OF_TRUST',
      description: 'Real external ceremony and commercial HSM evidence',
      scope: 'SUNREY_CHAIN',
      evidenceType: 'CEREMONY_TRANSCRIPT',
      source: 'external-ceremony-slot',
      authorizedVerifierRole: 'SECURITY',
      expirationOrReviewDateUtc: null,
      notes: 'Real external ceremony and commercial HSM evidence are not provided.',
      externalEvidence: true,
      chunkReference: 'CHUNK-64',
      verificationStatus: 'EXTERNAL_VERIFICATION_REQUIRED',
    },
    {
      requirementId: 'REQ-GENESIS-001',
      dimension: 'GENESIS',
      description: 'Deterministic genesis candidate with explicit zero/authorized allocation',
      scope: 'SUNREY_CHAIN',
      evidenceType: 'ENGINEERING_ARTIFACT',
      source: 'packages/sunrey-chain/src/mainnet/genesis-candidate.ts',
      authorizedVerifierRole: 'ENGINEERING',
      expirationOrReviewDateUtc: null,
      notes: 'Candidate only. Does not publish production genesis.',
      externalEvidence: false,
      chunkReference: 'CHUNK-65',
      verificationStatus: 'ENGINEERING_VERIFIED',
    },
    {
      requirementId: 'REQ-OBS-001',
      dimension: 'OBSERVABILITY',
      description: 'Operator observability and privacy-safe telemetry',
      scope: 'SUNREY_CHAIN',
      evidenceType: 'ENGINEERING_ARTIFACT',
      source: 'packages/sunrey-chain/src/ops',
      authorizedVerifierRole: 'OPERATIONS',
      expirationOrReviewDateUtc: null,
      notes: 'Engineering observability. Not a production SLO contract.',
      externalEvidence: false,
      chunkReference: 'CHUNK-55',
      verificationStatus: 'ENGINEERING_VERIFIED',
    },
    {
      requirementId: 'REQ-DR-001',
      dimension: 'DISASTER_RECOVERY',
      description: 'Backup, restore verification, and DR drills',
      scope: 'SUNREY_CHAIN',
      evidenceType: 'SOFTWARE_TEST',
      source: 'packages/sunrey-chain/src/ops',
      authorizedVerifierRole: 'OPERATIONS',
      expirationOrReviewDateUtc: null,
      notes: 'Engineering DR drills. Not a contractual recovery commitment.',
      externalEvidence: false,
      chunkReference: 'CHUNK-55',
      verificationStatus: 'ENGINEERING_VERIFIED',
    },
    {
      requirementId: 'REQ-STORAGE-001',
      dimension: 'STORAGE',
      description: 'Production-candidate chain storage, PostgreSQL durability, PITR, and restore drills',
      scope: 'SUNREY_CHAIN',
      evidenceType: 'SOFTWARE_TEST',
      source: 'packages/sunrey-chain/rust/crates/storage + packages/persistence/src/production',
      authorizedVerifierRole: 'ENGINEERING',
      expirationOrReviewDateUtc: null,
      notes: 'Engineering verification of crash-consistent storage. Does not imply a production provider deployment.',
      externalEvidence: false,
      chunkReference: 'CHUNK-67',
      verificationStatus: 'ENGINEERING_VERIFIED',
    },
    {
      requirementId: 'REQ-PERF-001',
      dimension: 'PERFORMANCE',
      description: 'Measured testnet engineering results and capacity assumptions',
      scope: 'SUNREY_CHAIN',
      evidenceType: 'CAPACITY_MEASUREMENT',
      source: 'packages/sunrey-chain/src/perf',
      authorizedVerifierRole: 'ENGINEERING',
      expirationOrReviewDateUtc: null,
      notes: 'ENGINEERING_MEASUREMENT only. Not a contractual performance promise.',
      externalEvidence: false,
      chunkReference: 'CHUNK-58',
      verificationStatus: 'ENGINEERING_VERIFIED',
    },
    {
      requirementId: 'REQ-PRIVACY-001',
      dimension: 'PRIVACY',
      description: 'PDV, consent, Clean Room, residency, retention, deletion, jurisdictional analysis',
      scope: 'PRIVACY',
      evidenceType: 'ENGINEERING_ARTIFACT',
      source: 'packages/personal-data-vault + packages/consent + packages/clean-room',
      authorizedVerifierRole: 'COUNSEL',
      expirationOrReviewDateUtc: null,
      notes: 'Software privacy controls exist in simulation. Jurisdictional privacy analysis and legal review are not provided.',
      externalEvidence: true,
      chunkReference: 'CHUNK-23',
      verificationStatus: 'EXTERNAL_VERIFICATION_REQUIRED',
    },
    {
      requirementId: 'REQ-CUSTODY-001',
      dimension: 'CUSTODY',
      description: 'Real HSM/provider, ceremony, segregation, reconciliation, withdrawal approval, DR, licensing',
      scope: 'INSTITUTIONAL_CUSTODY',
      evidenceType: 'ENGINEERING_ARTIFACT',
      source: 'packages/custody',
      authorizedVerifierRole: 'COUNSEL',
      expirationOrReviewDateUtc: null,
      notes: 'Simulation HSM does not satisfy real-provider evidence. Software custody is not a licensed custody business.',
      externalEvidence: true,
      chunkReference: 'CHUNK-47',
      verificationStatus: 'EXTERNAL_VERIFICATION_REQUIRED',
    },
    {
      requirementId: 'REQ-EXCHANGE-001',
      dimension: 'EXCHANGE',
      description: 'Custody, surveillance, listing, Travel Rule, licensing, staffing, security review',
      scope: 'SUNREY_EXCHANGE',
      evidenceType: 'ENGINEERING_ARTIFACT',
      source: 'packages/sunrey-exchange',
      authorizedVerifierRole: 'COUNSEL',
      expirationOrReviewDateUtc: null,
      notes: 'Software exchange is not a licensed exchange. Implementation alone is insufficient.',
      externalEvidence: true,
      chunkReference: 'CHUNK-29',
      verificationStatus: 'EXTERNAL_VERIFICATION_REQUIRED',
    },
    {
      requirementId: 'REQ-EXCHANGE-002',
      dimension: 'EXCHANGE',
      description: 'Exchange licensing/registration and market/legal approvals',
      scope: 'SUNREY_EXCHANGE',
      evidenceType: 'LICENSE_OR_REGISTRATION',
      source: 'external-exchange-license-slot',
      authorizedVerifierRole: 'COUNSEL',
      expirationOrReviewDateUtc: null,
      notes: 'No exchange license, registration, or market approval is recorded.',
      externalEvidence: true,
      chunkReference: null,
      verificationStatus: 'NOT_PROVIDED',
    },
    {
      requirementId: 'REQ-CUSTODY-002',
      dimension: 'CUSTODY',
      description: 'Real HSM/provider evidence; simulation HSM is insufficient',
      scope: 'INSTITUTIONAL_CUSTODY',
      evidenceType: 'PARTNER_AGREEMENT',
      source: 'external-custody-provider-slot',
      authorizedVerifierRole: 'COUNSEL',
      expirationOrReviewDateUtc: null,
      notes: 'Simulation HSM does not satisfy real-provider evidence.',
      externalEvidence: true,
      chunkReference: null,
      verificationStatus: 'NOT_PROVIDED',
    },
    {
      requirementId: 'REQ-ORACLE-001',
      dimension: 'PARTNER_DEPENDENCIES',
      description: 'Real oracle provider agreements, source diversity, and jurisdiction constraints',
      scope: 'ORACLE',
      evidenceType: 'PARTNER_AGREEMENT',
      source: 'external-oracle-slot',
      authorizedVerifierRole: 'COUNSEL',
      expirationOrReviewDateUtc: null,
      notes: 'Development oracle fixtures are not production feeds.',
      externalEvidence: true,
      chunkReference: null,
      verificationStatus: 'NOT_PROVIDED',
    },
    {
      requirementId: 'REQ-INTEROP-001',
      dimension: 'COMPLIANCE',
      description: 'Production interop remains separately controlled; no wrapped fiat',
      scope: 'INTEROPERABILITY',
      evidenceType: 'REGULATORY_APPROVAL',
      source: 'external-interop-slot',
      authorizedVerifierRole: 'COUNSEL',
      expirationOrReviewDateUtc: null,
      notes: 'External-chain verifier software exists. Security, conservation, relayer, incident, and legal reviews remain incomplete. No wrapped fiat.',
      externalEvidence: true,
      chunkReference: 'CHUNK-43',
      verificationStatus: 'NOT_PROVIDED',
    },
    {
      requirementId: 'REQ-PRIVACY-002',
      dimension: 'PRIVACY',
      description: 'Jurisdictional privacy analysis and human/legal review',
      scope: 'PRIVACY',
      evidenceType: 'COUNSEL_OPINION',
      source: 'external-privacy-slot',
      authorizedVerifierRole: 'COUNSEL',
      expirationOrReviewDateUtc: null,
      notes: 'PDV, consent, and Clean Room software exist in simulation. Residency, jurisdictional analysis, and legal review are not provided.',
      externalEvidence: true,
      chunkReference: null,
      verificationStatus: 'NOT_PROVIDED',
    },
    {
      requirementId: 'REQ-COMPLIANCE-001',
      dimension: 'COMPLIANCE',
      description: 'Kernel, screening fabric, and jurisdiction packs remain RESEARCH_REQUIRED',
      scope: 'COMPLIANCE',
      evidenceType: 'ENGINEERING_ARTIFACT',
      source: 'packages/kernel',
      authorizedVerifierRole: 'COUNSEL',
      expirationOrReviewDateUtc: null,
      notes: 'No policy rule is CONFIRMED_BY_COUNSEL.',
      externalEvidence: true,
      chunkReference: 'CHUNK-6',
      verificationStatus: 'EXTERNAL_VERIFICATION_REQUIRED',
    },
    {
      requirementId: 'REQ-LEGAL-001',
      dimension: 'LEGAL',
      description: 'Counsel opinion/reference for production operation',
      scope: 'ALL',
      evidenceType: 'COUNSEL_OPINION',
      source: 'external-legal-slot',
      authorizedVerifierRole: 'COUNSEL',
      expirationOrReviewDateUtc: null,
      notes: 'Unknown/unconfirmed. Do not mark CONFIRMED_BY_COUNSEL without genuine human counsel evidence.',
      externalEvidence: true,
      chunkReference: null,
      verificationStatus: 'NOT_PROVIDED',
    },
    {
      requirementId: 'REQ-REG-001',
      dimension: 'REGULATORY',
      description: 'Regulatory approval/reference for production operation',
      scope: 'ALL',
      evidenceType: 'REGULATORY_APPROVAL',
      source: 'external-regulatory-slot',
      authorizedVerifierRole: 'REGULATOR',
      expirationOrReviewDateUtc: null,
      notes: 'Unknown/unconfirmed. Current repository legal positions remain RESEARCH_REQUIRED.',
      externalEvidence: true,
      chunkReference: null,
      verificationStatus: 'NOT_PROVIDED',
    },
    {
      requirementId: 'REQ-LIC-001',
      dimension: 'LICENSING',
      description: 'License or registration evidence for regulated capabilities',
      scope: 'REGULATED_PRODUCTS',
      evidenceType: 'LICENSE_OR_REGISTRATION',
      source: 'external-licensing-slot',
      authorizedVerifierRole: 'COUNSEL',
      expirationOrReviewDateUtc: null,
      notes: 'No production license or registration is recorded.',
      externalEvidence: true,
      chunkReference: null,
      verificationStatus: 'NOT_PROVIDED',
    },
    {
      requirementId: 'REQ-PARTNER-001',
      dimension: 'PARTNER_DEPENDENCIES',
      description: 'Regulated partner agreements and real oracle/HSM/bank providers',
      scope: 'PARTNERS',
      evidenceType: 'PARTNER_AGREEMENT',
      source: 'external-partner-slot',
      authorizedVerifierRole: 'COUNSEL',
      expirationOrReviewDateUtc: null,
      notes: 'Development fixtures are not production feeds or banking partners.',
      externalEvidence: true,
      chunkReference: null,
      verificationStatus: 'NOT_PROVIDED',
    },
    {
      requirementId: 'REQ-HUMAN-001',
      dimension: 'HUMAN_AUTHORIZATION',
      description: 'Protocol, security, operations, and release authorities must sign',
      scope: 'ALL',
      evidenceType: 'HUMAN_AUTHORIZATION',
      source: 'packages/sunrey-chain/src/mainnet/authorization.ts',
      authorizedVerifierRole: 'HUMAN_AUTHORITY',
      expirationOrReviewDateUtc: null,
      notes: 'AI cannot sign. Absent human signatures keep the candidate unauthorized.',
      externalEvidence: true,
      chunkReference: 'CHUNK-65',
      verificationStatus: 'NOT_PROVIDED',
    },
    {
      requirementId: 'REQ-INFRA-001',
      dimension: 'INFRASTRUCTURE',
      description: 'Provider-neutral production infrastructure control plane',
      scope: 'SUNREY_CHAIN',
      evidenceType: 'ENGINEERING_ARTIFACT',
      source: 'packages/sunrey-chain/src/infra',
      authorizedVerifierRole: 'OPERATIONS',
      expirationOrReviewDateUtc: null,
      notes: 'Chunk 66 local provider harness is executable. Cloud adapters validate configuration without credentials. PRODUCTION_CANDIDATE does not activate mainnet.',
      externalEvidence: false,
      chunkReference: 'CHUNK-66',
      verificationStatus: 'ENGINEERING_VERIFIED',
      evidenceHash: digests.infraControlPlaneDigest,
      evidenceReference: `infra-control-plane:${digests.infraControlPlaneDigest}`,
    },
    {
      requirementId: 'REQ-INFRA-002',
      dimension: 'INFRASTRUCTURE',
      description: 'Workload identity, secret classes, network zones, and immutable release references',
      scope: 'SUNREY_CHAIN',
      evidenceType: 'SOFTWARE_TEST',
      source: 'packages/sunrey-chain/src/infra.test.ts',
      authorizedVerifierRole: 'SECURITY',
      expirationOrReviewDateUtc: null,
      notes: 'CI exercises SIMULATION_HSM and SOFTWARE_SECURE_PROVIDER only. External HSM verification remains incomplete.',
      externalEvidence: false,
      chunkReference: 'CHUNK-66',
      verificationStatus: 'ENGINEERING_VERIFIED',
      evidenceHash: digests.infraControlPlaneDigest,
      evidenceReference: `infra-security-tests:${digests.infraControlPlaneDigest}`,
    },
    {
      requirementId: 'REQ-DUAL-ECON-001',
      dimension: 'DUAL_ECONOMY_MODELING',
      description: 'Deterministic SunRey/MoonRey dual-economy simulator implemented',
      scope: 'SUNREY_CHAIN',
      evidenceType: 'SOFTWARE_TEST',
      source: 'packages/sunrey-economics',
      authorizedVerifierRole: 'ENGINEERING',
      expirationOrReviewDateUtc: null,
      notes: 'Chunk 75 engineering simulation. Not production monetary-policy activation or a price forecast.',
      externalEvidence: false,
      chunkReference: 'CHUNK-75',
      verificationStatus: 'ENGINEERING_VERIFIED',
    },
    {
      requirementId: 'REQ-DUAL-ECON-002',
      dimension: 'DUAL_ECONOMY_MODELING',
      description: 'Independent economic review of dual-economy simulation assumptions',
      scope: 'SUNREY_CHAIN',
      evidenceType: 'EXTERNAL_AUDIT_REPORT',
      source: 'external-economic-review-slot',
      authorizedVerifierRole: 'EXTERNAL_AUDITOR',
      expirationOrReviewDateUtc: null,
      notes: 'External economic review remains an explicit unfilled slot.',
      externalEvidence: true,
      chunkReference: 'CHUNK-75',
      verificationStatus: 'NOT_PROVIDED',
    },
    {
      requirementId: 'REQ-DUAL-ECON-003',
      dimension: 'DUAL_ECONOMY_MODELING',
      description: 'Human approval that simulation evidence may inform production policy',
      scope: 'SUNREY_CHAIN',
      evidenceType: 'HUMAN_AUTHORIZATION',
      source: 'human-economic-approval-slot',
      authorizedVerifierRole: 'HUMAN_AUTHORITY',
      expirationOrReviewDateUtc: null,
      notes: 'Human approval is not granted by software. Simulation is not production authorization.',
      externalEvidence: true,
      chunkReference: 'CHUNK-75',
      verificationStatus: 'NOT_PROVIDED',
    },
    {
      requirementId: 'REQ-ECON-STRESS-001',
      dimension: 'ECONOMIC_STRESS',
      description: 'Economic stack reconciled across Chunks 71–75',
      scope: 'SUNREY_CHAIN',
      evidenceType: 'SOFTWARE_TEST',
      source: 'packages/sunrey-chain/src/economics/stack.ts',
      authorizedVerifierRole: 'ENGINEERING',
      expirationOrReviewDateUtc: null,
      notes: 'Chunk 76 engineering reconciliation. Not production authorization.',
      externalEvidence: false,
      chunkReference: 'CHUNK-76',
      verificationStatus: 'ENGINEERING_VERIFIED',
    },
    {
      requirementId: 'REQ-ECON-STRESS-002',
      dimension: 'ECONOMIC_STRESS',
      description: 'Economic stress catalog implemented',
      scope: 'SUNREY_CHAIN',
      evidenceType: 'SOFTWARE_TEST',
      source: 'packages/sunrey-economics/src/stress/catalog.ts',
      authorizedVerifierRole: 'ENGINEERING',
      expirationOrReviewDateUtc: null,
      notes: 'At least 60 deterministic scenarios. Simulation only.',
      externalEvidence: false,
      chunkReference: 'CHUNK-76',
      verificationStatus: 'ENGINEERING_VERIFIED',
    },
    {
      requirementId: 'REQ-ECON-STRESS-003',
      dimension: 'ECONOMIC_STRESS',
      description: 'Critical invariant campaign',
      scope: 'SUNREY_CHAIN',
      evidenceType: 'SOFTWARE_TEST',
      source: 'packages/sunrey-economics/src/stress',
      authorizedVerifierRole: 'ENGINEERING',
      expirationOrReviewDateUtc: null,
      notes: 'Critical invariant campaign is engineering evidence only.',
      externalEvidence: false,
      chunkReference: 'CHUNK-76',
      verificationStatus: 'ENGINEERING_VERIFIED',
    },
    {
      requirementId: 'REQ-ECON-STRESS-004',
      dimension: 'ECONOMIC_STRESS',
      description: 'Compound scenario campaign',
      scope: 'SUNREY_CHAIN',
      evidenceType: 'SOFTWARE_TEST',
      source: 'packages/sunrey-economics/src/stress/catalog.ts',
      authorizedVerifierRole: 'ENGINEERING',
      expirationOrReviewDateUtc: null,
      notes: 'Compound energy/compute/liquidity, oracle/exchange/validator, and fee/custody/machine campaigns.',
      externalEvidence: false,
      chunkReference: 'CHUNK-76',
      verificationStatus: 'ENGINEERING_VERIFIED',
    },
    {
      requirementId: 'REQ-ECON-STRESS-005',
      dimension: 'ECONOMIC_STRESS',
      description: 'Extended campaign',
      scope: 'SUNREY_CHAIN',
      evidenceType: 'ENGINEERING_ARTIFACT',
      source: 'packages/sunrey-economics/src/stress/campaign.ts',
      authorizedVerifierRole: 'ENGINEERING',
      expirationOrReviewDateUtc: null,
      notes: '12/120/600 epoch campaigns are extended workflows, not ordinary PR CI.',
      externalEvidence: false,
      chunkReference: 'CHUNK-76',
      verificationStatus: 'ENGINEERING_VERIFIED',
    },
    {
      requirementId: 'REQ-ECON-STRESS-006',
      dimension: 'ECONOMIC_STRESS',
      description: 'Open critical findings',
      scope: 'SUNREY_CHAIN',
      evidenceType: 'ENGINEERING_ARTIFACT',
      source: 'packages/sunrey-economics/src/stress',
      authorizedVerifierRole: 'ENGINEERING',
      expirationOrReviewDateUtc: null,
      notes: 'Open critical findings remain an explicit engineering slot. Not a marketing score.',
      externalEvidence: false,
      chunkReference: 'CHUNK-76',
      verificationStatus: 'ENGINEERING_VERIFIED',
    },
    {
      requirementId: 'REQ-MONETARY-001',
      dimension: 'GENESIS',
      description: 'SunRey Coin monetary policy implementation',
      scope: 'SUNREY_COIN_NATIVE_ASSET',
      evidenceType: 'ENGINEERING_ARTIFACT',
      source: 'packages/sunrey-chain/src/economics',
      authorizedVerifierRole: 'ENGINEERING',
      expirationOrReviewDateUtc: null,
      notes: 'Chunk 71 constitution. Production quantities remain UNCONFIGURED.',
      externalEvidence: false,
      chunkReference: 'CHUNK-71',
      verificationStatus: 'ENGINEERING_VERIFIED',
    },
    {
      requirementId: 'REQ-MONETARY-002',
      dimension: 'GENESIS',
      description: 'MoonRey Coin monetary policy implementation',
      scope: 'MOONREY_COIN_NATIVE_ASSET',
      evidenceType: 'ENGINEERING_ARTIFACT',
      source: 'packages/sunrey-chain/src/economics',
      authorizedVerifierRole: 'ENGINEERING',
      expirationOrReviewDateUtc: null,
      notes: 'MoonRey remains bound to verified productive contribution. No admin mint.',
      externalEvidence: false,
      chunkReference: 'CHUNK-71',
      verificationStatus: 'ENGINEERING_VERIFIED',
    },
    {
      requirementId: 'REQ-MONETARY-003',
      dimension: 'GENESIS',
      description: 'Genesis supply configuration is zero unless separately approved',
      scope: 'SUNREY_CHAIN',
      evidenceType: 'ENGINEERING_ARTIFACT',
      source: 'packages/sunrey-chain/src/economics/genesis.ts',
      authorizedVerifierRole: 'ENGINEERING',
      expirationOrReviewDateUtc: null,
      notes: 'Zero-allocation production candidate. Non-zero quantities remain UNCONFIGURED.',
      externalEvidence: false,
      chunkReference: 'CHUNK-71',
      verificationStatus: 'ENGINEERING_VERIFIED',
    },
    {
      requirementId: 'REQ-MONETARY-004',
      dimension: 'HUMAN_AUTHORIZATION',
      description: 'Genesis allocation authorization',
      scope: 'SUNREY_CHAIN',
      evidenceType: 'HUMAN_AUTHORIZATION',
      source: 'packages/sunrey-chain/src/mainnet/authorization.ts',
      authorizedVerifierRole: 'HUMAN_AUTHORITY',
      expirationOrReviewDateUtc: null,
      notes: 'Non-zero production allocation requires a separately approved signed manifest. Absent.',
      externalEvidence: true,
      chunkReference: 'CHUNK-71',
      verificationStatus: 'NOT_PROVIDED',
    },
    {
      requirementId: 'REQ-MONETARY-005',
      dimension: 'GENESIS',
      description: 'Issuance authority authorization',
      scope: 'SUNREY_CHAIN',
      evidenceType: 'ENGINEERING_ARTIFACT',
      source: 'packages/sunrey-chain/src/economics/issuance.ts',
      authorizedVerifierRole: 'ENGINEERING',
      expirationOrReviewDateUtc: null,
      notes: 'MonetaryIssuanceAuthority is implemented. Production issuance remains UNCONFIGURED.',
      externalEvidence: false,
      chunkReference: 'CHUNK-71',
      verificationStatus: 'ENGINEERING_VERIFIED',
    },
    {
      requirementId: 'REQ-MONETARY-006',
      dimension: 'FORMAL_ASSURANCE',
      description: 'Native monetary policy and genesis allocation conservation models',
      scope: 'SUNREY_CHAIN',
      evidenceType: 'FORMAL_MODEL',
      source: 'packages/sunrey-chain/src/formal',
      authorizedVerifierRole: 'ENGINEERING',
      expirationOrReviewDateUtc: null,
      notes: 'NATIVE_MONETARY_POLICY and GENESIS_ALLOCATION_CONSERVATION are model-checked within stated bounds.',
      externalEvidence: false,
      chunkReference: 'CHUNK-71',
      verificationStatus: 'ENGINEERING_VERIFIED',
    },
    {
      requirementId: 'REQ-MONETARY-007',
      dimension: 'GENESIS',
      description: 'Economic simulation of dual-asset monetary constitution',
      scope: 'SUNREY_CHAIN',
      evidenceType: 'SOFTWARE_TEST',
      source: 'packages/sunrey-chain/src/economics/simulator.ts',
      authorizedVerifierRole: 'ENGINEERING',
      expirationOrReviewDateUtc: null,
      notes: 'Required ENGINEERING_SIMULATION scenarios executed. Not production tokenomics.',
      externalEvidence: false,
      chunkReference: 'CHUNK-71',
      verificationStatus: 'ENGINEERING_VERIFIED',
    },
    {
      requirementId: 'REQ-MONETARY-008',
      dimension: 'HUMAN_AUTHORIZATION',
      description: 'Human production approval of monetary quantities',
      scope: 'ALL',
      evidenceType: 'HUMAN_AUTHORIZATION',
      source: 'packages/sunrey-chain/src/mainnet/authorization.ts',
      authorizedVerifierRole: 'HUMAN_AUTHORITY',
      expirationOrReviewDateUtc: null,
      notes: 'Maximum supplies and allocation percentages remain UNCONFIGURED. AI cannot approve.',
      externalEvidence: true,
      chunkReference: 'CHUNK-71',
      verificationStatus: 'NOT_PROVIDED',
    },
    {
      requirementId: 'REQ-ECON-RC-001',
      dimension: 'RELEASE',
      description: 'SunRey economic testnet RC freeze and qualification evidence',
      scope: 'SUNREY_CHAIN',
      evidenceType: 'ENGINEERING_ARTIFACT',
      source: 'packages/sunrey-chain/src/release-candidate/economic',
      authorizedVerifierRole: 'ENGINEERING',
      expirationOrReviewDateUtc: null,
      notes: 'Chunk 78 economic RC is engineering qualification only. It does not authorize mainnet.',
      externalEvidence: false,
      chunkReference: 'CHUNK-78',
      verificationStatus: 'ENGINEERING_VERIFIED',
    },
    {
      requirementId: 'REQ-ECON-RC-002',
      dimension: 'HUMAN_AUTHORIZATION',
      description: 'External/human approval that economic RC may inform production activation',
      scope: 'SUNREY_CHAIN',
      evidenceType: 'HUMAN_AUTHORIZATION',
      source: 'human-economic-rc-approval-slot',
      authorizedVerifierRole: 'HUMAN_AUTHORITY',
      expirationOrReviewDateUtc: null,
      notes: 'Human and external approvals remain unfilled. Engineering qualification is not mainnet authorization.',
      externalEvidence: true,
      chunkReference: 'CHUNK-78',
      verificationStatus: 'NOT_PROVIDED',
    },
    {
      requirementId: 'REQ-GOVOPS-001',
      dimension: 'GOVERNANCE_OPERATIONS',
      description: 'Production governance operations package, preflight, and audit',
      scope: 'SUNREY_CHAIN',
      evidenceType: 'ENGINEERING_ARTIFACT',
      source: 'packages/sunrey-chain/src/governance-ops',
      authorizedVerifierRole: 'ENGINEERING',
      expirationOrReviewDateUtc: null,
      notes: 'Chunk 79 operational orchestration around Chunk 40. Not a governance token or second consensus engine.',
      externalEvidence: false,
      chunkReference: 'CHUNK-79',
      verificationStatus: 'ENGINEERING_VERIFIED',
    },
    {
      requirementId: 'REQ-GOVOPS-002',
      dimension: 'GOVERNANCE_OPERATIONS',
      description: 'Economic policy change package and canonical diff',
      scope: 'SUNREY_CHAIN',
      evidenceType: 'SOFTWARE_TEST',
      source: 'packages/sunrey-chain/src/governance-ops/diff.ts',
      authorizedVerifierRole: 'ENGINEERING',
      expirationOrReviewDateUtc: null,
      notes: 'Engineering control for future economic policy versions. Production quantities remain UNCONFIGURED.',
      externalEvidence: false,
      chunkReference: 'CHUNK-79',
      verificationStatus: 'ENGINEERING_VERIFIED',
    },
    {
      requirementId: 'REQ-GOVOPS-003',
      dimension: 'GOVERNANCE_OPERATIONS',
      description: 'Bounded emergency authority catalog and evidence',
      scope: 'SUNREY_CHAIN',
      evidenceType: 'SOFTWARE_TEST',
      source: 'packages/sunrey-chain/src/governance-ops/engine.ts',
      authorizedVerifierRole: 'SECURITY',
      expirationOrReviewDateUtc: null,
      notes: 'Emergency actions cannot mint, rewrite supply, confiscate wallets, or rewrite finalized history.',
      externalEvidence: false,
      chunkReference: 'CHUNK-79',
      verificationStatus: 'ENGINEERING_VERIFIED',
    },
    {
      requirementId: 'REQ-GOVOPS-004',
      dimension: 'HUMAN_AUTHORIZATION',
      description: 'Human multi-person approval architecture for governance operations',
      scope: 'SUNREY_CHAIN',
      evidenceType: 'ENGINEERING_ARTIFACT',
      source: 'packages/sunrey-chain/src/governance-ops/engine.ts',
      authorizedVerifierRole: 'ENGINEERING',
      expirationOrReviewDateUtc: null,
      notes: 'Software records the approval architecture. AI cannot sign. Production human signatures remain unfilled.',
      externalEvidence: false,
      chunkReference: 'CHUNK-79',
      verificationStatus: 'ENGINEERING_VERIFIED',
    },
    {
      requirementId: 'REQ-GOVOPS-005',
      dimension: 'GOVERNANCE_OPERATIONS',
      description: 'External legal approval of production governance operations',
      scope: 'SUNREY_CHAIN',
      evidenceType: 'COUNSEL_OPINION',
      source: 'external-governance-counsel-slot',
      authorizedVerifierRole: 'COUNSEL',
      expirationOrReviewDateUtc: null,
      notes: 'External legal approval is not provided and is not invented by software.',
      externalEvidence: true,
      chunkReference: 'CHUNK-79',
      verificationStatus: 'NOT_PROVIDED',
    },
    {
      requirementId: 'REQ-TREASURY-001',
      dimension: 'GENESIS',
      description: 'Protocol treasury policy and reserve classifications',
      scope: 'SUNREY_CHAIN',
      evidenceType: 'ENGINEERING_ARTIFACT',
      source: 'packages/sunrey-chain/src/economics/treasury',
      authorizedVerifierRole: 'ENGINEERING',
      expirationOrReviewDateUtc: null,
      notes: 'Chunk 77 native protocol treasury. Distinct from packages/treasury. Production treasury inactive.',
      externalEvidence: false,
      chunkReference: 'CHUNK-77',
      verificationStatus: 'ENGINEERING_VERIFIED',
    },
    {
      requirementId: 'REQ-TREASURY-002',
      dimension: 'GENESIS',
      description: 'Treasury spending policy and budget governance',
      scope: 'SUNREY_CHAIN',
      evidenceType: 'ENGINEERING_ARTIFACT',
      source: 'packages/sunrey-chain/src/economics/treasury/policy.ts',
      authorizedVerifierRole: 'ENGINEERING',
      expirationOrReviewDateUtc: null,
      notes: 'Versioned ProtocolTreasuryPolicy. Historical budgets keep the policy active for their authorized lifecycle.',
      externalEvidence: false,
      chunkReference: 'CHUNK-77',
      verificationStatus: 'ENGINEERING_VERIFIED',
    },
    {
      requirementId: 'REQ-TREASURY-003',
      dimension: 'SECURITY_TESTING',
      description: 'Treasury stress catalog and property reconciliation',
      scope: 'SUNREY_CHAIN',
      evidenceType: 'SOFTWARE_TEST',
      source: 'packages/sunrey-chain/src/economics/treasury/stress.ts',
      authorizedVerifierRole: 'ENGINEERING',
      expirationOrReviewDateUtc: null,
      notes: 'Budget exhaustion, duplicate disbursement, unauthorized recipient, wrong asset, reservation race, fee collapse, emergency expense.',
      externalEvidence: false,
      chunkReference: 'CHUNK-77',
      verificationStatus: 'ENGINEERING_VERIFIED',
    },
    {
      requirementId: 'REQ-TREASURY-004',
      dimension: 'FORMAL_ASSURANCE',
      description: 'Formal PROTOCOL_TREASURY model result',
      scope: 'SUNREY_CHAIN',
      evidenceType: 'FORMAL_MODEL',
      source: 'packages/sunrey-chain/src/formal',
      authorizedVerifierRole: 'ENGINEERING',
      expirationOrReviewDateUtc: null,
      notes: 'PROTOCOL_TREASURY is model-checked within stated bounds.',
      externalEvidence: false,
      chunkReference: 'CHUNK-77',
      verificationStatus: 'ENGINEERING_VERIFIED',
    },
    {
      requirementId: 'REQ-TREASURY-005',
      dimension: 'GENESIS',
      description: 'Production treasury limits remain unconfigured',
      scope: 'SUNREY_CHAIN',
      evidenceType: 'ENGINEERING_ARTIFACT',
      source: 'packages/sunrey-chain/src/economics/treasury/policy.ts',
      authorizedVerifierRole: 'ENGINEERING',
      expirationOrReviewDateUtc: null,
      notes: 'Production limits stay UNCONFIGURED unless separately approved. Production treasury inactive.',
      externalEvidence: false,
      chunkReference: 'CHUNK-77',
      verificationStatus: 'ENGINEERING_VERIFIED',
    },
    {
      requirementId: 'REQ-TREASURY-006',
      dimension: 'HUMAN_AUTHORIZATION',
      description: 'Human authorization of production treasury activation',
      scope: 'ALL',
      evidenceType: 'HUMAN_AUTHORIZATION',
      source: 'packages/sunrey-chain/src/mainnet/authorization.ts',
      authorizedVerifierRole: 'HUMAN_AUTHORITY',
      expirationOrReviewDateUtc: null,
      notes: 'AI cannot vote, approve, authorize transfer, or activate reserve policy.',
      externalEvidence: true,
      chunkReference: 'CHUNK-77',
      verificationStatus: 'NOT_PROVIDED',
    },
    {
      requirementId: 'REQ-TREASURY-007',
      dimension: 'HUMAN_AUTHORIZATION',
      description: 'Governance approval of production treasury policy',
      scope: 'ALL',
      evidenceType: 'HUMAN_AUTHORIZATION',
      source: 'packages/sunrey-chain/src/governance',
      authorizedVerifierRole: 'HUMAN_AUTHORITY',
      expirationOrReviewDateUtc: null,
      notes: 'AI cannot approve. Production treasury remains inactive.',
      externalEvidence: true,
      chunkReference: 'CHUNK-77',
      verificationStatus: 'NOT_PROVIDED',
    },
    {
      requirementId: 'REQ-PROVIDER-001',
      dimension: 'PARTNER_DEPENDENCIES',
      description: 'Chunk 82 external production provider acceptance harness',
      scope: 'PARTNERS',
      evidenceType: 'SOFTWARE_TEST',
      source: 'packages/sunrey-chain/src/providers',
      authorizedVerifierRole: 'ENGINEERING',
      expirationOrReviewDateUtc: null,
      notes: 'Local/sandbox provider acceptance only. External contracts, licenses, and commercial HSM evidence remain unfilled.',
      externalEvidence: false,
      chunkReference: 'CHUNK-82',
      verificationStatus: 'ENGINEERING_VERIFIED',
    },
    {
      requirementId: 'REQ-PROVIDER-002',
      dimension: 'PARTNER_DEPENDENCIES',
      description: 'External provider contracts, licenses, and commercial rights',
      scope: 'PARTNERS',
      evidenceType: 'PARTNER_AGREEMENT',
      source: 'external-provider-slot',
      authorizedVerifierRole: 'COUNSEL',
      expirationOrReviewDateUtc: null,
      notes: 'No fabricated partner agreement. Missing contract stays missing. Technical oracle success does not prove data rights.',
      externalEvidence: true,
      chunkReference: 'CHUNK-82',
      verificationStatus: 'NOT_PROVIDED',
    },
    {
      requirementId: 'REQ-PROVIDER-003',
      dimension: 'HUMAN_AUTHORIZATION',
      description: 'Human acceptance of external production providers',
      scope: 'PARTNERS',
      evidenceType: 'HUMAN_AUTHORIZATION',
      source: 'packages/sunrey-chain/src/providers/evaluation.ts',
      authorizedVerifierRole: 'HUMAN_AUTHORITY',
      expirationOrReviewDateUtc: null,
      notes: 'AI cannot mark HUMAN_ACCEPTED or PRODUCTION_ELIGIBLE.',
      externalEvidence: true,
      chunkReference: 'CHUNK-82',
      verificationStatus: 'NOT_PROVIDED',
    },
    {
      requirementId: 'REQ-ECON-REHEARSAL-001',
      dimension: 'GENESIS',
      description: 'Chunk 80 economic mainnet rehearsal engineering evidence',
      scope: 'SUNREY_CHAIN',
      evidenceType: 'SOFTWARE_TEST',
      source: 'packages/sunrey-chain/src/economic-rehearsal',
      authorizedVerifierRole: 'ENGINEERING',
      expirationOrReviewDateUtc: null,
      notes: 'Integrated rehearsal over canonical Chunks 76–79. Distinct rehearsal identity. Not production genesis.',
      externalEvidence: false,
      chunkReference: 'CHUNK-80',
      verificationStatus: 'ENGINEERING_VERIFIED',
    },
    {
      requirementId: 'REQ-ECON-REHEARSAL-002',
      dimension: 'HUMAN_AUTHORIZATION',
      description: 'Human authorization that economic rehearsal may inform production activation',
      scope: 'ALL',
      evidenceType: 'HUMAN_AUTHORIZATION',
      source: 'human-economic-rehearsal-approval-slot',
      authorizedVerifierRole: 'HUMAN_AUTHORITY',
      expirationOrReviewDateUtc: null,
      notes: 'Rehearsal classification does not authorize production. External/human slots remain unfilled.',
      externalEvidence: true,
      chunkReference: 'CHUNK-80',
      verificationStatus: 'NOT_PROVIDED',
    },
    {
      requirementId: 'REQ-CANDIDATE-V2-001',
      dimension: 'RELEASE',
      description: 'SunRey production network candidate v2 deterministic binding',
      scope: 'SUNREY_CHAIN',
      evidenceType: 'ENGINEERING_ARTIFACT',
      source: 'packages/sunrey-chain/src/mainnet/candidate-v2',
      authorizedVerifierRole: 'ENGINEERING',
      expirationOrReviewDateUtc: null,
      notes: 'Chunk 81 candidate remains CANDIDATE. mainnetEnabled=false. productionAuthorized=false.',
      externalEvidence: false,
      chunkReference: 'CHUNK-81',
      verificationStatus: 'ENGINEERING_VERIFIED',
    },
    {
      requirementId: 'REQ-CANDIDATE-V2-002',
      dimension: 'EXTERNAL_SECURITY_REVIEW',
      description: 'Independent production audit for candidate v2',
      scope: 'ALL',
      evidenceType: 'EXTERNAL_AUDIT_REPORT',
      source: 'external-production-audit-slot',
      authorizedVerifierRole: 'EXTERNAL_AUDITOR',
      expirationOrReviewDateUtc: null,
      notes: 'Missing independent audit remains missing. Software cannot convert absence into approved evidence.',
      externalEvidence: true,
      chunkReference: 'CHUNK-81',
      verificationStatus: 'NOT_PROVIDED',
    },
    {
      requirementId: 'REQ-CANDIDATE-V2-003',
      dimension: 'HUMAN_AUTHORIZATION',
      description: 'Human production authorization of candidate v2',
      scope: 'ALL',
      evidenceType: 'HUMAN_AUTHORIZATION',
      source: 'human-production-authorization-slot',
      authorizedVerifierRole: 'HUMAN_AUTHORITY',
      expirationOrReviewDateUtc: null,
      notes: 'AI production authorization is rejected. Human authorization remains NOT_PROVIDED.',
      externalEvidence: true,
      chunkReference: 'CHUNK-81',
      verificationStatus: 'NOT_PROVIDED',
    },
  ];
  return Object.freeze([...drafts.map((draft) => slot(draft, overlay)), ...mainnetRcReadinessRecords()]);
}

export function dimensionsCovered(): readonly MainnetReadinessDimension[] {
  return READINESS_DIMENSIONS;
}
