/**
 * Machine-readable readiness dimension catalog and default evidence slots.
 */

import type { MainnetReadinessDimension, ReadinessEvidenceRecord } from './types.ts';
import { READINESS_DIMENSIONS } from './types.ts';
import { freezeEvidence } from './evidence.ts';

type SlotDraft = Omit<ReadinessEvidenceRecord, 'verificationStatus' | 'evidenceHash' | 'evidenceReference'> & {
  readonly verificationStatus?: ReadinessEvidenceRecord['verificationStatus'];
  readonly evidenceHash?: string | null;
  readonly evidenceReference?: string | null;
};

function slot(draft: SlotDraft): ReadinessEvidenceRecord {
  return freezeEvidence({
    ...draft,
    evidenceHash: draft.evidenceHash ?? null,
    evidenceReference: draft.evidenceReference ?? null,
    verificationStatus: draft.verificationStatus ?? 'NOT_PROVIDED',
  });
}

export function defaultDimensionCatalog(): readonly ReadinessEvidenceRecord[] {
  const drafts: SlotDraft[] = [
    {
      requirementId: 'REQ-PROTOCOL-001',
      dimension: 'PROTOCOL',
      description: 'Canonical transaction protocol and codec remain the Chunk 32R owner',
      scope: 'SUNREY_CHAIN',
      evidenceType: 'ENGINEERING_ARTIFACT',
      source: 'packages/sunrey-chain/src/protocol',
      authorizedVerifierRole: 'ENGINEERING',
      expirationOrReviewDateUtc: null,
      notes: 'Engineering implementation evidence. Not a production launch.',
      externalEvidence: false,
      chunkReference: 'CHUNK-32',
      verificationStatus: 'ENGINEERING_VERIFIED',
    },
    {
      requirementId: 'REQ-CONSENSUS-001',
      dimension: 'CONSENSUS',
      description: 'Development Tendermint-class BFT exists; production consensus is not activated',
      scope: 'SUNREY_CHAIN',
      evidenceType: 'SOFTWARE_TEST',
      source: 'packages/sunrey-chain/rust/crates/consensus',
      authorizedVerifierRole: 'ENGINEERING',
      expirationOrReviewDateUtc: null,
      notes: 'Development consensus only. Production BFT remains disabled.',
      externalEvidence: false,
      chunkReference: 'CHUNK-37',
      verificationStatus: 'ENGINEERING_VERIFIED',
    },
    {
      requirementId: 'REQ-FORMAL-001',
      dimension: 'FORMAL_ASSURANCE',
      description: 'Formal model versions, bounds, properties, counterexamples, report digest',
      scope: 'SUNREY_CHAIN',
      evidenceType: 'FORMAL_MODEL',
      source: 'chunk-61-slot',
      authorizedVerifierRole: 'EXTERNAL_AUDITOR',
      expirationOrReviewDateUtc: null,
      notes: 'Chunk 61 formal assurance is not implemented on this tree. Slot reserved. Formal assurance is not a substitute for implementation or security review.',
      externalEvidence: true,
      chunkReference: 'CHUNK-61',
      verificationStatus: 'NOT_PROVIDED',
    },
    {
      requirementId: 'REQ-SECURITY-TEST-001',
      dimension: 'SECURITY_TESTING',
      description: 'Fuzz corpus, property campaigns, and adversarial-range invariant status',
      scope: 'SUNREY_CHAIN',
      evidenceType: 'SOFTWARE_TEST',
      source: 'packages/sunrey-chain/src/assurance + packages/sunrey-range',
      authorizedVerifierRole: 'SECURITY',
      expirationOrReviewDateUtc: null,
      notes: 'Chunks 56 and 57 engineering tests. Not an independent audit.',
      externalEvidence: false,
      chunkReference: 'CHUNK-56',
      verificationStatus: 'ENGINEERING_VERIFIED',
    },
    {
      requirementId: 'REQ-EXT-SEC-001',
      dimension: 'EXTERNAL_SECURITY_REVIEW',
      description: 'Independent review organization, scope, report hash, open critical/high, retest',
      scope: 'SUNREY_CHAIN',
      evidenceType: 'EXTERNAL_AUDIT_REPORT',
      source: 'chunk-62-slot',
      authorizedVerifierRole: 'EXTERNAL_AUDITOR',
      expirationOrReviewDateUtc: null,
      notes: 'No external audit report exists in this repository. Do not invent one.',
      externalEvidence: true,
      chunkReference: 'CHUNK-62',
      verificationStatus: 'NOT_PROVIDED',
    },
    {
      requirementId: 'REQ-CRYPTO-001',
      dimension: 'CRYPTOGRAPHY',
      description: 'CryptoPolicy reflects actually supported suites and providers',
      scope: 'SUNREY_CHAIN',
      evidenceType: 'ENGINEERING_ARTIFACT',
      source: 'packages/security',
      authorizedVerifierRole: 'SECURITY',
      expirationOrReviewDateUtc: null,
      notes: 'Production consensus is not configured to require unsupported PQ/HSM combinations.',
      externalEvidence: false,
      chunkReference: 'CHUNK-60',
      verificationStatus: 'ENGINEERING_VERIFIED',
    },
    {
      requirementId: 'REQ-PQC-001',
      dimension: 'PQC',
      description: 'Record actual PQ roles and providers; production PQ/HSM remains unselected',
      scope: 'SUNREY_CHAIN',
      evidenceType: 'ENGINEERING_ARTIFACT',
      source: 'packages/security/src/pqc-library-selection.ts',
      authorizedVerifierRole: 'SECURITY',
      expirationOrReviewDateUtc: null,
      notes: 'PQC software is not production HSM PQC capability. productionStatus=NOT_SELECTED_FOR_PRODUCTION.',
      externalEvidence: false,
      chunkReference: 'CHUNK-60',
      verificationStatus: 'ENGINEERING_VERIFIED',
    },
    {
      requirementId: 'REQ-SUPPLY-001',
      dimension: 'SUPPLY_CHAIN',
      description: 'Release artifact hashes, SBOM, provenance, dependency audit, reproducibility, signature',
      scope: 'SUNREY_CHAIN',
      evidenceType: 'RELEASE_ARTIFACT',
      source: 'packages/sunrey-chain/src/supply-chain',
      authorizedVerifierRole: 'RELEASE',
      expirationOrReviewDateUtc: null,
      notes: 'Chunk 59 engineering supply-chain. Production cosign/HSM release key is not present.',
      externalEvidence: false,
      chunkReference: 'CHUNK-59',
      verificationStatus: 'ENGINEERING_VERIFIED',
    },
    {
      requirementId: 'REQ-RELEASE-001',
      dimension: 'RELEASE',
      description: 'ReleaseAuthority signs artifacts only and does not activate protocol change',
      scope: 'SUNREY_CHAIN',
      evidenceType: 'RELEASE_ARTIFACT',
      source: 'packages/sunrey-chain/src/supply-chain/release.ts',
      authorizedVerifierRole: 'RELEASE',
      expirationOrReviewDateUtc: null,
      notes: 'Software release approval is not network launch.',
      externalEvidence: false,
      chunkReference: 'CHUNK-59',
      verificationStatus: 'ENGINEERING_VERIFIED',
    },
    {
      requirementId: 'REQ-VALOPS-001',
      dimension: 'VALIDATOR_OPERATIONS',
      description: 'Operator infrastructure, sentry, signer safety, join/exit workflows',
      scope: 'SUNREY_CHAIN',
      evidenceType: 'ENGINEERING_ARTIFACT',
      source: 'packages/sunrey-chain/src/ops',
      authorizedVerifierRole: 'OPERATIONS',
      expirationOrReviewDateUtc: null,
      notes: 'Engineering operator tooling. Not a production operations contract.',
      externalEvidence: false,
      chunkReference: 'CHUNK-54',
      verificationStatus: 'ENGINEERING_VERIFIED',
    },
    {
      requirementId: 'REQ-ROT-001',
      dimension: 'ROOT_OF_TRUST',
      description: 'Real external ceremony reference when it occurs; simulation is process readiness only',
      scope: 'SUNREY_CHAIN',
      evidenceType: 'CEREMONY_TRANSCRIPT',
      source: 'chunk-64-slot',
      authorizedVerifierRole: 'SECURITY',
      expirationOrReviewDateUtc: null,
      notes: 'Simulation rehearsal is evidence of process readiness, not proof of real production key creation.',
      externalEvidence: true,
      chunkReference: 'CHUNK-64',
      verificationStatus: 'EXTERNAL_VERIFICATION_REQUIRED',
    },
    {
      requirementId: 'REQ-GENESIS-001',
      dimension: 'GENESIS',
      description: 'Deterministic genesis candidate with explicit zero/authorized allocation',
      scope: 'SUNREY_CHAIN',
      evidenceType: 'ENGINEERING_ARTIFACT',
      source: 'packages/sunrey-chain/src/mainnet/genesis-candidate.ts',
      authorizedVerifierRole: 'ENGINEERING',
      expirationOrReviewDateUtc: null,
      notes: 'Candidate only. Does not publish production genesis.',
      externalEvidence: false,
      chunkReference: 'CHUNK-65',
      verificationStatus: 'ENGINEERING_VERIFIED',
    },
    {
      requirementId: 'REQ-OBS-001',
      dimension: 'OBSERVABILITY',
      description: 'Operator observability and privacy-safe telemetry',
      scope: 'SUNREY_CHAIN',
      evidenceType: 'ENGINEERING_ARTIFACT',
      source: 'packages/sunrey-chain/src/ops',
      authorizedVerifierRole: 'OPERATIONS',
      expirationOrReviewDateUtc: null,
      notes: 'Engineering observability. Not a production SLO contract.',
      externalEvidence: false,
      chunkReference: 'CHUNK-55',
      verificationStatus: 'ENGINEERING_VERIFIED',
    },
    {
      requirementId: 'REQ-DR-001',
      dimension: 'DISASTER_RECOVERY',
      description: 'Backup, restore verification, and DR drills',
      scope: 'SUNREY_CHAIN',
      evidenceType: 'SOFTWARE_TEST',
      source: 'packages/sunrey-chain/src/ops',
      authorizedVerifierRole: 'OPERATIONS',
      expirationOrReviewDateUtc: null,
      notes: 'Engineering DR drills. Not a contractual recovery commitment.',
      externalEvidence: false,
      chunkReference: 'CHUNK-55',
      verificationStatus: 'ENGINEERING_VERIFIED',
    },
    {
      requirementId: 'REQ-PERF-001',
      dimension: 'PERFORMANCE',
      description: 'Measured testnet engineering results and capacity assumptions',
      scope: 'SUNREY_CHAIN',
      evidenceType: 'CAPACITY_MEASUREMENT',
      source: 'packages/sunrey-chain/src/perf',
      authorizedVerifierRole: 'ENGINEERING',
      expirationOrReviewDateUtc: null,
      notes: 'ENGINEERING_MEASUREMENT only. Not a contractual performance promise.',
      externalEvidence: false,
      chunkReference: 'CHUNK-58',
      verificationStatus: 'ENGINEERING_VERIFIED',
    },
    {
      requirementId: 'REQ-PRIVACY-001',
      dimension: 'PRIVACY',
      description: 'PDV, consent, Clean Room, residency, retention, deletion, jurisdictional analysis',
      scope: 'PRIVACY',
      evidenceType: 'ENGINEERING_ARTIFACT',
      source: 'packages/personal-data-vault + packages/consent + packages/clean-room',
      authorizedVerifierRole: 'COUNSEL',
      expirationOrReviewDateUtc: null,
      notes: 'Software privacy controls exist in simulation. Jurisdictional privacy analysis and legal review are not provided.',
      externalEvidence: true,
      chunkReference: 'CHUNK-23',
      verificationStatus: 'EXTERNAL_VERIFICATION_REQUIRED',
    },
    {
      requirementId: 'REQ-CUSTODY-001',
      dimension: 'CUSTODY',
      description: 'Real HSM/provider, ceremony, segregation, reconciliation, withdrawal approval, DR, licensing',
      scope: 'INSTITUTIONAL_CUSTODY',
      evidenceType: 'ENGINEERING_ARTIFACT',
      source: 'packages/custody',
      authorizedVerifierRole: 'COUNSEL',
      expirationOrReviewDateUtc: null,
      notes: 'Simulation HSM does not satisfy real-provider evidence. Software custody is not a licensed custody business.',
      externalEvidence: true,
      chunkReference: 'CHUNK-47',
      verificationStatus: 'EXTERNAL_VERIFICATION_REQUIRED',
    },
    {
      requirementId: 'REQ-EXCHANGE-001',
      dimension: 'EXCHANGE',
      description: 'Custody, surveillance, listing, Travel Rule, licensing, staffing, security review',
      scope: 'SUNREY_EXCHANGE',
      evidenceType: 'ENGINEERING_ARTIFACT',
      source: 'packages/sunrey-exchange',
      authorizedVerifierRole: 'COUNSEL',
      expirationOrReviewDateUtc: null,
      notes: 'Software exchange is not a licensed exchange. Implementation alone is insufficient.',
      externalEvidence: true,
      chunkReference: 'CHUNK-29',
      verificationStatus: 'EXTERNAL_VERIFICATION_REQUIRED',
    },
    {
      requirementId: 'REQ-COMPLIANCE-001',
      dimension: 'COMPLIANCE',
      description: 'Kernel, screening fabric, and jurisdiction packs remain RESEARCH_REQUIRED',
      scope: 'COMPLIANCE',
      evidenceType: 'ENGINEERING_ARTIFACT',
      source: 'packages/kernel',
      authorizedVerifierRole: 'COUNSEL',
      expirationOrReviewDateUtc: null,
      notes: 'No policy rule is CONFIRMED_BY_COUNSEL.',
      externalEvidence: true,
      chunkReference: 'CHUNK-6',
      verificationStatus: 'EXTERNAL_VERIFICATION_REQUIRED',
    },
    {
      requirementId: 'REQ-LEGAL-001',
      dimension: 'LEGAL',
      description: 'Counsel opinion/reference for production operation',
      scope: 'ALL',
      evidenceType: 'COUNSEL_OPINION',
      source: 'external-legal-slot',
      authorizedVerifierRole: 'COUNSEL',
      expirationOrReviewDateUtc: null,
      notes: 'Unknown/unconfirmed. Do not mark CONFIRMED_BY_COUNSEL without genuine human counsel evidence.',
      externalEvidence: true,
      chunkReference: null,
      verificationStatus: 'NOT_PROVIDED',
    },
    {
      requirementId: 'REQ-REG-001',
      dimension: 'REGULATORY',
      description: 'Regulatory approval/reference for production operation',
      scope: 'ALL',
      evidenceType: 'REGULATORY_APPROVAL',
      source: 'external-regulatory-slot',
      authorizedVerifierRole: 'REGULATOR',
      expirationOrReviewDateUtc: null,
      notes: 'Unknown/unconfirmed. Current repository legal positions remain RESEARCH_REQUIRED.',
      externalEvidence: true,
      chunkReference: null,
      verificationStatus: 'NOT_PROVIDED',
    },
    {
      requirementId: 'REQ-LIC-001',
      dimension: 'LICENSING',
      description: 'License or registration evidence for regulated capabilities',
      scope: 'REGULATED_PRODUCTS',
      evidenceType: 'LICENSE_OR_REGISTRATION',
      source: 'external-licensing-slot',
      authorizedVerifierRole: 'COUNSEL',
      expirationOrReviewDateUtc: null,
      notes: 'No production license or registration is recorded.',
      externalEvidence: true,
      chunkReference: null,
      verificationStatus: 'NOT_PROVIDED',
    },
    {
      requirementId: 'REQ-PARTNER-001',
      dimension: 'PARTNER_DEPENDENCIES',
      description: 'Regulated partner agreements and real oracle/HSM/bank providers',
      scope: 'PARTNERS',
      evidenceType: 'PARTNER_AGREEMENT',
      source: 'external-partner-slot',
      authorizedVerifierRole: 'COUNSEL',
      expirationOrReviewDateUtc: null,
      notes: 'Development fixtures are not production feeds or banking partners.',
      externalEvidence: true,
      chunkReference: null,
      verificationStatus: 'NOT_PROVIDED',
    },
    {
      requirementId: 'REQ-HUMAN-001',
      dimension: 'HUMAN_AUTHORIZATION',
      description: 'Protocol, security, operations, and release authorities must sign',
      scope: 'ALL',
      evidenceType: 'HUMAN_AUTHORIZATION',
      source: 'packages/sunrey-chain/src/mainnet/authorization.ts',
      authorizedVerifierRole: 'HUMAN_AUTHORITY',
      expirationOrReviewDateUtc: null,
      notes: 'AI cannot sign. Absent human signatures keep the candidate unauthorized.',
      externalEvidence: true,
      chunkReference: 'CHUNK-65',
      verificationStatus: 'NOT_PROVIDED',
    },
  ];
  return Object.freeze(drafts.map(slot));
}

export function dimensionsCovered(): readonly MainnetReadinessDimension[] {
  return READINESS_DIMENSIONS;
}
