/** HELIOS H30 — Supervisory access and regulated change governance taxonomy. */

export const SUPERVISORY_ROLES = [
  'COMPLIANCE',
  'LEGAL',
  'AUDIT',
  'SUPERVISORY_ADMIN',
] as const;
export type SupervisoryRole = (typeof SUPERVISORY_ROLES)[number];

export const EXPORT_MODES = [
  'INTERNAL_REVIEW',
  'REGULATOR_EXPORT',
  'AUDIT_EXPORT',
] as const;
export type ExportMode = (typeof EXPORT_MODES)[number];

export const EXPORT_APPROVAL_STATES = [
  'PENDING',
  'APPROVED',
  'DENIED',
  'EXPIRED',
] as const;
export type ExportApprovalState = (typeof EXPORT_APPROVAL_STATES)[number];

export const ARTIFACT_CLASSES = [
  'LEGAL_ENTITY',
  'JURISDICTION',
  'CAPABILITY_VERSION',
  'CUSTOMER_ACCOUNT',
  'ACTION_DECISION_TIMELINE',
  'MANDATE_APPROVAL',
  'RISK_COMPLIANCE_DECISION',
  'MODEL_STRATEGY_VERSION',
  'FINANCIAL_LIFECYCLE',
  'FEES',
  'SETTLEMENT_RECONCILIATION',
  'REPORTING_STATUS',
  'EVIDENCE_HASHES',
  'SOFTWARE_CONTROL_VERSIONS',
  'TEST_EVIDENCE',
] as const;
export type ArtifactClass = (typeof ARTIFACT_CLASSES)[number];

export const CHANGE_REQUEST_STATES = [
  'OFFICIAL_SOURCE_CAPTURED',
  'APPLICABILITY_ASSESSMENT',
  'LEGAL_COMPLIANCE_REVIEW',
  'POLICY_CHANGE_PROPOSED',
  'TESTS_REQUIRED',
  'TESTS_PASSED',
  'APPROVAL_REQUIRED',
  'SCHEDULED',
  'ACTIVATED',
  'MONITORED',
  'REJECTED',
  'DEFERRED',
  'REVIEW_REQUIRED',
  'ROLLBACK_REQUIRED',
] as const;
export type ChangeRequestState = (typeof CHANGE_REQUEST_STATES)[number];

export const OFFICIAL_SOURCE_KINDS = [
  'REGULATOR_PUBLICATION',
  'LEGISLATION',
  'LEGAL_MEMO',
  'COUNSEL_DECISION',
] as const;
export type OfficialSourceKind = (typeof OFFICIAL_SOURCE_KINDS)[number];

export const UNOFFICIAL_SOURCE_KINDS = [
  'SOCIAL_MEDIA',
  'MODEL_OUTPUT',
  'UNSOURCED_SUMMARY',
  'UNOFFICIAL_ARTICLE',
] as const;
export type UnofficialSourceKind = (typeof UNOFFICIAL_SOURCE_KINDS)[number];

export const ACTIVATION_MODES = ['IMMEDIATE', 'SCHEDULED_EFFECTIVE_DATE'] as const;
export type ActivationMode = (typeof ACTIVATION_MODES)[number];

export const ACTOR_KINDS = ['HUMAN', 'AI'] as const;
export type ActorKind = (typeof ACTOR_KINDS)[number];

export const REDACTION_RULE_VERSION = 'helios-redaction-v1' as const;
export const REGULATORY_TRANSPARENCY_POLICY_VERSION = 'helios-regulatory-transparency-v1' as const;

export const HELIOS_REGULATORY_TRANSPARENCY_QUALIFIED =
  'HELIOS_REGULATORY_TRANSPARENCY_QUALIFIED' as const;
export const HELIOS_REGULATORY_TRANSPARENCY_BLOCKED =
  'HELIOS_REGULATORY_TRANSPARENCY_BLOCKED' as const;

/** Valid forward transitions in the regulated change lifecycle. */
export const CHANGE_STATE_TRANSITIONS: Readonly<
  Record<ChangeRequestState, readonly ChangeRequestState[]>
> = Object.freeze({
  OFFICIAL_SOURCE_CAPTURED: ['APPLICABILITY_ASSESSMENT', 'REJECTED', 'DEFERRED'],
  APPLICABILITY_ASSESSMENT: ['LEGAL_COMPLIANCE_REVIEW', 'REVIEW_REQUIRED', 'REJECTED', 'DEFERRED'],
  LEGAL_COMPLIANCE_REVIEW: ['POLICY_CHANGE_PROPOSED', 'REVIEW_REQUIRED', 'REJECTED', 'DEFERRED'],
  POLICY_CHANGE_PROPOSED: ['TESTS_REQUIRED', 'REJECTED', 'DEFERRED'],
  TESTS_REQUIRED: ['TESTS_PASSED', 'REJECTED', 'REVIEW_REQUIRED'],
  TESTS_PASSED: ['APPROVAL_REQUIRED', 'REJECTED'],
  APPROVAL_REQUIRED: ['SCHEDULED', 'ACTIVATED', 'REJECTED', 'REVIEW_REQUIRED'],
  SCHEDULED: ['ACTIVATED', 'REJECTED', 'DEFERRED'],
  ACTIVATED: ['MONITORED', 'ROLLBACK_REQUIRED'],
  MONITORED: ['ROLLBACK_REQUIRED'],
  REJECTED: [],
  DEFERRED: ['OFFICIAL_SOURCE_CAPTURED'],
  REVIEW_REQUIRED: ['APPLICABILITY_ASSESSMENT', 'LEGAL_COMPLIANCE_REVIEW', 'REJECTED'],
  ROLLBACK_REQUIRED: ['POLICY_CHANGE_PROPOSED', 'ACTIVATED'],
});
