export {
  assertTaxonomyComplete,
  evaluateTaxonomyCompleteness,
  productiveCategoriesWithoutSourcePath,
  unmappedActiveSourceCategories,
} from './completeness.ts';
export {
  CAPACITY_CLAIM_AUTOMATICALLY_ISSUES,
  MAPPING_AUTHORIZES_MOONREY,
  MAPPING_DECLARES_PRODUCTIVE_CONTRIBUTION,
  REFERENCE_PRICE_CAN_CREATE_CLAIM,
  RESERVE_CLAIM_AUTOMATICALLY_ISSUES,
  VERIFIED_FACT_ALONE_CAN_MINT,
  capacityClaimAutomaticallyIssues,
  mappingAuthorizesIssuance,
  mappingAuthorizesMoonRey,
  mappingCreatesProductiveContribution,
  mappingDeclaresProductiveContribution,
  mappingPreservesChunk71Authority,
  productionIsActive,
  referencePriceCanCreateClaim,
  reserveClaimAutomaticallyIssues,
  verifiedFactAloneCanMint,
} from './invariants.ts';
export { SOURCE_PRODUCTIVE_MAPPINGS } from './mapping.ts';
export {
  SourceProductiveTaxonomyRegistry,
  allowedClaimTypesFor,
  allowedFactTypesFor,
  canonicalSourceTaxonomy,
  factTypeIsMappedForSource,
  mappingRequiresAttribution,
  mappingsForFactType,
  mappingsForProductiveCategory,
  mappingsForSourceCategory,
  sourcePathExistsFor,
} from './registry.ts';
export {
  CANONICAL_DATA_SOURCE_CATEGORIES,
  DATA_SOURCE_CATEGORIES,
  ECONOMIC_ASSET_CATEGORY_REFERENCE,
  ECONOMIC_EVENT_CLASSES,
  ISSUANCE_BOUNDARY,
  LEGACY_DATA_SOURCE_ALIASES,
  MAPPING_STATUSES,
  OVERLAP_RISK_PRODUCTIVE_CATEGORIES,
  PRIMARY_FACT_TYPE_BY_CATEGORY,
  PRODUCTION_ACTIVE,
  SOURCE_TAXONOMY_ID,
  SOURCE_TAXONOMY_MAPPING_VERSION,
  SOURCE_TAXONOMY_SCHEMA_VERSION,
  isCanonicalDataSourceCategory,
  isDataSourceCategory,
  isEconomicEventClass,
  isLegacyDataSourceAlias,
  isMappingStatus,
  isAttributionRiskCategory,
  resolveSourceCategory,
} from './types.ts';
export type {
  CanonicalDataSourceCategory,
  DataSourceCategory,
  EconomicEventClass,
  IssuanceBoundary,
  LegacyDataSourceAlias,
  MappingEconomicAssetCategory,
  MappingRejection,
  MappingRejectionCode,
  MappingStatus,
  AttributionRiskProductiveCategory,
  SourceCategoryResolution,
  SourceProductiveMapping,
  TaxonomyCompletenessReport,
} from './types.ts';
