/**
 * ACCESS-19 — MoonRey Productive Capacity to Access Bridge identifiers.
 */

export const ACCESS_19_SCHEMA_VERSION = 1 as const;
export const ACCESS_19_CHUNK = 'ACCESS-19' as const;

export const PRODUCTIVE_ACCESS_BRIDGE_INVARIANT_IDS = [
  'NO_PRODUCTIVE_CAPACITY_DOUBLE_COUNT',
  'NO_ACCESS_USAGE_MINTS_MOONREY',
  'NO_PROVIDER_SETTLEMENT_EQUALS_MOONREY_ISSUANCE',
  'CAPACITY_COMMITMENT_LE_VERIFIED_AVAILABLE_CAPACITY',
  'NO_OUTPUT_DELIVERY_DOUBLE_ISSUANCE',
  'NO_PHANTOM_PRODUCTIVE_CAPACITY',
  'NO_ORACLE_FACT_ALONE_MINTS',
  'ONLY_CANONICAL_MR_BALANCE_AFFECTS_MR_TWAB',
] as const;

export type ProductiveAccessBridgeInvariantId = (typeof PRODUCTIVE_ACCESS_BRIDGE_INVARIANT_IDS)[number];

export const ACCESS_CAPACITY_COMMITMENT_STATUSES = [
  'DRAFT',
  'ACTIVE',
  'PARTIALLY_CONSUMED',
  'FULLY_CONSUMED',
  'EXPIRED',
  'REVOKED',
  'CANCELLED',
] as const;

export type AccessCapacityCommitmentStatus = (typeof ACCESS_CAPACITY_COMMITMENT_STATUSES)[number];

export const PROVIDER_SETTLEMENT_KINDS = ['FIAT', 'SUNREY_COIN', 'MOONREY_COIN', 'MIXED'] as const;
export type ProviderSettlementKind = (typeof PROVIDER_SETTLEMENT_KINDS)[number];

export const PRODUCTIVE_ACCESS_EXAMPLE_IDS = [
  'SOLAR_KWH',
  'GPU_CLUSTER_HOUR',
  'ROBOT_FLEET_HOUR',
  'AUTONOMOUS_VEHICLE_FLEET',
  'HOTEL_ROOM_NIGHT',
  'FACTORY_PRODUCTION_CAPACITY',
  'FOOD_DELIVERABLE_UNITS',
] as const;

export type ProductiveAccessExampleId = (typeof PRODUCTIVE_ACCESS_EXAMPLE_IDS)[number];
