/**
 * Machine-readable cryptographic inventory. Human form:
 * docs/security/cryptographic-inventory.md
 */

export const CRYPTOGRAPHIC_INVENTORY = Object.freeze([
  {
    id: 'execution-authority',
    owner: 'packages/permissions + packages/security',
    purpose: 'EXECUTION_AUTHORITY_SIGNING',
    algorithm: 'HMAC-SHA256',
    provider: 'simulation KeyProvider / future KMS',
    keyLifecycle: 'ACTIVE rotation via KeyProvider',
    quantumExposure: 'symmetric MAC; harvest-now is limited; not a public-key consensus secret',
    migrationPriority: 'retain HMAC contract; do not reuse for validator keys',
    targetArchitecture: 'KeyProvider + CryptoSuite sunrey-app-hmac-v1',
    currentStatus: 'IMPLEMENTED',
  },
  {
    id: 'evidence-hashing',
    owner: 'packages/evidence + packages/security',
    purpose: 'EVIDENCE_INTEGRITY',
    algorithm: 'SHA-256',
    provider: 'node:crypto createHash',
    keyLifecycle: 'hash-only; no signing key',
    quantumExposure: 'collision/preimage; vault ADR required before hash migration',
    migrationPriority: 'low; do not change vault hash in this chunk',
    targetArchitecture: 'unchanged SHA-256 until a vault ADR',
    currentStatus: 'IMPLEMENTED',
  },
  {
    id: 'consent-permits',
    owner: 'packages/consent + packages/security',
    purpose: 'DATA_USE_PERMIT_SIGNING',
    algorithm: 'HMAC-SHA256',
    provider: 'simulation KeyProvider',
    keyLifecycle: 'ACTIVE / DEPRECATED verify',
    quantumExposure: 'application MAC',
    migrationPriority: 'medium',
    targetArchitecture: 'sunrey-app-hmac-v1',
    currentStatus: 'IMPLEMENTED',
  },
  {
    id: 'hmac-webhooks',
    owner: 'packages/security',
    purpose: 'WEBHOOK_SIGNING',
    algorithm: 'HMAC-SHA256',
    provider: 'simulation KeyProvider',
    keyLifecycle: 'ACTIVE / DEPRECATED verify',
    quantumExposure: 'application MAC',
    migrationPriority: 'medium',
    targetArchitecture: 'sunrey-app-hmac-v1',
    currentStatus: 'IMPLEMENTED',
  },
  {
    id: 'passkeys',
    owner: 'packages/identity (reserved)',
    purpose: 'SESSION_SIGNING / future WebAuthn',
    algorithm: 'not selected; WebAuthn/passkeys are not implemented',
    provider: 'none',
    keyLifecycle: 'n/a',
    quantumExposure: 'future authenticator-dependent',
    migrationPriority: 'research',
    targetArchitecture: 'identity stack + CryptoSuite registry',
    currentStatus: 'NOT_IMPLEMENTED',
  },
  {
    id: 'data-encryption',
    owner: 'packages/security',
    purpose: 'DATA_ENCRYPTION',
    algorithm: 'AES-256-GCM',
    provider: 'simulation KeyProvider envelopes',
    keyLifecycle: 'ACTIVE encrypt; DEPRECATED decrypt',
    quantumExposure: 'harvest-now-decrypt-later on stored envelopes',
    migrationPriority: 'high for long-lived confidentiality',
    targetArchitecture: 'AES-256-GCM now; ML-KEM hybrid wrap later (DRAFT suite)',
    currentStatus: 'IMPLEMENTED',
  },
  {
    id: 'backup-encryption',
    owner: 'packages/security',
    purpose: 'BACKUP_ENCRYPTION',
    algorithm: 'AES-256-GCM',
    provider: 'simulation KeyProvider envelopes',
    keyLifecycle: 'ACTIVE encrypt; DEPRECATED decrypt',
    quantumExposure: 'harvest-now-decrypt-later',
    migrationPriority: 'high',
    targetArchitecture: 'same as data encryption; PQ KEM suite is DRAFT',
    currentStatus: 'IMPLEMENTED',
  },
  {
    id: 'custody',
    owner: 'packages/custody + packages/security',
    purpose: 'DATA_ENCRYPTION / future custody signing',
    algorithm: 'AES-256-GCM envelopes; no live custody HSM',
    provider: 'simulation',
    keyLifecycle: 'simulation only',
    quantumExposure: 'simulation payloads',
    migrationPriority: 'later custody chunk',
    targetArchitecture: 'KeyProvider + CryptoSuite; no universal custody key',
    currentStatus: 'IMPLEMENTED (simulation)',
  },
  {
    id: 'chain-operation-signing',
    owner: 'packages/sunrey-chain + packages/security',
    purpose: 'CHAIN_OPERATION_SIGNING',
    algorithm: 'HMAC-SHA256',
    provider: 'simulation KeyProvider',
    keyLifecycle: 'ACTIVE',
    quantumExposure: 'simulation trust-layer MAC; not consensus',
    migrationPriority: 'keep HMAC for simulation receipts; do not promote to consensus',
    targetArchitecture: 'remain application HMAC; consensus uses Ed25519 suites',
    currentStatus: 'IMPLEMENTED (simulation)',
  },
  {
    id: 'transaction-signatures',
    owner: 'packages/security + packages/sunrey-chain',
    purpose: 'TRANSACTION_SIGNING',
    algorithm: 'Ed25519 / ML_DSA_65_V1 / hybrid CLASSICAL_AND_PQ via CryptoSuite',
    provider: 'node-crypto-ed25519 + noble-post-quantum-0.5.4',
    libraryVersion: '@noble/post-quantum@0.5.4',
    keyLifecycle: 'KeyLifecycleState on descriptors',
    securityClassification: 'TESTNET_APPROVED standardized PQ; not production-certified',
    quantumExposure: 'public-key signatures forgeable by a future CRQC; hybrid TESTNET_APPROVED',
    migrationPriority: 'height-activated CLASSICAL_ONLY → HYBRID_AVAILABLE → HYBRID_REQUIRED_SELECTED_ROLES → PQ_PRIMARY',
    protocolDependencies: 'CryptoSuite registry, SignedBinding, wallet address v1',
    targetArchitecture: 'versioned CryptoSuite; no hard-coded algorithm in node code',
    currentStatus: 'IMPLEMENTED (development/testnet standardized PQ)',
  },
  {
    id: 'validator-signatures',
    owner: 'packages/sunrey-chain + packages/security',
    purpose: 'VALIDATOR_CONSENSUS_SIGNING / BLOCK_PROPOSAL_SIGNING',
    algorithm: 'Ed25519 and hybrid Ed25519+ML_DSA_65_V1',
    provider: 'node-crypto-ed25519 + noble-post-quantum-0.5.4',
    libraryVersion: '@noble/post-quantum@0.5.4',
    keyLifecycle: 'epoch/protocol governance rotation; historical verify retained',
    securityClassification: 'TESTNET_APPROVED; SLH-DSA is diversification only, not default consensus',
    quantumExposure: 'validator public keys',
    migrationPriority: 'hybrid-required selected roles at height H2',
    protocolDependencies: 'remote signer suite descriptor, UpgradePlan cryptoSchedule',
    targetArchitecture: 'no universal validator key',
    currentStatus: 'IMPLEMENTED (development/testnet hybrid rehearsal)',
  },
  {
    id: 'p2p-identities',
    owner: 'packages/sunrey-chain + packages/security',
    purpose: 'P2P_IDENTITY',
    algorithm: 'Ed25519 via CryptoSuite',
    provider: 'node-crypto-ed25519',
    keyLifecycle: 'descriptor only',
    quantumExposure: 'peer identity keys',
    migrationPriority: 'medium',
    targetArchitecture: 'CryptoSuite; Chunk 35 networking later',
    currentStatus: 'IMPLEMENTED (purpose + suite)',
  },
  {
    id: 'oracle-signatures',
    owner: 'packages/sunrey-chain + packages/security',
    purpose: 'ORACLE_SIGNING',
    algorithm: 'Ed25519 / hybrid Ed25519+ML_DSA_65_V1 via CryptoSuite',
    provider: 'node-crypto-ed25519 + noble-post-quantum-0.5.4',
    libraryVersion: '@noble/post-quantum@0.5.4',
    keyLifecycle: 'descriptor + height-activated feed policy',
    securityClassification: 'TESTNET_APPROVED for selected high-value feeds',
    quantumExposure: 'oracle public keys',
    migrationPriority: 'hybrid required for selected feeds at H2',
    protocolDependencies: 'CryptoPolicy, oracle observation commitment',
    targetArchitecture: 'CryptoSuite; Chunk 43 oracle runtime',
    currentStatus: 'IMPLEMENTED (purpose + suite + hybrid testnet feeds)',
  },
  {
    id: 'governance-signatures',
    owner: 'packages/sunrey-chain + packages/security',
    purpose: 'GOVERNANCE_SIGNING',
    algorithm: 'Ed25519 / hybrid Ed25519+ML_DSA_65_V1',
    provider: 'node-crypto-ed25519 + noble-post-quantum-0.5.4',
    libraryVersion: '@noble/post-quantum@0.5.4',
    keyPurpose: 'GOVERNANCE_SIGNING',
    securityClassification: 'TESTNET_APPROVED; AI cannot vote',
    migrationState: 'height-activated',
    protocolDependencies: 'UpgradePlan, CryptoPolicySchedule',
    currentStatus: 'IMPLEMENTED (testnet hybrid identities)',
  },
  {
    id: 'machine-identity-keys',
    owner: 'packages/sunrey-chain + packages/security',
    purpose: 'MACHINE_SIGNING',
    algorithm: 'Ed25519 / hybrid / ML_DSA_65_V1',
    provider: 'noble-post-quantum-0.5.4',
    libraryVersion: '@noble/post-quantum@0.5.4',
    keyPurpose: 'MACHINE_SIGNING',
    securityClassification: 'TESTNET_APPROVED; owner/controller semantics unchanged',
    migrationState: 'classical → hybrid → PQ-primary',
    protocolDependencies: 'machine economic identity',
    currentStatus: 'IMPLEMENTED (testnet PQ rotation)',
  },
  {
    id: 'ml-kem-session-establishment',
    owner: 'packages/security',
    purpose: 'DATA_ENCRYPTION / BACKUP_ENCRYPTION',
    algorithm: 'ML_KEM_768_V1',
    provider: 'noble-post-quantum-0.5.4',
    libraryVersion: '@noble/post-quantum@0.5.4',
    keyPurpose: 'DATA_ENCRYPTION',
    securityClassification: 'TESTNET_APPROVED KEM only; never used as a signature',
    migrationState: 'available for future confidentiality wrap',
    protocolDependencies: 'KemProvider port',
    currentStatus: 'IMPLEMENTED (provider; not a consensus primitive)',
  },
] as const);
