import type { AgentActionClass } from '../taxonomy.ts';
import { AgentToolRegistry, emptyOutputSchema, objectSchema, toolIdentityHash } from './registry.ts';
import type {
  AgentToolDefinition,
  ToolAuditClass,
  ToolCategory,
  ToolDataClass,
  ToolRiskClass,
} from './types.ts';

const V = '1.0.0';

function def(input: {
  readonly toolId: string;
  readonly description: string;
  readonly category: ToolCategory;
  readonly required: readonly string[];
  readonly properties: AgentToolDefinition['inputSchema']['properties'];
  readonly requiredMandate: AgentActionClass | 'NONE';
  readonly requiredCapabilities: readonly string[];
  readonly riskClass: ToolRiskClass;
  readonly readOnly: boolean;
  readonly createsProposal: boolean;
  readonly requiresUserApproval: boolean;
  readonly requiredDataClasses: readonly ToolDataClass[];
  readonly timeoutMs: number;
  readonly domainDependency: string;
  readonly purpose: string;
  readonly classification?: ToolAuditClass;
}): AgentToolDefinition {
  const properties = { ...input.properties };
  for (const key of input.required) {
    const field = properties[key];
    if (field) {
      properties[key] = { ...field, required: true };
    }
  }
  return Object.freeze({
    toolId: input.toolId,
    version: V,
    identityHash: toolIdentityHash(input.toolId, V, input.description),
    description: input.description,
    category: input.category,
    inputSchema: objectSchema(properties),
    outputSchema: emptyOutputSchema(),
    requiredMandate: input.requiredMandate,
    requiredCapabilities: input.requiredCapabilities,
    riskClass: input.riskClass,
    readOnly: input.readOnly,
    createsProposal: input.createsProposal,
    requiresUserApproval: input.requiresUserApproval,
    requiredDataClasses: input.requiredDataClasses,
    timeoutMs: input.timeoutMs,
    enabledEnvironments: Object.freeze(['simulation', 'sandbox'] as const),
    domainDependency: input.domainDependency,
    purpose: input.purpose,
    classification: input.classification ?? 'CANONICAL',
  });
}

const str = { type: 'string' as const };
const minor = { type: 'minor_units' as const };
const ccy = { type: 'currency' as const };

export const CANONICAL_AGENT_TOOLS: readonly AgentToolDefinition[] = Object.freeze([
  def({
    toolId: 'getFinancialSnapshot',
    description: 'Read the owner financial snapshot with class breakdown. Ledger-derived totals only.',
    category: 'READ_FINANCIAL',
    required: [],
    properties: {},
    requiredMandate: 'READ_FINANCIAL_STATE',
    requiredCapabilities: ['accounts'],
    riskClass: 'READ',
    readOnly: true,
    createsProposal: false,
    requiresUserApproval: false,
    requiredDataClasses: ['FINANCIAL_PRIVATE'],
    timeoutMs: 2_000,
    domainDependency: 'services/accounts + PEG snapshot via ports',
    purpose: 'Answer how much money the owner has without inventing numbers.',
  }),
  def({
    toolId: 'getAccounts',
    description: 'List owner accounts and currencies.',
    category: 'READ_FINANCIAL',
    required: [],
    properties: {},
    requiredMandate: 'READ_FINANCIAL_STATE',
    requiredCapabilities: ['accounts'],
    riskClass: 'READ',
    readOnly: true,
    createsProposal: false,
    requiresUserApproval: false,
    requiredDataClasses: ['FINANCIAL_PRIVATE'],
    timeoutMs: 2_000,
    domainDependency: 'services/accounts via AccountsPort',
    purpose: 'Enumerate owned accounts.',
  }),
  def({
    toolId: 'getAccountBalance',
    description: 'Read one owned account balance with class breakdown.',
    category: 'READ_FINANCIAL',
    required: ['accountId'],
    properties: { accountId: str },
    requiredMandate: 'READ_FINANCIAL_STATE',
    requiredCapabilities: ['accounts'],
    riskClass: 'READ',
    readOnly: true,
    createsProposal: false,
    requiresUserApproval: false,
    requiredDataClasses: ['FINANCIAL_PRIVATE'],
    timeoutMs: 2_000,
    domainDependency: 'services/accounts via AccountsPort',
    purpose: 'Read a single owned balance.',
  }),
  def({
    toolId: 'getRecentActivity',
    description: 'Read recent activity for an owned account.',
    category: 'READ_FINANCIAL',
    required: ['accountId'],
    properties: { accountId: str },
    requiredMandate: 'READ_FINANCIAL_STATE',
    requiredCapabilities: ['accounts'],
    riskClass: 'READ',
    readOnly: true,
    createsProposal: false,
    requiresUserApproval: false,
    requiredDataClasses: ['FINANCIAL_PRIVATE'],
    timeoutMs: 2_000,
    domainDependency: 'services/accounts activity projection',
    purpose: 'Show recent movements without treating activity as a balance authority.',
  }),
  def({
    toolId: 'analyzeSpending',
    description: 'Read PEG-derived spending analysis. Not a ledger authority.',
    category: 'READ_FINANCIAL',
    required: [],
    properties: {},
    requiredMandate: 'READ_FINANCIAL_STATE',
    requiredCapabilities: ['peg'],
    riskClass: 'READ',
    readOnly: true,
    createsProposal: false,
    requiresUserApproval: false,
    requiredDataClasses: ['FINANCIAL_PRIVATE'],
    timeoutMs: 2_000,
    domainDependency: 'packages/personal-economic-graph via port',
    purpose: 'Explain observed spending using PEG cash-flow facts.',
  }),
  def({
    toolId: 'getRecipients',
    description: 'List owned payment recipients.',
    category: 'PAYMENTS',
    required: [],
    properties: {},
    requiredMandate: 'READ_FINANCIAL_STATE',
    requiredCapabilities: ['payments'],
    riskClass: 'READ',
    readOnly: true,
    createsProposal: false,
    requiresUserApproval: false,
    requiredDataClasses: ['FINANCIAL_PRIVATE'],
    timeoutMs: 2_000,
    domainDependency: 'packages/payments PaymentPlatform',
    purpose: 'Identify an existing recipient. Agents cannot add beneficiaries.',
  }),
  def({
    toolId: 'createRecipientProposal',
    description: 'Refused. Agents cannot add or modify a beneficiary.',
    category: 'PAYMENTS',
    required: ['displayName'],
    properties: { displayName: str, destinationHint: str },
    requiredMandate: 'PREPARE_PAYMENT',
    requiredCapabilities: ['payments'],
    riskClass: 'PRIVILEGED_FINANCIAL_MUTATION',
    readOnly: false,
    createsProposal: false,
    requiresUserApproval: true,
    requiredDataClasses: ['FINANCIAL_PRIVATE'],
    timeoutMs: 1_000,
    domainDependency: 'packages/payments beneficiaries (human-only)',
    purpose: 'Fail closed so the model cannot invent a beneficiary path.',
    classification: 'UNSAFE',
  }),
  def({
    toolId: 'createPaymentQuote',
    description: 'Create a payment quote. Amounts are server-derived.',
    category: 'PAYMENTS',
    required: ['sourceAccountId', 'recipientId', 'amount', 'currency'],
    properties: { sourceAccountId: str, recipientId: str, amount: minor, currency: ccy, purpose: str },
    requiredMandate: 'PREPARE_PAYMENT',
    requiredCapabilities: ['payments'],
    riskClass: 'READ',
    readOnly: true,
    createsProposal: false,
    requiresUserApproval: false,
    requiredDataClasses: ['FINANCIAL_PRIVATE'],
    timeoutMs: 3_000,
    domainDependency: 'packages/payments quote preview',
    purpose: 'Price a payment without executing it.',
  }),
  def({
    toolId: 'createPaymentProposal',
    description: 'Create a payment proposal. Does not send money.',
    category: 'PAYMENTS',
    required: ['sourceAccountId', 'recipientId', 'amount', 'currency'],
    properties: { sourceAccountId: str, recipientId: str, amount: minor, currency: ccy, purpose: str, quoteId: str },
    requiredMandate: 'PREPARE_PAYMENT',
    requiredCapabilities: ['payments'],
    riskClass: 'PROPOSAL',
    readOnly: false,
    createsProposal: true,
    requiresUserApproval: true,
    requiredDataClasses: ['FINANCIAL_PRIVATE'],
    timeoutMs: 3_000,
    domainDependency: 'packages/sunrey-agent ProposalGate + payments',
    purpose: 'Prepare a human-reviewable payment. No execution.',
  }),
  def({
    toolId: 'getPaymentStatus',
    description: 'Read payment status for an owned payment.',
    category: 'PAYMENTS',
    required: ['paymentId'],
    properties: { paymentId: str },
    requiredMandate: 'READ_FINANCIAL_STATE',
    requiredCapabilities: ['payments'],
    riskClass: 'READ',
    readOnly: true,
    createsProposal: false,
    requiresUserApproval: false,
    requiredDataClasses: ['FINANCIAL_PRIVATE'],
    timeoutMs: 2_000,
    domainDependency: 'packages/payments PaymentPlatform',
    purpose: 'Report payment status without inferring execution from prose.',
  }),
  def({
    toolId: 'getFxQuote',
    description: 'Create or read an FX quote. Rates are server-owned.',
    category: 'FX',
    required: ['sourceCurrency', 'destinationCurrency', 'sourceAmount'],
    properties: { sourceCurrency: ccy, destinationCurrency: ccy, sourceAmount: minor },
    requiredMandate: 'READ_FINANCIAL_STATE',
    requiredCapabilities: ['fx'],
    riskClass: 'READ',
    readOnly: true,
    createsProposal: false,
    requiresUserApproval: false,
    requiredDataClasses: ['FINANCIAL_PRIVATE'],
    timeoutMs: 3_000,
    domainDependency: 'packages/payments FX quote engine',
    purpose: 'Obtain a server-derived FX quote. The model must not invent a rate.',
  }),
  def({
    toolId: 'createFxProposal',
    description: 'Create an FX conversion proposal. Does not execute the quote.',
    category: 'FX',
    required: ['quoteId', 'sourceAmount', 'sourceCurrency', 'destinationCurrency'],
    properties: { quoteId: str, sourceAmount: minor, sourceCurrency: ccy, destinationCurrency: ccy },
    requiredMandate: 'PREPARE_PAYMENT',
    requiredCapabilities: ['fx'],
    riskClass: 'PROPOSAL',
    readOnly: false,
    createsProposal: true,
    requiresUserApproval: true,
    requiredDataClasses: ['FINANCIAL_PRIVATE'],
    timeoutMs: 3_000,
    domainDependency: 'packages/payments FX + ProposalGate',
    purpose: 'Propose an FX conversion for human review.',
  }),
  def({
    toolId: 'getGoals',
    description: 'Read declared PEG / Grow goals.',
    category: 'GROW',
    required: [],
    properties: {},
    requiredMandate: 'READ_FINANCIAL_STATE',
    requiredCapabilities: ['grow'],
    riskClass: 'READ',
    readOnly: true,
    createsProposal: false,
    requiresUserApproval: false,
    requiredDataClasses: ['FINANCIAL_PRIVATE'],
    timeoutMs: 2_000,
    domainDependency: 'packages/personal-economic-graph + packages/platform grow',
    purpose: 'List goals. Creating a goal does not move money.',
  }),
  def({
    toolId: 'getOpportunities',
    description: 'Read Growth Orchestrator opportunities.',
    category: 'GROW',
    required: [],
    properties: {},
    requiredMandate: 'READ_FINANCIAL_STATE',
    requiredCapabilities: ['grow'],
    riskClass: 'READ',
    readOnly: true,
    createsProposal: false,
    requiresUserApproval: false,
    requiredDataClasses: ['FINANCIAL_PRIVATE'],
    timeoutMs: 2_000,
    domainDependency: 'packages/platform growth opportunity feed',
    purpose: 'Show eligible opportunities. Achievement is never promised.',
  }),
  def({
    toolId: 'getGrowthPlan',
    description: 'Read the current Grow My Money plan.',
    category: 'GROW',
    required: [],
    properties: { planId: str },
    requiredMandate: 'READ_FINANCIAL_STATE',
    requiredCapabilities: ['grow'],
    riskClass: 'READ',
    readOnly: true,
    createsProposal: false,
    requiresUserApproval: false,
    requiredDataClasses: ['FINANCIAL_PRIVATE'],
    timeoutMs: 2_000,
    domainDependency: 'packages/platform ProductGrowthPlan',
    purpose: 'Explain the current growth plan without executing it.',
  }),
  def({
    toolId: 'getGrowthProposals',
    description: 'List existing growth proposals. Fabricated ids are refused.',
    category: 'GROW',
    required: [],
    properties: {},
    requiredMandate: 'READ_FINANCIAL_STATE',
    requiredCapabilities: ['grow'],
    riskClass: 'READ',
    readOnly: true,
    createsProposal: false,
    requiresUserApproval: false,
    requiredDataClasses: ['FINANCIAL_PRIVATE'],
    timeoutMs: 2_000,
    domainDependency: 'packages/platform Financial Proposal + growth-tools',
    purpose: 'Read known proposals only.',
  }),
  def({
    toolId: 'createGrowthProposal',
    description: 'Create a Grow proposal from an opportunity. No execution.',
    category: 'GROW',
    required: ['opportunityId', 'amount', 'currency'],
    properties: { opportunityId: str, amount: minor, currency: ccy },
    requiredMandate: 'REBALANCE_WITHIN_POLICY',
    requiredCapabilities: ['grow'],
    riskClass: 'PROPOSAL',
    readOnly: false,
    createsProposal: true,
    requiresUserApproval: true,
    requiredDataClasses: ['FINANCIAL_PRIVATE'],
    timeoutMs: 3_000,
    domainDependency: 'packages/platform grow + sunrey-agent ProposalGate',
    purpose: 'Propose a growth action for human review.',
  }),
  def({
    toolId: 'modifyGrowthProposal',
    description: 'Create a superseding growth proposal. Does not edit posted state.',
    category: 'GROW',
    required: ['proposalId', 'amount'],
    properties: { proposalId: str, amount: minor },
    requiredMandate: 'REBALANCE_WITHIN_POLICY',
    requiredCapabilities: ['grow'],
    riskClass: 'PROPOSAL',
    readOnly: false,
    createsProposal: true,
    requiresUserApproval: true,
    requiredDataClasses: ['FINANCIAL_PRIVATE'],
    timeoutMs: 3_000,
    domainDependency: 'packages/platform grow proposal + growth-tools',
    purpose: 'Supersede a draft proposal. Agents cannot execute the result.',
  }),
  def({
    toolId: 'getPortfolio',
    description: 'Read the owner portfolio projection. No return-rate field.',
    category: 'PORTFOLIO',
    required: [],
    properties: {},
    requiredMandate: 'READ_FINANCIAL_STATE',
    requiredCapabilities: ['portfolio'],
    riskClass: 'READ',
    readOnly: true,
    createsProposal: false,
    requiresUserApproval: false,
    requiredDataClasses: ['FINANCIAL_PRIVATE'],
    timeoutMs: 2_000,
    domainDependency: 'packages/sunrey-exchange consumer + investments',
    purpose: 'Show holdings and allocation without a growth-rate field.',
  }),
  def({
    toolId: 'getHoldings',
    description: 'Read portfolio holdings.',
    category: 'PORTFOLIO',
    required: [],
    properties: {},
    requiredMandate: 'READ_FINANCIAL_STATE',
    requiredCapabilities: ['portfolio'],
    riskClass: 'READ',
    readOnly: true,
    createsProposal: false,
    requiresUserApproval: false,
    requiredDataClasses: ['FINANCIAL_PRIVATE'],
    timeoutMs: 2_000,
    domainDependency: 'packages/sunrey-exchange consumer portfolio',
    purpose: 'List holdings as integer quantities.',
  }),
  def({
    toolId: 'getPerformance',
    description: 'Read informational quantity change. Not a percentage return.',
    category: 'PORTFOLIO',
    required: [],
    properties: {},
    requiredMandate: 'READ_FINANCIAL_STATE',
    requiredCapabilities: ['portfolio'],
    riskClass: 'READ',
    readOnly: true,
    createsProposal: false,
    requiresUserApproval: false,
    requiredDataClasses: ['FINANCIAL_PRIVATE'],
    timeoutMs: 2_000,
    domainDependency: 'packages/sunrey-exchange consumer performance',
    purpose: 'Show informational quantity change only.',
  }),
  def({
    toolId: 'getAllocation',
    description: 'Read portfolio sleeve allocation next to totals.',
    category: 'PORTFOLIO',
    required: [],
    properties: {},
    requiredMandate: 'READ_FINANCIAL_STATE',
    requiredCapabilities: ['portfolio'],
    riskClass: 'READ',
    readOnly: true,
    createsProposal: false,
    requiresUserApproval: false,
    requiredDataClasses: ['FINANCIAL_PRIVATE'],
    timeoutMs: 2_000,
    domainDependency: 'packages/sunrey-exchange consumer portfolio',
    purpose: 'Show class/sleeve breakdown beside the total.',
  }),
  def({
    toolId: 'getPortfolioRisk',
    description: 'Read informational portfolio risk disclosure.',
    category: 'PORTFOLIO',
    required: [],
    properties: {},
    requiredMandate: 'READ_FINANCIAL_STATE',
    requiredCapabilities: ['portfolio'],
    riskClass: 'READ',
    readOnly: true,
    createsProposal: false,
    requiresUserApproval: false,
    requiredDataClasses: ['FINANCIAL_PRIVATE'],
    timeoutMs: 2_000,
    domainDependency: 'packages/sunrey-exchange consumer risk disclosure',
    purpose: 'Disclose risk. Not a guarantee.',
  }),
  def({
    toolId: 'getMarkets',
    description: 'List simulation exchange markets and eligibility.',
    category: 'EXCHANGE',
    required: [],
    properties: {},
    requiredMandate: 'READ_FINANCIAL_STATE',
    requiredCapabilities: ['exchange'],
    riskClass: 'READ',
    readOnly: true,
    createsProposal: false,
    requiresUserApproval: false,
    requiredDataClasses: ['PUBLIC'],
    timeoutMs: 2_000,
    domainDependency: 'packages/sunrey-exchange',
    purpose: 'Show markets. Last trade is not a guaranteed price.',
  }),
  def({
    toolId: 'getAsset',
    description: 'Read a listed asset. No official valuation invention.',
    category: 'EXCHANGE',
    required: ['assetId'],
    properties: { assetId: str },
    requiredMandate: 'READ_FINANCIAL_STATE',
    requiredCapabilities: ['exchange'],
    riskClass: 'READ',
    readOnly: true,
    createsProposal: false,
    requiresUserApproval: false,
    requiredDataClasses: ['PUBLIC'],
    timeoutMs: 2_000,
    domainDependency: 'packages/sunrey-exchange + sunrey-coin tool',
    purpose: 'Identify a listed asset.',
  }),
  def({
    toolId: 'getMarketPrice',
    description: 'Read last trade label. Not a guaranteed price.',
    category: 'EXCHANGE',
    required: ['marketId'],
    properties: { marketId: str },
    requiredMandate: 'READ_FINANCIAL_STATE',
    requiredCapabilities: ['exchange'],
    riskClass: 'READ',
    readOnly: true,
    createsProposal: false,
    requiresUserApproval: false,
    requiredDataClasses: ['PUBLIC'],
    timeoutMs: 2_000,
    domainDependency: 'packages/sunrey-exchange SubjectScopedSunReyExchangeTool',
    purpose: 'Explain last trade without inventing a ticker valuation.',
  }),
  def({
    toolId: 'getOrders',
    description: 'Read the owner open/recent exchange orders.',
    category: 'EXCHANGE',
    required: [],
    properties: {},
    requiredMandate: 'READ_FINANCIAL_STATE',
    requiredCapabilities: ['exchange'],
    riskClass: 'READ',
    readOnly: true,
    createsProposal: false,
    requiresUserApproval: false,
    requiredDataClasses: ['FINANCIAL_PRIVATE'],
    timeoutMs: 2_000,
    domainDependency: 'packages/sunrey-exchange consumer orders',
    purpose: 'List orders. Agents cannot cancel or settle.',
  }),
  def({
    toolId: 'getExchangeEligibility',
    description: 'Read CAN_TRADE, CAN_DEPOSIT, and CAN_WITHDRAW for the owner.',
    category: 'EXCHANGE',
    required: [],
    properties: { marketId: str },
    requiredMandate: 'READ_FINANCIAL_STATE',
    requiredCapabilities: ['exchange'],
    riskClass: 'READ',
    readOnly: true,
    createsProposal: false,
    requiresUserApproval: false,
    requiredDataClasses: ['FINANCIAL_PRIVATE'],
    timeoutMs: 2_000,
    domainDependency: 'packages/sunrey-exchange product eligibility',
    purpose: 'Server-controlled eligibility. Not a client-side gate.',
  }),
  def({
    toolId: 'getExchangeHoldings',
    description: 'Read owner exchange holdings projection.',
    category: 'EXCHANGE',
    required: [],
    properties: {},
    requiredMandate: 'READ_FINANCIAL_STATE',
    requiredCapabilities: ['exchange'],
    riskClass: 'READ',
    readOnly: true,
    createsProposal: false,
    requiresUserApproval: false,
    requiredDataClasses: ['FINANCIAL_PRIVATE'],
    timeoutMs: 2_000,
    domainDependency: 'packages/sunrey-exchange product holdings',
    purpose: 'Show holdings. Not a ledger authority.',
  }),
  def({
    toolId: 'previewExchangeOrder',
    description: 'Preview an exchange order. Price is not guaranteed.',
    category: 'EXCHANGE',
    required: ['marketId', 'side', 'quantity'],
    properties: { marketId: str, side: { type: 'enum', enum: ['BUY', 'SELL'] }, quantity: minor },
    requiredMandate: 'READ_FINANCIAL_STATE',
    requiredCapabilities: ['exchange'],
    riskClass: 'READ',
    readOnly: true,
    createsProposal: false,
    requiresUserApproval: false,
    requiredDataClasses: ['FINANCIAL_PRIVATE'],
    timeoutMs: 2_000,
    domainDependency: 'packages/sunrey-exchange product preview',
    purpose: 'Preview only. Does not place an order.',
  }),
  def({
    toolId: 'getExchangeOrderStatus',
    description: 'Read owner order and clearing status. Filled is not settled.',
    category: 'EXCHANGE',
    required: [],
    properties: { orderId: str },
    requiredMandate: 'READ_FINANCIAL_STATE',
    requiredCapabilities: ['exchange'],
    riskClass: 'READ',
    readOnly: true,
    createsProposal: false,
    requiresUserApproval: false,
    requiredDataClasses: ['FINANCIAL_PRIVATE'],
    timeoutMs: 2_000,
    domainDependency: 'packages/sunrey-exchange product clearing',
    purpose: 'Show order and clearing state. Agents cannot settle.',
  }),
  def({
    toolId: 'createExchangeOrderProposal',
    description: 'Create an exchange order proposal. Does not place the order.',
    category: 'EXCHANGE',
    required: ['marketId', 'side', 'quantity', 'assetId'],
    properties: {
      marketId: str,
      side: { type: 'enum', enum: ['BUY', 'SELL'] },
      quantity: minor,
      assetId: str,
    },
    requiredMandate: 'PREPARE_EXCHANGE_ORDER',
    requiredCapabilities: ['exchange'],
    riskClass: 'PROPOSAL',
    readOnly: false,
    createsProposal: true,
    requiresUserApproval: true,
    requiredDataClasses: ['FINANCIAL_PRIVATE'],
    timeoutMs: 3_000,
    domainDependency: 'packages/sunrey-exchange + ProposalGate',
    purpose: 'Propose a trade. No place/cancel/halt/settle.',
  }),
  def({
    toolId: 'getWallets',
    description: 'List subject-scoped custody wallets.',
    category: 'WALLETS_CUSTODY',
    required: [],
    properties: {},
    requiredMandate: 'READ_FINANCIAL_STATE',
    requiredCapabilities: ['custody'],
    riskClass: 'READ',
    readOnly: true,
    createsProposal: false,
    requiresUserApproval: false,
    requiredDataClasses: ['FINANCIAL_PRIVATE'],
    timeoutMs: 2_000,
    domainDependency: 'packages/custody via port',
    purpose: 'List subject-scoped customer wallets. Read-only. No signing material.',
  }),
  def({
    toolId: 'getWalletBalance',
    description: 'Read one owned wallet balance.',
    category: 'WALLETS_CUSTODY',
    required: ['walletId'],
    properties: { walletId: str },
    requiredMandate: 'READ_FINANCIAL_STATE',
    requiredCapabilities: ['custody'],
    riskClass: 'READ',
    readOnly: true,
    createsProposal: false,
    requiresUserApproval: false,
    requiredDataClasses: ['FINANCIAL_PRIVATE'],
    timeoutMs: 2_000,
    domainDependency: 'packages/custody via port',
    purpose: 'Read owned wallet quantity. Not a second ledger. No signing material.',
  }),
  def({
    toolId: 'getDepositStatus',
    description: 'Read an owned deposit status.',
    category: 'WALLETS_CUSTODY',
    required: ['depositId'],
    properties: { depositId: str },
    requiredMandate: 'READ_FINANCIAL_STATE',
    requiredCapabilities: ['custody'],
    riskClass: 'READ',
    readOnly: true,
    createsProposal: false,
    requiresUserApproval: false,
    requiredDataClasses: ['FINANCIAL_PRIVATE'],
    timeoutMs: 2_000,
    domainDependency: 'packages/custody getDeposit',
    purpose: 'Report deposit status.',
  }),
  def({
    toolId: 'createWithdrawalProposal',
    description: 'Create a withdrawal proposal when the destination is already approved.',
    category: 'WALLETS_CUSTODY',
    required: ['walletId', 'destinationId', 'amount', 'assetId'],
    properties: { walletId: str, destinationId: str, amount: minor, assetId: str },
    requiredMandate: 'REQUEST_HUMAN_APPROVAL',
    requiredCapabilities: ['custody'],
    riskClass: 'PROPOSAL',
    readOnly: false,
    createsProposal: true,
    requiresUserApproval: true,
    requiredDataClasses: ['FINANCIAL_PRIVATE'],
    timeoutMs: 3_000,
    domainDependency: 'packages/custody + ProposalGate',
    purpose: 'Propose a withdrawal. Agents cannot add destinations or execute.',
  }),
  def({
    toolId: 'getCards',
    description: 'List owned cards (last4 / status only).',
    category: 'CARDS',
    required: [],
    properties: {},
    requiredMandate: 'READ_FINANCIAL_STATE',
    requiredCapabilities: ['cards'],
    riskClass: 'READ',
    readOnly: true,
    createsProposal: false,
    requiresUserApproval: false,
    requiredDataClasses: ['FINANCIAL_PRIVATE'],
    timeoutMs: 2_000,
    domainDependency: 'packages/cards consumer product',
    purpose: 'List cards without PAN/CVV.',
  }),
  def({
    toolId: 'getCardStatus',
    description: 'Read one owned card status.',
    category: 'CARDS',
    required: ['cardId'],
    properties: { cardId: str },
    requiredMandate: 'READ_FINANCIAL_STATE',
    requiredCapabilities: ['cards'],
    riskClass: 'READ',
    readOnly: true,
    createsProposal: false,
    requiresUserApproval: false,
    requiredDataClasses: ['FINANCIAL_PRIVATE'],
    timeoutMs: 2_000,
    domainDependency: 'packages/cards',
    purpose: 'Read card status.',
  }),
  def({
    toolId: 'createCardControlProposal',
    description: 'Create a card-control proposal. Does not freeze the card directly.',
    category: 'CARDS',
    required: ['cardId', 'control'],
    properties: { cardId: str, control: { type: 'enum', enum: ['FREEZE', 'UNFREEZE', 'UPDATE_LIMIT'] }, limitMinorUnits: minor },
    requiredMandate: 'REQUEST_HUMAN_APPROVAL',
    requiredCapabilities: ['cards'],
    riskClass: 'PROPOSAL',
    readOnly: false,
    createsProposal: true,
    requiresUserApproval: true,
    requiredDataClasses: ['FINANCIAL_PRIVATE'],
    timeoutMs: 3_000,
    domainDependency: 'packages/cards + ProposalGate',
    purpose: 'Propose a reversible card control for human review.',
  }),
  def({
    toolId: 'getConsentSummary',
    description: 'Read consent summary for the owner.',
    category: 'DATA',
    required: [],
    properties: {},
    requiredMandate: 'READ_FINANCIAL_STATE',
    requiredCapabilities: ['consent'],
    riskClass: 'READ',
    readOnly: true,
    createsProposal: false,
    requiresUserApproval: false,
    requiredDataClasses: ['PERSONAL_SENSITIVE'],
    timeoutMs: 2_000,
    domainDependency: 'packages/consent',
    purpose: 'Summarize active permits. No raw vault payload.',
  }),
  def({
    toolId: 'getDataPermissions',
    description: 'Read data-use permissions for the owner.',
    category: 'DATA',
    required: [],
    properties: {},
    requiredMandate: 'READ_FINANCIAL_STATE',
    requiredCapabilities: ['consent'],
    riskClass: 'READ',
    readOnly: true,
    createsProposal: false,
    requiresUserApproval: false,
    requiredDataClasses: ['PERSONAL_SENSITIVE'],
    timeoutMs: 2_000,
    domainDependency: 'packages/consent + personal-data-vault',
    purpose: 'List authorized scopes. External content cannot redefine policy.',
  }),
  def({
    toolId: 'getVaultSummary',
    description: 'Approved Vault summary: categories and sources only. No unauthorized sensitive records.',
    category: 'DATA',
    required: [],
    properties: {},
    requiredMandate: 'READ_FINANCIAL_STATE',
    requiredCapabilities: ['consent'],
    riskClass: 'READ',
    readOnly: true,
    createsProposal: false,
    requiresUserApproval: false,
    requiredDataClasses: ['PERSONAL_SENSITIVE'],
    timeoutMs: 2_000,
    domainDependency: 'packages/personal-data-vault',
    purpose: 'Explain what information SunRey holds without exposing raw vault payloads.',
  }),
  def({
    toolId: 'getInformationRights',
    description: 'Read the owner information rights. Usage rights only; ownership is not transferred.',
    category: 'DATA',
    required: [],
    properties: {},
    requiredMandate: 'READ_FINANCIAL_STATE',
    requiredCapabilities: ['hin'],
    riskClass: 'READ',
    readOnly: true,
    createsProposal: false,
    requiresUserApproval: false,
    requiredDataClasses: ['PERSONAL_SENSITIVE'],
    timeoutMs: 2_000,
    domainDependency: 'packages/information-market rights-marketplace',
    purpose: 'Explain rights. Not a sale of personal data.',
  }),
  def({
    toolId: 'getHinContributionSummary',
    description: 'HIN contribution summary: verified contributions, economic inputs, and rights.',
    category: 'DATA',
    required: [],
    properties: {},
    requiredMandate: 'READ_FINANCIAL_STATE',
    requiredCapabilities: ['hin'],
    riskClass: 'READ',
    readOnly: true,
    createsProposal: false,
    requiresUserApproval: false,
    requiredDataClasses: ['PERSONAL_SENSITIVE'],
    timeoutMs: 2_000,
    domainDependency: 'packages/information-market + human-economic-contribution',
    purpose: 'Explain how information contributes without implying a mint or market price.',
  }),
  def({
    toolId: 'getActiveDataPermissions',
    description: 'Read active data permissions and licensed purposes.',
    category: 'DATA',
    required: [],
    properties: {},
    requiredMandate: 'READ_FINANCIAL_STATE',
    requiredCapabilities: ['hin'],
    riskClass: 'READ',
    readOnly: true,
    createsProposal: false,
    requiresUserApproval: false,
    requiredDataClasses: ['PERSONAL_SENSITIVE'],
    timeoutMs: 2_000,
    domainDependency: 'packages/information-market rights-marketplace',
    purpose: 'Show approved permissions. Purpose is preserved.',
  }),
  def({
    toolId: 'getHinParticipation',
    description: 'Read optional Human Information Network participation state. Withdrawal does not close financial services.',
    category: 'DATA',
    required: [],
    properties: {},
    requiredMandate: 'READ_FINANCIAL_STATE',
    requiredCapabilities: ['hin'],
    riskClass: 'READ',
    readOnly: true,
    createsProposal: false,
    requiresUserApproval: false,
    requiredDataClasses: ['PERSONAL_SENSITIVE'],
    timeoutMs: 2_000,
    domainDependency: 'packages/information-market',
    purpose: 'Show optional HIN participation. Withdrawal does not close financial services.',
  }),
  def({
    toolId: 'getVaultRecords',
    description: 'Read approved Vault record metadata for required categories or record ids only. Never the whole vault.',
    category: 'DATA',
    required: ['purpose'],
    properties: { purpose: str, categoryIds: str, recordIds: str },
    requiredMandate: 'READ_FINANCIAL_STATE',
    requiredCapabilities: ['consent'],
    riskClass: 'READ',
    readOnly: true,
    createsProposal: false,
    requiresUserApproval: false,
    requiredDataClasses: ['PERSONAL_SENSITIVE'],
    timeoutMs: 2_000,
    domainDependency: 'packages/personal-data-vault',
    purpose: 'Read approved Vault record metadata only. Wildcard vault access is forbidden.',
  }),
  def({
    toolId: 'requestHinConsentChange',
    description: 'Initiate a controlled HIN consent stop. Does not revoke until the user confirms on the server.',
    category: 'DATA',
    required: [],
    properties: {},
    requiredMandate: 'REQUEST_HUMAN_APPROVAL',
    requiredCapabilities: ['hin'],
    riskClass: 'PROPOSAL',
    readOnly: false,
    createsProposal: true,
    requiresUserApproval: true,
    requiredDataClasses: ['PERSONAL_SENSITIVE'],
    timeoutMs: 2_000,
    domainDependency: 'packages/information-market rights-marketplace',
    purpose: 'Start a controlled HIN consent stop. The agent cannot complete revocation.',
  }),
  def({
    toolId: 'getApprovedEarnings',
    description: 'Read approved information-rights earnings. Compensation is not guaranteed.',
    category: 'DATA',
    required: [],
    properties: {},
    requiredMandate: 'READ_FINANCIAL_STATE',
    requiredCapabilities: ['hin'],
    riskClass: 'READ',
    readOnly: true,
    createsProposal: false,
    requiresUserApproval: false,
    requiredDataClasses: ['FINANCIAL_PRIVATE'],
    timeoutMs: 2_000,
    domainDependency: 'packages/information-market rights-marketplace',
    purpose: 'Show settled earnings only. Agent cannot fabricate amounts.',
  }),
  def({
    toolId: 'explainLicense',
    description: 'Explain one owned information license. Does not accept terms.',
    category: 'DATA',
    required: ['licenseId'],
    properties: { licenseId: str },
    requiredMandate: 'READ_FINANCIAL_STATE',
    requiredCapabilities: ['hin'],
    riskClass: 'READ',
    readOnly: true,
    createsProposal: false,
    requiresUserApproval: false,
    requiredDataClasses: ['PERSONAL_SENSITIVE'],
    timeoutMs: 2_000,
    domainDependency: 'packages/information-market rights-marketplace',
    purpose: 'Explain a purpose-scoped license.',
  }),
  def({
    toolId: 'initiateConsentChange',
    description: 'Help the user start a consent change. Does not accept material licensing terms.',
    category: 'DATA',
    required: [],
    properties: {},
    requiredMandate: 'REQUEST_HUMAN_APPROVAL',
    requiredCapabilities: ['consent', 'hin'],
    riskClass: 'PROPOSAL',
    readOnly: false,
    createsProposal: true,
    requiresUserApproval: true,
    requiredDataClasses: ['PERSONAL_SENSITIVE'],
    timeoutMs: 3_000,
    domainDependency: 'packages/consent + packages/information-market',
    purpose: 'Propose a consent change. Human approval required. Agent cannot accept terms.',
  }),
  def({
    toolId: 'getNativeAsset',
    description: 'Read protocol-native SunRey Coin or MoonRey Coin metadata. Tickers stay unassigned.',
    category: 'READ_FINANCIAL',
    required: ['assetId'],
    properties: { assetId: str },
    requiredMandate: 'READ_FINANCIAL_STATE',
    requiredCapabilities: ['nativeEconomy'],
    riskClass: 'READ',
    readOnly: true,
    createsProposal: false,
    requiresUserApproval: false,
    requiredDataClasses: ['PUBLIC'],
    timeoutMs: 2_000,
    domainDependency: 'packages/sunrey-chain native-assets registry',
    purpose: 'Explain a native asset without inventing a ticker or minting.',
  }),
  def({
    toolId: 'getNativeSupply',
    description: 'Read protocol-native supply. Not a market capitalization.',
    category: 'READ_FINANCIAL',
    required: [],
    properties: { assetId: str },
    requiredMandate: 'READ_FINANCIAL_STATE',
    requiredCapabilities: ['nativeEconomy'],
    riskClass: 'READ',
    readOnly: true,
    createsProposal: false,
    requiresUserApproval: false,
    requiredDataClasses: ['PUBLIC'],
    timeoutMs: 2_000,
    domainDependency: 'packages/sunrey-chain AssetSupplyBook',
    purpose: 'Retrieve issued and circulating supply from the singular supply authority.',
  }),
  def({
    toolId: 'getNativeEconomy',
    description: 'Read approved native-economy explanation, supply, and Exchange last trade when present.',
    category: 'READ_FINANCIAL',
    required: [],
    properties: {},
    requiredMandate: 'READ_FINANCIAL_STATE',
    requiredCapabilities: ['nativeEconomy'],
    riskClass: 'READ',
    readOnly: true,
    createsProposal: false,
    requiresUserApproval: false,
    requiredDataClasses: ['PUBLIC'],
    timeoutMs: 2_000,
    domainDependency: 'packages/sunrey-chain native-assets client surface',
    purpose: 'Explain SunRey Coin and MoonRey Coin. Cannot declare a future price.',
  }),
  def({
    toolId: 'getProductiveEconomy',
    description: 'Read approved MoonRey productive-economy overview. Observations do not mint.',
    category: 'READ_FINANCIAL',
    required: [],
    properties: {},
    requiredMandate: 'READ_FINANCIAL_STATE',
    requiredCapabilities: ['productiveEconomy'],
    riskClass: 'READ',
    readOnly: true,
    createsProposal: false,
    requiresUserApproval: false,
    requiredDataClasses: ['PUBLIC'],
    timeoutMs: 2_000,
    domainDependency: 'packages/sunrey-chain productive/economy-data',
    purpose: 'Explain verified productive metrics. Cannot invent data or mint MoonRey.',
  }),
  def({
    toolId: 'getHinContributions',
    description: 'Read the owner HIN contribution list. No raw personal data. Not a mint.',
    category: 'DATA',
    required: [],
    properties: {},
    requiredMandate: 'READ_FINANCIAL_STATE',
    requiredCapabilities: ['hin'],
    riskClass: 'READ',
    readOnly: true,
    createsProposal: false,
    requiresUserApproval: false,
    requiredDataClasses: ['PERSONAL_SENSITIVE'],
    timeoutMs: 2_000,
    domainDependency: 'packages/human-economic-contribution hin-value',
    purpose: 'List Your Contributions. Cannot verify or mint.',
  }),
  def({
    toolId: 'getProductiveCategory',
    description: 'Compare or retrieve one approved productive-economy category.',
    category: 'READ_FINANCIAL',
    required: ['category'],
    properties: { category: str },
    requiredMandate: 'READ_FINANCIAL_STATE',
    requiredCapabilities: ['productiveEconomy'],
    riskClass: 'READ',
    readOnly: true,
    createsProposal: false,
    requiresUserApproval: false,
    requiredDataClasses: ['PUBLIC'],
    timeoutMs: 2_000,
    domainDependency: 'packages/sunrey-chain productive/economy-data',
    purpose: 'Compare categories using configured verified data only.',
  }),
  def({
    toolId: 'getHinMetrics',
    description: 'Read privacy-safe aggregate HIN metrics. Individual records are not exposed.',
    category: 'DATA',
    required: [],
    properties: {},
    requiredMandate: 'READ_FINANCIAL_STATE',
    requiredCapabilities: ['hin'],
    riskClass: 'READ',
    readOnly: true,
    createsProposal: false,
    requiresUserApproval: false,
    requiredDataClasses: ['PUBLIC'],
    timeoutMs: 2_000,
    domainDependency: 'packages/human-economic-contribution hin-value metrics',
    purpose: 'Summarize aggregate HIN activity. Cannot mint.',
  }),
  def({
    toolId: 'getProductiveMethodology',
    description: 'Explain a versioned Productive Value methodology. GPUV is not MoonRey.',
    category: 'READ_FINANCIAL',
    required: [],
    properties: { category: str },
    requiredMandate: 'READ_FINANCIAL_STATE',
    requiredCapabilities: ['productiveEconomy'],
    riskClass: 'READ',
    readOnly: true,
    createsProposal: false,
    requiresUserApproval: false,
    requiredDataClasses: ['PUBLIC'],
    timeoutMs: 2_000,
    domainDependency: 'packages/sunrey-chain productive value methodology registry',
    purpose: 'Explain methodology. Cannot change it or hardcode issuance ratios.',
  }),
  def({
    toolId: 'getHinSummary',
    description: 'Read the owner HIN contribution summary, economic value inputs, and data rights.',
    category: 'DATA',
    required: [],
    properties: {},
    requiredMandate: 'READ_FINANCIAL_STATE',
    requiredCapabilities: ['hin'],
    riskClass: 'READ',
    readOnly: true,
    createsProposal: false,
    requiresUserApproval: false,
    requiredDataClasses: ['PERSONAL_SENSITIVE'],
    timeoutMs: 2_000,
    domainDependency: 'packages/human-economic-contribution hin-value customer view',
    purpose: 'Customer contribution view. Token issuance is not promised.',
  }),
  def({
    toolId: 'getProductiveFreshness',
    description: 'Explain observation freshness. Stale data is not time-sensitive valuation input.',
    category: 'READ_FINANCIAL',
    required: [],
    properties: { category: str },
    requiredMandate: 'READ_FINANCIAL_STATE',
    requiredCapabilities: ['productiveEconomy'],
    riskClass: 'READ',
    readOnly: true,
    createsProposal: false,
    requiresUserApproval: false,
    requiredDataClasses: ['PUBLIC'],
    timeoutMs: 2_000,
    domainDependency: 'packages/sunrey-chain productive/economy-data freshness',
    purpose: 'Explain freshness. Cannot convert stale or outlier data into verified truth.',
  }),
  def({
    toolId: 'getHinValuationMethodologies',
    description: 'Read safe HIN valuation methodology metadata. Not a mint formula.',
    category: 'DATA',
    required: [],
    properties: {},
    requiredMandate: 'READ_FINANCIAL_STATE',
    requiredCapabilities: ['hin'],
    riskClass: 'READ',
    readOnly: true,
    createsProposal: false,
    requiresUserApproval: false,
    requiredDataClasses: ['PUBLIC'],
    timeoutMs: 2_000,
    domainDependency: 'packages/human-economic-contribution hin-value methodologies',
    purpose: 'Explain versioned valuation methodologies. Cannot set policy or mint.',
  }),
]);

export function createCanonicalToolRegistry(): AgentToolRegistry {
  const registry = new AgentToolRegistry();
  for (const tool of CANONICAL_AGENT_TOOLS) {
    registry.register(tool);
  }
  return registry;
}

export const CANONICAL_TOOL_COUNT = CANONICAL_AGENT_TOOLS.length;
