export const ECONOMIC_ASSET_REGISTRY_ISOLATION = Object.freeze({
  owner: 'packages/economic-asset-registry',
  capability: 'sunrey-economic-asset-registry',
  boundedContext: 'ECONOMIC_ASSET_REGISTRY',
  financialStateMutation: false,
  executionAuthorityRequired: false,
  kernelAuthorizationRequired: false,
  valuationImplemented: false,
  mintingImplemented: false,
  rawDataStored: false,
  isPersonalDataVault: false,
  isHumanInformationNetwork: false,
  isPersonalEconomicGraph: false,
  isProductiveEngine: false,
  isOracleConsensus: false,
  isMonetarySupply: false,
  productionActivated: false,
  forbiddenCompetingPackages: Object.freeze([
    'packages/dataset-registry',
    'packages/economic-assets',
    'packages/data-assets-v2',
    'packages/universal-data-registry',
    'packages/tokenized-data',
    'packages/dataset-verification',
    'packages/data-rights-registry',
    'packages/economic-provenance',
    'packages/asset-rights',
    'packages/economic-assets-v2',
  ]),
  sitsAbove: Object.freeze([
    'packages/information-market',
    'packages/personal-data-vault',
    'packages/personal-economic-graph',
    'packages/human-economic-contribution',
    'packages/sunrey-chain/src/oracle',
    'packages/sunrey-chain/src/productive',
    'packages/sunrey-chain/src/economics',
    'packages/sunrey-economics',
  ]),
  doesNotReplace: Object.freeze([
    'HIN',
    'PDV',
    'PEG',
    'Human Economic Contribution Registry',
    'Oracle Registry',
    'Productive Object Registry',
    'Productive Claim Registry',
    'Native Asset Supply Book',
  ]),
  mustNotImport: Object.freeze([
    'packages/kernel',
    'packages/permissions',
    'packages/ledger',
    'packages/sunrey-coin',
    'packages/platform',
    'packages/personal-economic-graph',
    'packages/information-market',
    'packages/consent',
    'packages/clean-room',
    'packages/personal-data-vault',
    'packages/human-economic-contribution',
    'packages/sunrey-chain',
    'packages/sunrey-economics',
    'services/',
  ]),
});
