export const VERIFICATION_REJECTION_CODES = [
  'CONTRIBUTION_NOT_FOUND',
  'CONTRIBUTION_CLASS_NOT_ELIGIBLE',
  'EVIDENCE_MISSING',
  'EVIDENCE_STALE',
  'EVIDENCE_CONFLICTED',
  'SOURCE_NOT_PERMITTED',
  'SOURCE_QUALITY_INSUFFICIENT',
  'ATTESTATION_REQUIRED',
  'INDEPENDENT_ATTESTATION_REQUIRED',
  'CONSENT_REQUIRED',
  'CONSENT_INVALID',
  'PURPOSE_REQUIRED',
  'PURPOSE_MISMATCH',
  'RIGHT_REQUIRED',
  'RIGHT_INVALID',
  'RIGHT_EXPIRED',
  'RIGHT_REVOKED_BEFORE_USE',
  'USAGE_RECEIPT_REQUIRED',
  'USAGE_NOT_REALIZED',
  'SUBJECT_MISMATCH',
  'JURISDICTION_UNRESOLVED',
  'MODEL_INFERENCE_INSUFFICIENT',
  'USER_DECLARATION_INSUFFICIENT',
  'SELF_ATTESTATION_INSUFFICIENT',
  'DUPLICATE_CONTRIBUTION',
  'RAW_PERSONAL_DATA_FORBIDDEN',
  'PROTECTED_TRAIT_RANKING_FORBIDDEN',
  'HUMAN_WORTH_SCORING_FORBIDDEN',
  'EVIDENCE_DIGEST_TAMPERED',
  'DUPLICATED_EVIDENCE_REFERENCE',
  'FINGERPRINT_REPLAY',
  'MEASUREMENT_MISMATCH',
  'PERIOD_MISMATCH',
  'SOURCE_MISMATCH',
  'INVALID_SUPERSESSION',
  'CONFLICTING_ATTESTATIONS',
  'POLICY_NOT_ACTIVE',
  'PRODUCTION_POLICY_NOT_ACTIVATED',
  'OTHER_CLASS_FAIL_CLOSED',
] as const;

export type VerificationDecisionCode = (typeof VERIFICATION_REJECTION_CODES)[number];

export const ADDITIONAL_EVIDENCE_CODES = Object.freeze([
  'EVIDENCE_MISSING',
  'ATTESTATION_REQUIRED',
  'PURPOSE_REQUIRED',
  'RIGHT_REQUIRED',
  'USAGE_RECEIPT_REQUIRED',
] as const satisfies readonly VerificationDecisionCode[]);

export type AdditionalEvidenceCode = (typeof ADDITIONAL_EVIDENCE_CODES)[number];

export function isVerificationDecisionCode(value: string): value is VerificationDecisionCode {
  return (VERIFICATION_REJECTION_CODES as readonly string[]).includes(value);
}

export function requiresAdditionalEvidence(code: VerificationDecisionCode): boolean {
  return (ADDITIONAL_EVIDENCE_CODES as readonly string[]).includes(code);
}
