export const GROW_ALLOCATION_STATUSES = [
  'REQUESTED',
  'RESERVED',
  'PARTIALLY_RESERVED',
  'RELEASED',
  'REFUSED',
  'EXPIRED',
  'REDUCED',
] as const;

export type GrowAllocationStatus = (typeof GROW_ALLOCATION_STATUSES)[number];

export const GROW_ALLOCATION_FAILURE_CODES = [
  'WORK_ORDER_NOT_ACTIVE',
  'WORK_ORDER_CUSTOMER_MISMATCH',
  'ACCOUNT_NOT_FOUND',
  'ACCOUNT_OWNER_MISMATCH',
  'CURRENCY_MISMATCH',
  'INSUFFICIENT_FUNDS',
  'LIQUIDITY_RETAINED',
  'MANDATE_LIMIT',
  'RISK_REFUSED',
  'COMPLIANCE_REFUSED',
  'AUTHORITY_REFUSED',
  'RESERVATION_FAILED',
  'ALLOCATION_NOT_FOUND',
  'INVALID_RELEASE',
  'ENVIRONMENT_NOT_SANDBOX',
  'LIVE_EXECUTION_DISABLED',
  'DUPLICATE_REQUEST',
  'CAPITAL_BOUNDARY_EXCEEDED',
] as const;

export type GrowAllocationFailureCode = (typeof GROW_ALLOCATION_FAILURE_CODES)[number];

export const GROW_ALLOCATION_EXECUTION_MODES = ['SANDBOX', 'PAPER'] as const;

export type GrowAllocationExecutionMode = (typeof GROW_ALLOCATION_EXECUTION_MODES)[number];
