/**
 * HELIOS M01 initial engineering universe.
 *
 * Reference/sandbox metadata only. Production execution authority is not implied.
 */

import type { CapitalMarketVenue } from '../types.ts';
import { buildCanonicalInstrumentId } from './id.ts';
import {
  MULTI_ASSET_SCHEMA,
  type CanonicalMultiAssetInstrument,
  type ProviderInstrumentMapping,
} from './types.ts';

export const MULTI_ASSET_INSTRUMENT_REGISTRY_ID = 'sunrey.capital-market.multi-asset.instruments.v1' as const;

const VENUE_NASDAQ: CapitalMarketVenue = Object.freeze({
  venueId: 'XNAS',
  mic: 'XNAS',
  displayName: 'NASDAQ',
  exchange: 'NASDAQ',
});

const VENUE_ARCA: CapitalMarketVenue = Object.freeze({
  venueId: 'ARCX',
  mic: 'ARCX',
  displayName: 'NYSE Arca',
  exchange: 'ARCA',
});

const VENUE_NYSE: CapitalMarketVenue = Object.freeze({
  venueId: 'XNYS',
  mic: 'XNYS',
  displayName: 'New York Stock Exchange',
  exchange: 'NYSE',
});

const VENUE_NDQ_INDEX: CapitalMarketVenue = Object.freeze({
  venueId: 'NDQ',
  mic: 'XNAS',
  displayName: 'Nasdaq Index Reference',
  exchange: 'NASDAQ',
});

const VENUE_SIM_GLOBAL: CapitalMarketVenue = Object.freeze({
  venueId: 'SIM',
  mic: 'XSIM',
  displayName: 'SunRey Simulation Global',
  exchange: 'SIM',
});

const VENUE_COMEX: CapitalMarketVenue = Object.freeze({
  venueId: 'XCEC',
  mic: 'XCEC',
  displayName: 'COMEX (reference)',
  exchange: 'COMEX',
});

const VENUE_NYMEX: CapitalMarketVenue = Object.freeze({
  venueId: 'XNYM',
  mic: 'XNYM',
  displayName: 'NYMEX (reference)',
  exchange: 'NYMEX',
});

const VENUE_CME: CapitalMarketVenue = Object.freeze({
  venueId: 'XCME',
  mic: 'XCME',
  displayName: 'CME (reference)',
  exchange: 'CME',
});

function mapping(providerId: string, symbol: string, nativeId: string | null = null): ProviderInstrumentMapping {
  return Object.freeze({ providerId, symbol, nativeId: nativeId ?? symbol });
}

function instrument(input: Omit<CanonicalMultiAssetInstrument, 'schema'>): CanonicalMultiAssetInstrument {
  return Object.freeze({ schema: MULTI_ASSET_SCHEMA, ...input });
}

export const ENGINEERING_UNIVERSE_INSTRUMENTS: readonly CanonicalMultiAssetInstrument[] = Object.freeze([
  instrument({
    instrumentId: buildCanonicalInstrumentId({
      assetClass: 'EQUITY',
      jurisdiction: 'US',
      symbol: 'AAPL',
      venueId: 'XNAS',
    }),
    symbol: 'AAPL',
    displayName: 'Apple Inc.',
    assetClass: 'EQUITY',
    jurisdiction: 'US',
    venue: VENUE_NASDAQ,
    tradingCurrency: 'USD',
    settlementCurrency: 'USD',
    isin: 'US0378331005',
    figi: null,
    providerMappings: Object.freeze([mapping('finnhub', 'AAPL')]),
    underlyingInstrumentId: null,
    baseAsset: null,
    quoteAsset: null,
    contractMultiplier: null,
    tickSize: 1 / 100,
    lotSize: 1,
    minimumQuantity: 1,
    quantityScale: 0,
    priceScale: 2,
    expiration: null,
    firstNoticeDate: null,
    lastTradeDate: null,
    settlementType: 'T+2',
    contractMonth: null,
    deliveryType: 'NONE',
    tradingCalendarRef: 'calendar:us-equity',
    capability: Object.freeze({ marketData: 'SANDBOX', execution: 'NONE' }),
    status: 'ACTIVE',
    metadataAuthority: 'SANDBOX',
  }),
  instrument({
    instrumentId: buildCanonicalInstrumentId({
      assetClass: 'EQUITY',
      jurisdiction: 'US',
      symbol: 'MSFT',
      venueId: 'XNAS',
    }),
    symbol: 'MSFT',
    displayName: 'Microsoft Corporation',
    assetClass: 'EQUITY',
    jurisdiction: 'US',
    venue: VENUE_NASDAQ,
    tradingCurrency: 'USD',
    settlementCurrency: 'USD',
    isin: 'US5949181045',
    figi: null,
    providerMappings: Object.freeze([mapping('finnhub', 'MSFT')]),
    underlyingInstrumentId: null,
    baseAsset: null,
    quoteAsset: null,
    contractMultiplier: null,
    tickSize: 1 / 100,
    lotSize: 1,
    minimumQuantity: 1,
    quantityScale: 0,
    priceScale: 2,
    expiration: null,
    firstNoticeDate: null,
    lastTradeDate: null,
    settlementType: 'T+2',
    contractMonth: null,
    deliveryType: 'NONE',
    tradingCalendarRef: 'calendar:us-equity',
    capability: Object.freeze({ marketData: 'SANDBOX', execution: 'NONE' }),
    status: 'ACTIVE',
    metadataAuthority: 'SANDBOX',
  }),
  instrument({
    instrumentId: buildCanonicalInstrumentId({
      assetClass: 'EQUITY',
      jurisdiction: 'US',
      symbol: 'NVDA',
      venueId: 'XNAS',
    }),
    symbol: 'NVDA',
    displayName: 'NVIDIA Corporation',
    assetClass: 'EQUITY',
    jurisdiction: 'US',
    venue: VENUE_NASDAQ,
    tradingCurrency: 'USD',
    settlementCurrency: 'USD',
    isin: 'US67066G1040',
    figi: null,
    providerMappings: Object.freeze([mapping('finnhub', 'NVDA')]),
    underlyingInstrumentId: null,
    baseAsset: null,
    quoteAsset: null,
    contractMultiplier: null,
    tickSize: 1 / 100,
    lotSize: 1,
    minimumQuantity: 1,
    quantityScale: 0,
    priceScale: 2,
    expiration: null,
    firstNoticeDate: null,
    lastTradeDate: null,
    settlementType: 'T+2',
    contractMonth: null,
    deliveryType: 'NONE',
    tradingCalendarRef: 'calendar:us-equity',
    capability: Object.freeze({ marketData: 'SANDBOX', execution: 'NONE' }),
    status: 'ACTIVE',
    metadataAuthority: 'SANDBOX',
  }),
  instrument({
    instrumentId: buildCanonicalInstrumentId({
      assetClass: 'ETF',
      jurisdiction: 'US',
      symbol: 'SPY',
      venueId: 'ARCX',
    }),
    symbol: 'SPY',
    displayName: 'SPDR S&P 500 ETF Trust',
    assetClass: 'ETF',
    jurisdiction: 'US',
    venue: VENUE_ARCA,
    tradingCurrency: 'USD',
    settlementCurrency: 'USD',
    isin: 'US78462F1030',
    figi: null,
    providerMappings: Object.freeze([mapping('finnhub', 'SPY')]),
    underlyingInstrumentId: null,
    baseAsset: null,
    quoteAsset: null,
    contractMultiplier: null,
    tickSize: 1 / 100,
    lotSize: 1,
    minimumQuantity: 1,
    quantityScale: 0,
    priceScale: 2,
    expiration: null,
    firstNoticeDate: null,
    lastTradeDate: null,
    settlementType: 'T+2',
    contractMonth: null,
    deliveryType: 'NONE',
    tradingCalendarRef: 'calendar:us-equity',
    capability: Object.freeze({ marketData: 'SANDBOX', execution: 'NONE' }),
    status: 'ACTIVE',
    metadataAuthority: 'SANDBOX',
  }),
  instrument({
    instrumentId: buildCanonicalInstrumentId({
      assetClass: 'ETF',
      jurisdiction: 'US',
      symbol: 'GLD',
      venueId: 'ARCX',
    }),
    symbol: 'GLD',
    displayName: 'SPDR Gold Shares',
    assetClass: 'ETF',
    jurisdiction: 'US',
    venue: VENUE_ARCA,
    tradingCurrency: 'USD',
    settlementCurrency: 'USD',
    isin: 'US78463V1070',
    figi: null,
    providerMappings: Object.freeze([mapping('finnhub', 'GLD')]),
    underlyingInstrumentId: null,
    baseAsset: null,
    quoteAsset: null,
    contractMultiplier: null,
    tickSize: 1 / 100,
    lotSize: 1,
    minimumQuantity: 1,
    quantityScale: 0,
    priceScale: 2,
    expiration: null,
    firstNoticeDate: null,
    lastTradeDate: null,
    settlementType: 'T+2',
    contractMonth: null,
    deliveryType: 'NONE',
    tradingCalendarRef: 'calendar:us-equity',
    capability: Object.freeze({ marketData: 'SANDBOX', execution: 'NONE' }),
    status: 'ACTIVE',
    metadataAuthority: 'SANDBOX',
  }),
  instrument({
    instrumentId: buildCanonicalInstrumentId({
      assetClass: 'ETF',
      jurisdiction: 'US',
      symbol: 'QQQ',
      venueId: 'XNAS',
    }),
    symbol: 'QQQ',
    displayName: 'Invesco QQQ Trust',
    assetClass: 'ETF',
    jurisdiction: 'US',
    venue: VENUE_NASDAQ,
    tradingCurrency: 'USD',
    settlementCurrency: 'USD',
    isin: 'US46090E1038',
    figi: null,
    providerMappings: Object.freeze([mapping('finnhub', 'QQQ')]),
    underlyingInstrumentId: buildCanonicalInstrumentId({
      assetClass: 'INDEX',
      jurisdiction: 'US',
      symbol: 'NDX',
      venueId: 'NDQ',
    }),
    baseAsset: null,
    quoteAsset: null,
    contractMultiplier: null,
    tickSize: 1 / 100,
    lotSize: 1,
    minimumQuantity: 1,
    quantityScale: 0,
    priceScale: 2,
    expiration: null,
    firstNoticeDate: null,
    lastTradeDate: null,
    settlementType: 'T+2',
    contractMonth: null,
    deliveryType: 'NONE',
    tradingCalendarRef: 'calendar:us-equity',
    capability: Object.freeze({ marketData: 'SANDBOX', execution: 'NONE' }),
    status: 'ACTIVE',
    metadataAuthority: 'SANDBOX',
  }),
  instrument({
    instrumentId: buildCanonicalInstrumentId({
      assetClass: 'INDEX',
      jurisdiction: 'US',
      symbol: 'NDX',
      venueId: 'NDQ',
    }),
    symbol: 'NDX',
    displayName: 'Nasdaq-100 Index (reference)',
    assetClass: 'INDEX',
    jurisdiction: 'US',
    venue: VENUE_NDQ_INDEX,
    tradingCurrency: 'USD',
    settlementCurrency: 'USD',
    isin: null,
    figi: null,
    providerMappings: Object.freeze([]),
    underlyingInstrumentId: null,
    baseAsset: null,
    quoteAsset: null,
    contractMultiplier: null,
    tickSize: 1 / 100,
    lotSize: null,
    minimumQuantity: null,
    quantityScale: 0,
    priceScale: 2,
    expiration: null,
    firstNoticeDate: null,
    lastTradeDate: null,
    settlementType: 'REFERENCE_ONLY',
    contractMonth: null,
    deliveryType: 'NONE',
    tradingCalendarRef: 'calendar:us-equity',
    capability: Object.freeze({ marketData: 'INDICATIVE', execution: 'NONE' }),
    status: 'ACTIVE',
    metadataAuthority: 'REFERENCE_ONLY',
  }),
  instrument({
    instrumentId: buildCanonicalInstrumentId({
      assetClass: 'CRYPTO_SPOT',
      jurisdiction: 'GLOBAL',
      symbol: 'BTCUSD',
      venueId: 'SIM',
      baseAsset: 'BTC',
      quoteAsset: 'USD',
    }),
    symbol: 'BTCUSD',
    displayName: 'Bitcoin / US Dollar (reference)',
    assetClass: 'CRYPTO_SPOT',
    jurisdiction: 'GLOBAL',
    venue: VENUE_SIM_GLOBAL,
    tradingCurrency: 'USD',
    settlementCurrency: 'USD',
    isin: null,
    figi: null,
    providerMappings: Object.freeze([
      mapping('coingecko', 'bitcoin', 'bitcoin'),
      mapping('sandbox', 'BTC/USD', 'sandbox:btc-usd'),
    ]),
    underlyingInstrumentId: null,
    baseAsset: 'BTC',
    quoteAsset: 'USD',
    contractMultiplier: null,
    tickSize: 1 / 100,
    lotSize: 1 / 100000,
    minimumQuantity: 1 / 100000,
    quantityScale: 8,
    priceScale: 2,
    expiration: null,
    firstNoticeDate: null,
    lastTradeDate: null,
    settlementType: 'T+0',
    contractMonth: null,
    deliveryType: 'NONE',
    tradingCalendarRef: 'calendar:crypto-24x7',
    capability: Object.freeze({ marketData: 'INDICATIVE', execution: 'NONE' }),
    status: 'ACTIVE',
    metadataAuthority: 'REFERENCE_ONLY',
  }),
  instrument({
    instrumentId: buildCanonicalInstrumentId({
      assetClass: 'CRYPTO_SPOT',
      jurisdiction: 'GLOBAL',
      symbol: 'ETHUSD',
      venueId: 'SIM',
      baseAsset: 'ETH',
      quoteAsset: 'USD',
    }),
    symbol: 'ETHUSD',
    displayName: 'Ethereum / US Dollar (reference)',
    assetClass: 'CRYPTO_SPOT',
    jurisdiction: 'GLOBAL',
    venue: VENUE_SIM_GLOBAL,
    tradingCurrency: 'USD',
    settlementCurrency: 'USD',
    isin: null,
    figi: null,
    providerMappings: Object.freeze([
      mapping('coingecko', 'ethereum', 'ethereum'),
      mapping('sandbox', 'ETH/USD', 'sandbox:eth-usd'),
    ]),
    underlyingInstrumentId: null,
    baseAsset: 'ETH',
    quoteAsset: 'USD',
    contractMultiplier: null,
    tickSize: 1 / 100,
    lotSize: 1 / 10000,
    minimumQuantity: 1 / 10000,
    quantityScale: 8,
    priceScale: 2,
    expiration: null,
    firstNoticeDate: null,
    lastTradeDate: null,
    settlementType: 'T+0',
    contractMonth: null,
    deliveryType: 'NONE',
    tradingCalendarRef: 'calendar:crypto-24x7',
    capability: Object.freeze({ marketData: 'INDICATIVE', execution: 'NONE' }),
    status: 'ACTIVE',
    metadataAuthority: 'REFERENCE_ONLY',
  }),
  instrument({
    instrumentId: buildCanonicalInstrumentId({
      assetClass: 'COMMODITY',
      jurisdiction: 'GLOBAL',
      symbol: 'GOLD',
      venueId: 'XCEC',
    }),
    symbol: 'GOLD',
    displayName: 'Gold (reference)',
    assetClass: 'COMMODITY',
    jurisdiction: 'GLOBAL',
    venue: VENUE_COMEX,
    tradingCurrency: 'USD',
    settlementCurrency: 'USD',
    isin: null,
    figi: null,
    providerMappings: Object.freeze([mapping('sandbox', 'XAUUSD', 'sandbox:gold-ref')]),
    underlyingInstrumentId: null,
    baseAsset: 'XAU',
    quoteAsset: 'USD',
    contractMultiplier: null,
    tickSize: 1 / 10,
    lotSize: 1,
    minimumQuantity: 1,
    quantityScale: 0,
    priceScale: 2,
    expiration: null,
    firstNoticeDate: null,
    lastTradeDate: null,
    settlementType: 'REFERENCE_ONLY',
    contractMonth: null,
    deliveryType: 'PHYSICAL',
    tradingCalendarRef: 'calendar:comex',
    capability: Object.freeze({ marketData: 'INDICATIVE', execution: 'NONE' }),
    status: 'ACTIVE',
    metadataAuthority: 'REFERENCE_ONLY',
  }),
  instrument({
    instrumentId: buildCanonicalInstrumentId({
      assetClass: 'COMMODITY',
      jurisdiction: 'GLOBAL',
      symbol: 'WTI',
      venueId: 'XNYM',
    }),
    symbol: 'WTI',
    displayName: 'WTI Crude Oil (reference)',
    assetClass: 'COMMODITY',
    jurisdiction: 'GLOBAL',
    venue: VENUE_NYMEX,
    tradingCurrency: 'USD',
    settlementCurrency: 'USD',
    isin: null,
    figi: null,
    providerMappings: Object.freeze([mapping('sandbox', 'CL', 'sandbox:wti-ref')]),
    underlyingInstrumentId: null,
    baseAsset: 'WTI',
    quoteAsset: 'USD',
    contractMultiplier: null,
    tickSize: 1 / 100,
    lotSize: 1,
    minimumQuantity: 1,
    quantityScale: 0,
    priceScale: 2,
    expiration: null,
    firstNoticeDate: null,
    lastTradeDate: null,
    settlementType: 'REFERENCE_ONLY',
    contractMonth: null,
    deliveryType: 'PHYSICAL',
    tradingCalendarRef: 'calendar:nymex',
    capability: Object.freeze({ marketData: 'INDICATIVE', execution: 'NONE' }),
    status: 'ACTIVE',
    metadataAuthority: 'REFERENCE_ONLY',
  }),
  instrument({
    instrumentId: buildCanonicalInstrumentId({
      assetClass: 'FUTURE',
      jurisdiction: 'GLOBAL',
      symbol: 'CL',
      venueId: 'XNYM',
      contractMonth: '202612',
    }),
    symbol: 'CL',
    displayName: 'WTI Crude Oil Future Dec 2026 (reference)',
    assetClass: 'FUTURE',
    jurisdiction: 'GLOBAL',
    venue: VENUE_NYMEX,
    tradingCurrency: 'USD',
    settlementCurrency: 'USD',
    isin: null,
    figi: null,
    providerMappings: Object.freeze([mapping('sandbox', 'CLZ26', 'sandbox:cl-dec-2026')]),
    underlyingInstrumentId: buildCanonicalInstrumentId({
      assetClass: 'COMMODITY',
      jurisdiction: 'GLOBAL',
      symbol: 'WTI',
      venueId: 'XNYM',
    }),
    baseAsset: 'WTI',
    quoteAsset: 'USD',
    contractMultiplier: 1000,
    tickSize: 1 / 100,
    lotSize: 1,
    minimumQuantity: 1,
    quantityScale: 0,
    priceScale: 2,
    expiration: '2026-11-20',
    firstNoticeDate: '2026-10-31',
    lastTradeDate: '2026-11-19',
    settlementType: 'PHYSICAL',
    contractMonth: '202612',
    deliveryType: 'PHYSICAL',
    tradingCalendarRef: 'calendar:nymex',
    capability: Object.freeze({ marketData: 'RESEARCH_REQUIRED', execution: 'NONE' }),
    status: 'ACTIVE',
    metadataAuthority: 'RESEARCH_REQUIRED',
  }),
  instrument({
    instrumentId: buildCanonicalInstrumentId({
      assetClass: 'FX_SPOT',
      jurisdiction: 'GLOBAL',
      symbol: 'EURUSD',
      venueId: 'SIM',
      baseAsset: 'EUR',
      quoteAsset: 'USD',
    }),
    symbol: 'EURUSD',
    displayName: 'Euro / US Dollar (reference)',
    assetClass: 'FX_SPOT',
    jurisdiction: 'GLOBAL',
    venue: VENUE_SIM_GLOBAL,
    tradingCurrency: 'USD',
    settlementCurrency: 'USD',
    isin: null,
    figi: null,
    providerMappings: Object.freeze([mapping('sandbox', 'EUR/USD', 'sandbox:eur-usd')]),
    underlyingInstrumentId: null,
    baseAsset: 'EUR',
    quoteAsset: 'USD',
    contractMultiplier: null,
    tickSize: 1 / 100000,
    lotSize: 1000,
    minimumQuantity: 1000,
    quantityScale: 0,
    priceScale: 5,
    expiration: null,
    firstNoticeDate: null,
    lastTradeDate: null,
    settlementType: 'T+2',
    contractMonth: null,
    deliveryType: 'CASH',
    tradingCalendarRef: 'calendar:fx-global',
    capability: Object.freeze({ marketData: 'INDICATIVE', execution: 'NONE' }),
    status: 'ACTIVE',
    metadataAuthority: 'REFERENCE_ONLY',
  }),
  instrument({
    instrumentId: buildCanonicalInstrumentId({
      assetClass: 'FX_SPOT',
      jurisdiction: 'GLOBAL',
      symbol: 'USDJPY',
      venueId: 'SIM',
      baseAsset: 'USD',
      quoteAsset: 'JPY',
    }),
    symbol: 'USDJPY',
    displayName: 'US Dollar / Japanese Yen (reference)',
    assetClass: 'FX_SPOT',
    jurisdiction: 'GLOBAL',
    venue: VENUE_SIM_GLOBAL,
    tradingCurrency: 'JPY',
    settlementCurrency: 'JPY',
    isin: null,
    figi: null,
    providerMappings: Object.freeze([mapping('sandbox', 'USD/JPY', 'sandbox:usd-jpy')]),
    underlyingInstrumentId: null,
    baseAsset: 'USD',
    quoteAsset: 'JPY',
    contractMultiplier: null,
    tickSize: 1 / 1000,
    lotSize: 1000,
    minimumQuantity: 1000,
    quantityScale: 0,
    priceScale: 3,
    expiration: null,
    firstNoticeDate: null,
    lastTradeDate: null,
    settlementType: 'T+2',
    contractMonth: null,
    deliveryType: 'CASH',
    tradingCalendarRef: 'calendar:fx-global',
    capability: Object.freeze({ marketData: 'INDICATIVE', execution: 'NONE' }),
    status: 'ACTIVE',
    metadataAuthority: 'REFERENCE_ONLY',
  }),
  instrument({
    instrumentId: buildCanonicalInstrumentId({
      assetClass: 'CASH',
      jurisdiction: 'US',
      symbol: 'USD',
      venueId: 'SIM',
    }),
    symbol: 'USD',
    displayName: 'US Dollar Cash (simulation)',
    assetClass: 'CASH',
    jurisdiction: 'US',
    venue: VENUE_SIM_GLOBAL,
    tradingCurrency: 'USD',
    settlementCurrency: 'USD',
    isin: null,
    figi: null,
    providerMappings: Object.freeze([]),
    underlyingInstrumentId: null,
    baseAsset: 'USD',
    quoteAsset: null,
    contractMultiplier: null,
    tickSize: 1 / 100,
    lotSize: 1,
    minimumQuantity: 1,
    quantityScale: 2,
    priceScale: 2,
    expiration: null,
    firstNoticeDate: null,
    lastTradeDate: null,
    settlementType: 'T+0',
    contractMonth: null,
    deliveryType: 'CASH',
    tradingCalendarRef: 'calendar:cash',
    capability: Object.freeze({ marketData: 'NONE', execution: 'NONE' }),
    status: 'ACTIVE',
    metadataAuthority: 'SANDBOX',
  }),
  instrument({
    instrumentId: buildCanonicalInstrumentId({
      assetClass: 'EQUITY',
      jurisdiction: 'US',
      symbol: 'DELIST',
      venueId: 'XNYS',
    }),
    symbol: 'DELIST',
    displayName: 'Delisted Example Corp (inactive)',
    assetClass: 'EQUITY',
    jurisdiction: 'US',
    venue: VENUE_NYSE,
    tradingCurrency: 'USD',
    settlementCurrency: 'USD',
    isin: null,
    figi: null,
    providerMappings: Object.freeze([]),
    underlyingInstrumentId: null,
    baseAsset: null,
    quoteAsset: null,
    contractMultiplier: null,
    tickSize: 1 / 100,
    lotSize: 1,
    minimumQuantity: 1,
    quantityScale: 0,
    priceScale: 2,
    expiration: null,
    firstNoticeDate: null,
    lastTradeDate: '2020-01-15',
    settlementType: 'T+2',
    contractMonth: null,
    deliveryType: 'NONE',
    tradingCalendarRef: 'calendar:us-equity',
    capability: Object.freeze({ marketData: 'NONE', execution: 'NONE' }),
    status: 'INACTIVE',
    metadataAuthority: 'REFERENCE_ONLY',
  }),
]);
