/**
 * Post-genesis operational readiness slots.
 *
 * These extend Chunk 65 readiness with operational dimensions. They do
 * not imply that the network has launched.
 */

import type { ReadinessEvidenceRecord } from '../mainnet/types.ts';

export function postGenesisReadinessRecords(): readonly ReadinessEvidenceRecord[] {
  return Object.freeze([
    {
      requirementId: 'REQ-POST-GENESIS-000',
      dimension: 'POST_GENESIS_OPERATIONS',
      description: 'Governed post-genesis stabilization phase, health checkpoints, and independent capability activation',
      scope: 'SUNREY_CHAIN',
      evidenceType: 'ENGINEERING_ARTIFACT',
      evidenceHash: null,
      evidenceReference: 'packages/sunrey-chain/src/post-genesis',
      source: 'packages/sunrey-chain/src/post-genesis',
      verificationStatus: 'ENGINEERING_VERIFIED',
      authorizedVerifierRole: 'OPERATIONS',
      expirationOrReviewDateUtc: null,
      notes: 'Extends readiness with post-genesis operational dimensions. Does not imply the network has launched.',
      externalEvidence: false,
      chunkReference: 'CHUNK-89',
    },
    {
      requirementId: 'REQ-POST-GENESIS-001',
      dimension: 'OBSERVABILITY',
      description: 'Post-genesis health checkpoints at governed height/epoch/finalized-state coordinates',
      scope: 'SUNREY_CHAIN',
      evidenceType: 'ENGINEERING_ARTIFACT',
      evidenceHash: null,
      evidenceReference: 'packages/sunrey-chain/src/post-genesis',
      source: 'packages/sunrey-chain/src/post-genesis',
      verificationStatus: 'ENGINEERING_VERIFIED',
      authorizedVerifierRole: 'ENGINEERING',
      expirationOrReviewDateUtc: null,
      notes: 'Engineering control plane only. Does not imply the network has launched.',
      externalEvidence: false,
      chunkReference: 'CHUNK-89',
    },
    {
      requirementId: 'REQ-POST-GENESIS-002',
      dimension: 'DISASTER_RECOVERY',
      description: 'Backup verification and restore validation on non-production clones',
      scope: 'SUNREY_CHAIN',
      evidenceType: 'SOFTWARE_TEST',
      evidenceHash: null,
      evidenceReference: 'packages/sunrey-chain/src/post-genesis/rehearsal.ts',
      source: 'packages/sunrey-chain/src/post-genesis',
      verificationStatus: 'ENGINEERING_VERIFIED',
      authorizedVerifierRole: 'OPERATIONS',
      expirationOrReviewDateUtc: null,
      notes: 'Restore is validated on isolated clones. The active network is not touched.',
      externalEvidence: false,
      chunkReference: 'CHUNK-89',
    },
    {
      requirementId: 'REQ-POST-GENESIS-003',
      dimension: 'EXCHANGE',
      description: 'Independent Exchange activation package; genesis does not enable Exchange',
      scope: 'SUNREY_EXCHANGE',
      evidenceType: 'LICENSE_OR_REGISTRATION',
      evidenceHash: null,
      evidenceReference: null,
      source: 'external-exchange-activation-slot',
      verificationStatus: 'NOT_PROVIDED',
      authorizedVerifierRole: 'COUNSEL',
      expirationOrReviewDateUtc: null,
      notes: 'Missing market/legal/provider evidence remains visible. Chain health is not Exchange authorization.',
      externalEvidence: true,
      chunkReference: 'CHUNK-89',
    },
    {
      requirementId: 'REQ-POST-GENESIS-004',
      dimension: 'CUSTODY',
      description: 'Independent custody withdrawal eligibility; production HSM evidence required',
      scope: 'INSTITUTIONAL_CUSTODY',
      evidenceType: 'EXTERNAL_AUDIT_REPORT',
      evidenceHash: null,
      evidenceReference: null,
      source: 'external-custody-hsm-slot',
      verificationStatus: 'NOT_PROVIDED',
      authorizedVerifierRole: 'EXTERNAL_AUDITOR',
      expirationOrReviewDateUtc: null,
      notes: 'Simulation HSM is not production HSM evidence.',
      externalEvidence: true,
      chunkReference: 'CHUNK-89',
    },
    {
      requirementId: 'REQ-POST-GENESIS-005',
      dimension: 'HUMAN_AUTHORIZATION',
      description: 'Human-only production capability activation; AI cannot authorize',
      scope: 'ALL',
      evidenceType: 'HUMAN_AUTHORIZATION',
      evidenceHash: null,
      evidenceReference: null,
      source: 'human-activation-authority-slot',
      verificationStatus: 'NOT_PROVIDED',
      authorizedVerifierRole: 'HUMAN_AUTHORITY',
      expirationOrReviewDateUtc: null,
      notes: 'AI may prepare evidence summaries. AI authorization is rejected.',
      externalEvidence: true,
      chunkReference: 'CHUNK-89',
    },
  ]);
}
