import {
  CANONICAL_ENV_PREFIX,
  CURRENT_MASTER_BRAND,
  GITHUB_REPOSITORY_RENAMED,
  HISTORICAL_HASH_DOMAINS_CHANGED,
  LEGACY_ENV_COMPATIBILITY,
  LEGACY_MASTER_BRAND_ACTIVE,
  PROTOCOL_IDS_CHANGED,
} from './product-identity.ts';

console.log(`CURRENT_MASTER_BRAND=${CURRENT_MASTER_BRAND}`);
console.log(`LEGACY_MASTER_BRAND_ACTIVE=${String(LEGACY_MASTER_BRAND_ACTIVE)}`);
console.log(`CANONICAL_ENV_PREFIX=${CANONICAL_ENV_PREFIX}`);
console.log(`LEGACY_ENV_COMPATIBILITY=${String(LEGACY_ENV_COMPATIBILITY)}`);
console.log(`PROTOCOL_IDS_CHANGED=${String(PROTOCOL_IDS_CHANGED)}`);
console.log(`HISTORICAL_HASH_DOMAINS_CHANGED=${String(HISTORICAL_HASH_DOMAINS_CHANGED)}`);
console.log(`GITHUB_REPOSITORY_RENAMED=${String(GITHUB_REPOSITORY_RENAMED)}`);
