/**
 * Wave 5 Prompt 19 — environmental oracle catalog entries.
 *
 * Eligible free weather, water, air-quality, wildfire, earthquake, climate,
 * and physical-risk providers from the Wave 0 catalog framework.
 */

import type { CatalogProviderEntry } from '../../../provider-sdk/src/catalog/types.ts';

export const ENVIRONMENTAL_CATALOG_PROVIDER_IDS = [
  'open-meteo',
  'open-meteo-ensemble',
  'nws',
  'aviationweather-noaa',
  'pirate-weather',
  'met-norway',
  'meltema',
  'usgs-water',
  'epa',
  'kanari',
  'usgs-earthquake',
  'openaq',
  'purpleair',
] as const;

export type EnvironmentalCatalogProviderId = (typeof ENVIRONMENTAL_CATALOG_PROVIDER_IDS)[number];

function envProvider(
  overrides: Partial<CatalogProviderEntry> &
    Pick<CatalogProviderEntry, 'provider_id' | 'name' | 'short_name' | 'description' | 'primary_category' | 'capabilities'>,
): CatalogProviderEntry {
  return Object.freeze({
    secondary_categories: Object.freeze([]),
    endpoints: Object.freeze({
      base_url: null,
      api_version: null,
      documentation_url: null,
      status_url: null,
    }),
    authentication: Object.freeze({
      type: 'none' as const,
      required: false,
      registration_required: false,
      environment_variable: null,
      notes: null,
    }),
    access: Object.freeze({
      status: 'verified_free' as const,
      free_tier_verified: true,
      registration_required: false,
      notes: null,
    }),
    commercial_use: Object.freeze({
      status: 'verified_allowed' as const,
      notes: null,
    }),
    redistribution: Object.freeze({
      status: 'attribution_required' as const,
      notes: null,
    }),
    rate_limits: Object.freeze({
      documented: true,
      requests_per_second: null,
      requests_per_minute: null,
      requests_per_hour: null,
      requests_per_day: null,
      monthly_quota: null,
      concurrency_limit: null,
      notes: 'Respect provider quotas; simulation uses fixtures only.',
    }),
    data_characteristics: Object.freeze({
      freshness: 'realtime',
      geographic_scope: Object.freeze(['GLOBAL']),
      historical_data: true,
      realtime: true,
      data_format: 'json',
      notes: null,
    }),
    sunrey: Object.freeze({
      domain: ['world', 'grow', 'financial_agent', 'research', 'moonrey', 'travel', 'infrastructure'] as const,
      canonical_provider_interface: 'EnvironmentalOracleProvider',
      priority: 'high',
      launch_tier: 'production_candidate',
      authority_class: 'reference_data',
      integration_state: 'adapter_implemented',
      existing_adapter: 'packages/sunrey-chain/src/environmental/adapters/index.ts',
    }),
    verification: Object.freeze({
      status: 'verified' as const,
      verified_against_official_docs: true,
      last_verified: '2026-08-31',
      notes: 'Wave 5 Prompt 19 environmental oracle subset.',
    }),
    ...overrides,
  });
}

export const ENVIRONMENTAL_CATALOG_ENTRIES: readonly CatalogProviderEntry[] = Object.freeze([
  envProvider({
    provider_id: 'open-meteo',
    name: 'Open-Meteo',
    short_name: 'Open-Meteo',
    description: 'Free open-source weather API with global coverage and no API key required.',
    primary_category: 'weather',
    capabilities: Object.freeze(['weather', 'precipitation', 'environmental']),
    endpoints: Object.freeze({
      base_url: 'https://api.open-meteo.com',
      api_version: 'v1',
      documentation_url: 'https://open-meteo.com/en/docs',
      status_url: null,
    }),
    sunrey: Object.freeze({
      domain: ['world', 'grow', 'financial_agent', 'research', 'moonrey', 'travel'] as const,
      canonical_provider_interface: 'EnvironmentalOracleProvider',
      priority: 'critical',
      launch_tier: 'production_candidate',
      authority_class: 'reference_data',
      integration_state: 'adapter_implemented',
      existing_adapter: 'packages/sunrey-chain/src/environmental/adapters/open-meteo.ts',
    }),
  }),
  envProvider({
    provider_id: 'open-meteo-ensemble',
    name: 'Open-Meteo Ensemble',
    short_name: 'Open-Meteo Ensemble',
    description: 'Ensemble weather model forecasts from Open-Meteo with per-model identity preserved.',
    primary_category: 'weather',
    capabilities: Object.freeze(['weather', 'precipitation', 'environmental', 'climate']),
    endpoints: Object.freeze({
      base_url: 'https://ensemble-api.open-meteo.com',
      api_version: 'v1',
      documentation_url: 'https://open-meteo.com/en/docs/ensemble-api',
      status_url: null,
    }),
    data_characteristics: Object.freeze({
      freshness: 'realtime',
      geographic_scope: Object.freeze(['GLOBAL']),
      historical_data: false,
      realtime: true,
      data_format: 'json',
      notes: 'Ensemble model runs retain individual model identity.',
    }),
  }),
  envProvider({
    provider_id: 'nws',
    name: 'U.S. National Weather Service',
    short_name: 'NWS',
    description: 'Official U.S. National Weather Service forecasts, observations, and alerts.',
    primary_category: 'weather',
    capabilities: Object.freeze(['weather', 'environmental', 'environmental_risk', 'wildfire']),
    endpoints: Object.freeze({
      base_url: 'https://api.weather.gov',
      api_version: null,
      documentation_url: 'https://www.weather.gov/documentation/services-web-api',
      status_url: null,
    }),
    data_characteristics: Object.freeze({
      freshness: 'realtime',
      geographic_scope: Object.freeze(['US']),
      historical_data: true,
      realtime: true,
      data_format: 'json',
      notes: 'United States coverage only.',
    }),
    sunrey: Object.freeze({
      domain: ['world', 'travel', 'financial_agent', 'research'] as const,
      canonical_provider_interface: 'EnvironmentalOracleProvider',
      priority: 'critical',
      launch_tier: 'production_candidate',
      authority_class: 'authoritative_official',
      integration_state: 'adapter_implemented',
      existing_adapter: 'packages/sunrey-chain/src/environmental/adapters/nws.ts',
    }),
  }),
  envProvider({
    provider_id: 'aviationweather-noaa',
    name: 'AviationWeather.gov (NOAA)',
    short_name: 'AviationWeather',
    description: 'NOAA Aviation Weather Center METARs, TAFs, and aviation hazard data.',
    primary_category: 'aviation',
    capabilities: Object.freeze(['weather', 'environmental', 'environmental_risk']),
    endpoints: Object.freeze({
      base_url: 'https://aviationweather.gov',
      api_version: 'v4',
      documentation_url: 'https://aviationweather.gov/data/api/',
      status_url: null,
    }),
    data_characteristics: Object.freeze({
      freshness: 'realtime',
      geographic_scope: Object.freeze(['GLOBAL']),
      historical_data: true,
      realtime: true,
      data_format: 'json',
      notes: 'Aviation-focused weather; global airport coverage.',
    }),
    sunrey: Object.freeze({
      domain: ['travel', 'world', 'financial_agent'] as const,
      canonical_provider_interface: 'EnvironmentalOracleProvider',
      priority: 'high',
      launch_tier: 'production_candidate',
      authority_class: 'authoritative_official',
      integration_state: 'adapter_implemented',
      existing_adapter: 'packages/sunrey-chain/src/environmental/adapters/aviationweather-noaa.ts',
    }),
  }),
  envProvider({
    provider_id: 'pirate-weather',
    name: 'Pirate Weather',
    short_name: 'Pirate Weather',
    description: 'Dark Sky-compatible weather API with free tier for personal use.',
    primary_category: 'weather',
    capabilities: Object.freeze(['weather', 'precipitation']),
    endpoints: Object.freeze({
      base_url: 'https://api.pirateweather.net',
      api_version: 'v1',
      documentation_url: 'https://pirateweather.net/en/latest/API.html',
      status_url: null,
    }),
    authentication: Object.freeze({
      type: 'api_key',
      required: true,
      registration_required: true,
      environment_variable: 'PIRATE_WEATHER_API_KEY',
      notes: 'Free tier requires registration.',
    }),
    access: Object.freeze({
      status: 'free_tier',
      free_tier_verified: true,
      registration_required: true,
      notes: 'Free tier for personal/non-commercial use.',
    }),
  }),
  envProvider({
    provider_id: 'met-norway',
    name: 'MET Norway',
    short_name: 'MET Norway',
    description: 'Norwegian Meteorological Institute Locationforecast API.',
    primary_category: 'weather',
    capabilities: Object.freeze(['weather', 'precipitation', 'environmental']),
    endpoints: Object.freeze({
      base_url: 'https://api.met.no',
      api_version: 'v2',
      documentation_url: 'https://api.met.no/weatherapi/documentation',
      status_url: null,
    }),
    data_characteristics: Object.freeze({
      freshness: 'realtime',
      geographic_scope: Object.freeze(['GLOBAL']),
      historical_data: false,
      realtime: true,
      data_format: 'json',
      notes: 'Global forecast; Norwegian official authority.',
    }),
    sunrey: Object.freeze({
      domain: ['world', 'travel', 'research'] as const,
      canonical_provider_interface: 'EnvironmentalOracleProvider',
      priority: 'high',
      launch_tier: 'production_candidate',
      authority_class: 'authoritative_official',
      integration_state: 'adapter_implemented',
      existing_adapter: 'packages/sunrey-chain/src/environmental/adapters/met-norway.ts',
    }),
  }),
  envProvider({
    provider_id: 'meltema',
    name: 'Meltemi',
    short_name: 'Meltemi',
    description: 'Open weather data API with global coverage.',
    primary_category: 'weather',
    capabilities: Object.freeze(['weather', 'precipitation']),
    endpoints: Object.freeze({
      base_url: 'https://api.meltemi.org',
      api_version: 'v1',
      documentation_url: 'https://meltemi.org/docs',
      status_url: null,
    }),
  }),
  envProvider({
    provider_id: 'usgs-water',
    name: 'USGS Water Services',
    short_name: 'USGS Water',
    description: 'U.S. Geological Survey instantaneous values and daily statistics for streamgages and wells.',
    primary_category: 'water',
    capabilities: Object.freeze(['water_data', 'environmental']),
    endpoints: Object.freeze({
      base_url: 'https://waterservices.usgs.gov',
      api_version: null,
      documentation_url: 'https://waterservices.usgs.gov/',
      status_url: null,
    }),
    data_characteristics: Object.freeze({
      freshness: 'delayed',
      geographic_scope: Object.freeze(['US']),
      historical_data: true,
      realtime: true,
      data_format: 'json',
      notes: 'United States water gauge coverage only; sub-daily gauge updates.',
    }),
    sunrey: Object.freeze({
      domain: ['world', 'moonrey', 'research', 'infrastructure'] as const,
      canonical_provider_interface: 'EnvironmentalOracleProvider',
      priority: 'critical',
      launch_tier: 'production_candidate',
      authority_class: 'authoritative_official',
      integration_state: 'adapter_implemented',
      existing_adapter: 'packages/sunrey-chain/src/environmental/adapters/usgs-water.ts',
    }),
  }),
  envProvider({
    provider_id: 'epa',
    name: 'U.S. EPA Air Quality System',
    short_name: 'EPA AQS',
    description: 'U.S. Environmental Protection Agency Air Quality System monitoring data.',
    primary_category: 'environmental',
    capabilities: Object.freeze(['air_quality', 'environmental']),
    endpoints: Object.freeze({
      base_url: 'https://aqs.epa.gov',
      api_version: null,
      documentation_url: 'https://aqs.epa.gov/aqsweb/documents/data_api.html',
      status_url: null,
    }),
    data_characteristics: Object.freeze({
      freshness: 'delayed',
      geographic_scope: Object.freeze(['US']),
      historical_data: true,
      realtime: false,
      data_format: 'json',
      notes: 'United States air quality monitoring network; hourly aggregation cadence.',
    }),
    sunrey: Object.freeze({
      domain: ['world', 'research', 'financial_agent'] as const,
      canonical_provider_interface: 'EnvironmentalOracleProvider',
      priority: 'high',
      launch_tier: 'production_candidate',
      authority_class: 'authoritative_official',
      integration_state: 'adapter_implemented',
      existing_adapter: 'packages/sunrey-chain/src/environmental/adapters/epa.ts',
    }),
  }),
  envProvider({
    provider_id: 'kanari',
    name: 'Kanari',
    short_name: 'Kanari',
    description: 'Air quality monitoring API with global sensor network.',
    primary_category: 'environmental',
    capabilities: Object.freeze(['air_quality', 'environmental']),
    endpoints: Object.freeze({
      base_url: 'https://api.kanari.cc',
      api_version: 'v1',
      documentation_url: 'https://kanari.cc/docs',
      status_url: null,
    }),
  }),
  envProvider({
    provider_id: 'usgs-earthquake',
    name: 'USGS Earthquake Hazards Program',
    short_name: 'USGS Earthquake',
    description: 'U.S. Geological Survey real-time earthquake event feed.',
    primary_category: 'environmental',
    capabilities: Object.freeze(['earthquake', 'environmental', 'environmental_risk']),
    endpoints: Object.freeze({
      base_url: 'https://earthquake.usgs.gov',
      api_version: null,
      documentation_url: 'https://earthquake.usgs.gov/fdsnws/event/1/',
      status_url: null,
    }),
    data_characteristics: Object.freeze({
      freshness: 'realtime',
      geographic_scope: Object.freeze(['GLOBAL']),
      historical_data: true,
      realtime: true,
      data_format: 'json',
      notes: 'Global seismic event observations; not predictions.',
    }),
    sunrey: Object.freeze({
      domain: ['world', 'research', 'financial_agent', 'infrastructure'] as const,
      canonical_provider_interface: 'EnvironmentalOracleProvider',
      priority: 'critical',
      launch_tier: 'production_candidate',
      authority_class: 'authoritative_official',
      integration_state: 'adapter_implemented',
      existing_adapter: 'packages/sunrey-chain/src/environmental/adapters/usgs-earthquake.ts',
    }),
  }),
  envProvider({
    provider_id: 'openaq',
    name: 'OpenAQ',
    short_name: 'OpenAQ',
    description: 'Global open air quality data platform aggregating government monitoring stations.',
    primary_category: 'environmental',
    capabilities: Object.freeze(['air_quality', 'environmental']),
    endpoints: Object.freeze({
      base_url: 'https://api.openaq.org',
      api_version: 'v3',
      documentation_url: 'https://docs.openaq.org/',
      status_url: 'https://status.openaq.org/',
    }),
    data_characteristics: Object.freeze({
      freshness: 'delayed',
      geographic_scope: Object.freeze(['GLOBAL']),
      historical_data: true,
      realtime: true,
      data_format: 'json',
      notes: 'AQI standards preserved per source; hourly station cadence, no cross-standard comparison without metadata.',
    }),
  }),
  envProvider({
    provider_id: 'purpleair',
    name: 'PurpleAir',
    short_name: 'PurpleAir',
    description: 'Community air quality sensor network with PM2.5 and PM10 readings.',
    primary_category: 'environmental',
    capabilities: Object.freeze(['air_quality', 'environmental']),
    endpoints: Object.freeze({
      base_url: 'https://api.purpleair.com',
      api_version: 'v1',
      documentation_url: 'https://api.purpleair.com/',
      status_url: null,
    }),
    authentication: Object.freeze({
      type: 'api_key',
      required: true,
      registration_required: true,
      environment_variable: 'PURPLEAIR_API_KEY',
      notes: 'Free read API key required.',
    }),
    access: Object.freeze({
      status: 'free_tier',
      free_tier_verified: true,
      registration_required: true,
      notes: 'Community sensor data.',
    }),
    sunrey: Object.freeze({
      domain: ['world', 'research'] as const,
      canonical_provider_interface: 'EnvironmentalOracleProvider',
      priority: 'medium',
      launch_tier: 'secondary_source',
      authority_class: 'community_data',
      integration_state: 'adapter_implemented',
      existing_adapter: 'packages/sunrey-chain/src/environmental/adapters/purpleair.ts',
    }),
  }),
]);
