import type { Jurisdiction } from '../../../../domain/src/jurisdiction.ts';
import { M02_REFERENCE_INSTRUMENT_IDS } from '../market-observation/instrument-registry.ts';
import type { ProviderCapabilityObject } from './types.ts';

const US_JURISDICTIONS: readonly Jurisdiction[] = Object.freeze(['US'] as Jurisdiction[]);
const GLOBAL_JURISDICTIONS: readonly Jurisdiction[] = Object.freeze(['US', 'GB', 'GLOBAL'] as Jurisdiction[]);

function capability(input: ProviderCapabilityObject): ProviderCapabilityObject {
  return Object.freeze(input);
}

/** Canonical provider capability catalog for M23 routing qualification. */
export const DEFAULT_EXECUTION_PROVIDER_CAPABILITIES: readonly ProviderCapabilityObject[] = Object.freeze([
  capability({
    routeId: 'route_equity_paper_sandbox',
    providerId: 'sunrey-investments-paper',
    accountId: 'acct_paper_equity_sandbox',
    supportedAssetClasses: Object.freeze(['etf', 'equity', 'index']),
    supportedInstruments: Object.freeze([
      M02_REFERENCE_INSTRUMENT_IDS.SPY,
      'SIM-ETF-1',
      'SIM-EQ-1',
    ]),
    supportedJurisdictions: US_JURISDICTIONS,
    marketDataCapability: 'FULL',
    executionCapability: 'FULL',
    custodyCapability: 'LIMITED',
    fundingCapability: 'FULL',
    withdrawalCapability: 'LIMITED',
    supportedOrderTypes: Object.freeze(['MARKET', 'LIMIT']),
    supportedSessions: Object.freeze(['OPEN', 'PRE_MARKET', 'POST_MARKET']),
    environment: 'sandbox',
    certificationState: 'SANDBOX_CERTIFIED',
    healthState: 'HEALTHY',
    venueIds: Object.freeze(['ARCX', 'SIM_EXCHANGE']),
    estimatedFeeBps: 0,
    estimatedSpreadBps: 5,
    liquidityScore: 900,
    rateLimitHeadroom: 100,
    implementationStatus: 'SANDBOX_QUALIFIED',
    credentialEnvVar: null,
  }),
  capability({
    routeId: 'route_crypto_sandbox_execution',
    providerId: 'sandbox_helios_investment_v1',
    accountId: 'acct_crypto_sandbox',
    supportedAssetClasses: Object.freeze(['crypto']),
    supportedInstruments: Object.freeze([M02_REFERENCE_INSTRUMENT_IDS.BTC]),
    supportedJurisdictions: GLOBAL_JURISDICTIONS,
    marketDataCapability: 'LIMITED',
    executionCapability: 'FULL',
    custodyCapability: 'FULL',
    fundingCapability: 'LIMITED',
    withdrawalCapability: 'LIMITED',
    supportedOrderTypes: Object.freeze(['MARKET', 'LIMIT']),
    supportedSessions: Object.freeze(['OPEN']),
    environment: 'sandbox',
    certificationState: 'SANDBOX_CERTIFIED',
    healthState: 'HEALTHY',
    venueIds: Object.freeze(['SIM']),
    estimatedFeeBps: 10,
    estimatedSpreadBps: 15,
    liquidityScore: 750,
    rateLimitHeadroom: 80,
    implementationStatus: 'SANDBOX_QUALIFIED',
    credentialEnvVar: null,
  }),
  capability({
    routeId: 'route_equity_finnhub_market_data_only',
    providerId: 'finnhub',
    accountId: 'acct_finnhub_data',
    supportedAssetClasses: Object.freeze(['etf', 'equity', 'index']),
    supportedInstruments: Object.freeze([M02_REFERENCE_INSTRUMENT_IDS.SPY]),
    supportedJurisdictions: US_JURISDICTIONS,
    marketDataCapability: 'FULL',
    executionCapability: 'UNAVAILABLE',
    custodyCapability: 'UNAVAILABLE',
    fundingCapability: 'UNAVAILABLE',
    withdrawalCapability: 'UNAVAILABLE',
    supportedOrderTypes: Object.freeze([]),
    supportedSessions: Object.freeze(['OPEN', 'PRE_MARKET', 'POST_MARKET']),
    environment: 'sandbox',
    certificationState: 'SANDBOX_CERTIFIED',
    healthState: 'HEALTHY',
    venueIds: Object.freeze(['ARCX']),
    estimatedFeeBps: 0,
    estimatedSpreadBps: 0,
    liquidityScore: 0,
    rateLimitHeadroom: 50,
    implementationStatus: 'CREDENTIAL_DEPENDENT',
    credentialEnvVar: 'FINNHUB_API_KEY',
  }),
  capability({
    routeId: 'route_crypto_coingecko_market_data_only',
    providerId: 'coingecko',
    accountId: 'acct_coingecko_data',
    supportedAssetClasses: Object.freeze(['crypto']),
    supportedInstruments: Object.freeze([M02_REFERENCE_INSTRUMENT_IDS.BTC]),
    supportedJurisdictions: GLOBAL_JURISDICTIONS,
    marketDataCapability: 'FULL',
    executionCapability: 'UNAVAILABLE',
    custodyCapability: 'UNAVAILABLE',
    fundingCapability: 'UNAVAILABLE',
    withdrawalCapability: 'UNAVAILABLE',
    supportedOrderTypes: Object.freeze([]),
    supportedSessions: Object.freeze(['OPEN']),
    environment: 'sandbox',
    certificationState: 'SANDBOX_CERTIFIED',
    healthState: 'HEALTHY',
    venueIds: Object.freeze(['SIM']),
    estimatedFeeBps: 0,
    estimatedSpreadBps: 0,
    liquidityScore: 0,
    rateLimitHeadroom: 30,
    implementationStatus: 'CREDENTIAL_DEPENDENT',
    credentialEnvVar: 'COINGECKO_API_KEY',
  }),
  capability({
    routeId: 'route_futures_cme_external',
    providerId: 'cme_futures_external',
    accountId: 'acct_futures_external',
    supportedAssetClasses: Object.freeze(['future', 'commodity']),
    supportedInstruments: Object.freeze(['FUTURE:US:CL:CONTINUOUS', 'COMMODITY:GLOBAL:GOLD:XCEC']),
    supportedJurisdictions: US_JURISDICTIONS,
    marketDataCapability: 'VIEW_ONLY',
    executionCapability: 'UNAVAILABLE',
    custodyCapability: 'UNAVAILABLE',
    fundingCapability: 'UNAVAILABLE',
    withdrawalCapability: 'UNAVAILABLE',
    supportedOrderTypes: Object.freeze(['MARKET', 'LIMIT']),
    supportedSessions: Object.freeze(['OPEN']),
    environment: 'production_disabled',
    certificationState: 'NOT_CERTIFIED',
    healthState: 'UNAVAILABLE',
    venueIds: Object.freeze(['XCME', 'XCEC']),
    estimatedFeeBps: 0,
    estimatedSpreadBps: 0,
    liquidityScore: 0,
    rateLimitHeadroom: 0,
    implementationStatus: 'EXTERNALLY_REQUIRED',
    credentialEnvVar: null,
  }),
  capability({
    routeId: 'route_equity_degraded_failover',
    providerId: 'sunrey-investments-paper-failover',
    accountId: 'acct_paper_equity_failover',
    supportedAssetClasses: Object.freeze(['etf', 'equity', 'index']),
    supportedInstruments: Object.freeze([M02_REFERENCE_INSTRUMENT_IDS.SPY, 'SIM-ETF-1']),
    supportedJurisdictions: US_JURISDICTIONS,
    marketDataCapability: 'FULL',
    executionCapability: 'FULL',
    custodyCapability: 'LIMITED',
    fundingCapability: 'FULL',
    withdrawalCapability: 'LIMITED',
    supportedOrderTypes: Object.freeze(['MARKET', 'LIMIT']),
    supportedSessions: Object.freeze(['OPEN', 'PRE_MARKET', 'POST_MARKET']),
    environment: 'sandbox',
    certificationState: 'SANDBOX_CERTIFIED',
    healthState: 'HEALTHY',
    venueIds: Object.freeze(['SIM_EXCHANGE']),
    estimatedFeeBps: 5,
    estimatedSpreadBps: 8,
    liquidityScore: 700,
    rateLimitHeadroom: 90,
    implementationStatus: 'SANDBOX_QUALIFIED',
    credentialEnvVar: null,
  }),
]);

export function createDefaultProviderCapabilityRegistry(
  overrides: readonly ProviderCapabilityObject[] = DEFAULT_EXECUTION_PROVIDER_CAPABILITIES,
) {
  const rows = [...overrides];
  return Object.freeze({
    listCapabilities(): readonly ProviderCapabilityObject[] {
      return Object.freeze([...rows]);
    },
    getCapability(providerId: string, accountId: string): ProviderCapabilityObject | null {
      return rows.find((row) => row.providerId === providerId && row.accountId === accountId) ?? null;
    },
  });
}
