use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum InteropError {
    UnregisteredChain,
    WrongExternalChainId,
    WrongGenesis,
    InvalidHeader,
    InvalidFinalityProof,
    InvalidMembershipProof,
    InvalidNonMembershipProof,
    ModifiedPacket,
    PacketReplay,
    AckReplay,
    ClientFrozen,
    ClientExpired,
    ClientNotFound,
    ConnectionNotFound,
    ChannelNotFound,
    PacketNotFound,
    SequenceMismatch,
    Timeout,
    CapabilityDenied,
    GovernanceRequired,
    AiCannotActivate,
    SizeExceeded,
    DuplicateUpdate,
    FutureHeightRejected,
    RateLimited,
    RelayerForbidden,
    WrappedFiatForbidden,
    ProductionAssetUnavailable,
    SupplyInvariantViolated,
    SchemaInvalid,
    ProofSystemMismatch,
    TrustAnchorMismatch,
    UpgradeUnauthorized,
    SilentUpgradeForbidden,
    ForeignValueNotEconomicTruth,
    IdentityNotAutomaticallyTrusted,
    PacketTypeDenied,
    OrderedSequenceGap,
    ConnectionHandshakeInvalid,
    StatusNotActivatable,
    VerificationNotImplemented,
    ExpiredRecoveryRequired,
    FiatLedgerMutationForbidden,
    MisbehaviorDetected,
    ChannelNotFoundOpen,
    TimeoutProofRequired,
    ClientNotActive,
    ProductionInteropDisabled,
    GlobalInteropPaused,
    NetworkPaused,
    AssetPaused,
    MessageExpired,
    UnsupportedMessageVersion,
    UnauthorizedRelayer,
    RpcMethodForbidden,
    NetworkEgressDenied,
    ExternalRpcTimeout,
    ExternalRpcStale,
    ExternalRpcReorg,
    ExternalRpcConflict,
    ExternalRpcMalformed,
    ExternalRpcRateLimited,
    KeyPurposeForbidden,
    OutboundSettlementCorruption,
    ValueLimitExceeded,
    MessageCountLimitExceeded,
    AnomalyThresholdExceeded,
    ObservationUnverified,
    WatcherForbidden,
}

impl InteropError {
    pub fn as_str(self) -> &'static str {
        match self {
            Self::UnregisteredChain => "UNREGISTERED_CHAIN",
            Self::WrongExternalChainId => "WRONG_EXTERNAL_CHAIN_ID",
            Self::WrongGenesis => "WRONG_GENESIS",
            Self::InvalidHeader => "INVALID_HEADER",
            Self::InvalidFinalityProof => "INVALID_FINALITY_PROOF",
            Self::InvalidMembershipProof => "INVALID_MEMBERSHIP_PROOF",
            Self::InvalidNonMembershipProof => "INVALID_NON_MEMBERSHIP_PROOF",
            Self::ModifiedPacket => "MODIFIED_PACKET",
            Self::PacketReplay => "PACKET_REPLAY",
            Self::AckReplay => "ACK_REPLAY",
            Self::ClientFrozen => "CLIENT_FROZEN",
            Self::ClientExpired => "CLIENT_EXPIRED",
            Self::ClientNotFound => "CLIENT_NOT_FOUND",
            Self::ConnectionNotFound => "CONNECTION_NOT_FOUND",
            Self::ChannelNotFound => "CHANNEL_NOT_FOUND",
            Self::PacketNotFound => "PACKET_NOT_FOUND",
            Self::SequenceMismatch => "SEQUENCE_MISMATCH",
            Self::Timeout => "TIMEOUT",
            Self::CapabilityDenied => "CAPABILITY_DENIED",
            Self::GovernanceRequired => "GOVERNANCE_REQUIRED",
            Self::AiCannotActivate => "AI_CANNOT_ACTIVATE",
            Self::SizeExceeded => "SIZE_EXCEEDED",
            Self::DuplicateUpdate => "DUPLICATE_UPDATE",
            Self::FutureHeightRejected => "FUTURE_HEIGHT_REJECTED",
            Self::RateLimited => "RATE_LIMITED",
            Self::RelayerForbidden => "RELAYER_FORBIDDEN",
            Self::WrappedFiatForbidden => "WRAPPED_FIAT_FORBIDDEN",
            Self::ProductionAssetUnavailable => "PRODUCTION_ASSET_UNAVAILABLE",
            Self::SupplyInvariantViolated => "SUPPLY_INVARIANT_VIOLATED",
            Self::SchemaInvalid => "SCHEMA_INVALID",
            Self::ProofSystemMismatch => "PROOF_SYSTEM_MISMATCH",
            Self::TrustAnchorMismatch => "TRUST_ANCHOR_MISMATCH",
            Self::UpgradeUnauthorized => "UPGRADE_UNAUTHORIZED",
            Self::SilentUpgradeForbidden => "SILENT_UPGRADE_FORBIDDEN",
            Self::ForeignValueNotEconomicTruth => "FOREIGN_VALUE_NOT_ECONOMIC_TRUTH",
            Self::IdentityNotAutomaticallyTrusted => "IDENTITY_NOT_AUTOMATICALLY_TRUSTED",
            Self::PacketTypeDenied => "PACKET_TYPE_DENIED",
            Self::OrderedSequenceGap => "ORDERED_SEQUENCE_GAP",
            Self::ConnectionHandshakeInvalid => "CONNECTION_HANDSHAKE_INVALID",
            Self::StatusNotActivatable => "STATUS_NOT_ACTIVATABLE",
            Self::VerificationNotImplemented => "VERIFICATION_NOT_IMPLEMENTED",
            Self::ExpiredRecoveryRequired => "EXPIRED_RECOVERY_REQUIRED",
            Self::FiatLedgerMutationForbidden => "FIAT_LEDGER_MUTATION_FORBIDDEN",
            Self::MisbehaviorDetected => "MISBEHAVIOR_DETECTED",
            Self::ChannelNotFoundOpen => "CHANNEL_NOT_OPEN",
            Self::TimeoutProofRequired => "TIMEOUT_PROOF_REQUIRED",
            Self::ClientNotActive => "CLIENT_NOT_ACTIVE",
            Self::ProductionInteropDisabled => "PRODUCTION_INTEROP_DISABLED",
            Self::GlobalInteropPaused => "GLOBAL_INTEROP_PAUSED",
            Self::NetworkPaused => "NETWORK_PAUSED",
            Self::AssetPaused => "ASSET_PAUSED",
            Self::MessageExpired => "MESSAGE_EXPIRED",
            Self::UnsupportedMessageVersion => "UNSUPPORTED_MESSAGE_VERSION",
            Self::UnauthorizedRelayer => "UNAUTHORIZED_RELAYER",
            Self::RpcMethodForbidden => "RPC_METHOD_FORBIDDEN",
            Self::NetworkEgressDenied => "NETWORK_EGRESS_DENIED",
            Self::ExternalRpcTimeout => "EXTERNAL_RPC_TIMEOUT",
            Self::ExternalRpcStale => "EXTERNAL_RPC_STALE",
            Self::ExternalRpcReorg => "EXTERNAL_RPC_REORG",
            Self::ExternalRpcConflict => "EXTERNAL_RPC_CONFLICT",
            Self::ExternalRpcMalformed => "EXTERNAL_RPC_MALFORMED",
            Self::ExternalRpcRateLimited => "EXTERNAL_RPC_RATE_LIMITED",
            Self::KeyPurposeForbidden => "KEY_PURPOSE_FORBIDDEN",
            Self::OutboundSettlementCorruption => "OUTBOUND_SETTLEMENT_CORRUPTION",
            Self::ValueLimitExceeded => "VALUE_LIMIT_EXCEEDED",
            Self::MessageCountLimitExceeded => "MESSAGE_COUNT_LIMIT_EXCEEDED",
            Self::AnomalyThresholdExceeded => "ANOMALY_THRESHOLD_EXCEEDED",
            Self::ObservationUnverified => "OBSERVATION_UNVERIFIED",
            Self::WatcherForbidden => "WATCHER_FORBIDDEN",
        }
    }
}

impl std::fmt::Display for InteropError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl std::error::Error for InteropError {}
