/**
 * Wave 4 provider catalog entries for compliance, KYB, fraud, and cybersecurity.
 */

const BASE_PROVIDER_FIELDS = {
  endpoints: {
    base_url: null as string | null,
    api_version: null as string | null,
    documentation_url: null as string | null,
    status_url: null as string | null,
  },
  authentication: {
    type: 'none' as const,
    required: false,
    registration_required: false,
    environment_variable: null as string | null,
    notes: null as string | null,
  },
  access: {
    status: 'verified_free' as const,
    free_tier_verified: true,
    registration_required: false,
    notes: null as string | null,
  },
  commercial_use: {
    status: 'verified_allowed' as const,
    notes: null as string | null,
  },
  redistribution: {
    status: 'attribution_required' as const,
    notes: null as string | null,
  },
  rate_limits: {
    documented: true,
    requests_per_second: null as number | null,
    requests_per_minute: null as number | null,
    requests_per_hour: null as number | null,
    requests_per_day: null as number | null,
    monthly_quota: null as number | null,
    concurrency_limit: null as number | null,
    notes: null as string | null,
  },
  data_characteristics: {
    freshness: 'daily' as const,
    geographic_scope: ['GLOBAL'] as string[],
    historical_data: true,
    realtime: false,
    data_format: 'json' as const,
    notes: null as string | null,
  },
  verification: {
    status: 'verified' as const,
    verified_against_official_docs: true,
    last_verified: '2026-08-30',
    notes: 'Wave 4 Prompt 17 fixture-backed adapter.',
  },
};

function entry(
  providerId: string,
  name: string,
  shortName: string,
  description: string,
  primaryCategory: string,
  capabilities: string[],
  domains: string[],
  iface: string,
  overrides: Record<string, unknown> = {},
) {
  return {
    provider_id: providerId,
    name,
    short_name: shortName,
    description,
    primary_category: primaryCategory,
    capabilities,
    ...BASE_PROVIDER_FIELDS,
    ...overrides,
    sunrey: {
      domain: domains,
      canonical_provider_interface: iface,
      priority: 'high',
      launch_tier: 'production_candidate',
      authority_class: primaryCategory === 'compliance' ? 'authoritative_official' : 'reference_data',
      integration_state: 'implemented',
      existing_adapter: 'packages/external-data/src/wave4/adapters.ts',
      ...(overrides.sunrey as object | undefined),
    },
    verification: {
      ...BASE_PROVIDER_FIELDS.verification,
      ...(overrides.verification as object | undefined),
    },
  };
}

export const WAVE4_CATALOG_ENTRIES = Object.freeze([
  entry(
    'open-sanctions',
    'OpenSanctions',
    'OpenSanctions',
    'Open-source sanctions, PEP, and watchlist data aggregated from official sources worldwide.',
    'compliance',
    ['sanctions', 'pep_screening', 'watchlists', 'adverse_media'],
    ['compliance', 'world', 'financial_agent'],
    'ComplianceEvidenceProvider',
    {
      endpoints: {
        base_url: 'https://api.opensanctions.org',
        api_version: 'v1',
        documentation_url: 'https://www.opensanctions.org/docs/api/',
        status_url: 'https://www.opensanctions.org/',
      },
      authentication: { type: 'api_key', required: false, registration_required: false, environment_variable: 'OPENSANCTIONS_API_KEY', notes: 'Optional API key for higher rate limits.' },
    },
  ),
  entry(
    'un-sanctions',
    'UN Security Council Sanctions',
    'UN Sanctions',
    'United Nations Security Council consolidated sanctions list.',
    'compliance',
    ['sanctions', 'watchlists'],
    ['compliance'],
    'ComplianceEvidenceProvider',
    {
      endpoints: {
        base_url: 'https://scsanctions.un.org',
        api_version: null,
        documentation_url: 'https://www.un.org/securitycouncil/sanctions/information',
        status_url: null,
      },
      authority_class: 'authoritative_official',
    },
  ),
  entry(
    'eu-sanctions',
    'EU Consolidated Sanctions List',
    'EU Sanctions',
    'European Union consolidated financial sanctions list.',
    'compliance',
    ['sanctions', 'watchlists'],
    ['compliance'],
    'ComplianceEvidenceProvider',
    {
      endpoints: {
        base_url: 'https://webgate.ec.europa.eu',
        api_version: null,
        documentation_url: 'https://finance.ec.europa.eu/eu-and-world/sanctions-restrictive-measures_en',
        status_url: null,
      },
    },
  ),
  entry(
    'gleif-lei',
    'GLEIF LEI Registry',
    'GLEIF',
    'Global Legal Entity Identifier Foundation open LEI data.',
    'kyb_identity',
    ['kyb', 'corporate_identity', 'lei_lookup'],
    ['compliance', 'world'],
    'BusinessIdentityEvidenceProvider',
    {
      endpoints: {
        base_url: 'https://api.gleif.org',
        api_version: 'v1',
        documentation_url: 'https://www.gleif.org/en/lei-data/gleif-api',
        status_url: null,
      },
    },
  ),
  entry(
    'companies-house-uk',
    'UK Companies House API',
    'Companies House',
    'UK company registration and officer data from Companies House.',
    'kyb_identity',
    ['kyb', 'corporate_identity', 'officer_lookup'],
    ['compliance', 'world'],
    'BusinessIdentityEvidenceProvider',
    {
      endpoints: {
        base_url: 'https://api.company-information.service.gov.uk',
        api_version: 'v1',
        documentation_url: 'https://developer.company-information.service.gov.uk/',
        status_url: null,
      },
      authentication: { type: 'api_key', required: true, registration_required: true, environment_variable: 'COMPANIES_HOUSE_API_KEY', notes: 'Free API key from Companies House developer portal.' },
      access: { status: 'free_tier', free_tier_verified: true, registration_required: true, notes: '600 requests per 5 minutes on free tier.' },
    },
  ),
  entry(
    'opencorporates',
    'OpenCorporates',
    'OpenCorporates',
    'Open database of company data from official registries worldwide.',
    'kyb_identity',
    ['kyb', 'corporate_identity'],
    ['compliance', 'world'],
    'BusinessIdentityEvidenceProvider',
    {
      endpoints: {
        base_url: 'https://api.opencorporates.com',
        api_version: 'v0.4',
        documentation_url: 'https://api.opencorporates.com/documentation/API-Reference',
        status_url: null,
      },
      authentication: { type: 'api_key', required: true, registration_required: true, environment_variable: 'OPENCORPORATES_API_KEY', notes: 'Free tier with rate limits.' },
      access: { status: 'free_tier', free_tier_verified: true, registration_required: true, notes: 'Limited free tier.' },
    },
  ),
  entry(
    'abuseipdb',
    'AbuseIPDB',
    'AbuseIPDB',
    'Community-driven IP address abuse reporting and reputation database.',
    'fraud_risk',
    ['ip_risk', 'network_risk', 'fraud_detection'],
    ['compliance', 'cybersecurity'],
    'DigitalRiskEvidenceProvider',
    {
      endpoints: {
        base_url: 'https://api.abuseipdb.com',
        api_version: 'v2',
        documentation_url: 'https://docs.abuseipdb.com/',
        status_url: null,
      },
      authentication: { type: 'api_key', required: true, registration_required: true, environment_variable: 'ABUSEIPDB_API_KEY', notes: 'Free tier with daily check limits.' },
      access: { status: 'free_tier', free_tier_verified: true, registration_required: true, notes: '1000 checks/day on free tier.' },
    },
  ),
  entry(
    'ip-api',
    'IP-API',
    'IP-API',
    'IP geolocation and network information service.',
    'fraud_risk',
    ['ip_risk', 'network_risk', 'geolocation'],
    ['compliance', 'cybersecurity'],
    'DigitalRiskEvidenceProvider',
    {
      endpoints: {
        base_url: 'http://ip-api.com',
        api_version: null,
        documentation_url: 'http://ip-api.com/docs',
        status_url: null,
      },
      rate_limits: { documented: true, requests_per_second: null, requests_per_minute: 45, requests_per_hour: null, requests_per_day: null, monthly_quota: null, concurrency_limit: null, notes: '45 requests per minute from single IP on free tier.' },
    },
  ),
  entry(
    'nvd',
    'National Vulnerability Database',
    'NVD',
    'NIST National Vulnerability Database CVE feed.',
    'cybersecurity',
    ['vulnerability_intelligence', 'cve_lookup'],
    ['cybersecurity', 'infrastructure'],
    'VulnerabilityIntelligenceProvider',
    {
      endpoints: {
        base_url: 'https://services.nvd.nist.gov',
        api_version: 'v2.0',
        documentation_url: 'https://nvd.nist.gov/developers/vulnerabilities',
        status_url: null,
      },
      authentication: { type: 'api_key', required: false, registration_required: true, environment_variable: 'NVD_API_KEY', notes: 'Optional API key for higher rate limits.' },
      data_characteristics: { freshness: 'daily', geographic_scope: ['GLOBAL'], historical_data: true, realtime: false, data_format: 'json', notes: 'CVE feed updated continuously.' },
    },
  ),
  entry(
    'urlhaus',
    'URLhaus',
    'URLhaus',
    'abuse.ch URLhaus malicious URL database.',
    'cybersecurity',
    ['malicious_url', 'malware', 'threat_intelligence'],
    ['cybersecurity', 'compliance'],
    'ThreatIntelligenceProvider',
    {
      endpoints: {
        base_url: 'https://urlhaus-api.abuse.ch',
        api_version: 'v1',
        documentation_url: 'https://urlhaus-api.abuse.ch/',
        status_url: null,
      },
    },
  ),
  entry(
    'mozilla-http-observatory',
    'Mozilla HTTP Observatory',
    'HTTP Observatory',
    'Mozilla HTTP security header and configuration scanner.',
    'cybersecurity',
    ['http_security', 'endpoint_security'],
    ['cybersecurity', 'infrastructure'],
    'EndpointSecurityProvider',
    {
      endpoints: {
        base_url: 'https://http-observatory.security.mozilla.org',
        api_version: 'v2',
        documentation_url: 'https://github.com/mozilla/http-observatory/blob/master/httpobs/docs/api.md',
        status_url: null,
      },
    },
  ),
  entry(
    'mozilla-tls-observatory',
    'Mozilla TLS Observatory',
    'TLS Observatory',
    'Mozilla TLS configuration and certificate analysis.',
    'cybersecurity',
    ['tls_security', 'endpoint_security'],
    ['cybersecurity', 'infrastructure'],
    'EndpointSecurityProvider',
    {
      endpoints: {
        base_url: 'https://tls-observatory.services.mozilla.com',
        api_version: 'v1',
        documentation_url: 'https://github.com/mozilla/tls-observatory',
        status_url: null,
      },
    },
  ),
  entry(
    'phishstats',
    'PhishStats',
    'PhishStats',
    'Phishing URL intelligence feed.',
    'cybersecurity',
    ['phishing', 'threat_intelligence', 'malicious_url'],
    ['cybersecurity', 'compliance'],
    'ThreatIntelligenceProvider',
    {
      endpoints: {
        base_url: 'https://phishstats.info',
        api_version: 'v1',
        documentation_url: 'https://phishstats.info/api',
        status_url: null,
      },
    },
  ),
  entry(
    'virushee',
    'Virushee',
    'Virushee',
    'Community malware hash and URL intelligence.',
    'cybersecurity',
    ['malware', 'threat_intelligence'],
    ['cybersecurity'],
    'ThreatIntelligenceProvider',
    {
      endpoints: {
        base_url: 'https://virushee.com',
        api_version: 'v1',
        documentation_url: 'https://virushee.com/api',
        status_url: null,
      },
      verification: { status: 'partially_verified', verified_against_official_docs: true, last_verified: '2026-08-30', notes: 'Community threat feed; terms partially verified.' },
    },
  ),
  entry(
    'cloudflare-trace',
    'Cloudflare Trace',
    'CF Trace',
    'Cloudflare diagnostic trace for network path analysis.',
    'cybersecurity',
    ['domain_security', 'network_diagnostics'],
    ['cybersecurity', 'infrastructure'],
    'EndpointSecurityProvider',
    {
      endpoints: {
        base_url: 'https://1.1.1.1',
        api_version: null,
        documentation_url: 'https://developers.cloudflare.com/1.1.1.1/',
        status_url: 'https://www.cloudflarestatus.com/',
      },
    },
  ),
  entry(
    'outagedeck',
    'OutageDeck',
    'OutageDeck',
    'Third-party service outage aggregation and status monitoring.',
    'cybersecurity',
    ['outage_monitoring', 'service_status'],
    ['cybersecurity', 'infrastructure', 'action_center'],
    'ServiceOutageProvider',
    {
      endpoints: {
        base_url: 'https://outagedeck.com',
        api_version: null,
        documentation_url: 'https://outagedeck.com/api',
        status_url: null,
      },
    },
  ),
  entry(
    'downstatus',
    'DownStatus',
    'DownStatus',
    'Service availability and outage status aggregator.',
    'cybersecurity',
    ['outage_monitoring', 'service_status'],
    ['cybersecurity', 'infrastructure', 'action_center'],
    'ServiceOutageProvider',
    {
      endpoints: {
        base_url: 'https://downstatus.com',
        api_version: null,
        documentation_url: 'https://downstatus.com/api',
        status_url: null,
      },
    },
  ),
  // Blocked providers — accounted for, not integrated
  {
    provider_id: 'world-check-refinitiv',
    name: 'World-Check (Refinitiv)',
    short_name: 'World-Check',
    description: 'Commercial PEP and sanctions screening. Paid subscription required; not eligible for free tier.',
    primary_category: 'compliance',
    capabilities: ['sanctions', 'pep_screening', 'adverse_media'],
    ...BASE_PROVIDER_FIELDS,
    access: { status: 'no_longer_free', free_tier_verified: false, registration_required: true, notes: 'Commercial only.' },
    commercial_use: { status: 'requires_legal_review', notes: 'Paid commercial service.' },
    sunrey: {
      domain: ['compliance'],
      canonical_provider_interface: 'ComplianceEvidenceProvider',
      priority: 'low',
      launch_tier: 'blocked_pending_review',
      authority_class: 'regulated_provider',
      integration_state: 'catalog_only',
      existing_adapter: null,
    },
    verification: { status: 'unverified', verified_against_official_docs: false, last_verified: null, notes: 'Blocked — commercial only, no free tier.' },
  },
  {
    provider_id: 'dow-jones-risk',
    name: 'Dow Jones Risk & Compliance',
    short_name: 'Dow Jones',
    description: 'Commercial risk and compliance data. Paid subscription required.',
    primary_category: 'compliance',
    capabilities: ['sanctions', 'pep_screening', 'adverse_media'],
    ...BASE_PROVIDER_FIELDS,
    access: { status: 'no_longer_free', free_tier_verified: false, registration_required: true, notes: 'Commercial only.' },
    commercial_use: { status: 'requires_legal_review', notes: 'Paid commercial service.' },
    sunrey: {
      domain: ['compliance'],
      canonical_provider_interface: 'ComplianceEvidenceProvider',
      priority: 'low',
      launch_tier: 'blocked_pending_review',
      authority_class: 'regulated_provider',
      integration_state: 'catalog_only',
      existing_adapter: null,
    },
    verification: { status: 'unverified', verified_against_official_docs: false, last_verified: null, notes: 'Blocked — commercial only.' },
  },
  {
    provider_id: 'lexisnexis-bridger',
    name: 'LexisNexis Bridger',
    short_name: 'Bridger',
    description: 'Commercial AML/sanctions screening platform. No free tier.',
    primary_category: 'compliance',
    capabilities: ['sanctions', 'pep_screening', 'aml'],
    ...BASE_PROVIDER_FIELDS,
    access: { status: 'no_longer_free', free_tier_verified: false, registration_required: true, notes: 'Commercial only.' },
    sunrey: {
      domain: ['compliance'],
      canonical_provider_interface: 'ComplianceEvidenceProvider',
      priority: 'low',
      launch_tier: 'blocked_pending_review',
      authority_class: 'regulated_provider',
      integration_state: 'catalog_only',
      existing_adapter: null,
    },
    verification: { status: 'unverified', verified_against_official_docs: false, last_verified: null, notes: 'Blocked — commercial only.' },
  },
  {
    provider_id: 'pep-wikidata-legacy',
    name: 'Wikidata PEP (Legacy)',
    short_name: 'Wikidata PEP',
    description: 'Legacy community PEP dataset. Deprecated in favor of OpenSanctions.',
    primary_category: 'compliance',
    capabilities: ['pep_screening'],
    ...BASE_PROVIDER_FIELDS,
    sunrey: {
      domain: ['compliance', 'research'],
      canonical_provider_interface: 'ComplianceEvidenceProvider',
      priority: 'low',
      launch_tier: 'research_only',
      authority_class: 'community_data',
      integration_state: 'catalog_only',
      existing_adapter: null,
    },
    verification: { status: 'deprecated', verified_against_official_docs: false, last_verified: '2024-01-01', notes: 'Deprecated — use OpenSanctions instead.' },
  },
]);

export const WAVE4_IMPLEMENTED_PROVIDER_IDS = Object.freeze(
  WAVE4_CATALOG_ENTRIES.filter(
    (e) => (e.sunrey as { integration_state?: string }).integration_state === 'implemented',
  ).map((e) => e.provider_id),
);

export const WAVE4_BLOCKED_PROVIDER_IDS = Object.freeze([
  'world-check-refinitiv',
  'dow-jones-risk',
  'lexisnexis-bridger',
]);

export const WAVE4_DEPRECATED_PROVIDER_IDS = Object.freeze(['pep-wikidata-legacy']);
