import type { ProtectedAsset } from './types.ts';

export const PROTECTED_ASSETS: readonly ProtectedAsset[] = Object.freeze([
  {
    asset_id: 'AST-VALIDATOR-CONSENSUS-KEYS',
    name: 'validator consensus keys',
    classification: 'key_material',
    ownerPath: 'packages/sunrey-chain/src/validator-keys.ts',
    trustBoundary: 'validator',
    notes: 'Separated from proposal, P2P, governance, and recovery keys. HMAC is forbidden for consensus.',
  },
  {
    asset_id: 'AST-GOVERNANCE-KEYS',
    name: 'governance keys',
    classification: 'key_material',
    ownerPath: 'packages/sunrey-chain/src/governance',
    trustBoundary: 'governance_authority',
    notes: 'Authorize height-activated UpgradePlan only. Not a software-release signer.',
  },
  {
    asset_id: 'AST-RELEASE-KEYS',
    name: 'release keys',
    classification: 'key_material',
    ownerPath: 'packages/sunrey-chain/src/supply-chain/release.ts',
    trustBoundary: 'release_authority',
    notes: 'ReleaseAuthority signs artifacts only. Local/test signing in this tree.',
  },
  {
    asset_id: 'AST-CUSTODY-SIGNING-KEYS',
    name: 'custody signing keys',
    classification: 'key_material',
    ownerPath: 'packages/custody/src/institutional',
    trustBoundary: 'custody_hsm',
    notes: 'Development HSM simulator. External production HSM integration is not completed.',
  },
  {
    asset_id: 'AST-WALLET-KEYS',
    name: 'wallet keys',
    classification: 'key_material',
    ownerPath: 'packages/sunrey-chain/src/wallet',
    trustBoundary: 'wallet_signer',
    notes: 'Local encrypted development keystore. PrivateKeyMaterial must not appear in logs.',
  },
  {
    asset_id: 'AST-PQC-KEYS',
    name: 'PQC keys',
    classification: 'key_material',
    ownerPath: 'packages/security/src/pq-provider.ts',
    trustBoundary: 'wallet_signer',
    notes: 'ML-DSA / ML-KEM / SLH-DSA development/testnet keys. Not production-approved.',
  },
  {
    asset_id: 'AST-NATIVE-SUPPLY',
    name: 'native asset supply state',
    classification: 'state',
    ownerPath: 'packages/sunrey-chain/src/native-assets',
    trustBoundary: 'validator',
    notes: 'Authoritative supply is chain state. Tickers remain NOT_ASSIGNED.',
  },
  {
    asset_id: 'AST-MOONREY-ISSUANCE-AUTHORITY',
    name: 'MoonRey issuance authority',
    classification: 'authority',
    ownerPath: 'packages/sunrey-chain/src/productive/issuance.ts',
    trustBoundary: 'governance_authority',
    notes: 'Productive-claim issuance only. Arbitrary ISSUE remains unavailable.',
  },
  {
    asset_id: 'AST-ORACLE-PROVIDER-KEYS',
    name: 'oracle provider keys',
    classification: 'key_material',
    ownerPath: 'packages/sunrey-chain/src/oracle/crypto.ts',
    trustBoundary: 'oracle_provider',
    notes: 'ORACLE_SIGNING purpose. Observations are not money.',
  },
  {
    asset_id: 'AST-CONSENT-ARTIFACTS',
    name: 'consent artifacts',
    classification: 'personal_data',
    ownerPath: 'packages/consent',
    trustBoundary: 'personal_data_vault',
    notes: 'Purpose Firewall gates use. Explorer must not expose private consent details.',
  },
  {
    asset_id: 'AST-PRIVATE-PERSONAL-DATA',
    name: 'private personal data',
    classification: 'personal_data',
    ownerPath: 'packages/personal-data-vault',
    trustBoundary: 'personal_data_vault',
    notes: 'Subject-bound encrypted payloads. Raw content is FORBIDDEN on Explorer.',
  },
  {
    asset_id: 'AST-UPGRADE-ARTIFACTS',
    name: 'upgrade artifacts',
    classification: 'artifact',
    ownerPath: 'packages/sunrey-chain/src/governance',
    trustBoundary: 'governance_authority',
    notes: 'UpgradePlan is height-activated. Software release does not activate protocol change.',
  },
  {
    asset_id: 'AST-GENESIS-MATERIAL',
    name: 'genesis material',
    classification: 'artifact',
    ownerPath: 'packages/sunrey-chain/src/testnet/genesis.ts',
    trustBoundary: 'release_authority',
    notes: 'Fixture genesis hash cb31243a83383bd6b2d31ad50757b28da06c487c293aeade8b1cb1ffa3e1fbd6. Test-only keys.',
  },
]);
