import type { AttackSurfaceEntry } from './types.ts';

export const ATTACK_SURFACE: readonly AttackSurfaceEntry[] = Object.freeze([
  {
    surface_id: 'SUR-P2P',
    name: 'P2P',
    authentication: 'P2P_IDENTITY suite binding',
    authorization: 'peer policy and sentry allowlists',
    networkExposure: 'public peers via sentry; validator host is private',
    rateLimits: 'peer-policy connection and gossip limits in ops',
    sensitiveOperations: ['block gossip', 'tx gossip', 'sync'],
    tests: ['packages/sunrey-chain/node', 'packages/sunrey-chain/src/ops/peer-policy.ts'],
  },
  {
    surface_id: 'SUR-RPC',
    name: 'RPC',
    authentication: 'unauthenticated public query; write paths require signed transactions',
    authorization: 'no validator or custody keys on the RPC process',
    networkExposure: 'public query / submit on testnet RPC',
    rateLimits: 'development rate-limit hooks in rust rpc crate',
    sensitiveOperations: ['broadcast tx', 'query account', 'query block'],
    tests: ['packages/sunrey-chain/rust/crates/rpc', 'packages/sunrey-chain/src/perf'],
  },
  {
    surface_id: 'SUR-EVENT-STREAM',
    name: 'event stream',
    authentication: 'SDK subscription token when configured; local demo is in-process',
    authorization: 'public events only; no PDV payloads',
    networkExposure: 'developer platform event subscriptions',
    rateLimits: 'SDK client backoff',
    sensitiveOperations: ['subscribe finalized blocks', 'subscribe receipts'],
    tests: ['packages/sunrey-sdk/src'],
  },
  {
    surface_id: 'SUR-EXPLORER-API',
    name: 'Explorer API',
    authentication: 'none on public explorer',
    authorization: 'ExplorerExposurePolicy default FORBIDDEN',
    networkExposure: 'public HTTP on testnet explorer',
    rateLimits: 'bounded identifier search; SQL rejected',
    sensitiveOperations: ['index query', 'rebuild', 'verify'],
    tests: ['packages/sunrey-explorer/src'],
  },
  {
    surface_id: 'SUR-FAUCET',
    name: 'faucet',
    authentication: 'testnet faucet authority auth.testnet.1.faucet',
    authorization: 'development faucet address only; not a mint of public product units',
    networkExposure: 'public testnet faucet',
    rateLimits: 'per-address faucet quota in testnet profiles',
    sensitiveOperations: ['request test units'],
    tests: ['packages/sunrey-chain/src/testnet'],
  },
  {
    surface_id: 'SUR-EXCHANGE',
    name: 'Exchange endpoints',
    authentication: 'signed account actions',
    authorization: 'reservation and listing governance',
    networkExposure: 'simulation exchange API',
    rateLimits: 'matching-engine admission limits',
    sensitiveOperations: ['place', 'cancel', 'reserve', 'settle DVP'],
    tests: ['packages/sunrey-exchange/src', 'tests/assurance/exchange.test.ts'],
  },
  {
    surface_id: 'SUR-RELAYER',
    name: 'relayer',
    authentication: 'interop packet proofs',
    authorization: 'channel freeze and at-most-once',
    networkExposure: 'development relayer',
    rateLimits: 'packet admission limits',
    sensitiveOperations: ['submit packet', 'ack', 'timeout'],
    tests: ['packages/sunrey-chain/src/interop'],
  },
  {
    surface_id: 'SUR-OPERATOR',
    name: 'operator interface',
    authentication: 'local operator CLI; no production credentials in git',
    authorization: 'ops commands cannot issue Execution Authority',
    networkExposure: 'host-local / private operator network',
    rateLimits: 'manual',
    sensitiveOperations: ['backup', 'failover', 'upgrade precheck', 'key ceremony'],
    tests: ['packages/sunrey-chain/src/ops/cli.ts', 'packages/sunrey-chain/src/ops.test.ts'],
  },
  {
    surface_id: 'SUR-REMOTE-SIGNER',
    name: 'remote signer interface',
    authentication: 'mTLS / local unix socket in development topology',
    authorization: 'signer-safety WAL; height/round uniqueness',
    networkExposure: 'private signer network, never public',
    rateLimits: 'one vote per (height, round, type)',
    sensitiveOperations: ['sign prevote', 'sign precommit', 'sign proposal'],
    tests: ['packages/sunrey-chain/src/ops/signer.ts', 'packages/sunrey-chain/src/ops/signer-safety.ts'],
  },
]);
