import type { SecurityControl } from './types.ts';

export const SECURITY_CONTROLS: readonly SecurityControl[] = Object.freeze([
  {
    control_id: 'CTL-CONSENSUS-QUORUM',
    description: 'Strictly more than two-thirds active voting power required to finalize.',
    kind: 'preventive',
    implementationPath: 'packages/sunrey-chain/rust/crates/consensus/src/quorum.rs',
    testReferences: ['packages/sunrey-chain/rust/crates/consensus/tests/safety.rs', 'packages/sunrey-chain/rust/crates/consensus/tests/properties.rs'],
    formalPropertyReferences: ['packages/sunrey-chain/src/assurance/consensus.ts'],
    runbook: 'docs/architecture/chunk-37-bft-consensus-core.md',
    knownLimitations: ['LIM-NO-FORMAL-VERIFICATION', 'LIM-DEV-CONSENSUS'],
    reviewStatus: 'IMPLEMENTED',
    domain: 'CONSENSUS',
  },
  {
    control_id: 'CTL-CONSENSUS-LOCK',
    description: 'Tendermint-class lock, valid-value, and NIL rules.',
    kind: 'preventive',
    implementationPath: 'packages/sunrey-chain/rust/crates/consensus/src/engine.rs',
    testReferences: ['packages/sunrey-chain/rust/crates/consensus/tests/safety.rs'],
    formalPropertyReferences: ['packages/sunrey-chain/rust/crates/consensus/ALGORITHM.md'],
    runbook: 'packages/sunrey-chain/rust/crates/consensus/ALGORITHM.md',
    knownLimitations: ['LIM-DEV-CONSENSUS'],
    reviewStatus: 'IMPLEMENTED',
    domain: 'CONSENSUS',
  },
  {
    control_id: 'CTL-VALIDATOR-ACCOUNTABILITY',
    description: 'Equivocation evidence, jail, and tombstone.',
    kind: 'detective',
    implementationPath: 'packages/sunrey-chain/src/evidence-format.ts',
    testReferences: ['packages/sunrey-chain/src/governance-malicious.test.ts'],
    formalPropertyReferences: [],
    runbook: 'docs/architecture/chunk-39-validator-accountability.md',
    knownLimitations: [],
    reviewStatus: 'IMPLEMENTED',
    domain: 'VALIDATORS',
  },
  {
    control_id: 'CTL-SIGNER-SEPARATION',
    description: 'Remote signer and sentry keep consensus keys off the public peer process.',
    kind: 'preventive',
    implementationPath: 'packages/sunrey-chain/src/ops/signer.ts',
    testReferences: ['packages/sunrey-chain/src/ops.test.ts'],
    formalPropertyReferences: [],
    runbook: 'docs/architecture/chunk-54-validator-operations.md',
    knownLimitations: ['LIM-NO-PRODUCTION-HSM'],
    reviewStatus: 'IMPLEMENTED',
    domain: 'VALIDATORS',
  },
  {
    control_id: 'CTL-SIGNER-WAL',
    description: 'Durable signer-safety WAL prevents double-sign sequences.',
    kind: 'preventive',
    implementationPath: 'packages/sunrey-chain/src/ops/signer-safety.ts',
    testReferences: ['packages/sunrey-chain/src/assurance/consensus.ts'],
    formalPropertyReferences: ['packages/sunrey-chain/src/assurance/coverage.ts'],
    runbook: null,
    knownLimitations: [],
    reviewStatus: 'IMPLEMENTED',
    domain: 'VALIDATORS',
  },
  {
    control_id: 'CTL-KEY-PURPOSE-SEPARATION',
    description: 'Typed key purposes. HMAC is forbidden for consensus.',
    kind: 'preventive',
    implementationPath: 'packages/security/src/purposes.ts',
    testReferences: ['packages/security/src'],
    formalPropertyReferences: [],
    runbook: 'docs/security/sunrey-blockchain-threat-model.md',
    knownLimitations: [],
    reviewStatus: 'IMPLEMENTED',
    domain: 'CRYPTOGRAPHY',
  },
  {
    control_id: 'CTL-SUITE-LIFECYCLE',
    description: 'Immutable CryptoSuite registry after construction. Unknown algorithm IDs fail closed.',
    kind: 'preventive',
    implementationPath: 'packages/security/src/crypto-suite.ts',
    testReferences: ['packages/security/src/pq-integration.test.ts'],
    formalPropertyReferences: [],
    runbook: 'docs/architecture/security.md',
    knownLimitations: ['LIM-NO-PRODUCTION-CRYPTO-APPROVAL'],
    reviewStatus: 'IMPLEMENTED',
    domain: 'CRYPTOGRAPHY',
  },
  {
    control_id: 'CTL-HYBRID-AND',
    description: 'CLASSICAL_AND_PQ requires both signatures over the same binding. No OR verification.',
    kind: 'preventive',
    implementationPath: 'packages/security/src/crypto-hybrid.ts',
    testReferences: ['packages/sunrey-chain/src/pqc/hybrid-rehearsal.test.ts'],
    formalPropertyReferences: [],
    runbook: 'docs/security/hybrid-signature-protocol.md',
    knownLimitations: ['LIM-NOT-QUANTUM-PROOF'],
    reviewStatus: 'IMPLEMENTED',
    domain: 'PQC',
  },
  {
    control_id: 'CTL-DOWNGRADE-REJECT',
    description: 'Downgrade-resistant bindings include suite and algorithm IDs.',
    kind: 'preventive',
    implementationPath: 'packages/security/src/crypto-hybrid.ts',
    testReferences: ['packages/security/src/pq-integration.test.ts'],
    formalPropertyReferences: [],
    runbook: 'docs/security/pqc-testnet-migration.md',
    knownLimitations: ['LIM-NOT-QUANTUM-PROOF'],
    reviewStatus: 'IMPLEMENTED',
    domain: 'PQC',
  },
  {
    control_id: 'CTL-WALLET-KEYSTORE',
    description: 'Local encrypted development keystore. Private keys are PrivateKeyMaterial.',
    kind: 'preventive',
    implementationPath: 'packages/sunrey-chain/src/wallet',
    testReferences: ['packages/sunrey-chain/src/wallet'],
    formalPropertyReferences: [],
    runbook: 'docs/architecture/chunk-46-sovereign-wallets.md',
    knownLimitations: [],
    reviewStatus: 'IMPLEMENTED',
    domain: 'WALLETS',
  },
  {
    control_id: 'CTL-MULTI-AUTH',
    description: 'M-of-N authorization, revoke, and historic verification.',
    kind: 'preventive',
    implementationPath: 'packages/sunrey-chain/src/wallet',
    testReferences: ['packages/sunrey-chain/rust/crates/wallet'],
    formalPropertyReferences: ['packages/sunrey-chain/src/assurance/coverage.ts'],
    runbook: 'docs/architecture/blockchain-account-authorization.md',
    knownLimitations: [],
    reviewStatus: 'IMPLEMENTED',
    domain: 'WALLETS',
  },
  {
    control_id: 'CTL-NATIVE-SUPPLY',
    description: 'Native supply is read from chain state. No stored Account balance.',
    kind: 'preventive',
    implementationPath: 'packages/sunrey-chain/src/native-assets',
    testReferences: ['packages/sunrey-chain/src/native-assets/native-assets.test.ts'],
    formalPropertyReferences: ['packages/sunrey-chain/src/assurance/properties.ts'],
    runbook: 'docs/architecture/native-asset-authority-boundary.md',
    knownLimitations: ['LIM-TICKERS-UNASSIGNED'],
    reviewStatus: 'IMPLEMENTED',
    domain: 'NATIVE_ASSETS',
  },
  {
    control_id: 'CTL-MOONREY-FINGERPRINT',
    description: 'Anti-double-count contribution fingerprint.',
    kind: 'preventive',
    implementationPath: 'packages/sunrey-chain/src/productive/fingerprint.ts',
    testReferences: ['packages/sunrey-chain/src/assurance/properties.ts'],
    formalPropertyReferences: ['packages/sunrey-chain/src/assurance/coverage.ts'],
    runbook: 'docs/architecture/moonrey-issuance-model.md',
    knownLimitations: ['LIM-DEV-ECONOMIC-PARAMS'],
    reviewStatus: 'IMPLEMENTED',
    domain: 'MOONREY_ISSUANCE',
  },
  {
    control_id: 'CTL-MOONREY-EPOCH-CAPS',
    description: 'Category, object, controller, and epoch issuance limits.',
    kind: 'preventive',
    implementationPath: 'packages/sunrey-chain/src/productive/issuance.ts',
    testReferences: ['packages/sunrey-chain/src/productive'],
    formalPropertyReferences: [],
    runbook: 'docs/architecture/moonrey-issuance-model.md',
    knownLimitations: ['LIM-DEV-ECONOMIC-PARAMS'],
    reviewStatus: 'IMPLEMENTED',
    domain: 'MOONREY_ISSUANCE',
  },
  {
    control_id: 'CTL-EXCHANGE-DVP',
    description: 'Delivery-versus-payment reservation and native clearing.',
    kind: 'preventive',
    implementationPath: 'packages/sunrey-exchange/src/native-clearing',
    testReferences: ['tests/assurance/exchange.test.ts'],
    formalPropertyReferences: [],
    runbook: 'docs/architecture/exchange-dvp-protocol.md',
    knownLimitations: [],
    reviewStatus: 'IMPLEMENTED',
    domain: 'EXCHANGE',
  },
  {
    control_id: 'CTL-EXCHANGE-RESERVE',
    description: 'Reservations must exist before settlement. No silent inventory.',
    kind: 'preventive',
    implementationPath: 'packages/sunrey-exchange/src',
    testReferences: ['packages/sunrey-exchange/src'],
    formalPropertyReferences: [],
    runbook: 'docs/architecture/chunk-49-universal-economic-exchange.md',
    knownLimitations: [],
    reviewStatus: 'IMPLEMENTED',
    domain: 'EXCHANGE',
  },
  {
    control_id: 'CTL-SURVEILLANCE',
    description: 'Deterministic alerts and case proposals. Detector output is not legal guilt.',
    kind: 'detective',
    implementationPath: 'packages/market-surveillance',
    testReferences: ['packages/market-surveillance/src'],
    formalPropertyReferences: [],
    runbook: null,
    knownLimitations: [],
    reviewStatus: 'IMPLEMENTED',
    domain: 'EXCHANGE',
  },
  {
    control_id: 'CTL-CUSTODY-POLICY',
    description: 'Institutional policy, dual control, and cold-signing paths.',
    kind: 'preventive',
    implementationPath: 'packages/custody/src/institutional',
    testReferences: ['packages/custody/src/institutional'],
    formalPropertyReferences: [],
    runbook: 'docs/architecture/native-custody-signing.md',
    knownLimitations: ['LIM-NO-PRODUCTION-HSM'],
    reviewStatus: 'IMPLEMENTED',
    domain: 'CUSTODY',
  },
  {
    control_id: 'CTL-CUSTODY-RECONCILE',
    description: 'Custody positions reconcile to finalized chain state.',
    kind: 'detective',
    implementationPath: 'packages/sunrey-chain/src/native-custody',
    testReferences: ['packages/custody/src'],
    formalPropertyReferences: [],
    runbook: 'docs/architecture/chunk-47-institutional-custody.md',
    knownLimitations: [],
    reviewStatus: 'IMPLEMENTED',
    domain: 'CUSTODY',
  },
  {
    control_id: 'CTL-HSM-SIMULATOR-BOUNDARY',
    description: 'Development HSM simulator is explicitly not a certified HSM.',
    kind: 'preventive',
    implementationPath: 'packages/security/src/hsm-simulator.ts',
    testReferences: ['packages/security/src'],
    formalPropertyReferences: [],
    runbook: 'docs/architecture/native-custody-signing.md',
    knownLimitations: ['LIM-NO-PRODUCTION-HSM'],
    reviewStatus: 'PARTIAL',
    domain: 'CUSTODY',
  },
  {
    control_id: 'CTL-ORACLE-QUORUM',
    description: 'Integer median aggregation with quorum and stale rejection.',
    kind: 'preventive',
    implementationPath: 'packages/sunrey-chain/src/oracle/aggregation.ts',
    testReferences: ['packages/sunrey-chain/src/oracle.test.ts'],
    formalPropertyReferences: ['packages/sunrey-chain/src/assurance/properties.ts'],
    runbook: 'docs/architecture/oracle-economic-fact-spec.md',
    knownLimitations: [],
    reviewStatus: 'IMPLEMENTED',
    domain: 'ORACLES',
  },
  {
    control_id: 'CTL-ORACLE-UNITS',
    description: 'Integer minor units. No floating-point economic facts.',
    kind: 'preventive',
    implementationPath: 'packages/sunrey-chain/src/oracle/units.ts',
    testReferences: ['packages/sunrey-chain/src/oracle.test.ts'],
    formalPropertyReferences: [],
    runbook: null,
    knownLimitations: [],
    reviewStatus: 'IMPLEMENTED',
    domain: 'ORACLES',
  },
  {
    control_id: 'CTL-ORACLE-BINDING',
    description: 'Oracle signatures bind network, domain, and suite.',
    kind: 'preventive',
    implementationPath: 'packages/sunrey-chain/src/oracle/crypto.ts',
    testReferences: ['packages/sunrey-chain/src/oracle.test.ts'],
    formalPropertyReferences: [],
    runbook: null,
    knownLimitations: [],
    reviewStatus: 'IMPLEMENTED',
    domain: 'ORACLES',
  },
  {
    control_id: 'CTL-INTEROP-ONCE',
    description: 'Packets are at-most-once.',
    kind: 'preventive',
    implementationPath: 'packages/sunrey-chain/src/interop/engine.ts',
    testReferences: ['packages/sunrey-chain/src/interop'],
    formalPropertyReferences: ['packages/sunrey-chain/src/assurance/coverage.ts'],
    runbook: 'docs/architecture/interchain-packet-protocol.md',
    knownLimitations: ['LIM-DEV-INTEROP'],
    reviewStatus: 'IMPLEMENTED',
    domain: 'INTEROPERABILITY',
  },
  {
    control_id: 'CTL-INTEROP-FREEZE',
    description: 'Frozen channels reject new packets.',
    kind: 'preventive',
    implementationPath: 'packages/sunrey-chain/src/interop/engine.ts',
    testReferences: ['packages/sunrey-chain/src/interop'],
    formalPropertyReferences: [],
    runbook: 'docs/architecture/interoperability-security-model.md',
    knownLimitations: ['LIM-DEV-INTEROP'],
    reviewStatus: 'IMPLEMENTED',
    domain: 'INTEROPERABILITY',
  },
  {
    control_id: 'CTL-LIGHT-CLIENT',
    description: 'Development light-client proof checks.',
    kind: 'preventive',
    implementationPath: 'packages/sunrey-chain/src/interop',
    testReferences: ['packages/sunrey-chain/src/interop'],
    formalPropertyReferences: [],
    runbook: 'docs/architecture/sunrey-light-client-protocol.md',
    knownLimitations: ['LIM-DEV-INTEROP'],
    reviewStatus: 'PARTIAL',
    domain: 'INTEROPERABILITY',
  },
  {
    control_id: 'CTL-PDV-ENCRYPT',
    description: 'Subject-bound envelope encryption. Plaintext hidden from metadata.',
    kind: 'preventive',
    implementationPath: 'packages/personal-data-vault',
    testReferences: ['packages/personal-data-vault/src/personal-data-vault.test.ts'],
    formalPropertyReferences: [],
    runbook: 'docs/architecture/personal-data-vault.md',
    knownLimitations: [],
    reviewStatus: 'IMPLEMENTED',
    domain: 'PRIVACY',
  },
  {
    control_id: 'CTL-PURPOSE-FIREWALL',
    description: 'Consent Ledger and Purpose Firewall gate use.',
    kind: 'preventive',
    implementationPath: 'packages/consent',
    testReferences: ['packages/consent/src'],
    formalPropertyReferences: [],
    runbook: 'docs/architecture/consent.md',
    knownLimitations: [],
    reviewStatus: 'IMPLEMENTED',
    domain: 'PRIVACY',
  },
  {
    control_id: 'CTL-EXPLORER-EXPOSURE',
    description: 'ExplorerExposurePolicy default FORBIDDEN. Raw PDV and KYC never served.',
    kind: 'preventive',
    implementationPath: 'packages/sunrey-explorer',
    testReferences: ['packages/sunrey-explorer/src', 'packages/personal-data-vault/src/architecture-guards.test.ts'],
    formalPropertyReferences: [],
    runbook: 'docs/architecture/explorer-privacy-policy.md',
    knownLimitations: [],
    reviewStatus: 'IMPLEMENTED',
    domain: 'PRIVACY',
  },
  {
    control_id: 'CTL-DEPENDENCY-POLICY',
    description: 'Blocked, unlocked, and unregistered-crypto dependencies fail closed.',
    kind: 'preventive',
    implementationPath: 'packages/sunrey-chain/src/supply-chain/policy.ts',
    testReferences: ['packages/sunrey-chain/src/supply-chain.test.ts'],
    formalPropertyReferences: [],
    runbook: 'docs/runbooks/software-supply-chain-incident.md',
    knownLimitations: [],
    reviewStatus: 'IMPLEMENTED',
    domain: 'SUPPLY_CHAIN',
  },
  {
    control_id: 'CTL-SBOM',
    description: 'CycloneDX SBOM and SLSA-style provenance for release targets.',
    kind: 'detective',
    implementationPath: 'packages/sunrey-chain/src/supply-chain/release.ts',
    testReferences: ['tests/chunk-59-supply-chain.test.ts'],
    formalPropertyReferences: [],
    runbook: 'docs/security/software-bill-of-materials.md',
    knownLimitations: [],
    reviewStatus: 'IMPLEMENTED',
    domain: 'SUPPLY_CHAIN',
  },
  {
    control_id: 'CTL-RELEASE-SIGN',
    description: 'ReleaseAuthority signs artifact digests. Tamper invalidates verify.',
    kind: 'preventive',
    implementationPath: 'packages/sunrey-chain/src/supply-chain/release.ts',
    testReferences: ['packages/sunrey-chain/src/supply-chain.test.ts'],
    formalPropertyReferences: [],
    runbook: 'docs/security/release-verification.md',
    knownLimitations: [],
    reviewStatus: 'IMPLEMENTED',
    domain: 'SUPPLY_CHAIN',
  },
  {
    control_id: 'CTL-RELEASE-NOT-PROTOCOL',
    description: 'Software release approval does not activate protocol change.',
    kind: 'preventive',
    implementationPath: 'packages/sunrey-chain/src/supply-chain/upgrade-bridge.ts',
    testReferences: ['packages/sunrey-chain/src/supply-chain.test.ts'],
    formalPropertyReferences: [],
    runbook: 'docs/runbooks/protocol-upgrade.md',
    knownLimitations: [],
    reviewStatus: 'IMPLEMENTED',
    domain: 'SUPPLY_CHAIN',
  },
  {
    control_id: 'CTL-GOVERNANCE-HEIGHT',
    description: 'UpgradePlan is height-activated. No governance token.',
    kind: 'preventive',
    implementationPath: 'packages/sunrey-chain/src/governance/engine.ts',
    testReferences: ['packages/sunrey-chain/src/governance.test.ts'],
    formalPropertyReferences: [],
    runbook: 'docs/architecture/chunk-40-protocol-governance.md',
    knownLimitations: [],
    reviewStatus: 'IMPLEMENTED',
    domain: 'OPERATIONS',
  },
  {
    control_id: 'CTL-UPGRADE-PRECHECK',
    description: 'Operator upgrade precheck requires an approved release record.',
    kind: 'preventive',
    implementationPath: 'packages/sunrey-chain/src/supply-chain/upgrade-bridge.ts',
    testReferences: ['packages/sunrey-chain/src/supply-chain.test.ts'],
    formalPropertyReferences: [],
    runbook: 'docs/runbooks/protocol-upgrade.md',
    knownLimitations: [],
    reviewStatus: 'IMPLEMENTED',
    domain: 'OPERATIONS',
  },
  {
    control_id: 'CTL-MULTI-DOMAIN',
    description: 'Multi-failure-domain topology and fencing.',
    kind: 'recovery',
    implementationPath: 'packages/sunrey-chain/src/ops/topology.ts',
    testReferences: ['packages/sunrey-chain/src/ops.test.ts'],
    formalPropertyReferences: [],
    runbook: 'docs/architecture/chunk-55-resilience-observability.md',
    knownLimitations: ['LIM-ENGINEERING-SLO'],
    reviewStatus: 'IMPLEMENTED',
    domain: 'OPERATIONS',
  },
  {
    control_id: 'CTL-DR-DRILLS',
    description: 'Disaster-recovery drills for signer, region, and backup restore.',
    kind: 'recovery',
    implementationPath: 'packages/sunrey-chain/src/ops/drills.ts',
    testReferences: ['packages/sunrey-chain/src/ops.test.ts'],
    formalPropertyReferences: [],
    runbook: 'docs/architecture/chunk-55-resilience-observability.md',
    knownLimitations: ['LIM-ENGINEERING-SLO'],
    reviewStatus: 'IMPLEMENTED',
    domain: 'OPERATIONS',
  },
  {
    control_id: 'CTL-BACKUP',
    description: 'Snapshot and backup restore paths for development/testnet nodes.',
    kind: 'recovery',
    implementationPath: 'packages/sunrey-chain/src/ops/backup.ts',
    testReferences: ['packages/sunrey-chain/src/ops.test.ts'],
    formalPropertyReferences: [],
    runbook: 'docs/architecture/chunk-55-resilience-observability.md',
    knownLimitations: ['LIM-ENGINEERING-SLO'],
    reviewStatus: 'IMPLEMENTED',
    domain: 'OPERATIONS',
  },
  {
    control_id: 'CTL-REPLAY-BINDING',
    description: 'Signature bindings include network, chain, protocol, schema, domain, and payload hash.',
    kind: 'preventive',
    implementationPath: 'packages/sunrey-chain/src/protocol',
    testReferences: ['packages/sunrey-chain/src/local-node/codec.test.ts', 'packages/sunrey-chain/src/assurance/protocol.ts'],
    formalPropertyReferences: [],
    runbook: 'docs/architecture/chunk-32-resume.md',
    knownLimitations: [],
    reviewStatus: 'IMPLEMENTED',
    domain: 'PROTOCOL_ENCODING',
  },
  {
    control_id: 'CTL-MACHINE-MANDATE',
    description: 'Machine commerce requires a controller-bound mandate. Agents cannot execute.',
    kind: 'preventive',
    implementationPath: 'packages/sunrey-chain/src/machine-economy/engine.ts',
    testReferences: ['packages/sunrey-chain/src/machine-economy.test.ts'],
    formalPropertyReferences: [],
    runbook: 'docs/architecture/machine-commerce-protocol.md',
    knownLimitations: [],
    reviewStatus: 'IMPLEMENTED',
    domain: 'MACHINE_ECONOMY',
  },
  {
    control_id: 'CTL-FEE-RESERVE',
    description: 'Integer fee schedule with reserve, charge, and release. No floating-point.',
    kind: 'preventive',
    implementationPath: 'packages/sunrey-chain/src/fees',
    testReferences: ['packages/sunrey-chain/src/fees.test.ts'],
    formalPropertyReferences: ['packages/sunrey-chain/src/assurance/properties.ts'],
    runbook: 'docs/architecture/sunrey-resource-metering.md',
    knownLimitations: [],
    reviewStatus: 'IMPLEMENTED',
    domain: 'NATIVE_ASSETS',
  },
]);

export function controlCount(rows: readonly SecurityControl[] = SECURITY_CONTROLS): number {
  return rows.length;
}

export function controlsLinkedToTests(rows: readonly SecurityControl[] = SECURITY_CONTROLS): boolean {
  return rows.every((row) => row.testReferences.length > 0);
}
