export const CRYPTO_REVIEW_PACKAGE = Object.freeze({
  title: 'Cryptographic review package',
  claims_production_approval: false,
  claims_quantum_proof: false,
  registry: {
    owner: 'packages/security',
    suiteIds: [
      'sunrey-app-hmac-v1',
      'sunrey-ed25519-v1',
      'sunrey-hybrid-ed25519-mldsa-sim-v1',
      'sunrey-hybrid-ed25519-mldsa-v1',
      'sunrey-mldsa-65-v1',
      'sunrey-mlkem-768-v1',
      'sunrey-slhdsa-sha2-128s-v1',
    ],
    algorithmIds: [
      'HMAC-SHA256',
      'SHA-256',
      'AES-256-GCM',
      'HKDF-SHA-256',
      'Ed25519',
      'ML-DSA-65',
      'ML_DSA_65_V1',
      'ML-KEM-768',
      'ML_KEM_768_V1',
      'SLH-DSA-SHA2-128S',
      'SLH_DSA_SHA2_128S_V1',
      'SIMULATION-ML-DSA-65',
      'SIMULATION-ML-KEM-768',
      'SIMULATION-SLH-DSA-SHA2-128S',
    ],
    inventory: 'docs/security/cryptographic-inventory.json',
  },
  keyPurposeMatrix: {
    application: [
      'EXECUTION_AUTHORITY_SIGNING',
      'EVIDENCE_INTEGRITY',
      'SESSION_SIGNING',
      'DATA_ENCRYPTION',
      'BACKUP_ENCRYPTION',
      'SERVICE_AUTHENTICATION',
      'WEBHOOK_SIGNING',
      'DATA_USE_PERMIT_SIGNING',
      'CLEAN_ROOM_JOIN_TOKEN',
      'CHAIN_OPERATION_SIGNING',
    ],
    chain: [
      'TRANSACTION_SIGNING',
      'VALIDATOR_CONSENSUS_SIGNING',
      'BLOCK_PROPOSAL_SIGNING',
      'P2P_IDENTITY',
      'ORACLE_SIGNING',
      'GOVERNANCE_SIGNING',
      'WALLET_SIGNING',
      'INTEROPERABILITY_SIGNING',
      'MACHINE_SIGNING',
    ],
    hmacForbiddenFor: ['VALIDATOR_CONSENSUS_SIGNING', 'BLOCK_PROPOSAL_SIGNING'],
  },
  providerSelection: {
    classical: 'node:crypto Ed25519 (RFC 8032)',
    pqc: '@noble/post-quantum@0.5.4',
    pqcProviderId: 'noble-post-quantum-0.5.4',
    hsm: 'sunrey-development-hsm-simulator / hsm-sim-v1',
    hsmCertified: false,
  },
  pqcIntegrationNotes: {
    mldsa: 'ML-DSA-65 via noble-post-quantum for development/testnet hybrid signatures.',
    mlkem: 'ML-KEM-768 reserved for hybrid envelopes. Stored AES envelopes remain classically confidential.',
    slhdsa: 'SLH-DSA-SHA2-128S available as a suite. Not the default testnet policy.',
    environment: 'TESTNET_APPROVED or TEST_ONLY. Not main-network. Not quantum-proof.',
  },
  hybridSemantics: {
    policy: 'CLASSICAL_AND_PQ',
    bothMustVerify: true,
    orVerificationForbidden: true,
    verifyLegacyOnlyCannotOriginateHybrid: true,
  },
  downgradeControls: [
    'Unknown algorithm IDs fail closed',
    'Bindings include suite and algorithm IDs',
    'DOWNGRADE_REJECTED policy',
    'AI cannot flip CryptoPolicy',
  ],
  knownAnswerTests: [
    'packages/security/src/ed25519-vectors.ts',
    'packages/security/src/pq-official-vectors.json',
    'packages/security/src/pq-integration.test.ts',
  ],
  cryptoDependencyInventory: 'docs/security/cryptographic-inventory.md',
  performanceImpact: {
    source: 'docs/security/pqc-performance.md',
    resultClass: 'ENGINEERING_MEASUREMENT',
    note: 'Chunk 60 real PQC is recorded separately from classical protocol measurements.',
  },
  currentLimitations: [
    'external production HSM integration not yet completed',
    'production cryptographic approval not automatically granted',
    'system is not claimed quantum-proof',
  ],
});
