import type { KnownSecurityLimitation } from './types.ts';

export const KNOWN_SECURITY_LIMITATIONS: readonly KnownSecurityLimitation[] = Object.freeze([
  {
    limitation_id: 'LIM-NO-EXTERNAL-AUDIT',
    subsystem: 'audit-readiness',
    description: 'No independent external audit has been completed or claimed.',
    riskClassification: 'MEDIUM',
    temporaryMitigation: 'This bundle prepares reviewers. It is an engineering package, not an audit result.',
    plannedRemediation: 'Commission an independent review after this package is accepted.',
    externalDependency: 'external reviewer engagement',
    status: 'OPEN',
  },
  {
    limitation_id: 'LIM-NO-FORMAL-VERIFICATION',
    subsystem: 'assurance',
    description: 'Machine-checked proofs / TLA+ models are not present. Chunk 56 is fuzz and property assurance.',
    riskClassification: 'MEDIUM',
    temporaryMitigation: 'Property tests, consensus safety tests, and fuzz smoke are the current formal-adjacent evidence.',
    plannedRemediation: 'Add a dedicated formal-methods chunk if counsel and engineering commission one.',
    externalDependency: 'formal tool selection',
    status: 'OPEN',
  },
  {
    limitation_id: 'LIM-NO-PRODUCTION-HSM',
    subsystem: 'custody',
    description: 'External production HSM integration is not completed. Development simulator only.',
    riskClassification: 'HIGH',
    temporaryMitigation: 'HSM simulator is labeled not-certified. Production credentials stay provider-controlled and absent from git.',
    plannedRemediation: 'Integrate a production HSM/KMS behind existing packages/security ports.',
    externalDependency: 'HSM vendor and certification',
    status: 'OPEN',
  },
  {
    limitation_id: 'LIM-NO-PRODUCTION-CRYPTO-APPROVAL',
    subsystem: 'cryptography',
    description: 'Production cryptographic approval is not automatically granted. Suites are TESTNET_APPROVED or earlier.',
    riskClassification: 'HIGH',
    temporaryMitigation: 'CryptoPolicy refuses production activation. ENVIRONMENT remains simulation.',
    plannedRemediation: 'Human cryptographic approval after independent review.',
    externalDependency: 'cryptographic review and counsel',
    status: 'OPEN',
  },
  {
    limitation_id: 'LIM-NOT-QUANTUM-PROOF',
    subsystem: 'pqc',
    description: 'Hybrid PQC is development/testnet only. The system is not claimed quantum-proof.',
    riskClassification: 'HIGH',
    temporaryMitigation: 'CLASSICAL_AND_PQ AND-verification. Production PQ / HSM / counsel approval pending.',
    plannedRemediation: 'Production PQ provider, HSM, and counsel review.',
    externalDependency: '@noble/post-quantum and future certified modules',
    status: 'OPEN',
  },
  {
    limitation_id: 'LIM-DEV-CONSENSUS',
    subsystem: 'consensus',
    description: 'Consensus is a development Tendermint-class engine, not a production deployment.',
    riskClassification: 'MEDIUM',
    temporaryMitigation: 'Seven-validator development/testnet only. productionNetworkEnabled remains false.',
    plannedRemediation: 'Production consensus is a later, separately authorized chunk.',
    externalDependency: null,
    status: 'OPEN',
  },
  {
    limitation_id: 'LIM-DEV-INTEROP',
    subsystem: 'interoperability',
    description: 'Production interoperability remains unimplemented.',
    riskClassification: 'MEDIUM',
    temporaryMitigation: 'Development gateway, freeze, and at-most-once packet rules only.',
    plannedRemediation: 'Production interop after independent review of the development gateway.',
    externalDependency: null,
    status: 'OPEN',
  },
  {
    limitation_id: 'LIM-DEV-ECONOMIC-PARAMS',
    subsystem: 'moonrey-issuance',
    description: 'MoonRey issuance uses development/testnet economic parameters. Public moonrey-coin remains PLANNED.',
    riskClassification: 'MEDIUM',
    temporaryMitigation: 'Parameters are labeled development/testnet. Tickers remain NOT_ASSIGNED.',
    plannedRemediation: 'Human-set main-network parameters after review. Not inferred by agents.',
    externalDependency: null,
    status: 'OPEN',
  },
  {
    limitation_id: 'LIM-TICKERS-UNASSIGNED',
    subsystem: 'native-assets',
    description: 'Public tickers remain NOT_ASSIGNED.',
    riskClassification: 'LOW',
    temporaryMitigation: 'Protocol and tests refuse invented ticker symbols.',
    plannedRemediation: 'Assign tickers only after a dedicated product decision.',
    externalDependency: null,
    status: 'OPEN',
  },
  {
    limitation_id: 'LIM-ENGINEERING-SLO',
    subsystem: 'operations',
    description: 'Observability SLOs remain ENGINEERING_TEST_TARGETS, not production guarantees.',
    riskClassification: 'LOW',
    temporaryMitigation: 'Reports label measurements as engineering results.',
    plannedRemediation: 'Production SLO ownership after operational review.',
    externalDependency: null,
    status: 'OPEN',
  },
  {
    limitation_id: 'LIM-NO-LIVE-RAILS',
    subsystem: 'operations',
    description: 'ENVIRONMENT is simulation. LIVE_* flags stay false. No external bank or payment provider.',
    riskClassification: 'LOW',
    temporaryMitigation: 'Deployment-posture CI fails if flags change.',
    plannedRemediation: 'Live rails require a later authorized chunk and human approval.',
    externalDependency: null,
    status: 'MITIGATED',
  },
]);

export function limitationCount(
  rows: readonly KnownSecurityLimitation[] = KNOWN_SECURITY_LIMITATIONS,
): number {
  return rows.length;
}
