import type { ThreatModel } from './types.ts';

export const THREAT_MODELS: readonly ThreatModel[] = Object.freeze([
  {
    threat_id: 'THR-CONSENSUS-BYZANTINE',
    title: 'consensus Byzantine behavior',
    domain: 'CONSENSUS',
    description: 'Equivocation, double proposal, lock-rule violation, or cartel below or at f < 1/3.',
    controls: ['CTL-CONSENSUS-QUORUM', 'CTL-CONSENSUS-LOCK', 'CTL-VALIDATOR-ACCOUNTABILITY'],
    tests: [
      'packages/sunrey-chain/rust/crates/consensus/tests/safety.rs',
      'packages/sunrey-chain/src/assurance/consensus.ts',
      'packages/sunrey-range BFT-DOUBLE-PROPOSAL',
    ],
    residualRisk: 'Byzantine power at or above one-third is unmitigated by BFT assumptions.',
  },
  {
    threat_id: 'THR-SIGNER-COMPROMISE',
    title: 'signer compromise',
    domain: 'VALIDATORS',
    description: 'Remote or local signer private key theft or WAL rollback.',
    controls: ['CTL-SIGNER-SEPARATION', 'CTL-SIGNER-WAL', 'CTL-KEY-PURPOSE-SEPARATION'],
    tests: [
      'packages/sunrey-chain/src/ops/signer-safety.ts',
      'packages/sunrey-chain/rust/crates/consensus fuzz signer_safety_decoder',
    ],
    residualRisk: 'A compromised signer still forges that validator identity until rotation.',
  },
  {
    threat_id: 'THR-WALLET-COMPROMISE',
    title: 'wallet compromise',
    domain: 'WALLETS',
    description: 'Endpoint theft of wallet or recovery material.',
    controls: ['CTL-WALLET-KEYSTORE', 'CTL-KEY-PURPOSE-SEPARATION', 'CTL-MULTI-AUTH'],
    tests: ['packages/sunrey-chain/src/wallet', 'packages/sunrey-chain/rust/crates/wallet'],
    residualRisk: 'Compromise of an endpoint still forges that user signatures.',
  },
  {
    threat_id: 'THR-CUSTODY-COMPROMISE',
    title: 'custody compromise',
    domain: 'CUSTODY',
    description: 'Single-approver or policy bypass of institutional vaults.',
    controls: ['CTL-CUSTODY-POLICY', 'CTL-CUSTODY-RECONCILE', 'CTL-HSM-SIMULATOR-BOUNDARY'],
    tests: [
      'packages/custody/src/institutional',
      'packages/sunrey-range CUSTODY-SINGLE-APPROVER',
    ],
    residualRisk: 'Development HSM simulator is not a certified vault. Production HSM is not completed.',
  },
  {
    threat_id: 'THR-ORACLE-MANIPULATION',
    title: 'oracle manipulation',
    domain: 'ORACLES',
    description: 'Stale, ordered, or minority observations accepted as VerifiedEconomicFacts.',
    controls: ['CTL-ORACLE-QUORUM', 'CTL-ORACLE-UNITS', 'CTL-ORACLE-BINDING'],
    tests: ['packages/sunrey-chain/src/oracle.test.ts', 'packages/sunrey-chain/src/assurance/properties.ts'],
    residualRisk: 'A colluding oracle majority can still publish a false fact within policy.',
  },
  {
    threat_id: 'THR-ECONOMIC-DOUBLE-COUNT',
    title: 'economic double counting',
    domain: 'MOONREY_ISSUANCE',
    description: 'Reuse of a productive contribution fingerprint or epoch overflow.',
    controls: ['CTL-MOONREY-FINGERPRINT', 'CTL-MOONREY-EPOCH-CAPS', 'CTL-NATIVE-SUPPLY'],
    tests: ['packages/sunrey-chain/src/productive', 'packages/sunrey-chain/src/assurance/properties.ts'],
    residualRisk: 'Oracle-quality inputs remain a dependency of productive claims.',
  },
  {
    threat_id: 'THR-EXCHANGE-MANIPULATION',
    title: 'Exchange manipulation',
    domain: 'EXCHANGE',
    description: 'Reservation bypass, DVP mismatch, or self-trade abuse.',
    controls: ['CTL-EXCHANGE-DVP', 'CTL-EXCHANGE-RESERVE', 'CTL-SURVEILLANCE'],
    tests: ['tests/assurance/exchange.test.ts', 'packages/sunrey-exchange/src'],
    residualRisk: 'Simulation matching is not a live market. Surveillance proposes cases only.',
  },
  {
    threat_id: 'THR-GOVERNANCE-COMPROMISE',
    title: 'governance compromise',
    domain: 'OPERATIONS',
    description: 'Unauthorized UpgradePlan or software release treated as protocol activation.',
    controls: ['CTL-GOVERNANCE-HEIGHT', 'CTL-RELEASE-NOT-PROTOCOL', 'CTL-UPGRADE-PRECHECK'],
    tests: [
      'packages/sunrey-chain/src/governance.test.ts',
      'packages/sunrey-chain/src/supply-chain/upgrade-bridge.ts',
    ],
    residualRisk: 'Compromised governance keys can still schedule a height-activated plan.',
  },
  {
    threat_id: 'THR-SUPPLY-CHAIN-COMPROMISE',
    title: 'supply-chain compromise',
    domain: 'SUPPLY_CHAIN',
    description: 'Blocked, unlocked, unregistered-crypto, or tampered release artifacts.',
    controls: ['CTL-DEPENDENCY-POLICY', 'CTL-SBOM', 'CTL-RELEASE-SIGN'],
    tests: ['packages/sunrey-chain/src/supply-chain.test.ts', 'tests/chunk-59-supply-chain.test.ts'],
    residualRisk: 'A compromised CI runner can still alter this tree before signing.',
  },
  {
    threat_id: 'THR-INTEROP-PROOF-FAILURE',
    title: 'interop proof failure',
    domain: 'INTEROPERABILITY',
    description: 'Replay, freeze-bypass, or forged light-client packet.',
    controls: ['CTL-INTEROP-ONCE', 'CTL-INTEROP-FREEZE', 'CTL-LIGHT-CLIENT'],
    tests: ['packages/sunrey-chain/src/interop', 'packages/sunrey-range interop scenarios'],
    residualRisk: 'Production interoperability remains unimplemented.',
  },
  {
    threat_id: 'THR-PRIVACY-LEAKAGE',
    title: 'privacy leakage',
    domain: 'PRIVACY',
    description: 'Raw subject-level data leaving PDV, Clean Room, or Explorer.',
    controls: ['CTL-PDV-ENCRYPT', 'CTL-PURPOSE-FIREWALL', 'CTL-EXPLORER-EXPOSURE'],
    tests: [
      'packages/personal-data-vault/src/personal-data-vault.test.ts',
      'packages/personal-data-vault/src/architecture-guards.test.ts',
      'packages/clean-room/src',
      'packages/sunrey-explorer/src',
    ],
    residualRisk: 'Operator logs outside these packages can still leak if misconfigured.',
  },
  {
    threat_id: 'THR-PQC-DOWNGRADE',
    title: 'PQC downgrade',
    domain: 'PQC',
    description: 'Hybrid CLASSICAL_AND_PQ reduced to classical-only verification.',
    controls: ['CTL-HYBRID-AND', 'CTL-DOWNGRADE-REJECT', 'CTL-SUITE-LIFECYCLE'],
    tests: [
      'packages/security/src/pq-integration.test.ts',
      'packages/sunrey-chain/src/pqc/hybrid-rehearsal.test.ts',
    ],
    residualRisk: 'Misconfigured migration state could still allow classical-only. Not quantum-proof.',
  },
  {
    threat_id: 'THR-REGIONAL-INFRA-FAILURE',
    title: 'regional infrastructure failure',
    domain: 'OPERATIONS',
    description: 'Validator, signer, or region loss without quorum or recovery.',
    controls: ['CTL-MULTI-DOMAIN', 'CTL-DR-DRILLS', 'CTL-BACKUP'],
    tests: ['packages/sunrey-chain/src/ops.test.ts', 'packages/sunrey-chain/src/ops/drills.ts'],
    residualRisk: 'Engineering SLOs are ENGINEERING_TEST_TARGETS, not production guarantees.',
  },
]);
