/**
 * Canonical family records for the unified economic data fabric.
 *
 * This is an operational routing index. Chunk 116 SourceProductiveMapping
 * remains the semantic authority for DataSourceCategory, FactType,
 * ProductiveCategory, and ClaimType.
 */

import type { FactType, UnitCode } from '../../types.ts';
import type { ProductiveCategory } from '../../../productive/types.ts';
import type { DataSourceCategory } from '../../../productive/source-taxonomy/types.ts';
import {
  FABRIC_NORMALIZATION_VERSION,
  FABRIC_SOURCE_TAXONOMY_VERSION,
  type ConnectorProfileType,
  type EconomicDataProviderFamilyRecord,
  type PrivacyClass,
  type ProviderFamilyId,
  type StorageClass,
} from './types.ts';

const CONNECTOR_PROFILES: readonly ConnectorProfileType[] = Object.freeze([
  'FILE_FIXTURE',
  'HTTPS_API_KEY',
  'HTTPS_MTLS',
  'HTTPS_OAUTH',
  'SIGNED_REQUEST',
  'PRIVATE_NETWORK',
]);

function family(input: {
  readonly familyId: ProviderFamilyId;
  readonly implementationState: EconomicDataProviderFamilyRecord['implementationState'];
  readonly adapterOwnerPath: string | null;
  readonly supportedSourceCategories: readonly DataSourceCategory[];
  readonly supportedFactTypes: readonly FactType[];
  readonly supportedProductiveCategories: readonly ProductiveCategory[];
  readonly supportedUnits: readonly UnitCode[];
  readonly supportedSchemaIds: readonly string[];
  readonly certificationProfileIds: readonly string[];
  readonly privacyClass: PrivacyClass;
  readonly defaultStorageClass: StorageClass;
}): EconomicDataProviderFamilyRecord {
  return Object.freeze({
    familyId: input.familyId,
    version: 1,
    implementationState: input.implementationState,
    adapterOwnerPath: input.adapterOwnerPath,
    supportedSourceCategories: Object.freeze([...input.supportedSourceCategories]),
    supportedFactTypes: Object.freeze([...input.supportedFactTypes]),
    supportedProductiveCategories: Object.freeze([...input.supportedProductiveCategories]),
    supportedUnits: Object.freeze([...input.supportedUnits]),
    supportedSchemaIds: Object.freeze([...input.supportedSchemaIds]),
    connectorProfileTypes: CONNECTOR_PROFILES,
    certificationProfileIds: Object.freeze([...input.certificationProfileIds]),
    privacyClass: input.privacyClass,
    defaultStorageClass: input.defaultStorageClass,
    sourceTaxonomyVersion: FABRIC_SOURCE_TAXONOMY_VERSION,
    normalizationVersion: FABRIC_NORMALIZATION_VERSION,
    productionActivated: false,
    liveProviderConnected: false,
  });
}

export const CANONICAL_PROVIDER_FAMILIES: readonly EconomicDataProviderFamilyRecord[] = Object.freeze([
  family({
    familyId: 'ENERGY',
    implementationState: 'ADAPTER_IMPLEMENTED',
    adapterOwnerPath: 'packages/sunrey-chain/src/oracle/production/provider-families/energy',
    supportedSourceCategories: ['energy'],
    supportedFactTypes: ['ENERGY_PRODUCTION', 'ENERGY_CAPACITY', 'ENERGY_CONSUMPTION'],
    supportedProductiveCategories: ['ENERGY'],
    supportedUnits: ['Wh', 'kWh', 'MWh'],
    supportedSchemaIds: [
      'ENERGY_INTERVAL_V1',
      'ENERGY_CUMULATIVE_REGISTER_V1',
      'ENERGY_CONSUMPTION_INTERVAL_V1',
      'ENERGY_EXPORT_INTERVAL_V1',
      'ENERGY_CAPACITY_REFERENCE_V1',
    ],
    certificationProfileIds: ['energy.certification.v1'],
    privacyClass: 'FACILITY_AGGREGATE',
    defaultStorageClass: 'MEASUREMENT_AND_PROVENANCE',
  }),
  family({
    familyId: 'COMPUTE',
    implementationState: 'ADAPTER_IMPLEMENTED',
    adapterOwnerPath: 'packages/sunrey-chain/src/oracle/production/provider-families/compute',
    supportedSourceCategories: ['compute'],
    supportedFactTypes: ['COMPUTE_CAPACITY', 'COMPUTE_USAGE'],
    supportedProductiveCategories: ['COMPUTE'],
    supportedUnits: ['compute_s', 'gpu_s', 'machine_h'],
    supportedSchemaIds: ['COMPUTE_USAGE_V1', 'GPU_USAGE_V1', 'CPU_USAGE_V1'],
    certificationProfileIds: ['compute.certification.v1'],
    privacyClass: 'OPERATOR_AGGREGATE',
    defaultStorageClass: 'MEASUREMENT_AND_PROVENANCE',
  }),
  family({
    familyId: 'AI_COMPUTE',
    implementationState: 'ADAPTER_IMPLEMENTED',
    adapterOwnerPath: 'packages/sunrey-chain/src/oracle/production/provider-families/compute',
    supportedSourceCategories: ['ai_usage', 'ai_compute'],
    supportedFactTypes: ['AI_INFERENCE_USAGE', 'AI_COMPUTE_CAPACITY', 'AI_TRAINING_USAGE'],
    supportedProductiveCategories: ['AI_COMPUTE'],
    supportedUnits: ['token_inference', 'gpu_s'],
    supportedSchemaIds: ['AI_INFERENCE_USAGE_V1', 'AI_TRAINING_USAGE_V1', 'AI_COMPUTE_CAPACITY_V1'],
    certificationProfileIds: ['compute.ai.certification.v1'],
    privacyClass: 'OPERATOR_AGGREGATE',
    defaultStorageClass: 'COMMITMENT_ONLY',
  }),
  family({
    familyId: 'MANUFACTURING',
    implementationState: 'ADAPTER_IMPLEMENTED',
    adapterOwnerPath: 'packages/sunrey-chain/src/oracle/production/provider-families/manufacturing',
    supportedSourceCategories: ['manufacturing'],
    supportedFactTypes: ['MANUFACTURING_CAPACITY', 'MANUFACTURING_OUTPUT'],
    supportedProductiveCategories: ['MANUFACTURING'],
    supportedUnits: ['units_produced', 'machine_h', 'kg', 'tonne'],
    supportedSchemaIds: [
      'manufacturing.mes.output.v1',
      'manufacturing.erp.output-batch.v1',
      'manufacturing.scada.read.v1',
      'manufacturing.plc.telemetry.v1',
      'manufacturing.robot.output.v1',
      'manufacturing.historian.counter.v1',
      'manufacturing.qms.attestation.v1',
      'manufacturing.weigh-scale.mass.v1',
    ],
    certificationProfileIds: ['manufacturing.certification.v1'],
    privacyClass: 'FACILITY_AGGREGATE',
    defaultStorageClass: 'MEASUREMENT_AND_PROVENANCE',
  }),
  family({
    familyId: 'AUTOMATED_MACHINE_OUTPUT',
    implementationState: 'ADAPTER_IMPLEMENTED',
    adapterOwnerPath: 'packages/sunrey-chain/src/oracle/production/provider-families/manufacturing',
    supportedSourceCategories: ['automated_machine_output'],
    supportedFactTypes: ['AUTOMATED_MACHINE_OUTPUT'],
    supportedProductiveCategories: ['AUTOMATED_MACHINE_OUTPUT'],
    supportedUnits: ['units_produced', 'kg', 'tonne'],
    supportedSchemaIds: ['manufacturing.robot.output.v1', 'manufacturing.historian.counter.v1'],
    certificationProfileIds: ['manufacturing.automated.certification.v1'],
    privacyClass: 'FACILITY_AGGREGATE',
    defaultStorageClass: 'MEASUREMENT_AND_PROVENANCE',
  }),
  family({
    familyId: 'LOGISTICS',
    implementationState: 'ADAPTER_IMPLEMENTED',
    adapterOwnerPath: 'packages/sunrey-chain/src/oracle/production/provider-families/logistics',
    supportedSourceCategories: ['logistics'],
    supportedFactTypes: ['LOGISTICS_CAPACITY', 'DELIVERY_COMPLETION'],
    supportedProductiveCategories: ['LOGISTICS_TRANSPORTATION'],
    supportedUnits: ['tonne_km', 'units_produced', 'kg', 'tonne'],
    supportedSchemaIds: ['logistics.resource.v1', 'delivery.completion.v1'],
    certificationProfileIds: ['logistics.certification.v1'],
    privacyClass: 'OPERATOR_AGGREGATE',
    defaultStorageClass: 'MEASUREMENT_AND_PROVENANCE',
  }),
  family({
    familyId: 'STORAGE',
    implementationState: 'ADAPTER_IMPLEMENTED',
    adapterOwnerPath: 'packages/sunrey-chain/src/oracle/production/provider-families/logistics',
    supportedSourceCategories: ['storage'],
    supportedFactTypes: ['STORAGE_CAPACITY'],
    supportedProductiveCategories: ['STORAGE'],
    supportedUnits: ['GB', 'TB', 'm3'],
    supportedSchemaIds: ['storage.warehouse.v1'],
    certificationProfileIds: ['storage.certification.v1'],
    privacyClass: 'FACILITY_AGGREGATE',
    defaultStorageClass: 'MEASUREMENT_AND_PROVENANCE',
  }),
  family({
    familyId: 'MINERALS_RESOURCES',
    implementationState: 'ADAPTER_IMPLEMENTED',
    adapterOwnerPath: 'packages/sunrey-chain/src/oracle/production/provider-families/resources',
    supportedSourceCategories: ['resources', 'minerals_resources'],
    supportedFactTypes: ['RESOURCE_RESERVE', 'RESOURCE_EXTRACTION'],
    supportedProductiveCategories: ['MINERALS_RAW_MATERIALS'],
    supportedUnits: ['kg', 'tonne'],
    supportedSchemaIds: [
      'minerals.mine-production.v1',
      'minerals.weighbridge.v1',
      'minerals.haulage.v1',
      'minerals.process-plant.v1',
      'minerals.stockpile.v1',
      'minerals.survey.v1',
      'minerals.reserve-report.v1',
    ],
    certificationProfileIds: ['resources.certification.v1'],
    privacyClass: 'FACILITY_AGGREGATE',
    defaultStorageClass: 'MEASUREMENT_AND_PROVENANCE',
  }),
  family({
    familyId: 'AGRICULTURE_FOOD',
    implementationState: 'ROUTING_INDEX_ONLY',
    adapterOwnerPath: null,
    supportedSourceCategories: ['food_agriculture'],
    supportedFactTypes: ['FOOD_PRODUCTION', 'AGRICULTURAL_OUTPUT'],
    supportedProductiveCategories: ['FOOD_AGRICULTURE'],
    supportedUnits: ['kg', 'tonne'],
    supportedSchemaIds: [],
    certificationProfileIds: [],
    privacyClass: 'AGGREGATE_ONLY',
    defaultStorageClass: 'COMMITMENT_ONLY',
  }),
  family({
    familyId: 'WATER',
    implementationState: 'ROUTING_INDEX_ONLY',
    adapterOwnerPath: null,
    supportedSourceCategories: ['water'],
    supportedFactTypes: ['WATER_PRODUCTION', 'WATER_AVAILABILITY'],
    supportedProductiveCategories: ['WATER'],
    supportedUnits: ['L', 'm3'],
    supportedSchemaIds: [],
    certificationProfileIds: [],
    privacyClass: 'AGGREGATE_ONLY',
    defaultStorageClass: 'COMMITMENT_ONLY',
  }),
  family({
    familyId: 'REAL_ESTATE',
    implementationState: 'ROUTING_INDEX_ONLY',
    adapterOwnerPath: null,
    supportedSourceCategories: ['real_estate_use'],
    supportedFactTypes: ['REAL_ESTATE_USE_CAPACITY'],
    supportedProductiveCategories: ['REAL_ESTATE_USE'],
    supportedUnits: ['m2'],
    supportedSchemaIds: [],
    certificationProfileIds: [],
    privacyClass: 'FACILITY_AGGREGATE',
    defaultStorageClass: 'COMMITMENT_ONLY',
  }),
  family({
    familyId: 'INFRASTRUCTURE',
    implementationState: 'ROUTING_INDEX_ONLY',
    adapterOwnerPath: null,
    supportedSourceCategories: ['infrastructure'],
    supportedFactTypes: ['INFRASTRUCTURE_CAPACITY', 'INFRASTRUCTURE_USAGE'],
    supportedProductiveCategories: ['INFRASTRUCTURE'],
    supportedUnits: ['m2', 'units_produced'],
    supportedSchemaIds: [],
    certificationProfileIds: [],
    privacyClass: 'FACILITY_AGGREGATE',
    defaultStorageClass: 'COMMITMENT_ONLY',
  }),
  family({
    familyId: 'BANDWIDTH',
    implementationState: 'ROUTING_INDEX_ONLY',
    adapterOwnerPath: null,
    supportedSourceCategories: ['bandwidth'],
    supportedFactTypes: ['BANDWIDTH_CAPACITY', 'BANDWIDTH_USAGE'],
    supportedProductiveCategories: ['BANDWIDTH_COMMUNICATIONS'],
    supportedUnits: ['GB_s'],
    supportedSchemaIds: [],
    certificationProfileIds: [],
    privacyClass: 'OPERATOR_AGGREGATE',
    defaultStorageClass: 'COMMITMENT_ONLY',
  }),
  family({
    familyId: 'GOODS',
    implementationState: 'ROUTING_INDEX_ONLY',
    adapterOwnerPath: null,
    supportedSourceCategories: ['goods'],
    supportedFactTypes: ['GOODS_OUTPUT', 'GOODS_DELIVERY'],
    supportedProductiveCategories: ['GOODS'],
    supportedUnits: ['units_produced', 'kg', 'tonne'],
    supportedSchemaIds: [],
    certificationProfileIds: [],
    privacyClass: 'OPERATOR_AGGREGATE',
    defaultStorageClass: 'COMMITMENT_ONLY',
  }),
  family({
    familyId: 'SERVICES',
    implementationState: 'ROUTING_INDEX_ONLY',
    adapterOwnerPath: null,
    supportedSourceCategories: ['services', 'service_delivery'],
    supportedFactTypes: ['SERVICE_DELIVERY'],
    supportedProductiveCategories: ['SERVICES'],
    supportedUnits: ['units_produced', 'machine_h'],
    supportedSchemaIds: [],
    certificationProfileIds: [],
    privacyClass: 'OPERATOR_AGGREGATE',
    defaultStorageClass: 'COMMITMENT_ONLY',
  }),
  family({
    familyId: 'REFERENCE_DATA',
    implementationState: 'ADAPTER_IMPLEMENTED',
    adapterOwnerPath: 'packages/sunrey-chain/src/oracle/production/provider-families/energy',
    supportedSourceCategories: ['reference_price', 'energy', 'resources', 'minerals_resources', 'food_agriculture', 'goods'],
    supportedFactTypes: ['REFERENCE_PRICE'],
    supportedProductiveCategories: [],
    supportedUnits: ['units_produced'],
    supportedSchemaIds: ['ENERGY_REFERENCE_PRICE_V1'],
    certificationProfileIds: ['reference-data.certification.v1'],
    privacyClass: 'REFERENCE_PUBLIC',
    defaultStorageClass: 'REFERENCE_METADATA',
  }),
]);
