/**
 * ACCESS Wave 2 — Canonical provider descriptor catalog.
 *
 * Static descriptors for all registered Access providers. No secrets.
 */

import type { AccessProviderDescriptor } from './descriptor.ts';

const SIMULATION_NOW = '2026-08-31T09:00:00.000Z';

function descriptor(input: AccessProviderDescriptor): AccessProviderDescriptor {
  return Object.freeze(input);
}

export const ACCESS_PROVIDER_DESCRIPTORS: Readonly<Record<string, AccessProviderDescriptor>> = Object.freeze({
  // Commercial providers (ACCESS-14/21)
  expedia: descriptor({
    providerId: 'expedia',
    name: 'Expedia Rapid (lodging + travel)',
    providerTypes: Object.freeze(['AGGREGATOR', 'FULFILLMENT']),
    categories: Object.freeze(['HOUSING_ROOM_NIGHTS', 'TRAVEL', 'VEHICLE_HOURS']),
    capabilities: Object.freeze([
      'CATALOG_SEARCH',
      'AVAILABILITY',
      'REALTIME_PRICING',
      'QUOTE',
      'RESERVE',
      'BOOK',
      'CANCEL',
      'FULFILLMENT_STATUS',
      'WEBHOOKS',
      'REFUND',
    ]),
    geographies: Object.freeze(['US', 'GLOBAL']),
    environment: 'SANDBOX',
    activationState: 'SANDBOX_ENABLED',
    commercialStatus: 'SANDBOX',
    credentialStatus: 'CONFIGURED',
    fulfillmentModel: 'AGGREGATOR_CONFIRM',
    settlementModel: 'DIRECT_BOOKING_PAYMENT',
    supportsIdempotency: true,
    supportsWebhooks: true,
    supportsReconciliation: true,
    contractRef: 'contract/expedia-sandbox',
    metadata: Object.freeze({ integratedAt: SIMULATION_NOW, adapter: 'expedia-sandbox' }),
  }),
  turo: descriptor({
    providerId: 'turo',
    name: 'Turo (mobility)',
    providerTypes: Object.freeze(['DIRECT_PROVIDER', 'FULFILLMENT']),
    categories: Object.freeze(['VEHICLE_HOURS']),
    capabilities: Object.freeze([
      'CATALOG_SEARCH',
      'AVAILABILITY',
      'QUOTE',
      'RESERVE',
      'BOOK',
      'CANCEL',
      'FULFILLMENT_STATUS',
      'WEBHOOKS',
    ]),
    geographies: Object.freeze(['US']),
    environment: 'SIMULATION',
    activationState: 'PREVIEW',
    commercialStatus: 'COMMERCIAL_NEGOTIATION',
    credentialStatus: 'MISSING',
    fulfillmentModel: 'DIRECT',
    settlementModel: 'DIRECT_BOOKING_PAYMENT',
    supportsIdempotency: true,
    supportsWebhooks: true,
    supportsReconciliation: true,
    contractRef: null,
    metadata: Object.freeze({ partnerApprovalRequired: 'true' }),
  }),
  doordash: descriptor({
    providerId: 'doordash',
    name: 'DoorDash (food delivery)',
    providerTypes: Object.freeze(['MARKETPLACE', 'FULFILLMENT']),
    categories: Object.freeze(['FOOD']),
    capabilities: Object.freeze(['CATALOG_SEARCH', 'AVAILABILITY', 'QUOTE', 'FULFILLMENT_STATUS', 'WEBHOOKS']),
    geographies: Object.freeze(['US']),
    environment: 'SIMULATION',
    activationState: 'PREVIEW',
    commercialStatus: 'COMMERCIAL_NEGOTIATION',
    credentialStatus: 'MISSING',
    fulfillmentModel: 'MARKETPLACE_HANDOFF',
    settlementModel: 'DIRECT_BOOKING_PAYMENT',
    supportsIdempotency: true,
    supportsWebhooks: true,
    supportsReconciliation: false,
    contractRef: null,
    metadata: Object.freeze({ partnerApprovalRequired: 'true' }),
  }),
  amazon: descriptor({
    providerId: 'amazon',
    name: 'Amazon (commerce)',
    providerTypes: Object.freeze(['MARKETPLACE', 'FULFILLMENT']),
    categories: Object.freeze(['GOODS', 'FOOD']),
    capabilities: Object.freeze(['CATALOG_SEARCH', 'AVAILABILITY', 'QUOTE', 'BOOK', 'FULFILLMENT_STATUS', 'WEBHOOKS']),
    geographies: Object.freeze(['US', 'GLOBAL']),
    environment: 'SIMULATION',
    activationState: 'PREVIEW',
    commercialStatus: 'COMMERCIAL_NEGOTIATION',
    credentialStatus: 'MISSING',
    fulfillmentModel: 'MARKETPLACE_HANDOFF',
    settlementModel: 'INVOICE',
    supportsIdempotency: true,
    supportsWebhooks: true,
    supportsReconciliation: false,
    contractRef: null,
    metadata: Object.freeze({ partnerApprovalRequired: 'true' }),
  }),
  airbnb: descriptor({
    providerId: 'airbnb',
    name: 'Airbnb (stays + experiences)',
    providerTypes: Object.freeze(['DIRECT_PROVIDER', 'FULFILLMENT']),
    categories: Object.freeze(['HOUSING_ROOM_NIGHTS', 'EXPERIENCES']),
    capabilities: Object.freeze([
      'CATALOG_SEARCH',
      'AVAILABILITY',
      'QUOTE',
      'RESERVE',
      'BOOK',
      'CANCEL',
      'WEBHOOKS',
    ]),
    geographies: Object.freeze(['GLOBAL']),
    environment: 'SIMULATION',
    activationState: 'PREVIEW',
    commercialStatus: 'COMMERCIAL_NEGOTIATION',
    credentialStatus: 'MISSING',
    fulfillmentModel: 'DIRECT',
    settlementModel: 'DIRECT_BOOKING_PAYMENT',
    supportsIdempotency: true,
    supportsWebhooks: true,
    supportsReconciliation: true,
    contractRef: null,
    metadata: Object.freeze({ partnerApprovalRequired: 'true' }),
  }),

  // Discovery providers (ACCESS Wave 2)
  gbfs_mobility: descriptor({
    providerId: 'gbfs_mobility',
    name: 'GBFS Mobility Discovery',
    providerTypes: Object.freeze(['DISCOVERY']),
    categories: Object.freeze(['VEHICLE_HOURS', 'TRANSPORTATION']),
    capabilities: Object.freeze(['CATALOG_SEARCH', 'AVAILABILITY']),
    geographies: Object.freeze(['GLOBAL']),
    environment: 'SIMULATION',
    activationState: 'SANDBOX_ENABLED',
    commercialStatus: 'DISCOVERY_TERMS',
    credentialStatus: 'NOT_REQUIRED',
    fulfillmentModel: 'DISCOVERY_ONLY',
    settlementModel: 'OTHER',
    supportsIdempotency: true,
    supportsWebhooks: false,
    supportsReconciliation: false,
    contractRef: 'terms/gbfs-discovery',
    metadata: Object.freeze({ protocol: 'GBFS' }),
  }),
  travel_discovery: descriptor({
    providerId: 'travel_discovery',
    name: 'Travel Discovery (air/rail)',
    providerTypes: Object.freeze(['DISCOVERY', 'AGGREGATOR']),
    categories: Object.freeze(['TRAVEL', 'TRANSPORTATION']),
    capabilities: Object.freeze(['CATALOG_SEARCH', 'AVAILABILITY', 'REALTIME_PRICING']),
    geographies: Object.freeze(['GLOBAL']),
    environment: 'SIMULATION',
    activationState: 'SANDBOX_ENABLED',
    commercialStatus: 'DISCOVERY_TERMS',
    credentialStatus: 'NOT_REQUIRED',
    fulfillmentModel: 'DISCOVERY_ONLY',
    settlementModel: 'OTHER',
    supportsIdempotency: true,
    supportsWebhooks: false,
    supportsReconciliation: false,
    contractRef: 'terms/travel-discovery',
    metadata: Object.freeze({ scope: 'airlines,rail' }),
  }),
  experiences_discovery: descriptor({
    providerId: 'experiences_discovery',
    name: 'Experiences Discovery',
    providerTypes: Object.freeze(['DISCOVERY']),
    categories: Object.freeze(['EXPERIENCES']),
    capabilities: Object.freeze(['CATALOG_SEARCH', 'AVAILABILITY']),
    geographies: Object.freeze(['GLOBAL']),
    environment: 'SIMULATION',
    activationState: 'SANDBOX_ENABLED',
    commercialStatus: 'DISCOVERY_TERMS',
    credentialStatus: 'NOT_REQUIRED',
    fulfillmentModel: 'DISCOVERY_ONLY',
    settlementModel: 'OTHER',
    supportsIdempotency: true,
    supportsWebhooks: false,
    supportsReconciliation: false,
    contractRef: 'terms/experiences-discovery',
    metadata: Object.freeze({}),
  }),
  hotels_discovery: descriptor({
    providerId: 'hotels_discovery',
    name: 'Hotels Discovery',
    providerTypes: Object.freeze(['DISCOVERY']),
    categories: Object.freeze(['HOUSING_ROOM_NIGHTS']),
    capabilities: Object.freeze(['CATALOG_SEARCH', 'AVAILABILITY', 'REALTIME_PRICING']),
    geographies: Object.freeze(['GLOBAL']),
    environment: 'SIMULATION',
    activationState: 'SANDBOX_ENABLED',
    commercialStatus: 'DISCOVERY_TERMS',
    credentialStatus: 'NOT_REQUIRED',
    fulfillmentModel: 'DISCOVERY_ONLY',
    settlementModel: 'OTHER',
    supportsIdempotency: true,
    supportsWebhooks: false,
    supportsReconciliation: false,
    contractRef: 'terms/hotels-discovery',
    metadata: Object.freeze({}),
  }),
  transportation_discovery: descriptor({
    providerId: 'transportation_discovery',
    name: 'Transportation Discovery (transit/robotaxi)',
    providerTypes: Object.freeze(['DISCOVERY']),
    categories: Object.freeze(['TRANSPORTATION', 'VEHICLE_HOURS']),
    capabilities: Object.freeze(['CATALOG_SEARCH', 'AVAILABILITY']),
    geographies: Object.freeze(['US', 'GLOBAL']),
    environment: 'SIMULATION',
    activationState: 'SANDBOX_ENABLED',
    commercialStatus: 'DISCOVERY_TERMS',
    credentialStatus: 'NOT_REQUIRED',
    fulfillmentModel: 'DISCOVERY_ONLY',
    settlementModel: 'OTHER',
    supportsIdempotency: true,
    supportsWebhooks: false,
    supportsReconciliation: false,
    contractRef: 'terms/transportation-discovery',
    metadata: Object.freeze({ scope: 'transit,robotaxi' }),
  }),
  compute_discovery: descriptor({
    providerId: 'compute_discovery',
    name: 'AI/Compute Discovery',
    providerTypes: Object.freeze(['DISCOVERY', 'CAPACITY_CONTRIBUTOR']),
    categories: Object.freeze(['COMPUTE', 'ROBOTICS']),
    capabilities: Object.freeze(['CATALOG_SEARCH', 'AVAILABILITY']),
    geographies: Object.freeze(['GLOBAL']),
    environment: 'SIMULATION',
    activationState: 'SANDBOX_ENABLED',
    commercialStatus: 'DISCOVERY_TERMS',
    credentialStatus: 'NOT_REQUIRED',
    fulfillmentModel: 'CAPACITY_ONLY',
    settlementModel: 'FUTURE_NATIVE_MR',
    supportsIdempotency: true,
    supportsWebhooks: false,
    supportsReconciliation: false,
    contractRef: 'terms/compute-discovery',
    metadata: Object.freeze({ futureSettlement: 'FUTURE_NATIVE_MR', productionEnabled: 'false' }),
  }),
});
