export const AGENT_ACTION_CLASSES = [
  'READ_FINANCIAL_STATE',
  'PREPARE_PAYMENT',
  'EXECUTE_PREAPPROVED_PAYMENT',
  'PREPARE_EXCHANGE_ORDER',
  'EXECUTE_BOUNDED_EXCHANGE_ORDER',
  'REBALANCE_WITHIN_POLICY',
  'MANAGE_ALLOWED_PRODUCTIVE_SERVICE',
  'REQUEST_HUMAN_APPROVAL',
] as const;

export type AgentActionClass = (typeof AGENT_ACTION_CLASSES)[number];

export const HIGH_RISK_ACTION_CLASSES = [
  'ADD_WITHDRAWAL_DESTINATION',
  'WALLET_RECOVERY',
  'KEY_ROTATION',
  'CHANGE_AGENT_MANDATE',
  'LARGE_TRANSFER_BEYOND_LIMIT',
  'NEW_REGULATED_PRODUCT',
  'LEVERAGE_OR_BORROWING',
] as const;

export type HighRiskActionClass = (typeof HIGH_RISK_ACTION_CLASSES)[number];

export const AGENT_ASSET_IDS = [
  'SUNREY_COIN',
  'MOONREY_COIN',
  'FIAT_ACCOUNT',
  'LISTED_ASSET',
] as const;

export type AgentAssetId = (typeof AGENT_ASSET_IDS)[number];

export const AGENT_APPROVAL_CLASSES = [
  'NO_ADDITIONAL_APPROVAL_WITHIN_MANDATE',
  'MOBILE_CONFIRMATION',
  'SECOND_DEVICE_CONFIRMATION',
  'CUSTODY_APPROVAL',
  'MULTI_PERSON_APPROVAL',
] as const;

export type AgentApprovalClass = (typeof AGENT_APPROVAL_CLASSES)[number];

export const MANDATE_MODES = ['SIMULATION_ONLY', 'PRODUCTION'] as const;
export type MandateMode = (typeof MANDATE_MODES)[number];

export const MANDATE_STATES = ['ACTIVE', 'SUSPENDED', 'EXPIRED', 'REVOKED'] as const;
export type MandateState = (typeof MANDATE_STATES)[number];

export const PROPOSAL_STATES = [
  'DRAFT',
  'PENDING_APPROVAL',
  'APPROVED',
  'INELIGIBLE',
  'EXECUTED',
  'FAILED',
] as const;
export type ProposalState = (typeof PROPOSAL_STATES)[number];

export const REVOCATION_SCOPES = ['MANDATE', 'AGENT', 'DELEGATED_KEY', 'ACTION_CLASS', 'WALLET_KILL'] as const;
export type RevocationScope = (typeof REVOCATION_SCOPES)[number];

export const EXPECTED_OUTCOME_CLASSES = [
  'PAYMENT_PREPARED',
  'PAYMENT_SUBMITTED_FOR_AUTHORIZATION',
  'EXCHANGE_ORDER_PREPARED',
  'EXCHANGE_ORDER_SUBMITTED_FOR_AUTHORIZATION',
  'REBALANCE_PREPARED',
  'HUMAN_APPROVAL_REQUESTED',
  'READ_ONLY',
  'SIMULATION_EVALUATION',
] as const;
export type ExpectedOutcomeClass = (typeof EXPECTED_OUTCOME_CLASSES)[number];

export const SAFETY_EVENT_KINDS = [
  'EXECUTION_FAILURE',
  'PRICE_PROTECTION_REJECTION',
  'MARKET_UNAVAILABLE',
  'COMPLIANCE_REJECTION',
  'MANDATE_LIMIT_REJECTION',
  'NETWORK_FAILURE',
  'SELF_EXPANSION_ATTEMPT',
  'PROMPT_INJECTION_BLOCKED',
  'REVOKED_MANDATE_USED',
  'AI_IDENTITY_SIGN_ATTEMPT',
] as const;
export type SafetyEventKind = (typeof SAFETY_EVENT_KINDS)[number];

export const FORBIDDEN_STRATEGY_CLAIMS = [
  'GUARANTEED_RETURN',
  'GUARANTEED_PROFIT',
  'GUARANTEED_BALANCE_GROWTH',
  'RISK_FREE_TRADING',
] as const;
export type ForbiddenStrategyClaim = (typeof FORBIDDEN_STRATEGY_CLAIMS)[number];

export const AGENT_MANDATE_REFUSAL_CODES = [
  'ORPHAN_AGENT',
  'MANDATE_EXPIRED',
  'MANDATE_REVOKED',
  'ACTION_CLASS_NOT_PERMITTED',
  'ASSET_NOT_PERMITTED',
  'MARKET_NOT_PERMITTED',
  'DESTINATION_NOT_PERMITTED',
  'BUDGET_EXCEEDED',
  'FREQUENCY_EXCEEDED',
  'SELF_EXPANSION_FORBIDDEN',
  'HIGH_RISK_REQUIRES_HUMAN',
  'APPROVAL_REQUIRED',
  'APPROVAL_REPLAY',
  'WRONG_WALLET',
  'WRONG_NETWORK',
  'SIMULATION_CANNOT_SUBMIT',
  'PRODUCTION_PRECONDITIONS_UNMET',
  'JURISDICTION_UNAVAILABLE',
  'COMPLIANCE_REFUSED',
  'RISK_RESTRICTED',
  'WALLET_AUTHORIZATION_REFUSED',
  'AI_CANNOT_SIGN',
  'MASTER_KEY_FORBIDDEN',
  'HUMAN_INFORMATION_NOT_PERMITTED',
  'WILDCARD_ASSET_FORBIDDEN',
  'PROFIT_GUARANTEE_FORBIDDEN',
  'PENDING_INELIGIBLE_AFTER_REVOCATION',
  'SCHEDULE_DOES_NOT_AUTHORIZE',
  'PROMPT_INJECTION',
] as const;
export type AgentMandateRefusalCode = (typeof AGENT_MANDATE_REFUSAL_CODES)[number];

export const HUMAN_REQUIRED_ACTIONS = new Set<string>([
  ...HIGH_RISK_ACTION_CLASSES,
  'CHANGE_AGENT_MANDATE',
]);

export const EXECUTABLE_ACTION_CLASSES = new Set<AgentActionClass>([
  'EXECUTE_PREAPPROVED_PAYMENT',
  'EXECUTE_BOUNDED_EXCHANGE_ORDER',
  'REBALANCE_WITHIN_POLICY',
  'MANAGE_ALLOWED_PRODUCTIVE_SERVICE',
]);

export function isAgentActionClass(value: unknown): value is AgentActionClass {
  return typeof value === 'string' && (AGENT_ACTION_CLASSES as readonly string[]).includes(value);
}

export function isHighRiskAction(value: string): boolean {
  return (HIGH_RISK_ACTION_CLASSES as readonly string[]).includes(value);
}
