/**
 * Chunk 76 economic stress identifiers.
 *
 * Engineering classifications only. Not a legal, investment, or
 * marketing security score.
 */

export const ECONOMIC_STRESS_SCHEMA_VERSION = 1 as const;
export const ECONOMIC_STRESS_TOOL_VERSION = 'sunrey-economics-stress/1' as const;
export const ECONOMIC_STRESS_LABEL = 'ENGINEERING_SIMULATION' as const;

export const ECONOMIC_INVARIANT_IDS = [
  'SUNREY_SUPPLY_RECONCILES',
  'MOONREY_SUPPLY_RECONCILES',
  'NO_HIDDEN_NATIVE_ISSUANCE',
  'NO_DUPLICATE_MOONREY_ISSUANCE',
  'NO_DUPLICATE_VALIDATOR_REWARD',
  'NO_DUPLICATE_VALIDATOR_PENALTY',
  'FEE_RESERVATION_RECONCILES',
  'FEE_DISPOSITION_RECONCILES',
  'EXCHANGE_DVP_CONSERVES_ASSETS',
  'CUSTODY_RECONCILES',
  'MACHINE_MANDATES_HOLD',
  'GENESIS_POLICY_REMAINS_IMMUTABLE',
  'GOVERNANCE_VERSIONING_HOLDS',
  'ORACLE_FAILURE_DOES_NOT_FABRICATE_FACTS',
  'ACCESS_CAPACITY_NOT_OVERSOLD',
  'ACCESS_RESERVATION_REQUIRES_EXECUTION_AUTHORITY',
  'ACCESS_ACTIVITY_ISSUES_NO_NATIVE_ASSET',
  'ACCESS_EVIDENCE_CHAIN_RECONSTRUCTS',
] as const;
export type EconomicInvariantId = (typeof ECONOMIC_INVARIANT_IDS)[number];

export const STRESS_DOMAINS = [
  'LIQUIDITY',
  'PRODUCTIVE',
  'ORACLE',
  'DOUBLE_COUNT',
  'FEE',
  'VALIDATOR',
  'HUMAN',
  'AUTOMATION',
  'MACHINE',
  'EXCHANGE',
  'CUSTODY',
  'COMPOUND',
  'NO_QUORUM',
  'ACCESS',
] as const;
export type StressDomain = (typeof STRESS_DOMAINS)[number];

export const STRESS_SEVERITIES = ['INFO', 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL'] as const;
export type StressSeverity = (typeof STRESS_SEVERITIES)[number];

export const FAILURE_CLASSES = [
  'SAFETY_FAILURE',
  'ACCOUNTING_FAILURE',
  'AVAILABILITY_DEGRADATION',
  'LIQUIDITY_STRESS',
  'CONCENTRATION_RISK',
  'POLICY_CONFIGURATION_RISK',
  'EXPECTED_FAIL_CLOSED_BEHAVIOR',
] as const;
export type FailureClass = (typeof FAILURE_CLASSES)[number];

export const FINDING_VERIFICATION_STATES = [
  'OPEN',
  'REMEDIATED_UNVERIFIED',
  'VERIFIED',
  'ACCEPTED_LIMITATION',
] as const;
export type FindingVerificationState = (typeof FINDING_VERIFICATION_STATES)[number];

export const SHOCK_KINDS = [
  'LIQUIDITY_THIN_BOOK',
  'LIQUIDITY_LARGE_ORDER',
  'LIQUIDITY_SPREAD_WIDEN',
  'LIQUIDITY_ONE_SIDED',
  'LIQUIDITY_MM_UNAVAILABLE',
  'LIQUIDITY_VOLUME_SURGE',
  'PROD_ISSUANCE_PRESSURE',
  'PROD_ENERGY_COLLAPSE',
  'PROD_COMPUTE_ABUNDANCE',
  'PROD_COMPUTE_SHORTAGE',
  'PROD_MANUFACTURING_COLLAPSE',
  'PROD_LOGISTICS_SHORTAGE',
  'PROD_AI_SURGE',
  'PROD_ROBOT_SURGE',
  'PROD_OPERATOR_CONCENTRATION',
  'ORACLE_OUTAGE',
  'ORACLE_STALE',
  'ORACLE_CONFLICT',
  'ORACLE_ONE_CONTROLLER',
  'ORACLE_UNIT_MISMATCH',
  'ORACLE_DELAYED',
  'ORACLE_REFERENCE_UNAVAILABLE',
  'DUP_REPLAY',
  'DUP_CAPACITY_OUTPUT',
  'DUP_DELIVERY_OUTPUT',
  'DUP_CROSS_CATEGORY',
  'DUP_LINEAGE_MUTATION',
  'DUP_REORDERED_EVIDENCE',
  'DUP_EPOCH_BOUNDARY',
  'FEE_SATURATION',
  'FEE_BURST',
  'FEE_PQ_MIX',
  'FEE_INTEROP_HEAVY',
  'FEE_ORACLE_HEAVY',
  'FEE_EXCHANGE_HEAVY',
  'FEE_PRIORITY',
  'FEE_MAX_BOUNDARY',
  'VAL_LOW_FEE',
  'VAL_HIGH_FEE',
  'VAL_JAIL',
  'VAL_PENALTY',
  'VAL_BOND_CONCENTRATION',
  'VAL_EXIT',
  'VAL_UNBOND',
  'VAL_REWARD_DEPLETION',
  'HUM_DEMAND_FALL',
  'HUM_DEMAND_RISE',
  'HUM_PARTICIPANT_GROWTH',
  'HUM_INFO_RIGHT_COLLAPSE',
  'HUM_COMMUNITY_DISTRIBUTION',
  'AUTO_SHOCK',
  'MACH_SPEND_BURST',
  'MACH_MANDATE_EXHAUSTION',
  'MACH_ROBOT_ENERGY',
  'MACH_AI_COMPUTE',
  'MACH_OPERATOR_CONCENTRATION',
  'MACH_FAILED_DELIVERY',
  'MACH_ESCROW_BACKLOG',
  'EXCH_PRICE_MOVE',
  'EXCH_CANCEL_SURGE',
  'EXCH_PARTIAL_FILL',
  'EXCH_SETTLEMENT_CONGESTION',
  'EXCH_CUSTODY_DELAY',
  'EXCH_SUBMISSION_AMBIGUITY',
  'CUST_WITHDRAWAL_SURGE',
  'CUST_SIGNER_UNAVAILABLE',
  'CUST_SUBMISSION_UNKNOWN',
  'CUST_RECONCILIATION_LAG',
  'CUST_VAULT_RESTRICTED',
  'COMPOUND_ENERGY_COMPUTE_LIQUIDITY',
  'COMPOUND_ORACLE_EXCHANGE_VALIDATOR',
  'COMPOUND_FEE_CUSTODY_MACHINE',
  'NO_QUORUM_FREEZE',
  'ACCESS_ABUNDANCE',
  'ACCESS_DEMAND_SURGE',
  'ACCESS_PRODUCTIVE_SHOCK',
  'ACCESS_GEOGRAPHIC_SCARCITY',
  'ACCESS_TEMPORAL_SCARCITY',
  'ACCESS_PROVIDER_FAILURE',
  'ACCESS_ORACLE_STALE',
  'ACCESS_EXCHANGE_UNAVAILABLE',
  'ACCESS_SETTLEMENT_FAILURE',
  'ACCESS_POLICY_CHANGE',
  'ACCESS_MASS_CONCURRENCY',
  'ACCESS_ABUNDANT_VEHICLE',
  'ACCESS_PREMIUM_SCARCE_VEHICLE',
  'ACCESS_COMPOSITE_TRAVEL',
  'ACCESS_HOUSEHOLD_FOOD',
] as const;
export type ShockKind = (typeof SHOCK_KINDS)[number];

export const CAMPAIGN_IDS = [
  'smoke',
  'critical-invariants',
  'compound',
  'extended-12',
  'extended-120',
  'extended-600',
  'parameterized-dual-economy-rehearsal',
  'access-economy',
] as const;
export type CampaignId = (typeof CAMPAIGN_IDS)[number];
