apiVersion: v1
kind: Secret
metadata:
  name: sunrey-platform-secret-refs
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  databaseMigrator: secret://sunrey-preproduction/database/migrator
  databaseApp: secret://sunrey-preproduction/database/app-readwrite
  databaseReadonly: secret://sunrey-preproduction/database/app-readonly
  databaseBackup: secret://sunrey-preproduction/database/backup
  tlsApi: secret://sunrey-preproduction/tls/api
  tlsRpc: secret://sunrey-preproduction/tls/rpc
  queue: secret://sunrey-preproduction/queue/events
  objectStorage: secret://sunrey-preproduction/storage/objects
  registry: secret://sunrey-preproduction/registry/pull
  kmsAuth: secret://sunrey-preproduction/kms/auth
  hsmAuth: secret://sunrey-preproduction/hsm/auth
  paymentsSandbox: secret://sunrey-preproduction/providers/payments-sandbox
  fxSandbox: secret://sunrey-preproduction/providers/fx-sandbox
  cardsSandbox: secret://sunrey-preproduction/providers/cards-sandbox
