export {
  DEFAULT_M10_BREAKOUT_BUFFER_BPS,
  DEFAULT_M10_CONFIG,
  DEFAULT_M10_ENTRY_QUANTITY_UNITS,
  DEFAULT_M10_LOOKBACK_PERIODS,
  DEFAULT_M10_MAX_HOLDING_PERIOD_HOURS,
  DEFAULT_M10_MAX_OBSERVATION_AGE_MS,
  DEFAULT_M10_MAX_REALIZED_VOLATILITY_BPS,
  DEFAULT_M10_MAX_SPREAD_BPS,
  DEFAULT_M10_MIN_REALIZED_VOLATILITY_BPS,
  DEFAULT_M10_PERSISTENCE_BARS,
  DEFAULT_M10_TRAILING_STOP_VOL_MULTIPLIER,
  DEFAULT_M10_VOLUME_RATIO_THRESHOLD,
  HELIOS_M10_CAPSULE_ID,
  HELIOS_M10_FAMILY_ID,
  HELIOS_M10_RULE_ID,
  HELIOS_M10_RULE_VERSION,
  HELIOS_MULTI_ASSET_M10_CRYPTO_MOMENTUM_BREAKOUT_QUALIFIED,
  type CryptoMomentumBreakoutConfig,
} from './constants.ts';
export {
  evaluateCryptoMomentumBreakoutRule,
  HELIOS_M10_CRYPTO_MOMENTUM_BREAKOUT_V1,
} from './rule.ts';
export type {
  CryptoMomentumBar,
  CryptoMomentumBreakoutControls,
  CryptoMomentumDecision,
  CryptoMomentumEvaluateInput,
  CryptoMomentumForcedExit,
  CryptoMomentumFreshnessStatus,
  CryptoMomentumGovernance,
  CryptoMomentumMarketState,
  CryptoMomentumPosition,
  CryptoMomentumProviderHealth,
} from './types.ts';
export {
  M10_FIXTURE_DEFAULTS,
  VALID_GOVERNANCE,
  baseBtcBar,
  baseEthBar,
  computeRollingRangeHighPriorBars,
  cryptoMomentumEvaluationManifest,
  flatPosition,
  openPosition,
  validBreakoutControls,
  validBtcBreakoutMarket,
  validEthBreakoutMarket,
} from './fixtures.ts';
