/**
 * ACCESS-01 structural isolation for the Human Access Economy bounded context.
 *
 * Domain vocabulary and orchestration live here. Entitlements, scarcity,
 * reservations, exchange markets, and chain commitments are implemented in
 * specialized modules listed under composesWith — not competing authorities.
 */

export const ACCESS_ECONOMY_ISOLATION = Object.freeze({
  owner: 'packages/access-economy',
  boundedContextId: 'ACCESS_ECONOMY',
  capability: 'sunrey-access-economy-domain',
  financialStateMutation: false,
  executionAuthorityRequired: false,
  kernelAuthorizationRequired: false,
  pricingImplemented: false,
  reservationExecutionImplemented: false,
  exchangeIntegrationImplemented: false,
  mintingImplemented: false,
  settlementImplemented: false,
  custodyImplemented: false,
  exchangeImplemented: false,
  complianceImplemented: false,
  oracleConsensusImplemented: false,
  identityTruthImplemented: false,
  legalEligibilityTruthImplemented: false,
  humanWorthScoringImplemented: false,
  socialCreditImplemented: false,
  accessCoinImplemented: false,
  productionActivated: false,
  issuesExecutionAuthority: false,
  authorizesLedgerPosting: false,
  authorizesMinting: false,
  authorizesSettlement: false,
  fabricPort: 'AccessFabricPort',
  isSourceOfTruth: true,
  orchestratesAbove: Object.freeze([
    'packages/personal-economic-graph',
    'packages/agent',
    'packages/sunrey-agent',
  ]),
  composesWith: Object.freeze([
    'packages/access-fabric',
    'packages/sunrey-access',
    'packages/sunrey-access-fabric',
    'packages/human-access-economy',
    'packages/sunrey-chain',
    'packages/sunrey-exchange',
    'packages/economic-asset-registry',
    'packages/consent',
    'packages/personal-data-vault',
    'packages/information-market',
    'packages/evidence',
    'packages/regulatory-twin',
  ]),
  doesNotReplace: Object.freeze([
    'Compliance Kernel',
    'Execution Authority',
    'Ledger',
    'Exchange',
    'Custody',
    'Oracle consensus',
    'SunRey Coin supply',
    'MoonRey Coin supply',
    'Personal Economic Graph',
    'Productive Economy',
    'Regulatory Digital Twin',
    'Identity truth',
    'Legal eligibility truth',
  ]),
  forbiddenCompetingPackages: Object.freeze([
    'packages/access-economy-v2',
    'packages/access-core',
    'packages/access-platform',
    'packages/access-system',
    'packages/access-engine',
    'packages/access-simulation',
    'packages/access-coin',
    'packages/access-token',
    'packages/access-ledger',
    'packages/access-exchange',
    'packages/access-custody',
    'packages/access-kernel',
    'packages/access-oracle',
    'packages/entitlements',
    'packages/social-credit',
    'packages/human-worth-access',
    'packages/licensing',
    'packages/reservation-engine',
    'packages/access-market',
  ]),
  mustNotImport: Object.freeze([
    'packages/kernel',
    'packages/ledger',
    'packages/permissions',
    'packages/custody',
    'packages/sunrey-exchange',
    'packages/sunrey-chain',
    'packages/payments',
    'packages/platform',
    'packages/personal-economic-graph',
    'packages/agent',
    'packages/sunrey-agent',
    'packages/regulatory-twin',
    'services/',
  ]),
});
