export const ACCESS_ECONOMY_ISOLATION = Object.freeze({
  owner: 'packages/access-economy',
  capability: 'sunrey-access-fabric',
  boundedContext: 'ACCESS_ECONOMY',
  financialStateMutation: false,
  executionAuthorityRequired: false,
  kernelAuthorizationRequired: false,
  mintingImplemented: false,
  settlementImplemented: false,
  custodyImplemented: false,
  exchangeImplemented: false,
  complianceImplemented: false,
  oracleConsensusImplemented: false,
  identityTruthImplemented: false,
  legalEligibilityTruthImplemented: false,
  humanWorthScoringImplemented: false,
  socialCreditImplemented: false,
  accessCoinImplemented: false,
  productionActivated: false,
  forbiddenCompetingPackages: Object.freeze([
    'packages/access-fabric',
    'packages/access-economy-v2',
    'packages/human-access-economy',
    'packages/access-rights',
    'packages/access-coin',
    'packages/access-token',
    'packages/capacity-access',
    'packages/access-market',
    'packages/access-registry',
    'packages/access-ledger',
    'packages/access-exchange',
    'packages/access-custody',
    'packages/access-kernel',
    'packages/access-oracle',
    'packages/social-credit',
    'packages/human-worth-access',
  ]),
  fabricPort: 'AccessFabricPort',
  isSourceOfTruth: false,
  orchestratesAbove: Object.freeze([
    'packages/personal-economic-graph',
    'packages/agent',
    'packages/sunrey-agent',
  ]),
  composesWith: Object.freeze([
    'packages/kernel',
    'packages/permissions',
    'packages/ledger',
    'packages/custody',
    'packages/sunrey-exchange',
    'packages/sunrey-chain',
    'packages/payments',
    'packages/evidence',
    'packages/economic-asset-registry',
    'packages/regulatory-twin',
  ]),
  doesNotReplace: Object.freeze([
    'Compliance Kernel',
    'Execution Authority',
    'Ledger',
    'Exchange',
    'Custody',
    'Oracle consensus',
    'SunRey Coin supply',
    'MoonRey Coin supply',
    'Personal Economic Graph',
    'Productive Economy',
    'Regulatory Digital Twin',
    'Identity truth',
    'Legal eligibility truth',
  ]),
  mustNotImport: Object.freeze([
    'packages/kernel',
    'packages/permissions',
    'packages/ledger',
    'packages/custody',
    'packages/sunrey-exchange',
    'packages/sunrey-chain',
    'packages/sunrey-coin',
    'packages/payments',
    'packages/platform',
    'packages/personal-economic-graph',
    'packages/agent',
    'packages/sunrey-agent',
    'packages/economic-asset-registry',
    'packages/regulatory-twin',
    'packages/evidence',
    'services/',
  ]),
});
