/**
 * HELIOS H21 — Decision-Validity Envelope taxonomies.
 * Deterministic validation artifact coordinating existing authorities.
 * Not a Risk Engine. Does not grant financial authority.
 */

export const ENVELOPE_VALIDITY_STATUSES = [
  'VALID',
  'INVALID',
  'EXPIRED',
  'DEGRADED',
  'REVIEW_REQUIRED',
  'UNKNOWN',
] as const;

export type EnvelopeValidityStatus = (typeof ENVELOPE_VALIDITY_STATUSES)[number];

export const ENVELOPE_FAILURE_ACTIONS = [
  'WAIT',
  'ABANDON',
  'RESEARCH_AGAIN',
  'REQUALIFY',
  'NO_ACTION',
] as const;

export type EnvelopeFailureAction = (typeof ENVELOPE_FAILURE_ACTIONS)[number];

export const ENVELOPE_COMPONENT_KINDS = [
  'EVIDENCE_VALIDITY',
  'MARKET_TERMS',
  'LIQUIDITY_CAPACITY',
  'MARKET_STATE',
  'CUSTOMER_ACCOUNT_STATE',
  'MANDATE_APPROVAL',
  'STRATEGY_QUALIFICATION',
  'RISK_CONTEXT',
  'COMPLIANCE_JURISDICTION',
  'PROVIDER_ROUTE',
  'MODEL_RESEARCH_VALIDITY',
] as const;

export type EnvelopeComponentKind = (typeof ENVELOPE_COMPONENT_KINDS)[number];

export const ENVELOPE_REASON_CODES = [
  'OK',
  'EVIDENCE_STALE',
  'EVIDENCE_MISSING',
  'EVIDENCE_ENTITLEMENT_DENIED',
  'EVIDENCE_CONTRADICTION',
  'EVIDENCE_CORROBORATION_MISSING',
  'MARKET_SPREAD_WIDENED',
  'MARKET_TERMS_MATERIAL_CHANGE',
  'TRANSACTION_COST_DESTROYS_EDGE',
  'INSUFFICIENT_LIQUIDITY',
  'CAPACITY_EXCEEDED',
  'CAPITAL_UNAVAILABLE',
  'RESERVATION_CONFLICT',
  'VENUE_CLOSED',
  'INSTRUMENT_HALTED',
  'INSTRUMENT_INACTIVE',
  'ACCOUNT_INACTIVE',
  'ACCOUNT_FUNDS_INSUFFICIENT',
  'ACCOUNT_RESTRICTED',
  'MANDATE_REVOKED',
  'APPROVAL_EXPIRED',
  'APPROVAL_REVOKED',
  'STRATEGY_CAPSULE_EXPIRED',
  'STRATEGY_CAPSULE_REVOKED',
  'STRATEGY_CAPSULE_UNQUALIFIED',
  'MODEL_VERSION_UNQUALIFIED',
  'RESEARCH_EXPIRED',
  'PROVIDER_ROUTE_UNAVAILABLE',
  'PROVIDER_ROUTE_MISCONFIGURED',
  'JURISDICTION_CAPABILITY_DISABLED',
  'RISK_REFUSED',
  'RISK_REVIEW_REQUIRED',
  'CRITICAL_STATE_UNKNOWN',
  'ENVELOPE_EXPIRED',
  'CUSTOMER_MISMATCH',
  'REVALIDATION_REQUIRED',
  'RESTART_REVALIDATION',
] as const;

export type EnvelopeReasonCode = (typeof ENVELOPE_REASON_CODES)[number];

export const DECISION_VALIDITY_POLICY_VERSION = 'helios-decision-validity-v1' as const;
