import type { FactType } from '../oracle/types.ts';
import type { ProductiveCategory } from '../productive/types.ts';
import type { ContextRequirement, MeasurementDimension, SemanticQualifier } from './constitution.ts';
import type { CanonicalUnitDefinition } from './types.ts';

const ENERGY_FACTS: readonly FactType[] = ['ENERGY_PRODUCTION', 'ENERGY_CAPACITY', 'ENERGY_CONSUMPTION'];
const MASS_FACTS: readonly FactType[] = [
  'FOOD_PRODUCTION',
  'AGRICULTURAL_OUTPUT',
  'RESOURCE_RESERVE',
  'RESOURCE_EXTRACTION',
  'MANUFACTURING_OUTPUT',
];
const VOLUME_FACTS: readonly FactType[] = ['WATER_PRODUCTION', 'WATER_AVAILABILITY'];
const COMPUTE_FACTS: readonly FactType[] = ['COMPUTE_CAPACITY', 'COMPUTE_USAGE'];
const ITEM_FACTS: readonly FactType[] = [
  'MANUFACTURING_OUTPUT',
  'MANUFACTURING_CAPACITY',
  'DELIVERY_COMPLETION',
  'SERVICE_DELIVERY',
];

function define(input: {
  readonly unitId: string;
  readonly symbol: string;
  readonly dimension: MeasurementDimension;
  readonly canonicalBaseUnit: string;
  readonly scaleNumerator: bigint;
  readonly scaleDenominator?: bigint;
  readonly semanticQualifier?: SemanticQualifier;
  readonly aliases?: readonly string[];
  readonly deprecatedAliases?: readonly string[];
  readonly requiresContext?: boolean;
  readonly contextRequirements?: readonly ContextRequirement[];
  readonly allowedFactTypes?: readonly FactType[];
  readonly allowedProductiveCategories?: readonly ProductiveCategory[];
}): CanonicalUnitDefinition {
  if (input.scaleNumerator <= 0n || (input.scaleDenominator ?? 1n) <= 0n) {
    throw new Error(`unit ${input.unitId} must use a positive rational scale`);
  }
  return Object.freeze({
    unitId: input.unitId,
    symbol: input.symbol,
    dimension: input.dimension,
    canonicalBaseUnit: input.canonicalBaseUnit,
    scaleNumerator: input.scaleNumerator,
    scaleDenominator: input.scaleDenominator ?? 1n,
    semanticQualifier: input.semanticQualifier ?? 'UNQUALIFIED',
    aliases: Object.freeze([...(input.aliases ?? [])]),
    deprecatedAliases: Object.freeze([...(input.deprecatedAliases ?? [])]),
    requiresContext: input.requiresContext ?? false,
    contextRequirements: Object.freeze([...(input.contextRequirements ?? [])]),
    allowedFactTypes: Object.freeze([...(input.allowedFactTypes ?? [])]),
    allowedProductiveCategories: Object.freeze([...(input.allowedProductiveCategories ?? [])]),
  });
}

export const CANONICAL_UNIT_DEFINITIONS: readonly CanonicalUnitDefinition[] = Object.freeze([
  define({
    unitId: 'Wh',
    symbol: 'Wh',
    dimension: 'ENERGY',
    canonicalBaseUnit: 'Wh',
    scaleNumerator: 1n,
    allowedFactTypes: ENERGY_FACTS,
    allowedProductiveCategories: ['ENERGY'],
  }),
  define({
    unitId: 'kWh',
    symbol: 'kWh',
    dimension: 'ENERGY',
    canonicalBaseUnit: 'Wh',
    scaleNumerator: 1_000n,
    allowedFactTypes: ENERGY_FACTS,
    allowedProductiveCategories: ['ENERGY'],
  }),
  define({
    unitId: 'MWh',
    symbol: 'MWh',
    dimension: 'ENERGY',
    canonicalBaseUnit: 'Wh',
    scaleNumerator: 1_000_000n,
    allowedFactTypes: ENERGY_FACTS,
    allowedProductiveCategories: ['ENERGY'],
  }),
  define({
    unitId: 'g',
    symbol: 'g',
    dimension: 'MASS',
    canonicalBaseUnit: 'g',
    scaleNumerator: 1n,
    allowedFactTypes: MASS_FACTS,
    allowedProductiveCategories: ['FOOD_AGRICULTURE', 'MINERALS_RAW_MATERIALS'],
  }),
  define({
    unitId: 'kg',
    symbol: 'kg',
    dimension: 'MASS',
    canonicalBaseUnit: 'g',
    scaleNumerator: 1_000n,
    allowedFactTypes: MASS_FACTS,
    allowedProductiveCategories: ['FOOD_AGRICULTURE', 'MINERALS_RAW_MATERIALS', 'MANUFACTURING'],
  }),
  define({
    unitId: 'tonne',
    symbol: 't',
    dimension: 'MASS',
    canonicalBaseUnit: 'g',
    scaleNumerator: 1_000_000n,
    aliases: ['t'],
    allowedFactTypes: MASS_FACTS,
    allowedProductiveCategories: ['FOOD_AGRICULTURE', 'MINERALS_RAW_MATERIALS'],
  }),
  define({
    unitId: 'L',
    symbol: 'L',
    dimension: 'VOLUME',
    canonicalBaseUnit: 'L',
    scaleNumerator: 1n,
    allowedFactTypes: VOLUME_FACTS,
    allowedProductiveCategories: ['WATER'],
  }),
  define({
    unitId: 'm3',
    symbol: 'm3',
    dimension: 'VOLUME',
    canonicalBaseUnit: 'L',
    scaleNumerator: 1_000n,
    requiresContext: true,
    contextRequirements: ['DURATION'],
    allowedFactTypes: [...VOLUME_FACTS, 'STORAGE_CAPACITY'],
    allowedProductiveCategories: ['WATER', 'STORAGE'],
  }),
  define({
    unitId: 'm2',
    symbol: 'm2',
    dimension: 'AREA',
    canonicalBaseUnit: 'm2',
    scaleNumerator: 1n,
    requiresContext: true,
    contextRequirements: ['DURATION'],
    allowedFactTypes: ['REAL_ESTATE_USE_CAPACITY'],
    allowedProductiveCategories: ['REAL_ESTATE_USE'],
  }),
  define({
    unitId: 'm2_s',
    symbol: 'm2·s',
    dimension: 'AREA_TIME',
    canonicalBaseUnit: 'm2_s',
    scaleNumerator: 1n,
    allowedProductiveCategories: ['REAL_ESTATE_USE'],
  }),
  define({
    unitId: 'm2_hour',
    symbol: 'm2·h',
    dimension: 'AREA_TIME',
    canonicalBaseUnit: 'm2_s',
    scaleNumerator: 3_600n,
    allowedProductiveCategories: ['REAL_ESTATE_USE'],
  }),
  define({
    unitId: 'L_s',
    symbol: 'L·s',
    dimension: 'VOLUME_TIME',
    canonicalBaseUnit: 'L_s',
    scaleNumerator: 1n,
    allowedProductiveCategories: ['STORAGE', 'WATER'],
  }),
  define({
    unitId: 'm3_s',
    symbol: 'm3·s',
    dimension: 'VOLUME_TIME',
    canonicalBaseUnit: 'L_s',
    scaleNumerator: 1_000n,
    allowedProductiveCategories: ['STORAGE'],
  }),
  define({
    unitId: 'm3_hour',
    symbol: 'm3·h',
    dimension: 'VOLUME_TIME',
    canonicalBaseUnit: 'L_s',
    scaleNumerator: 3_600_000n,
    allowedProductiveCategories: ['STORAGE'],
  }),
  define({
    unitId: 'gpu_s',
    symbol: 'GPU·s',
    dimension: 'GPU_TIME',
    canonicalBaseUnit: 'gpu_s',
    scaleNumerator: 1n,
    aliases: ['GPU_SECOND'],
    allowedFactTypes: [...COMPUTE_FACTS, 'AI_INFERENCE_USAGE', 'AI_TRAINING_USAGE', 'AI_COMPUTE_CAPACITY'],
    allowedProductiveCategories: ['COMPUTE', 'AI_COMPUTE'],
  }),
  define({
    unitId: 'GPU_HOUR',
    symbol: 'GPU·h',
    dimension: 'GPU_TIME',
    canonicalBaseUnit: 'gpu_s',
    scaleNumerator: 3_600n,
    allowedFactTypes: [...COMPUTE_FACTS, 'AI_INFERENCE_USAGE', 'AI_TRAINING_USAGE', 'AI_COMPUTE_CAPACITY'],
    allowedProductiveCategories: ['COMPUTE', 'AI_COMPUTE'],
  }),
  define({
    unitId: 'cpu_s',
    symbol: 'CPU·s',
    dimension: 'CPU_TIME',
    canonicalBaseUnit: 'cpu_s',
    scaleNumerator: 1n,
    allowedFactTypes: COMPUTE_FACTS,
    allowedProductiveCategories: ['COMPUTE'],
  }),
  define({
    unitId: 'CPU_HOUR',
    symbol: 'CPU·h',
    dimension: 'CPU_TIME',
    canonicalBaseUnit: 'cpu_s',
    scaleNumerator: 3_600n,
    allowedFactTypes: COMPUTE_FACTS,
    allowedProductiveCategories: ['COMPUTE'],
  }),
  define({
    unitId: 'compute_s',
    symbol: 'compute·s',
    dimension: 'GENERIC_COMPUTE_TIME',
    canonicalBaseUnit: 'compute_s',
    scaleNumerator: 1n,
    requiresContext: true,
    contextRequirements: ['RESOURCE_CLASS'],
    allowedFactTypes: COMPUTE_FACTS,
    allowedProductiveCategories: ['COMPUTE'],
  }),
  define({
    unitId: 'token_inference',
    symbol: 'tok_inf',
    dimension: 'AI_TOKEN_COUNT',
    canonicalBaseUnit: 'TOKEN',
    scaleNumerator: 1n,
    semanticQualifier: 'INFERENCE_PROCESSED_TOKENS',
    aliases: ['TOKEN'],
    allowedFactTypes: ['AI_INFERENCE_USAGE'],
    allowedProductiveCategories: ['AI_COMPUTE'],
  }),
  define({
    unitId: 'TOKEN',
    symbol: 'tok',
    dimension: 'AI_TOKEN_COUNT',
    canonicalBaseUnit: 'TOKEN',
    scaleNumerator: 1n,
    semanticQualifier: 'INFERENCE_PROCESSED_TOKENS',
    aliases: ['token_inference'],
    allowedFactTypes: ['AI_INFERENCE_USAGE'],
    allowedProductiveCategories: ['AI_COMPUTE'],
  }),
  define({
    unitId: 'machine_s',
    symbol: 'machine·s',
    dimension: 'MACHINE_TIME',
    canonicalBaseUnit: 'machine_s',
    scaleNumerator: 1n,
    semanticQualifier: 'MACHINE_USAGE',
    allowedFactTypes: ['MANUFACTURING_CAPACITY', 'SERVICE_DELIVERY'],
    allowedProductiveCategories: ['MANUFACTURING', 'SERVICES', 'INFRASTRUCTURE'],
  }),
  define({
    unitId: 'machine_h',
    symbol: 'machine·h',
    dimension: 'MACHINE_TIME',
    canonicalBaseUnit: 'machine_s',
    scaleNumerator: 3_600n,
    semanticQualifier: 'MACHINE_USAGE',
    allowedFactTypes: ['MANUFACTURING_CAPACITY', 'SERVICE_DELIVERY'],
    allowedProductiveCategories: ['MANUFACTURING', 'SERVICES', 'INFRASTRUCTURE'],
  }),
  define({
    unitId: 'units_produced',
    symbol: 'units',
    dimension: 'ITEM_COUNT',
    canonicalBaseUnit: 'UNIT',
    scaleNumerator: 1n,
    semanticQualifier: 'ITEM_OUTPUT',
    aliases: ['UNIT'],
    allowedFactTypes: ITEM_FACTS,
    allowedProductiveCategories: ['MANUFACTURING', 'GOODS', 'AUTOMATED_MACHINE_OUTPUT'],
  }),
  define({
    unitId: 'UNIT',
    symbol: 'unit',
    dimension: 'ITEM_COUNT',
    canonicalBaseUnit: 'UNIT',
    scaleNumerator: 1n,
    semanticQualifier: 'ITEM_OUTPUT',
    aliases: ['units_produced'],
    allowedFactTypes: ITEM_FACTS,
    allowedProductiveCategories: ['MANUFACTURING', 'GOODS', 'AUTOMATED_MACHINE_OUTPUT'],
  }),
  define({
    unitId: 't_km',
    symbol: 't·km',
    dimension: 'MASS_DISTANCE',
    canonicalBaseUnit: 't_km',
    scaleNumerator: 1n,
    aliases: ['tonne_km'],
    allowedFactTypes: ['LOGISTICS_CAPACITY'],
    allowedProductiveCategories: ['LOGISTICS_TRANSPORTATION'],
  }),
  define({
    unitId: 'tonne_km',
    symbol: 't·km',
    dimension: 'MASS_DISTANCE',
    canonicalBaseUnit: 't_km',
    scaleNumerator: 1n,
    aliases: ['t_km'],
    allowedFactTypes: ['LOGISTICS_CAPACITY'],
    allowedProductiveCategories: ['LOGISTICS_TRANSPORTATION'],
  }),
  define({
    unitId: 'B',
    symbol: 'B',
    dimension: 'DATA_VOLUME',
    canonicalBaseUnit: 'B',
    scaleNumerator: 1n,
    allowedFactTypes: ['STORAGE_CAPACITY', 'BANDWIDTH_USAGE'],
    allowedProductiveCategories: ['BANDWIDTH_COMMUNICATIONS'],
  }),
  define({
    unitId: 'MB',
    symbol: 'MB',
    dimension: 'DATA_VOLUME',
    canonicalBaseUnit: 'B',
    scaleNumerator: 1_000_000n,
    allowedFactTypes: ['STORAGE_CAPACITY', 'BANDWIDTH_USAGE'],
    allowedProductiveCategories: ['BANDWIDTH_COMMUNICATIONS'],
  }),
  define({
    unitId: 'GB',
    symbol: 'GB',
    dimension: 'DATA_VOLUME',
    canonicalBaseUnit: 'B',
    scaleNumerator: 1_000_000_000n,
    allowedFactTypes: ['STORAGE_CAPACITY', 'BANDWIDTH_USAGE', 'BANDWIDTH_CAPACITY'],
    allowedProductiveCategories: ['BANDWIDTH_COMMUNICATIONS'],
  }),
  define({
    unitId: 'TB',
    symbol: 'TB',
    dimension: 'DATA_VOLUME',
    canonicalBaseUnit: 'B',
    scaleNumerator: 1_000_000_000_000n,
    allowedFactTypes: ['STORAGE_CAPACITY'],
    allowedProductiveCategories: ['BANDWIDTH_COMMUNICATIONS'],
  }),
  define({
    unitId: 'B_s',
    symbol: 'B/s',
    dimension: 'DATA_RATE',
    canonicalBaseUnit: 'B_s',
    scaleNumerator: 1n,
    requiresContext: true,
    contextRequirements: ['DURATION'],
    allowedFactTypes: ['BANDWIDTH_CAPACITY', 'BANDWIDTH_USAGE'],
    allowedProductiveCategories: ['BANDWIDTH_COMMUNICATIONS'],
  }),
  define({
    unitId: 'GB_s',
    symbol: 'GB/s',
    dimension: 'DATA_RATE',
    canonicalBaseUnit: 'B_s',
    scaleNumerator: 1_000_000_000n,
    requiresContext: true,
    contextRequirements: ['DURATION'],
    allowedFactTypes: ['BANDWIDTH_CAPACITY', 'BANDWIDTH_USAGE'],
    allowedProductiveCategories: ['BANDWIDTH_COMMUNICATIONS'],
  }),
  define({
    unitId: 'facility_hour',
    symbol: 'fac·h',
    dimension: 'FACILITY_TIME',
    canonicalBaseUnit: 'facility_hour',
    scaleNumerator: 1n,
    allowedProductiveCategories: ['INFRASTRUCTURE'],
  }),
  define({
    unitId: 'service_hour',
    symbol: 'svc·h',
    dimension: 'SERVICE_TIME',
    canonicalBaseUnit: 'service_hour',
    scaleNumerator: 1n,
    allowedFactTypes: ['SERVICE_DELIVERY'],
    allowedProductiveCategories: ['SERVICES'],
  }),
]);

export function isMeasurementDimension(value: string): value is MeasurementDimension {
  return CANONICAL_UNIT_DEFINITIONS.some((definition) => definition.dimension === value);
}
