/**
 * Wave 7 — canonical privileged-operation matrix.
 *
 * Maps every consequential administrative action to required roles,
 * assurance, key roles, approval model, and audit requirements.
 * Thresholds remain governed configuration; this catalog does not
 * invent business rules.
 */

import type { KeyRole } from './key-classification.ts';

export const PRIVILEGED_OPERATION_CATEGORIES = [
  'PROVIDER',
  'POLICY',
  'RIGHTS',
  'IDENTITY',
  'ADMIN_ROLE',
  'FEATURE_FLAG',
  'VALIDATOR',
  'KEY_ACCESS',
  'TRANSACTION_SIGNING',
  'GOVERNANCE',
  'MAINNET',
  'ISSUANCE',
  'MONETARY',
] as const;

export type PrivilegedOperationCategory = (typeof PRIVILEGED_OPERATION_CATEGORIES)[number];

export const APPROVAL_MODELS = [
  'SINGLE_ADMIN',
  'DUAL_CONTROL',
  'MULTI_PARTY_GOVERNANCE',
  'CEREMONY_ONLY',
  'NOT_PERMITTED',
] as const;

export type ApprovalModel = (typeof APPROVAL_MODELS)[number];

export type PrivilegedOperation = {
  readonly operationId: string;
  readonly category: PrivilegedOperationCategory;
  readonly description: string;
  readonly owner: string;
  readonly approvalModel: ApprovalModel;
  readonly requiredRoles: readonly string[];
  readonly stepUpRequired: boolean;
  readonly keyRole: KeyRole | null;
  readonly bypassesMonetaryControl: false;
  readonly auditKind: string;
  readonly evidenceRequired: boolean;
};

export const PRIVILEGED_OPERATIONS: readonly PrivilegedOperation[] = Object.freeze([
  {
    operationId: 'provider.enable',
    category: 'PROVIDER',
    description: 'Enable a provider in the activation registry',
    owner: 'packages/provider-sdk',
    approvalModel: 'DUAL_CONTROL',
    requiredRoles: ['ADMIN_SRE', 'ADMIN_PLATFORM'],
    stepUpRequired: true,
    keyRole: 'SERVICE_KEY',
    bypassesMonetaryControl: false,
    auditKind: 'privileged.provider.enable',
    evidenceRequired: true,
  },
  {
    operationId: 'provider.disable',
    category: 'PROVIDER',
    description: 'Kill-switch disable a provider',
    owner: 'packages/kernel/src/operations',
    approvalModel: 'DUAL_CONTROL',
    requiredRoles: ['ADMIN_SRE', 'ADMIN_SECURITY'],
    stepUpRequired: true,
    keyRole: null,
    bypassesMonetaryControl: false,
    auditKind: 'privileged.provider.disable',
    evidenceRequired: true,
  },
  {
    operationId: 'provider.configure',
    category: 'PROVIDER',
    description: 'Change provider trust or configuration',
    owner: 'packages/kernel/src/operations',
    approvalModel: 'DUAL_CONTROL',
    requiredRoles: ['ADMIN_SRE', 'ADMIN_PLATFORM'],
    stepUpRequired: true,
    keyRole: 'SERVICE_KEY',
    bypassesMonetaryControl: false,
    auditKind: 'privileged.provider.configure',
    evidenceRequired: true,
  },
  {
    operationId: 'policy.activate',
    category: 'POLICY',
    description: 'Activate a jurisdiction policy pack',
    owner: 'packages/kernel/src/policy',
    approvalModel: 'DUAL_CONTROL',
    requiredRoles: ['ADMIN_COMPLIANCE_APPROVE', 'ADMIN_COMPLIANCE'],
    stepUpRequired: true,
    keyRole: null,
    bypassesMonetaryControl: false,
    auditKind: 'privileged.policy.activate',
    evidenceRequired: true,
  },
  {
    operationId: 'policy.retire',
    category: 'POLICY',
    description: 'Retire a jurisdiction policy pack',
    owner: 'packages/kernel/src/policy',
    approvalModel: 'DUAL_CONTROL',
    requiredRoles: ['ADMIN_COMPLIANCE_APPROVE'],
    stepUpRequired: true,
    keyRole: null,
    bypassesMonetaryControl: false,
    auditKind: 'privileged.policy.retire',
    evidenceRequired: true,
  },
  {
    operationId: 'rights.commit',
    category: 'RIGHTS',
    description: 'Commit an access right on chain',
    owner: 'packages/sunrey-chain/src/access',
    approvalModel: 'SINGLE_ADMIN',
    requiredRoles: ['ADMIN_PLATFORM'],
    stepUpRequired: true,
    keyRole: null,
    bypassesMonetaryControl: false,
    auditKind: 'privileged.rights.commit',
    evidenceRequired: true,
  },
  {
    operationId: 'rights.revoke',
    category: 'RIGHTS',
    description: 'Revoke an access right',
    owner: 'packages/sunrey-chain/src/access',
    approvalModel: 'DUAL_CONTROL',
    requiredRoles: ['ADMIN_PLATFORM', 'ADMIN_COMPLIANCE'],
    stepUpRequired: true,
    keyRole: null,
    bypassesMonetaryControl: false,
    auditKind: 'privileged.rights.revoke',
    evidenceRequired: true,
  },
  {
    operationId: 'identity.suspend',
    category: 'IDENTITY',
    description: 'Suspend a person identity',
    owner: 'packages/identity',
    approvalModel: 'SINGLE_ADMIN',
    requiredRoles: ['ADMIN_COMPLIANCE', 'ADMIN_FRAUD'],
    stepUpRequired: true,
    keyRole: null,
    bypassesMonetaryControl: false,
    auditKind: 'privileged.identity.suspend',
    evidenceRequired: true,
  },
  {
    operationId: 'identity.recovery_override',
    category: 'IDENTITY',
    description: 'Override identity recovery controls',
    owner: 'packages/identity',
    approvalModel: 'DUAL_CONTROL',
    requiredRoles: ['ADMIN_COMPLIANCE_APPROVE', 'ADMIN_SECURITY'],
    stepUpRequired: true,
    keyRole: 'ADMIN_AUTHENTICATION_CREDENTIAL',
    bypassesMonetaryControl: false,
    auditKind: 'privileged.identity.recovery_override',
    evidenceRequired: true,
  },
  {
    operationId: 'admin_role.grant',
    category: 'ADMIN_ROLE',
    description: 'Grant a staff capability to an identity',
    owner: 'packages/identity',
    approvalModel: 'DUAL_CONTROL',
    requiredRoles: ['ADMIN_SECURITY', 'ADMIN_COMPLIANCE_APPROVE'],
    stepUpRequired: true,
    keyRole: 'ADMIN_AUTHENTICATION_CREDENTIAL',
    bypassesMonetaryControl: false,
    auditKind: 'privileged.admin_role.grant',
    evidenceRequired: true,
  },
  {
    operationId: 'admin_role.revoke',
    category: 'ADMIN_ROLE',
    description: 'Revoke a staff capability',
    owner: 'packages/identity',
    approvalModel: 'DUAL_CONTROL',
    requiredRoles: ['ADMIN_SECURITY'],
    stepUpRequired: true,
    keyRole: null,
    bypassesMonetaryControl: false,
    auditKind: 'privileged.admin_role.revoke',
    evidenceRequired: true,
  },
  {
    operationId: 'feature_flag.runtime_toggle',
    category: 'FEATURE_FLAG',
    description: 'Runtime toggle of LIVE_* or ENVIRONMENT flags',
    owner: 'packages/config',
    approvalModel: 'NOT_PERMITTED',
    requiredRoles: [],
    stepUpRequired: false,
    keyRole: null,
    bypassesMonetaryControl: false,
    auditKind: 'privileged.feature_flag.denied',
    evidenceRequired: true,
  },
  {
    operationId: 'feature_flag.staged_activation',
    category: 'FEATURE_FLAG',
    description: 'Staged capability activation rehearsal',
    owner: 'packages/sunrey-chain/src/post-genesis/staged-activation',
    approvalModel: 'MULTI_PARTY_GOVERNANCE',
    requiredRoles: ['PROTOCOL_GOVERNANCE', 'SECURITY_GOVERNANCE', 'RELEASE_GOVERNANCE'],
    stepUpRequired: true,
    keyRole: 'GOVERNANCE_SIGNING_KEY',
    bypassesMonetaryControl: false,
    auditKind: 'privileged.feature_flag.staged',
    evidenceRequired: true,
  },
  {
    operationId: 'validator.set_change',
    category: 'VALIDATOR',
    description: 'Change the active validator set',
    owner: 'packages/sunrey-chain/src/validators',
    approvalModel: 'MULTI_PARTY_GOVERNANCE',
    requiredRoles: ['VALIDATOR_GOVERNANCE', 'PROTOCOL_GOVERNANCE'],
    stepUpRequired: true,
    keyRole: 'VALIDATOR_KEY',
    bypassesMonetaryControl: false,
    auditKind: 'privileged.validator.set_change',
    evidenceRequired: true,
  },
  {
    operationId: 'validator.key_rotate',
    category: 'VALIDATOR',
    description: 'Rotate a validator consensus key',
    owner: 'packages/sunrey-chain/src/validators',
    approvalModel: 'CEREMONY_ONLY',
    requiredRoles: ['VALIDATOR_GOVERNANCE'],
    stepUpRequired: true,
    keyRole: 'VALIDATOR_KEY',
    bypassesMonetaryControl: false,
    auditKind: 'privileged.validator.key_rotate',
    evidenceRequired: true,
  },
  {
    operationId: 'key.access',
    category: 'KEY_ACCESS',
    description: 'Access a high-value signing key handle',
    owner: 'packages/security',
    approvalModel: 'CEREMONY_ONLY',
    requiredRoles: ['SECURITY_GOVERNANCE'],
    stepUpRequired: true,
    keyRole: null,
    bypassesMonetaryControl: false,
    auditKind: 'privileged.key.access',
    evidenceRequired: true,
  },
  {
    operationId: 'transaction.sign_user',
    category: 'TRANSACTION_SIGNING',
    description: 'Sign a user custody transaction',
    owner: 'packages/custody',
    approvalModel: 'SINGLE_ADMIN',
    requiredRoles: ['CUSTODY_OPERATOR'],
    stepUpRequired: false,
    keyRole: 'USER_WALLET_KEY',
    bypassesMonetaryControl: false,
    auditKind: 'privileged.transaction.sign_user',
    evidenceRequired: true,
  },
  {
    operationId: 'transaction.sign_validator',
    category: 'TRANSACTION_SIGNING',
    description: 'Sign a validator consensus message',
    owner: 'packages/sunrey-chain/src/validators',
    approvalModel: 'NOT_PERMITTED',
    requiredRoles: ['VALIDATOR_SIGNER'],
    stepUpRequired: false,
    keyRole: 'VALIDATOR_KEY',
    bypassesMonetaryControl: false,
    auditKind: 'privileged.transaction.sign_validator',
    evidenceRequired: true,
  },
  {
    operationId: 'governance.approve',
    category: 'GOVERNANCE',
    description: 'Approve a governance operation package',
    owner: 'packages/sunrey-chain/src/governance-ops',
    approvalModel: 'MULTI_PARTY_GOVERNANCE',
    requiredRoles: ['PROTOCOL_GOVERNANCE', 'SECURITY_GOVERNANCE', 'ECONOMIC_GOVERNANCE'],
    stepUpRequired: true,
    keyRole: 'GOVERNANCE_SIGNING_KEY',
    bypassesMonetaryControl: false,
    auditKind: 'privileged.governance.approve',
    evidenceRequired: true,
  },
  {
    operationId: 'governance.activate_package',
    category: 'GOVERNANCE',
    description: 'Activate an approved governance package',
    owner: 'packages/sunrey-chain/src/governance-ops',
    approvalModel: 'MULTI_PARTY_GOVERNANCE',
    requiredRoles: ['PROTOCOL_GOVERNANCE', 'RELEASE_GOVERNANCE'],
    stepUpRequired: true,
    keyRole: 'GOVERNANCE_SIGNING_KEY',
    bypassesMonetaryControl: false,
    auditKind: 'privileged.governance.activate',
    evidenceRequired: true,
  },
  {
    operationId: 'mainnet.activate',
    category: 'MAINNET',
    description: 'Activate mainnet',
    owner: 'packages/sunrey-chain/src/release-candidate/mainnet',
    approvalModel: 'CEREMONY_ONLY',
    requiredRoles: ['GENESIS_AUTHORITY', 'PROTOCOL_GOVERNANCE', 'SECURITY_GOVERNANCE', 'RELEASE_GOVERNANCE'],
    stepUpRequired: true,
    keyRole: 'GOVERNANCE_SIGNING_KEY',
    bypassesMonetaryControl: false,
    auditKind: 'privileged.mainnet.activate',
    evidenceRequired: true,
  },
  {
    operationId: 'issuance.sunrey.activate',
    category: 'ISSUANCE',
    description: 'Activate SunRey production issuance',
    owner: 'packages/sunrey-chain/src/economics/production-activation',
    approvalModel: 'MULTI_PARTY_GOVERNANCE',
    requiredRoles: ['ECONOMIC_GOVERNANCE', 'PROTOCOL_GOVERNANCE'],
    stepUpRequired: true,
    keyRole: 'GOVERNANCE_SIGNING_KEY',
    bypassesMonetaryControl: false,
    auditKind: 'privileged.issuance.sunrey',
    evidenceRequired: true,
  },
  {
    operationId: 'issuance.moonrey.activate',
    category: 'ISSUANCE',
    description: 'Activate MoonRey production issuance',
    owner: 'packages/sunrey-chain/src/economics/production-activation',
    approvalModel: 'MULTI_PARTY_GOVERNANCE',
    requiredRoles: ['ECONOMIC_GOVERNANCE', 'PROTOCOL_GOVERNANCE'],
    stepUpRequired: true,
    keyRole: 'GOVERNANCE_SIGNING_KEY',
    bypassesMonetaryControl: false,
    auditKind: 'privileged.issuance.moonrey',
    evidenceRequired: true,
  },
  {
    operationId: 'monetary.parameter_change',
    category: 'MONETARY',
    description: 'Change a production economic parameter',
    owner: 'packages/sunrey-chain/src/economics/production-activation/parameter-package',
    approvalModel: 'MULTI_PARTY_GOVERNANCE',
    requiredRoles: ['ECONOMIC_GOVERNANCE'],
    stepUpRequired: true,
    keyRole: 'GOVERNANCE_SIGNING_KEY',
    bypassesMonetaryControl: false,
    auditKind: 'privileged.monetary.parameter',
    evidenceRequired: true,
  },
  {
    operationId: 'circuit_breaker.release',
    category: 'FEATURE_FLAG',
    description: 'Release a domain circuit-breaker after incident',
    owner: 'packages/sunrey-chain/src/governance-ops/launch-abort',
    approvalModel: 'DUAL_CONTROL',
    requiredRoles: ['ADMIN_SECURITY', 'ADMIN_SRE'],
    stepUpRequired: true,
    keyRole: null,
    bypassesMonetaryControl: false,
    auditKind: 'privileged.circuit_breaker.release',
    evidenceRequired: true,
  },
  {
    operationId: 'break_glass.open',
    category: 'ADMIN_ROLE',
    description: 'Open a recorded break-glass session',
    owner: 'packages/security/src/productization/privileged',
    approvalModel: 'SINGLE_ADMIN',
    requiredRoles: ['BREAK_GLASS_OPERATOR'],
    stepUpRequired: true,
    keyRole: 'ADMIN_AUTHENTICATION_CREDENTIAL',
    bypassesMonetaryControl: false,
    auditKind: 'privileged.break_glass.open',
    evidenceRequired: true,
  },
]);

const BY_ID = new Map(PRIVILEGED_OPERATIONS.map((row) => [row.operationId, row]));

export function privilegedOperation(operationId: string): PrivilegedOperation | null {
  return BY_ID.get(operationId) ?? null;
}

export function privilegedOperationsByCategory(
  category: PrivilegedOperationCategory,
): readonly PrivilegedOperation[] {
  return PRIVILEGED_OPERATIONS.filter((row) => row.category === category);
}

export function privilegedOperationCount(): number {
  return PRIVILEGED_OPERATIONS.length;
}
