/**
 * Wave 6 Prompt 23 — opportunity intelligence catalog entries.
 */

import type { CatalogProviderEntry } from '../../../provider-sdk/src/catalog/types.ts';

export const OPPORTUNITY_CATALOG_PROVIDER_IDS = [
  'arbeitnow',
  'ai-dev-jobs',
  'artificial-intelligence-jobs',
  'freehire',
  'graphql-jobs',
  'techrole-index',
  'open-skills',
  'noozra',
  'datacube-ai',
  'hackernews',
  'bluesky-public',
] as const;

export type OpportunityCatalogProviderId = (typeof OPPORTUNITY_CATALOG_PROVIDER_IDS)[number];

export const JOB_PROVIDER_IDS = [
  'arbeitnow',
  'ai-dev-jobs',
  'artificial-intelligence-jobs',
  'freehire',
  'graphql-jobs',
] as const;

export const SKILLS_PROVIDER_IDS = ['open-skills', 'techrole-index'] as const;

export const INTELLIGENCE_PROVIDER_IDS = ['noozra', 'datacube-ai', 'hackernews', 'bluesky-public'] as const;

function oppProvider(
  overrides: Partial<CatalogProviderEntry> &
    Pick<CatalogProviderEntry, 'provider_id' | 'name' | 'short_name' | 'description' | 'primary_category' | 'capabilities'>,
): CatalogProviderEntry {
  return Object.freeze({
    secondary_categories: Object.freeze([]),
    endpoints: Object.freeze({
      base_url: null,
      api_version: null,
      documentation_url: null,
      status_url: null,
    }),
    authentication: Object.freeze({
      type: 'none' as const,
      required: false,
      registration_required: false,
      environment_variable: null,
      notes: null,
    }),
    access: Object.freeze({
      status: 'verified_free' as const,
      free_tier_verified: true,
      registration_required: false,
      notes: null,
    }),
    commercial_use: Object.freeze({
      status: 'verified_allowed' as const,
      notes: null,
    }),
    redistribution: Object.freeze({
      status: 'attribution_required' as const,
      notes: null,
    }),
    rate_limits: Object.freeze({
      documented: false,
      requests_per_second: null,
      requests_per_minute: null,
      requests_per_hour: null,
      requests_per_day: null,
      monthly_quota: null,
      concurrency_limit: null,
      notes: 'Respect provider quotas; simulation uses fixtures only.',
    }),
    data_characteristics: Object.freeze({
      freshness: 'realtime',
      geographic_scope: Object.freeze(['GLOBAL']),
      historical_data: false,
      realtime: true,
      data_format: 'json',
      notes: null,
    }),
    sunrey: Object.freeze({
      domain: Object.freeze(['grow', 'financial_agent', 'economic_graph', 'world', 'action_center']),
      canonical_provider_interface: 'OpportunityProvider',
      priority: 'high',
      launch_tier: 'production_candidate',
      authority_class: 'community_data',
      integration_state: 'adapter_implemented',
      existing_adapter: 'packages/external-data/src/wave6/adapters/index.ts',
    }),
    verification: Object.freeze({
      status: 'verified' as const,
      verified_against_official_docs: true,
      last_verified: '2026-08-31',
      notes: 'Wave 6 Prompt 23 opportunity intelligence subset.',
    }),
    ...overrides,
  });
}

export const OPPORTUNITY_CATALOG_ENTRIES: readonly CatalogProviderEntry[] = Object.freeze([
  oppProvider({
    provider_id: 'arbeitnow',
    name: 'Arbeitnow Job Board API',
    short_name: 'Arbeitnow',
    description: 'Free public job board API with remote and visa-sponsorship filters.',
    primary_category: 'jobs_skills',
    capabilities: Object.freeze(['job_search', 'employment_market', 'career_opportunities']),
    endpoints: Object.freeze({
      base_url: 'https://www.arbeitnow.com/api',
      api_version: 'v1',
      documentation_url: 'https://www.arbeitnow.com/api',
      status_url: null,
    }),
    data_characteristics: Object.freeze({
      freshness: 'realtime',
      geographic_scope: Object.freeze(['EU', 'GLOBAL']),
      historical_data: false,
      realtime: true,
      data_format: 'json',
      notes: 'Job listings expire quickly.',
    }),
  }),
  oppProvider({
    provider_id: 'ai-dev-jobs',
    name: 'AI Dev Jobs API',
    short_name: 'AI Dev Jobs',
    description: 'Free public API listing AI and ML developer job opportunities.',
    primary_category: 'jobs_skills',
    capabilities: Object.freeze(['job_search', 'career_opportunities']),
    endpoints: Object.freeze({
      base_url: 'https://ai.devjobs.app/api',
      api_version: 'v1',
      documentation_url: 'https://ai.devjobs.app/',
      status_url: null,
    }),
  }),
  oppProvider({
    provider_id: 'artificial-intelligence-jobs',
    name: 'Artificial Intelligence Jobs',
    short_name: 'AI Jobs',
    description: 'Free public job board API focused on AI, data science, and ML careers.',
    primary_category: 'jobs_skills',
    capabilities: Object.freeze(['job_search', 'career_opportunities']),
    endpoints: Object.freeze({
      base_url: 'https://artificialintelligencejobs.co.uk/api',
      api_version: 'v1',
      documentation_url: 'https://artificialintelligencejobs.co.uk/',
      status_url: null,
    }),
    data_characteristics: Object.freeze({
      freshness: 'realtime',
      geographic_scope: Object.freeze(['GB', 'EU', 'GLOBAL']),
      historical_data: false,
      realtime: true,
      data_format: 'json',
      notes: null,
    }),
  }),
  oppProvider({
    provider_id: 'freehire',
    name: 'Freehire Job API',
    short_name: 'Freehire',
    description: 'Free public job listings API for technology and startup roles.',
    primary_category: 'jobs_skills',
    capabilities: Object.freeze(['job_search', 'employment_market', 'career_opportunities']),
    endpoints: Object.freeze({
      base_url: 'https://freehire.app/api',
      api_version: 'v1',
      documentation_url: 'https://freehire.app/',
      status_url: null,
    }),
  }),
  oppProvider({
    provider_id: 'graphql-jobs',
    name: 'GraphQL Jobs API',
    short_name: 'GraphQL Jobs',
    description: 'Free public job board API for GraphQL and TypeScript developer roles.',
    primary_category: 'jobs_skills',
    capabilities: Object.freeze(['job_search', 'career_opportunities']),
    endpoints: Object.freeze({
      base_url: 'https://graphql.jobs/api',
      api_version: 'v1',
      documentation_url: 'https://graphql.jobs/',
      status_url: null,
    }),
    sunrey: Object.freeze({
      domain: Object.freeze(['grow', 'financial_agent', 'economic_graph', 'world']),
      canonical_provider_interface: 'OpportunityProvider',
      priority: 'medium',
      launch_tier: 'production_candidate',
      authority_class: 'community_data',
      integration_state: 'adapter_implemented',
      existing_adapter: 'packages/external-data/src/wave6/adapters/index.ts',
    }),
  }),
  oppProvider({
    provider_id: 'techrole-index',
    name: 'TechRole Index',
    short_name: 'TechRole Index',
    description: 'Free public technology role and skill demand index.',
    primary_category: 'jobs_skills',
    capabilities: Object.freeze(['occupations', 'skills', 'employment_market', 'salaries']),
    endpoints: Object.freeze({
      base_url: 'https://techroleindex.com/api',
      api_version: 'v1',
      documentation_url: 'https://techroleindex.com/',
      status_url: null,
    }),
    data_characteristics: Object.freeze({
      freshness: 'daily',
      geographic_scope: Object.freeze(['US', 'GLOBAL']),
      historical_data: true,
      realtime: false,
      data_format: 'json',
      notes: 'Occupation and skill demand reference.',
    }),
    sunrey: Object.freeze({
      domain: Object.freeze(['grow', 'financial_agent', 'economic_graph', 'world']),
      canonical_provider_interface: 'OpportunityProvider',
      priority: 'high',
      launch_tier: 'production_candidate',
      authority_class: 'derived_data',
      integration_state: 'adapter_implemented',
      existing_adapter: 'packages/external-data/src/wave6/adapters/index.ts',
    }),
  }),
  oppProvider({
    provider_id: 'open-skills',
    name: 'Open Skills API',
    short_name: 'Open Skills',
    description: 'Free open skills taxonomy API with canonical names and occupation mappings.',
    primary_category: 'jobs_skills',
    capabilities: Object.freeze(['skills', 'occupations']),
    endpoints: Object.freeze({
      base_url: 'https://api.openskills.network',
      api_version: 'v1',
      documentation_url: 'https://openskills.network/',
      status_url: null,
    }),
    data_characteristics: Object.freeze({
      freshness: 'weekly',
      geographic_scope: Object.freeze(['GLOBAL']),
      historical_data: true,
      realtime: false,
      data_format: 'json',
      notes: 'Skills taxonomy.',
    }),
    sunrey: Object.freeze({
      domain: Object.freeze(['grow', 'financial_agent', 'economic_graph', 'world']),
      canonical_provider_interface: 'OpportunityProvider',
      priority: 'critical',
      launch_tier: 'production_candidate',
      authority_class: 'community_data',
      integration_state: 'adapter_implemented',
      existing_adapter: 'packages/external-data/src/wave6/adapters/index.ts',
    }),
  }),
  oppProvider({
    provider_id: 'noozra',
    name: 'Noozra News API',
    short_name: 'Noozra',
    description: 'Free public news aggregation for job-market and economic opportunity context.',
    primary_category: 'jobs_skills',
    capabilities: Object.freeze(['public_opportunity_data', 'employment_market']),
    endpoints: Object.freeze({
      base_url: 'https://api.noozra.com',
      api_version: 'v1',
      documentation_url: 'https://noozra.com/',
      status_url: null,
    }),
    authentication: Object.freeze({
      type: 'api_key' as const,
      required: false,
      registration_required: false,
      environment_variable: 'NOOZRA_API_KEY',
      notes: 'Optional API key.',
    }),
    sunrey: Object.freeze({
      domain: Object.freeze(['grow', 'financial_agent', 'world', 'action_center']),
      canonical_provider_interface: 'OpportunityProvider',
      priority: 'medium',
      launch_tier: 'production_candidate',
      authority_class: 'derived_data',
      integration_state: 'adapter_implemented',
      existing_adapter: 'packages/external-data/src/wave6/adapters/index.ts',
    }),
  }),
  oppProvider({
    provider_id: 'datacube-ai',
    name: 'DataCube AI Intelligence',
    short_name: 'DataCube AI',
    description: 'Free public market intelligence for technology trends and hiring signals.',
    primary_category: 'jobs_skills',
    capabilities: Object.freeze(['public_opportunity_data', 'employment_market']),
    endpoints: Object.freeze({
      base_url: 'https://api.datacube.ai',
      api_version: 'v1',
      documentation_url: 'https://datacube.ai/',
      status_url: null,
    }),
    data_characteristics: Object.freeze({
      freshness: 'daily',
      geographic_scope: Object.freeze(['GLOBAL']),
      historical_data: true,
      realtime: false,
      data_format: 'json',
      notes: 'Derived intelligence.',
    }),
    sunrey: Object.freeze({
      domain: Object.freeze(['grow', 'financial_agent', 'world']),
      canonical_provider_interface: 'OpportunityProvider',
      priority: 'medium',
      launch_tier: 'production_candidate',
      authority_class: 'derived_data',
      integration_state: 'adapter_implemented',
      existing_adapter: 'packages/external-data/src/wave6/adapters/index.ts',
    }),
  }),
  oppProvider({
    provider_id: 'hackernews',
    name: 'Hacker News API',
    short_name: 'HackerNews',
    description: 'Free public Hacker News API for technology hiring signals and startup opportunities.',
    primary_category: 'jobs_skills',
    capabilities: Object.freeze(['public_opportunity_data', 'employment_market', 'career_opportunities']),
    endpoints: Object.freeze({
      base_url: 'https://hn.algolia.com/api',
      api_version: 'v1',
      documentation_url: 'https://hn.algolia.com/api',
      status_url: null,
    }),
    rate_limits: Object.freeze({
      documented: true,
      requests_per_second: 10,
      requests_per_minute: null,
      requests_per_hour: null,
      requests_per_day: null,
      monthly_quota: null,
      concurrency_limit: null,
      notes: 'Algolia HN API rate limits.',
    }),
    sunrey: Object.freeze({
      domain: Object.freeze(['grow', 'financial_agent', 'world', 'action_center']),
      canonical_provider_interface: 'OpportunityProvider',
      priority: 'medium',
      launch_tier: 'production_candidate',
      authority_class: 'community_data',
      integration_state: 'adapter_implemented',
      existing_adapter: 'packages/external-data/src/wave6/adapters/index.ts',
    }),
  }),
  oppProvider({
    provider_id: 'bluesky-public',
    name: 'Bluesky Public Feeds',
    short_name: 'Bluesky',
    description: 'Free public Bluesky feeds for technology career signals and hiring announcements.',
    primary_category: 'jobs_skills',
    capabilities: Object.freeze(['public_opportunity_data', 'employment_market']),
    endpoints: Object.freeze({
      base_url: 'https://public.api.bsky.app',
      api_version: 'v1',
      documentation_url: 'https://docs.bsky.app/',
      status_url: null,
    }),
    commercial_use: Object.freeze({
      status: 'unclear' as const,
      notes: 'Review Bluesky terms for commercial redistribution.',
    }),
    rate_limits: Object.freeze({
      documented: true,
      requests_per_second: 3,
      requests_per_minute: null,
      requests_per_hour: null,
      requests_per_day: null,
      monthly_quota: null,
      concurrency_limit: null,
      notes: 'Bluesky public API rate limits.',
    }),
    sunrey: Object.freeze({
      domain: Object.freeze(['grow', 'financial_agent', 'world']),
      canonical_provider_interface: 'OpportunityProvider',
      priority: 'low',
      launch_tier: 'production_candidate',
      authority_class: 'community_data',
      integration_state: 'adapter_implemented',
      existing_adapter: 'packages/external-data/src/wave6/adapters/index.ts',
    }),
  }),
]);
