/**
 * Wave 6 simulation fixtures — deterministic, bounded, no live HTTP.
 */

import type {
  AIEconomicObservation,
  AIModelObservation,
  HinReferenceObservation,
  KnowledgeEntity,
  OpportunityObservation,
  PatentObservation,
  ResearchWork,
} from './models.ts';

export const TIMEOUT_RESEARCH_PROVIDER = 'research-timeout-fixture';
export const MALFORMED_PATENT_PROVIDER = 'patent-malformed-fixture';
export const STALE_AI_PRICING_PROVIDER = 'ai-pricing-stale-fixture';

export const FIXTURE_RESEARCH_WORKS: readonly ResearchWork[] = Object.freeze([
  Object.freeze({
    workId: 'doi:10.1038/s41586-024-07000-1',
    title: 'Efficient transformer architectures for economic forecasting',
    abstract: 'We study bounded attention models for macro indicator prediction under simulation constraints.',
    authors: Object.freeze([
      Object.freeze({
        authorId: 'orcid:0000-0001-2345-6789',
        displayName: 'Ada Researcher',
        orcid: '0000-0001-2345-6789',
        providerNativeId: 'A1234567890',
        providerId: 'sec-edgar',
      }),
    ]),
    institutions: Object.freeze([
      Object.freeze({
        institutionId: 'inst:stanford-econ',
        name: 'Stanford Institute for Economic Policy Research',
        country: 'US',
        providerNativeId: '0000012345',
        providerId: 'sec-edgar',
      }),
    ]),
    publicationDate: '2024-06-15',
    venue: 'Nature (simulation fixture)',
    workType: 'CORPORATE_FILING' as const,
    doi: '10.1038/s41586-024-07000-1',
    externalIds: Object.freeze({ cik: '0000320193', accession: '0000320193-24-000001' }),
    topics: Object.freeze(['machine-learning', 'macroeconomics', 'finance']),
    citationsCount: 42,
    openAccessStatus: 'OPEN',
    sourceUrl: 'https://data.sec.gov/submissions/CIK0000320193.json',
    providerId: 'sec-edgar',
    freshness: 'fresh' as const,
    authorityClass: 'authoritative_official' as const,
    provenance: 'wave6-fixture:sec-edgar-research',
    grantsLegalConclusion: false as const,
  }),
  Object.freeze({
    workId: 'federal-register:2024-12345',
    title: 'Proposed rule on AI model transparency in financial services',
    abstract: 'Agency proposes disclosure requirements for automated decision systems used by regulated entities.',
    authors: Object.freeze([]),
    institutions: Object.freeze([
      Object.freeze({
        institutionId: 'inst:us-federal-register',
        name: 'National Archives and Records Administration',
        country: 'US',
        providerNativeId: 'NARA',
        providerId: 'federal-register',
      }),
    ]),
    publicationDate: '2024-08-01',
    venue: 'Federal Register',
    workType: 'REGULATORY_DOCUMENT' as const,
    doi: null,
    externalIds: Object.freeze({ document_number: '2024-12345' }),
    topics: Object.freeze(['artificial-intelligence', 'financial-regulation', 'compliance']),
    citationsCount: null,
    openAccessStatus: 'PUBLIC_DOMAIN',
    sourceUrl: 'https://www.federalregister.gov/documents/2024/12345',
    providerId: 'federal-register',
    freshness: 'fresh' as const,
    authorityClass: 'authoritative_official' as const,
    provenance: 'wave6-fixture:federal-register',
    grantsLegalConclusion: false as const,
  }),
  Object.freeze({
    workId: 'doi:10.1038/s41586-024-07000-1',
    title: 'Efficient transformer architectures for economic forecasting',
    abstract: 'Duplicate fixture entry for data-quality testing — same DOI, different provider context.',
    authors: Object.freeze([
      Object.freeze({
        authorId: 'orcid:0000-0001-2345-6789',
        displayName: 'Ada Researcher',
        orcid: '0000-0001-2345-6789',
        providerNativeId: 'W1234567890',
        providerId: 'co2-offset',
      }),
    ]),
    institutions: Object.freeze([]),
    publicationDate: '2024-06-15',
    venue: 'Environmental Research Letters (simulation)',
    workType: 'PREPRINT' as const,
    doi: '10.1038/s41586-024-07000-1',
    externalIds: Object.freeze({ openalex: 'W1234567890' }),
    topics: Object.freeze(['carbon-accounting', 'machine-learning']),
    citationsCount: 12,
    openAccessStatus: 'OPEN',
    sourceUrl: 'https://www.co2offset.io/projects/fixture-001',
    providerId: 'co2-offset',
    freshness: 'aging' as const,
    authorityClass: 'community_data' as const,
    provenance: 'wave6-fixture:co2-offset-research',
    grantsLegalConclusion: false as const,
  }),
]);

export const FIXTURE_PATENTS: readonly PatentObservation[] = Object.freeze([
  Object.freeze({
    patentId: 'US-20240123456-A1',
    applicationNumber: 'US-18/123456',
    publicationNumber: 'US-2024-0123456-A1',
    title: 'Method for bounded inference routing in financial agent systems',
    abstract: 'Systems and methods for policy-gated model selection without automatic production reconfiguration.',
    inventors: Object.freeze(['Jordan Inventor', 'Sam Engineer']),
    assignee: 'SunRey Simulation Labs',
    filingDate: '2023-11-01',
    publicationDate: '2024-05-15',
    grantDate: null,
    status: 'PUBLISHED' as const,
    jurisdiction: 'US',
    classificationCodes: Object.freeze(['G06N20/00', 'G06Q40/00']),
    citations: Object.freeze(['US-20230111111-A1']),
    sourceUrl: 'https://patents.example/sim/US20240123456',
    providerId: 'sec-edgar',
    freshness: 'fresh' as const,
    provenance: 'wave6-fixture:patent-landscape',
    grantsInfringementConclusion: false as const,
  }),
  Object.freeze({
    patentId: 'EP-2024-009876',
    applicationNumber: 'EP-24123456',
    publicationNumber: 'EP-2024-009876-A1',
    title: 'Distributed ledger settlement with compliance kernel gating',
    abstract: 'Fixture patent for jurisdiction identity testing.',
    inventors: Object.freeze(['Alex Builder']),
    assignee: 'Example Corp EU',
    filingDate: '2024-01-10',
    publicationDate: '2024-07-01',
    grantDate: null,
    status: 'PUBLISHED' as const,
    jurisdiction: 'EP',
    classificationCodes: Object.freeze(['G06Q20/38']),
    citations: Object.freeze([]),
    sourceUrl: 'https://patents.example/sim/EP2024009876',
    providerId: 'federal-register',
    freshness: 'fresh' as const,
    provenance: 'wave6-fixture:patent-landscape',
    grantsInfringementConclusion: false as const,
  }),
]);

export const FIXTURE_KNOWLEDGE_ENTITIES: readonly KnowledgeEntity[] = Object.freeze([
  Object.freeze({
    entityId: 'kg:technology:transformer-architecture',
    name: 'Transformer architecture',
    description: 'Neural network architecture using self-attention mechanisms.',
    entityType: 'TECHNOLOGY',
    aliases: Object.freeze(['transformer model', 'attention model']),
    properties: Object.freeze({ field: 'machine-learning' }),
    relationships: Object.freeze([
      Object.freeze({ relation: 'USED_IN', targetId: 'kg:domain:economic-forecasting' }),
    ]),
    provider: 'website-carbon',
    authorityClass: 'reference_data' as const,
    provenance: 'wave6-fixture:knowledge-graph',
    trustedSunReyFact: false as const,
  }),
]);

export const FIXTURE_AI_MODELS: readonly AIModelObservation[] = Object.freeze([
  Object.freeze({
    modelId: 's3m-primary-v1',
    providerName: 'SunRey AI Runtime',
    modelName: 'S3M Primary',
    modelFamily: 'S3M',
    contextWindow: 128_000,
    inputPricingMinor: 150n,
    outputPricingMinor: 600n,
    currency: 'USD',
    pricingUnit: 'per_1M_tokens',
    availability: 'AVAILABLE' as const,
    capabilities: Object.freeze(['structured_output', 'financial_reasoning']),
    observedAt: '2026-08-31T12:00:00.000Z',
    providerId: 'website-carbon',
    freshness: 'fresh' as const,
    provenance: 'wave6-fixture:ai-model-metadata',
    reconfiguresModelGateway: false as const,
  }),
  Object.freeze({
    modelId: 'generic-llm-preview',
    providerName: 'Generic Provider',
    modelName: 'Preview LLM',
    modelFamily: 'GPT-class',
    contextWindow: 32_000,
    inputPricingMinor: 500n,
    outputPricingMinor: 1500n,
    currency: 'USD',
    pricingUnit: 'per_1M_tokens',
    availability: 'PREVIEW' as const,
    capabilities: Object.freeze(['chat']),
    observedAt: '2026-08-20T12:00:00.000Z',
    providerId: STALE_AI_PRICING_PROVIDER,
    freshness: 'stale' as const,
    provenance: 'wave6-fixture:ai-model-metadata-stale',
    reconfiguresModelGateway: false as const,
  }),
]);

export const FIXTURE_AI_ECONOMICS: readonly AIEconomicObservation[] = Object.freeze([
  Object.freeze({
    observationId: 'ai-econ:token-cost:s3m-primary',
    metricType: 'TOKEN_COST' as const,
    value: 0.00015,
    unit: 'USD_per_1k_input_tokens',
    currency: 'USD',
    modelId: 's3m-primary-v1',
    observedAt: '2026-08-31T12:00:00.000Z',
    providerId: 'website-carbon',
    freshness: 'fresh' as const,
    provenance: 'wave6-fixture:ai-economics',
    mintsMoonRey: false as const,
  }),
  Object.freeze({
    observationId: 'ai-econ:compute-cost:gpu-hour',
    metricType: 'COMPUTE_COST' as const,
    value: 2.5,
    unit: 'USD_per_gpu_hour',
    currency: 'USD',
    modelId: null,
    observedAt: '2026-08-31T12:00:00.000Z',
    providerId: 'co2-offset',
    freshness: 'fresh' as const,
    provenance: 'wave6-fixture:compute-economics',
    mintsMoonRey: false as const,
  }),
]);

export const FIXTURE_HIN_REFERENCE: readonly HinReferenceObservation[] = Object.freeze([
  Object.freeze({
    referenceId: 'food:mandi:wheat:IN-KA',
    category: 'FOOD' as const,
    label: 'Wheat modal price — Karnataka mandi',
    value: '2450',
    unit: 'INR/quintal',
    jurisdiction: 'IN',
    dataset: 'mandi_prices',
    sourceAgency: 'Government of India',
    retrievedAt: '2026-08-31T12:00:00.000Z',
    sourceTimestamp: '2026-08-30T00:00:00.000Z',
    licensing: 'National Data Sharing and Accessibility Policy — attribution required',
    providerId: 'indian-mandi-prices',
    provenance: 'wave6-fixture:hin-food-reference',
    isPrivateUserData: false as const,
    infersHealthCondition: false as const,
  }),
  Object.freeze({
    referenceId: 'food:mandi:rice:IN-TN',
    category: 'FOOD' as const,
    label: 'Rice modal price — Tamil Nadu mandi',
    value: '3200',
    unit: 'INR/quintal',
    jurisdiction: 'IN',
    dataset: 'mandi_prices',
    sourceAgency: 'Government of India',
    retrievedAt: '2026-08-31T12:00:00.000Z',
    sourceTimestamp: '2026-08-30T00:00:00.000Z',
    licensing: 'National Data Sharing and Accessibility Policy — attribution required',
    providerId: 'indian-mandi-prices',
    provenance: 'wave6-fixture:hin-food-reference',
    isPrivateUserData: false as const,
    infersHealthCondition: false as const,
  }),
]);

export const FIXTURE_OPPORTUNITIES: readonly OpportunityObservation[] = Object.freeze([
  Object.freeze({
    opportunityId: 'job:sim:data-analyst-001',
    kind: 'JOB' as const,
    title: 'Junior Data Analyst — public sector economics',
    description: 'Analyze open macro datasets; no private health data required.',
    location: 'Remote / US',
    skills: Object.freeze(['python', 'statistics', 'data-visualization']),
    sourceUrl: 'https://jobs.example/sim/data-analyst-001',
    providerId: 'federal-register',
    retrievedAt: '2026-08-31T12:00:00.000Z',
    provenance: 'wave6-fixture:opportunity-service',
    submitsApplication: false as const,
    sharesPrivateProfile: false as const,
  }),
  Object.freeze({
    opportunityId: 'skill:sim:ml-engineering-101',
    kind: 'SKILL' as const,
    title: 'Machine learning engineering fundamentals',
    description: 'Learning path aligned with public research on transformer architectures.',
    location: null,
    skills: Object.freeze(['machine-learning', 'python', 'model-evaluation']),
    sourceUrl: 'https://learning.example/sim/ml-101',
    providerId: 'co2-offset',
    retrievedAt: '2026-08-31T12:00:00.000Z',
    provenance: 'wave6-fixture:opportunity-service',
    submitsApplication: false as const,
    sharesPrivateProfile: false as const,
  }),
]);

export const FIXTURE_AUTHOR_NAME_COLLISION = Object.freeze({
  authorA: Object.freeze({
    authorId: 'author:smith:0001',
    displayName: 'John Smith',
    orcid: null,
    providerNativeId: 'A-SMITH-001',
    providerId: 'sec-edgar',
  }),
  authorB: Object.freeze({
    authorId: 'author:smith:0002',
    displayName: 'John Smith',
    orcid: '0000-0002-9999-0001',
    providerNativeId: 'A-SMITH-002',
    providerId: 'federal-register',
  }),
});

export const MALFORMED_PATENT_JSON = '{ "patentId": "broken", "title": ';
