/**
 * Canonical event namespace / taxonomy.
 *
 * Implemented namespaces match functionality that exists on this tree.
 * Reserved namespaces are documented only — they do not invent product
 * behavior.
 */

export const IMPLEMENTED_EVENT_NAMESPACES = [
  'customer',
  'account',
  'ledger',
  'kernel',
  'evidence',
  'policy',
  'security',
  'identity',
  'payment',
  'fx',
  'banking',
  'compliance',
  'fraud',
  'rail',
  'card',
  'economic_graph',
  'wallet',
  'acceptance',
  'treasury',
] as const;

export const RESERVED_EVENT_NAMESPACES = [
  'investment',
  'agent',
  'consent',
  'data',
  'pyr',
  'exchange',
  'regulatory',
  'notification',
  'analytics',
] as const;

export type ImplementedEventNamespace = (typeof IMPLEMENTED_EVENT_NAMESPACES)[number];
export type ReservedEventNamespace = (typeof RESERVED_EVENT_NAMESPACES)[number];

export const EVENT_TYPE_NAMES = [
  'AccountOpened',
  'DepositPosted',
  'WithdrawalPosted',
  'InternalTransferPosted',
  'CustomerStatusChanged',
  'KernelDecisionRecorded',
  'PolicyPackActivated',
  'PolicyPackRetired',
  'PolicyReviewRequested',
  'PolicyReviewDecided',
  'KeyCreated',
  'KeyRotated',
  'KeyRetired',
  'KeyRevoked',
  'IdentityCreated',
  'IdentityActivated',
  'IdentitySuspended',
  'IdentityKycUpdated',
  'IdentitySessionCreated',
  'IdentitySessionRevoked',
  'IdentityDeviceRegistered',
  'IdentityDeviceTrustChanged',
  'IdentityRecoveryRequested',
  'BeneficiaryCreated',
  'PaymentInitiated',
  'PaymentHeld',
  'PaymentSubmitted',
  'PaymentSettled',
  'PaymentFailed',
  'PaymentReturned',
  'PaymentCancelled',
  'FxQuoteCreated',
  'FxQuoteAccepted',
  'FxQuoteExpired',
  'HoldCreated',
  'HoldReleased',
  'HoldCaptured',
  'HoldCancelled',
  'StatementGenerated',
  'ReconciliationMismatch',
  'AccountPositionChanged',
  'FeePosted',
  'InterestPosted',
  'ReversalPosted',
  'PendingSettlementInitiated',
  'PendingSettlementSettled',
  'PendingSettlementReturned',
  'ComplianceScreeningCompleted',
  'ComplianceScreeningReviewRequired',
  'ComplianceCaseOpened',
  'ComplianceCaseDecided',
  'ComplianceAlertCreated',
  'FraudRiskEvaluated',
  'RailSubmissionCreated',
  'RailSubmissionAccepted',
  'RailSubmissionUnknown',
  'RailPaymentProcessing',
  'RailPaymentSettled',
  'RailPaymentRejected',
  'RailPaymentReturned',
  'RailProviderDegraded',
  'RailReconciliationMismatch',
  'CardCreated',
  'CardActivated',
  'CardFrozen',
  'CardUnfrozen',
  'CardClosed',
  'CardAuthorizationApproved',
  'CardAuthorizationDeclined',
  'CardAuthorizationReversed',
  'CardClearingReceived',
  'CardTransactionSettled',
  'CardRefundReceived',
  'CardDisputeOpened',
  'CardDisputeDecided',
  'EconomicGraphNodeCreated',
  'EconomicGraphFactUpdated',
  'EconomicGraphRelationshipCreated',
  'EconomicGraphSnapshotCreated',
  'EconomicGraphOpportunityCreated',
  'WalletProvisioningRequested',
  'WalletProvisioningStepUpRequired',
  'WalletTokenActivated',
  'WalletTokenSuspended',
  'WalletTokenDeleted',
  'AcceptanceDeviceRegistered',
  'AcceptanceSessionCreated',
  'AcceptancePaymentApproved',
  'AcceptancePaymentDeclined',
  'AcceptancePaymentSettled',
  'AcceptanceReconciliationMismatch',
  'TreasuryLiquidityReserved',
  'TreasuryLiquidityReleased',
  'TreasuryLiquidityCommitted',
  'TreasuryRouteSelected',
  'TreasuryProviderRestricted',
  'TreasuryCorridorHalted',
  'TreasuryExposureElevated',
  'TreasuryRebalanceProposed',
  'TreasuryReconciliationMismatch',
] as const;

export type ImplementedEventTypeName = (typeof EVENT_TYPE_NAMES)[number];

export const EVENT_SCHEMA_REFS = {
  AccountOpened: 'solstice.account.opened/1',
  DepositPosted: 'solstice.ledger.deposit_posted/1',
  WithdrawalPosted: 'solstice.ledger.withdrawal_posted/1',
  InternalTransferPosted: 'solstice.ledger.internal_transfer_posted/1',
  CustomerStatusChanged: 'solstice.customer.status_changed/1',
  KernelDecisionRecorded: 'solstice.kernel.decision_recorded/1',
  PolicyPackActivated: 'solstice.policy.pack_activated/1',
  PolicyPackRetired: 'solstice.policy.pack_retired/1',
  PolicyReviewRequested: 'solstice.policy.review_requested/1',
  PolicyReviewDecided: 'solstice.policy.review_decided/1',
  KeyCreated: 'solstice.security.key_created/1',
  KeyRotated: 'solstice.security.key_rotated/1',
  KeyRetired: 'solstice.security.key_retired/1',
  KeyRevoked: 'solstice.security.key_revoked/1',
  IdentityCreated: 'solstice.identity.created/1',
  IdentityActivated: 'solstice.identity.activated/1',
  IdentitySuspended: 'solstice.identity.suspended/1',
  IdentityKycUpdated: 'solstice.identity.kyc.updated/1',
  IdentitySessionCreated: 'solstice.identity.session.created/1',
  IdentitySessionRevoked: 'solstice.identity.session.revoked/1',
  IdentityDeviceRegistered: 'solstice.identity.device.registered/1',
  IdentityDeviceTrustChanged: 'solstice.identity.device.trust_changed/1',
  IdentityRecoveryRequested: 'solstice.identity.recovery.requested/1',
  BeneficiaryCreated: 'solstice.payment.beneficiary.created/1',
  PaymentInitiated: 'solstice.payment.initiated/1',
  PaymentHeld: 'solstice.payment.held/1',
  PaymentSubmitted: 'solstice.payment.submitted/1',
  PaymentSettled: 'solstice.payment.settled/1',
  PaymentFailed: 'solstice.payment.failed/1',
  PaymentReturned: 'solstice.payment.returned/1',
  PaymentCancelled: 'solstice.payment.cancelled/1',
  FxQuoteCreated: 'solstice.fx.quote.created/1',
  FxQuoteAccepted: 'solstice.fx.quote.accepted/1',
  FxQuoteExpired: 'solstice.fx.quote.expired/1',
  HoldCreated: 'solstice.banking.hold.created/1',
  HoldReleased: 'solstice.banking.hold.released/1',
  HoldCaptured: 'solstice.banking.hold.captured/1',
  HoldCancelled: 'solstice.banking.hold.cancelled/1',
  StatementGenerated: 'solstice.banking.statement.generated/1',
  ReconciliationMismatch: 'solstice.banking.reconciliation.mismatch/1',
  AccountPositionChanged: 'solstice.account.position.changed/1',
  FeePosted: 'solstice.banking.fee.posted/1',
  InterestPosted: 'solstice.banking.interest.posted/1',
  ReversalPosted: 'solstice.banking.reversal.posted/1',
  PendingSettlementInitiated: 'solstice.banking.pending.initiated/1',
  PendingSettlementSettled: 'solstice.banking.pending.settled/1',
  PendingSettlementReturned: 'solstice.banking.pending.returned/1',
  ComplianceScreeningCompleted: 'solstice.compliance.screening.completed/1',
  ComplianceScreeningReviewRequired: 'solstice.compliance.screening.review_required/1',
  ComplianceCaseOpened: 'solstice.compliance.case.opened/1',
  ComplianceCaseDecided: 'solstice.compliance.case.decided/1',
  ComplianceAlertCreated: 'solstice.compliance.alert.created/1',
  FraudRiskEvaluated: 'solstice.fraud.risk.evaluated/1',
  RailSubmissionCreated: 'solstice.rail.submission.created/1',
  RailSubmissionAccepted: 'solstice.rail.submission.accepted/1',
  RailSubmissionUnknown: 'solstice.rail.submission.unknown/1',
  RailPaymentProcessing: 'solstice.rail.payment.processing/1',
  RailPaymentSettled: 'solstice.rail.payment.settled/1',
  RailPaymentRejected: 'solstice.rail.payment.rejected/1',
  RailPaymentReturned: 'solstice.rail.payment.returned/1',
  RailProviderDegraded: 'solstice.rail.provider.degraded/1',
  RailReconciliationMismatch: 'solstice.rail.reconciliation.mismatch/1',
  CardCreated: 'solstice.card.created/1',
  CardActivated: 'solstice.card.activated/1',
  CardFrozen: 'solstice.card.frozen/1',
  CardUnfrozen: 'solstice.card.unfrozen/1',
  CardClosed: 'solstice.card.closed/1',
  CardAuthorizationApproved: 'solstice.card.authorization.approved/1',
  CardAuthorizationDeclined: 'solstice.card.authorization.declined/1',
  CardAuthorizationReversed: 'solstice.card.authorization.reversed/1',
  CardClearingReceived: 'solstice.card.clearing.received/1',
  CardTransactionSettled: 'solstice.card.transaction.settled/1',
  CardRefundReceived: 'solstice.card.refund.received/1',
  CardDisputeOpened: 'solstice.card.dispute.opened/1',
  CardDisputeDecided: 'solstice.card.dispute.decided/1',
  EconomicGraphNodeCreated: 'solstice.economic_graph.node.created/1',
  EconomicGraphFactUpdated: 'solstice.economic_graph.fact.updated/1',
  EconomicGraphRelationshipCreated: 'solstice.economic_graph.relationship.created/1',
  EconomicGraphSnapshotCreated: 'solstice.economic_graph.snapshot.created/1',
  EconomicGraphOpportunityCreated: 'solstice.economic_graph.opportunity.created/1',
  WalletProvisioningRequested: 'solstice.wallet.provisioning.requested/1',
  WalletProvisioningStepUpRequired: 'solstice.wallet.provisioning.step_up_required/1',
  WalletTokenActivated: 'solstice.wallet.token.activated/1',
  WalletTokenSuspended: 'solstice.wallet.token.suspended/1',
  WalletTokenDeleted: 'solstice.wallet.token.deleted/1',
  AcceptanceDeviceRegistered: 'solstice.acceptance.device.registered/1',
  AcceptanceSessionCreated: 'solstice.acceptance.session.created/1',
  AcceptancePaymentApproved: 'solstice.acceptance.payment.approved/1',
  AcceptancePaymentDeclined: 'solstice.acceptance.payment.declined/1',
  AcceptancePaymentSettled: 'solstice.acceptance.payment.settled/1',
  AcceptanceReconciliationMismatch: 'solstice.acceptance.reconciliation.mismatch/1',
  TreasuryLiquidityReserved: 'solstice.treasury.liquidity.reserved/1',
  TreasuryLiquidityReleased: 'solstice.treasury.liquidity.released/1',
  TreasuryLiquidityCommitted: 'solstice.treasury.liquidity.committed/1',
  TreasuryRouteSelected: 'solstice.treasury.route.selected/1',
  TreasuryProviderRestricted: 'solstice.treasury.provider.restricted/1',
  TreasuryCorridorHalted: 'solstice.treasury.corridor.halted/1',
  TreasuryExposureElevated: 'solstice.treasury.exposure.elevated/1',
  TreasuryRebalanceProposed: 'solstice.treasury.rebalance.proposed/1',
  TreasuryReconciliationMismatch: 'solstice.treasury.reconciliation.mismatch/1',
} as const;

export const EVENT_NAMESPACES_BY_TYPE: {
  readonly [K in ImplementedEventTypeName]: ImplementedEventNamespace;
} = {
  AccountOpened: 'account',
  DepositPosted: 'ledger',
  WithdrawalPosted: 'ledger',
  InternalTransferPosted: 'ledger',
  CustomerStatusChanged: 'customer',
  KernelDecisionRecorded: 'kernel',
  PolicyPackActivated: 'policy',
  PolicyPackRetired: 'policy',
  PolicyReviewRequested: 'policy',
  PolicyReviewDecided: 'policy',
  KeyCreated: 'security',
  KeyRotated: 'security',
  KeyRetired: 'security',
  KeyRevoked: 'security',
  IdentityCreated: 'identity',
  IdentityActivated: 'identity',
  IdentitySuspended: 'identity',
  IdentityKycUpdated: 'identity',
  IdentitySessionCreated: 'identity',
  IdentitySessionRevoked: 'identity',
  IdentityDeviceRegistered: 'identity',
  IdentityDeviceTrustChanged: 'identity',
  IdentityRecoveryRequested: 'identity',
  BeneficiaryCreated: 'payment',
  PaymentInitiated: 'payment',
  PaymentHeld: 'payment',
  PaymentSubmitted: 'payment',
  PaymentSettled: 'payment',
  PaymentFailed: 'payment',
  PaymentReturned: 'payment',
  PaymentCancelled: 'payment',
  FxQuoteCreated: 'fx',
  FxQuoteAccepted: 'fx',
  FxQuoteExpired: 'fx',
  HoldCreated: 'banking',
  HoldReleased: 'banking',
  HoldCaptured: 'banking',
  HoldCancelled: 'banking',
  StatementGenerated: 'banking',
  ReconciliationMismatch: 'banking',
  AccountPositionChanged: 'account',
  FeePosted: 'banking',
  InterestPosted: 'banking',
  ReversalPosted: 'banking',
  PendingSettlementInitiated: 'banking',
  PendingSettlementSettled: 'banking',
  PendingSettlementReturned: 'banking',
  ComplianceScreeningCompleted: 'compliance',
  ComplianceScreeningReviewRequired: 'compliance',
  ComplianceCaseOpened: 'compliance',
  ComplianceCaseDecided: 'compliance',
  ComplianceAlertCreated: 'compliance',
  FraudRiskEvaluated: 'fraud',
  RailSubmissionCreated: 'rail',
  RailSubmissionAccepted: 'rail',
  RailSubmissionUnknown: 'rail',
  RailPaymentProcessing: 'rail',
  RailPaymentSettled: 'rail',
  RailPaymentRejected: 'rail',
  RailPaymentReturned: 'rail',
  RailProviderDegraded: 'rail',
  RailReconciliationMismatch: 'rail',
  CardCreated: 'card',
  CardActivated: 'card',
  CardFrozen: 'card',
  CardUnfrozen: 'card',
  CardClosed: 'card',
  CardAuthorizationApproved: 'card',
  CardAuthorizationDeclined: 'card',
  CardAuthorizationReversed: 'card',
  CardClearingReceived: 'card',
  CardTransactionSettled: 'card',
  CardRefundReceived: 'card',
  CardDisputeOpened: 'card',
  CardDisputeDecided: 'card',
  EconomicGraphNodeCreated: 'economic_graph',
  EconomicGraphFactUpdated: 'economic_graph',
  EconomicGraphRelationshipCreated: 'economic_graph',
  EconomicGraphSnapshotCreated: 'economic_graph',
  EconomicGraphOpportunityCreated: 'economic_graph',
  WalletProvisioningRequested: 'wallet',
  WalletProvisioningStepUpRequired: 'wallet',
  WalletTokenActivated: 'wallet',
  WalletTokenSuspended: 'wallet',
  WalletTokenDeleted: 'wallet',
  AcceptanceDeviceRegistered: 'acceptance',
  AcceptanceSessionCreated: 'acceptance',
  AcceptancePaymentApproved: 'acceptance',
  AcceptancePaymentDeclined: 'acceptance',
  AcceptancePaymentSettled: 'acceptance',
  AcceptanceReconciliationMismatch: 'acceptance',
  TreasuryLiquidityReserved: 'treasury',
  TreasuryLiquidityReleased: 'treasury',
  TreasuryLiquidityCommitted: 'treasury',
  TreasuryRouteSelected: 'treasury',
  TreasuryProviderRestricted: 'treasury',
  TreasuryCorridorHalted: 'treasury',
  TreasuryExposureElevated: 'treasury',
  TreasuryRebalanceProposed: 'treasury',
  TreasuryReconciliationMismatch: 'treasury',
};

export function schemaRefFor(eventType: string, version: number): string {
  const known = EVENT_SCHEMA_REFS[eventType as ImplementedEventTypeName];
  if (known && version === 1) {
    return known;
  }
  const ns = EVENT_NAMESPACES_BY_TYPE[eventType as ImplementedEventTypeName] ?? 'unknown';
  return `solstice.${ns}.${camelToSnake(eventType)}/${version}`;
}

function camelToSnake(value: string): string {
  return value
    .replace(/([a-z0-9])([A-Z])/g, '$1_$2')
    .replace(/([A-Z])([A-Z][a-z])/g, '$1_$2')
    .toLowerCase();
}
