/**
 * Canonical event namespace / taxonomy.
 *
 * Implemented namespaces match functionality that exists on this tree.
 * Reserved namespaces are documented only — they do not invent product
 * behavior.
 */

export const IMPLEMENTED_EVENT_NAMESPACES = [
  'customer',
  'account',
  'ledger',
  'kernel',
  'evidence',
  'policy',
  'security',
  'identity',
  'payment',
  'fx',
  'banking',
  'compliance',
  'fraud',
  'rail',
  'card',
  'economic_graph',
  'wallet',
  'acceptance',
  'mandate',
  'growth',
  'economic_value',
  'treasury',
  'investment',
  'regulatory',
  'risk',
  'model',
  'data',
  'strategy',
  'capital_mesh',
  'consent',
  'clean_room',
  'sunrey_coin',
  'information_market',
  'oracle',
  'sunrey_chain',
  'exchange',
  'custody',
  'surveillance',
  'workflow',
  'job',
  'provider',
  'webhook',
] as const;

export const RESERVED_EVENT_NAMESPACES = [
  'agent',
  'pyr',
  'notification',
  'analytics',
] as const;

export type ImplementedEventNamespace = (typeof IMPLEMENTED_EVENT_NAMESPACES)[number];
export type ReservedEventNamespace = (typeof RESERVED_EVENT_NAMESPACES)[number];

export const EVENT_TYPE_NAMES = [
  'AccountOpened',
  'AccountActivated',
  'AccountRestricted',
  'AccountClosed',
  'CustomerActivityRecorded',
  'DepositPosted',
  'WithdrawalPosted',
  'InternalTransferPosted',
  'CustomerStatusChanged',
  'KernelDecisionRecorded',
  'PolicyPackActivated',
  'PolicyPackRetired',
  'PolicyReviewRequested',
  'PolicyReviewDecided',
  'KeyCreated',
  'KeyRotated',
  'KeyRetired',
  'KeyRevoked',
  'IdentityCreated',
  'IdentityActivated',
  'IdentitySuspended',
  'IdentityKycUpdated',
  'IdentitySessionCreated',
  'IdentitySessionRevoked',
  'IdentityDeviceRegistered',
  'IdentityDeviceTrustChanged',
  'IdentityRecoveryRequested',
  'IdentitySecurityRecorded',
  'BeneficiaryCreated',
  'PaymentInitiated',
  'PaymentHeld',
  'PaymentSubmitted',
  'PaymentSettled',
  'PaymentFailed',
  'PaymentReturned',
  'PaymentCancelled',
  'FxQuoteCreated',
  'FxQuoteAccepted',
  'FxQuoteExpired',
  'HoldCreated',
  'HoldReleased',
  'HoldCaptured',
  'HoldCancelled',
  'StatementGenerated',
  'ReconciliationMismatch',
  'AccountPositionChanged',
  'FeePosted',
  'InterestPosted',
  'ReversalPosted',
  'PendingSettlementInitiated',
  'PendingSettlementSettled',
  'PendingSettlementReturned',
  'ComplianceScreeningCompleted',
  'ComplianceScreeningReviewRequired',
  'ComplianceCaseOpened',
  'ComplianceCaseDecided',
  'ComplianceAlertCreated',
  'FraudRiskEvaluated',
  'RailSubmissionCreated',
  'RailSubmissionAccepted',
  'RailSubmissionUnknown',
  'RailPaymentProcessing',
  'RailPaymentSettled',
  'RailPaymentRejected',
  'RailPaymentReturned',
  'RailProviderDegraded',
  'RailReconciliationMismatch',
  'CardCreated',
  'CardActivated',
  'CardFrozen',
  'CardUnfrozen',
  'CardClosed',
  'CardAuthorizationApproved',
  'CardAuthorizationDeclined',
  'CardAuthorizationReversed',
  'CardClearingReceived',
  'CardTransactionSettled',
  'CardRefundReceived',
  'CardDisputeOpened',
  'CardDisputeDecided',
  'EconomicGraphNodeCreated',
  'EconomicGraphFactUpdated',
  'EconomicGraphRelationshipCreated',
  'EconomicGraphSnapshotCreated',
  'EconomicGraphOpportunityCreated',
  'WalletProvisioningRequested',
  'WalletProvisioningStepUpRequired',
  'WalletTokenActivated',
  'WalletTokenSuspended',
  'WalletTokenDeleted',
  'AcceptanceDeviceRegistered',
  'AcceptanceSessionCreated',
  'AcceptancePaymentApproved',
  'AcceptancePaymentDeclined',
  'AcceptancePaymentSettled',
  'AcceptanceReconciliationMismatch',
  'MandateDraftCreated',
  'MandateConfirmed',
  'MandateActivated',
  'MandatePaused',
  'MandateRevoked',
  'GrowthCycleStarted',
  'GrowthPlanCreated',
  'GrowthPlanStale',
  'GrowthActionProposed',
  'EconomicValueSnapshotCreated',
  'EconomicValueDimensionChanged',
  'EconomicValueAttributionRecorded',
  'EconomicValueGoalProgressUpdated',
  'EconomicValueModelActivated',

  'TreasuryLiquidityReserved',
  'TreasuryLiquidityReleased',
  'TreasuryLiquidityCommitted',
  'TreasuryRouteSelected',
  'TreasuryProviderRestricted',
  'TreasuryCorridorHalted',
  'TreasuryExposureElevated',
  'TreasuryRebalanceProposed',
  'TreasuryReconciliationMismatch',
  'InvestmentAccountOpened',
  'InvestmentCashFunded',
  'InvestmentCashWithdrawn',
  'InvestmentOrderCreated',
  'InvestmentOrderAccepted',
  'InvestmentOrderPartiallyFilled',
  'InvestmentOrderFilled',
  'InvestmentOrderCancelled',
  'InvestmentPositionChanged',
  'InvestmentSettlementCompleted',
  'InvestmentDividendReceived',
  'InvestmentReconciliationMismatch',
  'RegulatoryTwinScenarioCreated',
  'RegulatoryTwinRunCompleted',
  'RegulatoryTwinImpactDetected',
  'RegulatoryTwinInvariantFailed',
  'RegulatoryTwinReadinessAssessed',
  'RiskAssessmentCompleted',
  'RiskLimitBreached',
  'RiskPortfolioSnapshotCreated',
  'RiskStressCompleted',
  'ModelRegistered',
  'ModelVersionCreated',
  'ModelValidated',
  'ModelApprovedForSimulation',
  'ModelRetired',
  'DataVaultCreated',
  'DataVaultAssetIngested',
  'DataVaultAssetVersioned',
  'DataVaultAssetDeleted',
  'DataVaultAccessAllowed',
  'DataVaultAccessDenied',
  'DataVaultExportCreated',
  'DataVaultDerivationCreated',
  'DataVaultKeyRotated',
  'StrategyCreated',
  'StrategyCompiled',
  'StrategyBacktestStarted',
  'StrategyBacktestCompleted',
  'StrategyValidationFailed',
  'StrategyShadowApproved',
  'StrategyShadowStarted',
  'StrategyPaperApproved',
  'StrategyPaperStarted',
  'StrategyPaperHalted',
  'StrategyRetired',
  'CapitalMeshRunStarted',
  'CapitalMeshThesisCreated',
  'CapitalMeshCandidateCreated',
  'CapitalMeshReviewCompleted',
  'CapitalMeshVetoApplied',
  'CapitalMeshProposalCreated',
  'CapitalMeshProposalStale',
  'ConsentDraftCreated',
  'ConsentGranted',
  'ConsentRevoked',
  'ConsentExpired',
  'ConsentSuperseded',
  'ConsentPermitIssued',
  'ConsentAccessDenied',
  'ConsentPurposeVersioned',
  'CleanRoomSessionCreated',
  'CleanRoomSessionAuthorized',
  'CleanRoomSessionDenied',
  'CleanRoomJobStarted',
  'CleanRoomJobCompleted',
  'CleanRoomJobFailed',
  'CleanRoomEgressReleased',
  'CleanRoomEgressSuppressed',
  'CleanRoomEgressDenied',
  'CleanRoomContributionRecorded',
  'SunReyCoinContributionEvaluated',
  'SunReyCoinIssuanceProposed',
  'SunReyCoinIssued',
  'SunReyCoinTransferCompleted',
  'SunReyCoinBurned',
  'SunReyCoinSupplyReconciled',
  'SunReyCoinReconciliationMismatch',
  'InformationMarketRequestPublished',
  'InformationMarketOpportunityOffered',
  'InformationMarketOpportunityAccepted',
  'InformationMarketContributionAuthorized',
  'InformationMarketContributionCompleted',
  'InformationMarketCompensationPending',
  'InformationMarketCompensationSettled',
  'InformationMarketRequestClosed',
  'OracleAttestationIssued',
  'OracleAttestationExpired',
  'ProofOfContributionCreated',
  'SunReyChainIntentCreated',
  'SunReyChainOperationSubmitted',
  'SunReyChainOperationUnknown',
  'SunReyChainOperationFinalized',
  'SunReyChainAnchorRecorded',
  'SunReyChainAnchorReorgObserved',
  'SunReyChainReconciliationMismatch',
  'SunReyChainHealthDegraded',
  'ExchangeAccountCreated',
  'ExchangeOrderAccepted',
  'ExchangeOrderOpened',
  'ExchangeOrderPartiallyFilled',
  'ExchangeOrderFilled',
  'ExchangeOrderCancelled',
  'ExchangeTradeMatched',
  'ExchangeTradeSettled',
  'ExchangeMarketHalted',
  'ExchangeMarketResumed',
  'ExchangeReconciliationMismatch',
  'ExchangeListingDecided',
  'CustodyDepositNoticeReceived',
  'CustodyDepositCredited',
  'CustodyDestinationAdded',
  'CustodyWithdrawalBlocked',
  'CustodyWithdrawalUnknown',
  'CustodyWithdrawalSettled',
  'SurveillanceAlertRaised',
  'SurveillanceCaseOpened',
  'WorkflowStarted',
  'WorkflowCompleted',
  'WorkflowFailed',
  'JobEnqueued',
  'JobDeadLettered',
  'ProviderWebhookAccepted',
  'ProviderWebhookRejected',
  'OutboundWebhookDelivered',
  'OutboundWebhookFailed',
] as const;

export type ImplementedEventTypeName = (typeof EVENT_TYPE_NAMES)[number];

export const EVENT_SCHEMA_REFS = {
  AccountOpened: 'solstice.account.opened/1',
  AccountActivated: 'solstice.account.activated/1',
  AccountRestricted: 'solstice.account.restricted/1',
  AccountClosed: 'solstice.account.closed/1',
  CustomerActivityRecorded: 'solstice.account.activity.recorded/1',
  DepositPosted: 'solstice.ledger.deposit_posted/1',
  WithdrawalPosted: 'solstice.ledger.withdrawal_posted/1',
  InternalTransferPosted: 'solstice.ledger.internal_transfer_posted/1',
  CustomerStatusChanged: 'solstice.customer.status_changed/1',
  KernelDecisionRecorded: 'solstice.kernel.decision_recorded/1',
  PolicyPackActivated: 'solstice.policy.pack_activated/1',
  PolicyPackRetired: 'solstice.policy.pack_retired/1',
  PolicyReviewRequested: 'solstice.policy.review_requested/1',
  PolicyReviewDecided: 'solstice.policy.review_decided/1',
  KeyCreated: 'solstice.security.key_created/1',
  KeyRotated: 'solstice.security.key_rotated/1',
  KeyRetired: 'solstice.security.key_retired/1',
  KeyRevoked: 'solstice.security.key_revoked/1',
  IdentityCreated: 'solstice.identity.created/1',
  IdentityActivated: 'solstice.identity.activated/1',
  IdentitySuspended: 'solstice.identity.suspended/1',
  IdentityKycUpdated: 'solstice.identity.kyc.updated/1',
  IdentitySessionCreated: 'solstice.identity.session.created/1',
  IdentitySessionRevoked: 'solstice.identity.session.revoked/1',
  IdentityDeviceRegistered: 'solstice.identity.device.registered/1',
  IdentityDeviceTrustChanged: 'solstice.identity.device.trust_changed/1',
  IdentityRecoveryRequested: 'solstice.identity.recovery.requested/1',
  IdentitySecurityRecorded: 'solstice.identity.security.recorded/1',
  BeneficiaryCreated: 'solstice.payment.beneficiary.created/1',
  PaymentInitiated: 'solstice.payment.initiated/1',
  PaymentHeld: 'solstice.payment.held/1',
  PaymentSubmitted: 'solstice.payment.submitted/1',
  PaymentSettled: 'solstice.payment.settled/1',
  PaymentFailed: 'solstice.payment.failed/1',
  PaymentReturned: 'solstice.payment.returned/1',
  PaymentCancelled: 'solstice.payment.cancelled/1',
  FxQuoteCreated: 'solstice.fx.quote.created/1',
  FxQuoteAccepted: 'solstice.fx.quote.accepted/1',
  FxQuoteExpired: 'solstice.fx.quote.expired/1',
  HoldCreated: 'solstice.banking.hold.created/1',
  HoldReleased: 'solstice.banking.hold.released/1',
  HoldCaptured: 'solstice.banking.hold.captured/1',
  HoldCancelled: 'solstice.banking.hold.cancelled/1',
  StatementGenerated: 'solstice.banking.statement.generated/1',
  ReconciliationMismatch: 'solstice.banking.reconciliation.mismatch/1',
  AccountPositionChanged: 'solstice.account.position.changed/1',
  FeePosted: 'solstice.banking.fee.posted/1',
  InterestPosted: 'solstice.banking.interest.posted/1',
  ReversalPosted: 'solstice.banking.reversal.posted/1',
  PendingSettlementInitiated: 'solstice.banking.pending.initiated/1',
  PendingSettlementSettled: 'solstice.banking.pending.settled/1',
  PendingSettlementReturned: 'solstice.banking.pending.returned/1',
  ComplianceScreeningCompleted: 'solstice.compliance.screening.completed/1',
  ComplianceScreeningReviewRequired: 'solstice.compliance.screening.review_required/1',
  ComplianceCaseOpened: 'solstice.compliance.case.opened/1',
  ComplianceCaseDecided: 'solstice.compliance.case.decided/1',
  ComplianceAlertCreated: 'solstice.compliance.alert.created/1',
  FraudRiskEvaluated: 'solstice.fraud.risk.evaluated/1',
  RailSubmissionCreated: 'solstice.rail.submission.created/1',
  RailSubmissionAccepted: 'solstice.rail.submission.accepted/1',
  RailSubmissionUnknown: 'solstice.rail.submission.unknown/1',
  RailPaymentProcessing: 'solstice.rail.payment.processing/1',
  RailPaymentSettled: 'solstice.rail.payment.settled/1',
  RailPaymentRejected: 'solstice.rail.payment.rejected/1',
  RailPaymentReturned: 'solstice.rail.payment.returned/1',
  RailProviderDegraded: 'solstice.rail.provider.degraded/1',
  RailReconciliationMismatch: 'solstice.rail.reconciliation.mismatch/1',
  CardCreated: 'solstice.card.created/1',
  CardActivated: 'solstice.card.activated/1',
  CardFrozen: 'solstice.card.frozen/1',
  CardUnfrozen: 'solstice.card.unfrozen/1',
  CardClosed: 'solstice.card.closed/1',
  CardAuthorizationApproved: 'solstice.card.authorization.approved/1',
  CardAuthorizationDeclined: 'solstice.card.authorization.declined/1',
  CardAuthorizationReversed: 'solstice.card.authorization.reversed/1',
  CardClearingReceived: 'solstice.card.clearing.received/1',
  CardTransactionSettled: 'solstice.card.transaction.settled/1',
  CardRefundReceived: 'solstice.card.refund.received/1',
  CardDisputeOpened: 'solstice.card.dispute.opened/1',
  CardDisputeDecided: 'solstice.card.dispute.decided/1',
  EconomicGraphNodeCreated: 'solstice.economic_graph.node.created/1',
  EconomicGraphFactUpdated: 'solstice.economic_graph.fact.updated/1',
  EconomicGraphRelationshipCreated: 'solstice.economic_graph.relationship.created/1',
  EconomicGraphSnapshotCreated: 'solstice.economic_graph.snapshot.created/1',
  EconomicGraphOpportunityCreated: 'solstice.economic_graph.opportunity.created/1',
  WalletProvisioningRequested: 'solstice.wallet.provisioning.requested/1',
  WalletProvisioningStepUpRequired: 'solstice.wallet.provisioning.step_up_required/1',
  WalletTokenActivated: 'solstice.wallet.token.activated/1',
  WalletTokenSuspended: 'solstice.wallet.token.suspended/1',
  WalletTokenDeleted: 'solstice.wallet.token.deleted/1',
  AcceptanceDeviceRegistered: 'solstice.acceptance.device.registered/1',
  AcceptanceSessionCreated: 'solstice.acceptance.session.created/1',
  AcceptancePaymentApproved: 'solstice.acceptance.payment.approved/1',
  AcceptancePaymentDeclined: 'solstice.acceptance.payment.declined/1',
  AcceptancePaymentSettled: 'solstice.acceptance.payment.settled/1',
  AcceptanceReconciliationMismatch: 'solstice.acceptance.reconciliation.mismatch/1',
  MandateDraftCreated: 'solstice.mandate.draft_created/1',
  MandateConfirmed: 'solstice.mandate.confirmed/1',
  MandateActivated: 'solstice.mandate.activated/1',
  MandatePaused: 'solstice.mandate.paused/1',
  MandateRevoked: 'solstice.mandate.revoked/1',
  GrowthCycleStarted: 'solstice.growth.cycle_started/1',
  GrowthPlanCreated: 'solstice.growth.plan_created/1',
  GrowthPlanStale: 'solstice.growth.plan_stale/1',
  GrowthActionProposed: 'solstice.growth.action_proposed/1',
  EconomicValueSnapshotCreated: 'solstice.economic_value.snapshot_created/1',
  EconomicValueDimensionChanged: 'solstice.economic_value.dimension_changed/1',
  EconomicValueAttributionRecorded: 'solstice.economic_value.attribution_recorded/1',
  EconomicValueGoalProgressUpdated: 'solstice.economic_value.goal_progress_updated/1',
  EconomicValueModelActivated: 'solstice.economic_value.model_activated/1',

  TreasuryLiquidityReserved: 'solstice.treasury.liquidity.reserved/1',
  TreasuryLiquidityReleased: 'solstice.treasury.liquidity.released/1',
  TreasuryLiquidityCommitted: 'solstice.treasury.liquidity.committed/1',
  TreasuryRouteSelected: 'solstice.treasury.route.selected/1',
  TreasuryProviderRestricted: 'solstice.treasury.provider.restricted/1',
  TreasuryCorridorHalted: 'solstice.treasury.corridor.halted/1',
  TreasuryExposureElevated: 'solstice.treasury.exposure.elevated/1',
  TreasuryRebalanceProposed: 'solstice.treasury.rebalance.proposed/1',
  TreasuryReconciliationMismatch: 'solstice.treasury.reconciliation.mismatch/1',
  InvestmentAccountOpened: 'solstice.investment.account.opened/1',
  InvestmentCashFunded: 'solstice.investment.cash.funded/1',
  InvestmentCashWithdrawn: 'solstice.investment.cash.withdrawn/1',
  InvestmentOrderCreated: 'solstice.investment.order.created/1',
  InvestmentOrderAccepted: 'solstice.investment.order.accepted/1',
  InvestmentOrderPartiallyFilled: 'solstice.investment.order.partially_filled/1',
  InvestmentOrderFilled: 'solstice.investment.order.filled/1',
  InvestmentOrderCancelled: 'solstice.investment.order.cancelled/1',
  InvestmentPositionChanged: 'solstice.investment.position.changed/1',
  InvestmentSettlementCompleted: 'solstice.investment.settlement.completed/1',
  InvestmentDividendReceived: 'solstice.investment.dividend.received/1',
  InvestmentReconciliationMismatch: 'solstice.investment.reconciliation.mismatch/1',
  RegulatoryTwinScenarioCreated: 'solstice.regulatory.scenario_created/1',
  RegulatoryTwinRunCompleted: 'solstice.regulatory.run_completed/1',
  RegulatoryTwinImpactDetected: 'solstice.regulatory.impact_detected/1',
  RegulatoryTwinInvariantFailed: 'solstice.regulatory.invariant_failed/1',
  RegulatoryTwinReadinessAssessed: 'solstice.regulatory.readiness_assessed/1',
  RiskAssessmentCompleted: 'solstice.risk.assessment.completed/1',
  RiskLimitBreached: 'solstice.risk.limit.breached/1',
  RiskPortfolioSnapshotCreated: 'solstice.risk.portfolio.snapshot.created/1',
  RiskStressCompleted: 'solstice.risk.stress.completed/1',
  ModelRegistered: 'solstice.model.registered/1',
  ModelVersionCreated: 'solstice.model.version.created/1',
  ModelValidated: 'solstice.model.validated/1',
  ModelApprovedForSimulation: 'solstice.model.approved_for_simulation/1',
  ModelRetired: 'solstice.model.retired/1',
  DataVaultCreated: 'solstice.data.vault.created/1',
  DataVaultAssetIngested: 'solstice.data.asset.ingested/1',
  DataVaultAssetVersioned: 'solstice.data.asset.versioned/1',
  DataVaultAssetDeleted: 'solstice.data.asset.deleted/1',
  DataVaultAccessAllowed: 'solstice.data.access.allowed/1',
  DataVaultAccessDenied: 'solstice.data.access.denied/1',
  DataVaultExportCreated: 'solstice.data.export.created/1',
  DataVaultDerivationCreated: 'solstice.data.derivation.created/1',
  DataVaultKeyRotated: 'solstice.data.key.rotated/1',
  StrategyCreated: 'solstice.strategy.created/1',
  StrategyCompiled: 'solstice.strategy.compiled/1',
  StrategyBacktestStarted: 'solstice.strategy.backtest.started/1',
  StrategyBacktestCompleted: 'solstice.strategy.backtest.completed/1',
  StrategyValidationFailed: 'solstice.strategy.validation.failed/1',
  StrategyShadowApproved: 'solstice.strategy.shadow.approved/1',
  StrategyShadowStarted: 'solstice.strategy.shadow.started/1',
  StrategyPaperApproved: 'solstice.strategy.paper.approved/1',
  StrategyPaperStarted: 'solstice.strategy.paper.started/1',
  StrategyPaperHalted: 'solstice.strategy.paper.halted/1',
  StrategyRetired: 'solstice.strategy.retired/1',
  CapitalMeshRunStarted: 'solstice.capital_mesh.run.started/1',
  CapitalMeshThesisCreated: 'solstice.capital_mesh.thesis.created/1',
  CapitalMeshCandidateCreated: 'solstice.capital_mesh.candidate.created/1',
  CapitalMeshReviewCompleted: 'solstice.capital_mesh.review.completed/1',
  CapitalMeshVetoApplied: 'solstice.capital_mesh.veto.applied/1',
  CapitalMeshProposalCreated: 'solstice.capital_mesh.proposal.created/1',
  CapitalMeshProposalStale: 'solstice.capital_mesh.proposal.stale/1',
  ConsentDraftCreated: 'solstice.consent.draft.created/1',
  ConsentGranted: 'solstice.consent.granted/1',
  ConsentRevoked: 'solstice.consent.revoked/1',
  ConsentExpired: 'solstice.consent.expired/1',
  ConsentSuperseded: 'solstice.consent.superseded/1',
  ConsentPermitIssued: 'solstice.consent.permit.issued/1',
  ConsentAccessDenied: 'solstice.consent.access.denied/1',
  ConsentPurposeVersioned: 'solstice.consent.purpose.versioned/1',
  CleanRoomSessionCreated: 'solstice.clean_room.session.created/1',
  CleanRoomSessionAuthorized: 'solstice.clean_room.session.authorized/1',
  CleanRoomSessionDenied: 'solstice.clean_room.session.denied/1',
  CleanRoomJobStarted: 'solstice.clean_room.job.started/1',
  CleanRoomJobCompleted: 'solstice.clean_room.job.completed/1',
  CleanRoomJobFailed: 'solstice.clean_room.job.failed/1',
  CleanRoomEgressReleased: 'solstice.clean_room.egress.released/1',
  CleanRoomEgressSuppressed: 'solstice.clean_room.egress.suppressed/1',
  CleanRoomEgressDenied: 'solstice.clean_room.egress.denied/1',
  CleanRoomContributionRecorded: 'solstice.clean_room.contribution.recorded/1',
  SunReyCoinContributionEvaluated: 'solstice.sunrey_coin.contribution.evaluated/1',
  SunReyCoinIssuanceProposed: 'solstice.sunrey_coin.issuance.proposed/1',
  SunReyCoinIssued: 'solstice.sunrey_coin.issued/1',
  SunReyCoinTransferCompleted: 'solstice.sunrey_coin.transfer.completed/1',
  SunReyCoinBurned: 'solstice.sunrey_coin.burned/1',
  SunReyCoinSupplyReconciled: 'solstice.sunrey_coin.supply.reconciled/1',
  SunReyCoinReconciliationMismatch: 'solstice.sunrey_coin.reconciliation.mismatch/1',
  InformationMarketRequestPublished: 'solstice.information_market.request.published/1',
  InformationMarketOpportunityOffered: 'solstice.information_market.opportunity.offered/1',
  InformationMarketOpportunityAccepted: 'solstice.information_market.opportunity.accepted/1',
  InformationMarketContributionAuthorized: 'solstice.information_market.contribution.authorized/1',
  InformationMarketContributionCompleted: 'solstice.information_market.contribution.completed/1',
  InformationMarketCompensationPending: 'solstice.information_market.compensation.pending/1',
  InformationMarketCompensationSettled: 'solstice.information_market.compensation.settled/1',
  InformationMarketRequestClosed: 'solstice.information_market.request.closed/1',
  SunReyChainIntentCreated: 'solstice.sunrey_chain.intent.created/1',
  SunReyChainOperationSubmitted: 'solstice.sunrey_chain.operation.submitted/1',
  SunReyChainOperationUnknown: 'solstice.sunrey_chain.operation.unknown/1',
  SunReyChainOperationFinalized: 'solstice.sunrey_chain.operation.finalized/1',
  SunReyChainAnchorRecorded: 'solstice.sunrey_chain.anchor.recorded/1',
  SunReyChainAnchorReorgObserved: 'solstice.sunrey_chain.anchor.reorg_observed/1',
  SunReyChainReconciliationMismatch: 'solstice.sunrey_chain.reconciliation.mismatch/1',
  SunReyChainHealthDegraded: 'solstice.sunrey_chain.health.degraded/1',
  OracleAttestationIssued: 'solstice.oracle.attestation.issued/1',
  OracleAttestationExpired: 'solstice.oracle.attestation.expired/1',
  ProofOfContributionCreated: 'solstice.information_market.proof_of_contribution.created/1',
  ExchangeAccountCreated: 'solstice.exchange.account.created/1',
  ExchangeOrderAccepted: 'solstice.exchange.order.accepted/1',
  ExchangeOrderOpened: 'solstice.exchange.order.opened/1',
  ExchangeOrderPartiallyFilled: 'solstice.exchange.order.partially_filled/1',
  ExchangeOrderFilled: 'solstice.exchange.order.filled/1',
  ExchangeOrderCancelled: 'solstice.exchange.order.cancelled/1',
  ExchangeTradeMatched: 'solstice.exchange.trade.matched/1',
  ExchangeTradeSettled: 'solstice.exchange.trade.settled/1',
  ExchangeMarketHalted: 'solstice.exchange.market.halted/1',
  ExchangeMarketResumed: 'solstice.exchange.market.resumed/1',
  ExchangeReconciliationMismatch: 'solstice.exchange.reconciliation.mismatch/1',
  ExchangeListingDecided: 'solstice.exchange.listing.decided/1',
  CustodyDepositNoticeReceived: 'solstice.custody.deposit.notice_received/1',
  CustodyDepositCredited: 'solstice.custody.deposit.credited/1',
  CustodyDestinationAdded: 'solstice.custody.destination.added/1',
  CustodyWithdrawalBlocked: 'solstice.custody.withdrawal.blocked/1',
  CustodyWithdrawalUnknown: 'solstice.custody.withdrawal.unknown/1',
  CustodyWithdrawalSettled: 'solstice.custody.withdrawal.settled/1',
  SurveillanceAlertRaised: 'solstice.surveillance.alert.raised/1',
  SurveillanceCaseOpened: 'solstice.surveillance.case.opened/1',
  WorkflowStarted: 'solstice.workflow.started/1',
  WorkflowCompleted: 'solstice.workflow.completed/1',
  WorkflowFailed: 'solstice.workflow.failed/1',
  JobEnqueued: 'solstice.job.enqueued/1',
  JobDeadLettered: 'solstice.job.dead_lettered/1',
  ProviderWebhookAccepted: 'solstice.provider.webhook.accepted/1',
  ProviderWebhookRejected: 'solstice.provider.webhook.rejected/1',
  OutboundWebhookDelivered: 'solstice.webhook.outbound.delivered/1',
  OutboundWebhookFailed: 'solstice.webhook.outbound.failed/1',
} as const;

export const EVENT_NAMESPACES_BY_TYPE: {
  readonly [K in ImplementedEventTypeName]: ImplementedEventNamespace;
} = {
  AccountOpened: 'account',
  AccountActivated: 'account',
  AccountRestricted: 'account',
  AccountClosed: 'account',
  CustomerActivityRecorded: 'account',
  DepositPosted: 'ledger',
  WithdrawalPosted: 'ledger',
  InternalTransferPosted: 'ledger',
  CustomerStatusChanged: 'customer',
  KernelDecisionRecorded: 'kernel',
  PolicyPackActivated: 'policy',
  PolicyPackRetired: 'policy',
  PolicyReviewRequested: 'policy',
  PolicyReviewDecided: 'policy',
  KeyCreated: 'security',
  KeyRotated: 'security',
  KeyRetired: 'security',
  KeyRevoked: 'security',
  IdentityCreated: 'identity',
  IdentityActivated: 'identity',
  IdentitySuspended: 'identity',
  IdentityKycUpdated: 'identity',
  IdentitySessionCreated: 'identity',
  IdentitySessionRevoked: 'identity',
  IdentityDeviceRegistered: 'identity',
  IdentityDeviceTrustChanged: 'identity',
  IdentityRecoveryRequested: 'identity',
  IdentitySecurityRecorded: 'identity',
  BeneficiaryCreated: 'payment',
  PaymentInitiated: 'payment',
  PaymentHeld: 'payment',
  PaymentSubmitted: 'payment',
  PaymentSettled: 'payment',
  PaymentFailed: 'payment',
  PaymentReturned: 'payment',
  PaymentCancelled: 'payment',
  FxQuoteCreated: 'fx',
  FxQuoteAccepted: 'fx',
  FxQuoteExpired: 'fx',
  HoldCreated: 'banking',
  HoldReleased: 'banking',
  HoldCaptured: 'banking',
  HoldCancelled: 'banking',
  StatementGenerated: 'banking',
  ReconciliationMismatch: 'banking',
  AccountPositionChanged: 'account',
  FeePosted: 'banking',
  InterestPosted: 'banking',
  ReversalPosted: 'banking',
  PendingSettlementInitiated: 'banking',
  PendingSettlementSettled: 'banking',
  PendingSettlementReturned: 'banking',
  ComplianceScreeningCompleted: 'compliance',
  ComplianceScreeningReviewRequired: 'compliance',
  ComplianceCaseOpened: 'compliance',
  ComplianceCaseDecided: 'compliance',
  ComplianceAlertCreated: 'compliance',
  FraudRiskEvaluated: 'fraud',
  RailSubmissionCreated: 'rail',
  RailSubmissionAccepted: 'rail',
  RailSubmissionUnknown: 'rail',
  RailPaymentProcessing: 'rail',
  RailPaymentSettled: 'rail',
  RailPaymentRejected: 'rail',
  RailPaymentReturned: 'rail',
  RailProviderDegraded: 'rail',
  RailReconciliationMismatch: 'rail',
  CardCreated: 'card',
  CardActivated: 'card',
  CardFrozen: 'card',
  CardUnfrozen: 'card',
  CardClosed: 'card',
  CardAuthorizationApproved: 'card',
  CardAuthorizationDeclined: 'card',
  CardAuthorizationReversed: 'card',
  CardClearingReceived: 'card',
  CardTransactionSettled: 'card',
  CardRefundReceived: 'card',
  CardDisputeOpened: 'card',
  CardDisputeDecided: 'card',
  EconomicGraphNodeCreated: 'economic_graph',
  EconomicGraphFactUpdated: 'economic_graph',
  EconomicGraphRelationshipCreated: 'economic_graph',
  EconomicGraphSnapshotCreated: 'economic_graph',
  EconomicGraphOpportunityCreated: 'economic_graph',
  WalletProvisioningRequested: 'wallet',
  WalletProvisioningStepUpRequired: 'wallet',
  WalletTokenActivated: 'wallet',
  WalletTokenSuspended: 'wallet',
  WalletTokenDeleted: 'wallet',
  AcceptanceDeviceRegistered: 'acceptance',
  AcceptanceSessionCreated: 'acceptance',
  AcceptancePaymentApproved: 'acceptance',
  AcceptancePaymentDeclined: 'acceptance',
  AcceptancePaymentSettled: 'acceptance',
  AcceptanceReconciliationMismatch: 'acceptance',
  MandateDraftCreated: 'mandate',
  MandateConfirmed: 'mandate',
  MandateActivated: 'mandate',
  MandatePaused: 'mandate',
  MandateRevoked: 'mandate',
  GrowthCycleStarted: 'growth',
  GrowthPlanCreated: 'growth',
  GrowthPlanStale: 'growth',
  GrowthActionProposed: 'growth',
  EconomicValueSnapshotCreated: 'economic_value',
  EconomicValueDimensionChanged: 'economic_value',
  EconomicValueAttributionRecorded: 'economic_value',
  EconomicValueGoalProgressUpdated: 'economic_value',
  EconomicValueModelActivated: 'economic_value',

  TreasuryLiquidityReserved: 'treasury',
  TreasuryLiquidityReleased: 'treasury',
  TreasuryLiquidityCommitted: 'treasury',
  TreasuryRouteSelected: 'treasury',
  TreasuryProviderRestricted: 'treasury',
  TreasuryCorridorHalted: 'treasury',
  TreasuryExposureElevated: 'treasury',
  TreasuryRebalanceProposed: 'treasury',
  TreasuryReconciliationMismatch: 'treasury',
  InvestmentAccountOpened: 'investment',
  InvestmentCashFunded: 'investment',
  InvestmentCashWithdrawn: 'investment',
  InvestmentOrderCreated: 'investment',
  InvestmentOrderAccepted: 'investment',
  InvestmentOrderPartiallyFilled: 'investment',
  InvestmentOrderFilled: 'investment',
  InvestmentOrderCancelled: 'investment',
  InvestmentPositionChanged: 'investment',
  InvestmentSettlementCompleted: 'investment',
  InvestmentDividendReceived: 'investment',
  InvestmentReconciliationMismatch: 'investment',
  RegulatoryTwinScenarioCreated: 'regulatory',
  RegulatoryTwinRunCompleted: 'regulatory',
  RegulatoryTwinImpactDetected: 'regulatory',
  RegulatoryTwinInvariantFailed: 'regulatory',
  RegulatoryTwinReadinessAssessed: 'regulatory',
  RiskAssessmentCompleted: 'risk',
  RiskLimitBreached: 'risk',
  RiskPortfolioSnapshotCreated: 'risk',
  RiskStressCompleted: 'risk',
  ModelRegistered: 'model',
  ModelVersionCreated: 'model',
  ModelValidated: 'model',
  ModelApprovedForSimulation: 'model',
  ModelRetired: 'model',
  DataVaultCreated: 'data',
  DataVaultAssetIngested: 'data',
  DataVaultAssetVersioned: 'data',
  DataVaultAssetDeleted: 'data',
  DataVaultAccessAllowed: 'data',
  DataVaultAccessDenied: 'data',
  DataVaultExportCreated: 'data',
  DataVaultDerivationCreated: 'data',
  DataVaultKeyRotated: 'data',
  StrategyCreated: 'strategy',
  StrategyCompiled: 'strategy',
  StrategyBacktestStarted: 'strategy',
  StrategyBacktestCompleted: 'strategy',
  StrategyValidationFailed: 'strategy',
  StrategyShadowApproved: 'strategy',
  StrategyShadowStarted: 'strategy',
  StrategyPaperApproved: 'strategy',
  StrategyPaperStarted: 'strategy',
  StrategyPaperHalted: 'strategy',
  StrategyRetired: 'strategy',
  CapitalMeshRunStarted: 'capital_mesh',
  CapitalMeshThesisCreated: 'capital_mesh',
  CapitalMeshCandidateCreated: 'capital_mesh',
  CapitalMeshReviewCompleted: 'capital_mesh',
  CapitalMeshVetoApplied: 'capital_mesh',
  CapitalMeshProposalCreated: 'capital_mesh',
  CapitalMeshProposalStale: 'capital_mesh',
  ConsentDraftCreated: 'consent',
  ConsentGranted: 'consent',
  ConsentRevoked: 'consent',
  ConsentExpired: 'consent',
  ConsentSuperseded: 'consent',
  ConsentPermitIssued: 'consent',
  ConsentAccessDenied: 'consent',
  ConsentPurposeVersioned: 'consent',
  CleanRoomSessionCreated: 'clean_room',
  CleanRoomSessionAuthorized: 'clean_room',
  CleanRoomSessionDenied: 'clean_room',
  CleanRoomJobStarted: 'clean_room',
  CleanRoomJobCompleted: 'clean_room',
  CleanRoomJobFailed: 'clean_room',
  CleanRoomEgressReleased: 'clean_room',
  CleanRoomEgressSuppressed: 'clean_room',
  CleanRoomEgressDenied: 'clean_room',
  CleanRoomContributionRecorded: 'clean_room',
  SunReyCoinContributionEvaluated: 'sunrey_coin',
  SunReyCoinIssuanceProposed: 'sunrey_coin',
  SunReyCoinIssued: 'sunrey_coin',
  SunReyCoinTransferCompleted: 'sunrey_coin',
  SunReyCoinBurned: 'sunrey_coin',
  SunReyCoinSupplyReconciled: 'sunrey_coin',
  SunReyCoinReconciliationMismatch: 'sunrey_coin',
  InformationMarketRequestPublished: 'information_market',
  InformationMarketOpportunityOffered: 'information_market',
  InformationMarketOpportunityAccepted: 'information_market',
  InformationMarketContributionAuthorized: 'information_market',
  InformationMarketContributionCompleted: 'information_market',
  InformationMarketCompensationPending: 'information_market',
  InformationMarketCompensationSettled: 'information_market',
  InformationMarketRequestClosed: 'information_market',
  OracleAttestationIssued: 'oracle',
  OracleAttestationExpired: 'oracle',
  ProofOfContributionCreated: 'information_market',
  SunReyChainIntentCreated: 'sunrey_chain',
  SunReyChainOperationSubmitted: 'sunrey_chain',
  SunReyChainOperationUnknown: 'sunrey_chain',
  SunReyChainOperationFinalized: 'sunrey_chain',
  SunReyChainAnchorRecorded: 'sunrey_chain',
  SunReyChainAnchorReorgObserved: 'sunrey_chain',
  SunReyChainReconciliationMismatch: 'sunrey_chain',
  SunReyChainHealthDegraded: 'sunrey_chain',
  ExchangeAccountCreated: 'exchange',
  ExchangeOrderAccepted: 'exchange',
  ExchangeOrderOpened: 'exchange',
  ExchangeOrderPartiallyFilled: 'exchange',
  ExchangeOrderFilled: 'exchange',
  ExchangeOrderCancelled: 'exchange',
  ExchangeTradeMatched: 'exchange',
  ExchangeTradeSettled: 'exchange',
  ExchangeMarketHalted: 'exchange',
  ExchangeMarketResumed: 'exchange',
  ExchangeReconciliationMismatch: 'exchange',
  ExchangeListingDecided: 'exchange',
  CustodyDepositNoticeReceived: 'custody',
  CustodyDepositCredited: 'custody',
  CustodyDestinationAdded: 'custody',
  CustodyWithdrawalBlocked: 'custody',
  CustodyWithdrawalUnknown: 'custody',
  CustodyWithdrawalSettled: 'custody',
  SurveillanceAlertRaised: 'surveillance',
  SurveillanceCaseOpened: 'surveillance',
  WorkflowStarted: 'workflow',
  WorkflowCompleted: 'workflow',
  WorkflowFailed: 'workflow',
  JobEnqueued: 'job',
  JobDeadLettered: 'job',
  ProviderWebhookAccepted: 'provider',
  ProviderWebhookRejected: 'provider',
  OutboundWebhookDelivered: 'webhook',
  OutboundWebhookFailed: 'webhook',
};

export const HISTORICAL_EVENT_SCHEMA_PREFIX = 'solstice.' as const;
export const CANONICAL_EVENT_SCHEMA_PREFIX = 'sunrey.' as const;

export function schemaRefFor(eventType: string, version: number): string {
  const known = EVENT_SCHEMA_REFS[eventType as ImplementedEventTypeName];
  if (known && version === 1) {
    return known;
  }
  const ns = EVENT_NAMESPACES_BY_TYPE[eventType as ImplementedEventTypeName] ?? 'unknown';
  return `${CANONICAL_EVENT_SCHEMA_PREFIX}${ns}.${camelToSnake(eventType)}/${version}`;
}

export type EventSchemaRefProjection = {
  readonly storedSchemaRef: string;
  readonly historicalPrefix: boolean;
  readonly displayBrand: 'SunRey';
};

export function projectEventSchemaRef(schemaRef: string): EventSchemaRefProjection {
  return Object.freeze({
    storedSchemaRef: schemaRef,
    historicalPrefix: schemaRef.startsWith(HISTORICAL_EVENT_SCHEMA_PREFIX),
    displayBrand: 'SunRey',
  });
}

function camelToSnake(value: string): string {
  return value
    .replace(/([a-z0-9])([A-Z])/g, '$1_$2')
    .replace(/([A-Z])([A-Z][a-z])/g, '$1_$2')
    .toLowerCase();
}
