export const WAVE4_ECONOMIC_AWARENESS_FABRIC_CAPABILITY = Object.freeze({
  capabilityId: 'sunrey-economic-awareness-fabric',
  wave: 4,
  schemaVersion: 'sunrey.economic-awareness-fabric.v1',
  environment: 'simulation' as const,
  mayObserve: true,
  mayIngest: true,
  mayNormalize: true,
  mayEnrich: true,
  mayCorrelate: true,
  mayResolveEntities: true,
  mayCalculateConfidence: true,
  mayDetectDuplicates: true,
  mayBuildEvidence: true,
  mayProposeVerifiedFacts: true,
  mayProposeClaims: true,
  mayIssueSunRey: false,
  mayIssueMoonRey: false,
  mayBurnSupply: false,
  mayModifyBlockchainBalances: false,
  mayApproveMonetaryGovernance: false,
  maySetMarketPrice: false,
  mayChangeMonetaryPolicy: false,
});
