/**
 * Wave 2 Prompt 8 — macroeconomic and government-economic-data catalog entries.
 *
 * Partial population of config/providers/free-api-catalog.yaml for the macro
 * subset. These are real public APIs documented in official provider docs;
 * they are not invented capabilities.
 */

import type { CatalogProviderEntry } from '../../../provider-sdk/src/catalog/types.ts';

function macroProvider(
  overrides: Partial<CatalogProviderEntry> & Pick<CatalogProviderEntry, 'provider_id' | 'name' | 'short_name' | 'description'>,
): CatalogProviderEntry {
  const base: CatalogProviderEntry = {
    provider_id: overrides.provider_id,
    name: overrides.name,
    short_name: overrides.short_name,
    description: overrides.description,
    primary_category: 'macroeconomics',
    capabilities: ['macroeconomic_indicators', 'economic_indicators'],
    endpoints: {
      base_url: null,
      api_version: null,
      documentation_url: null,
      status_url: null,
    },
    authentication: {
      type: 'none',
      required: false,
      registration_required: false,
      environment_variable: null,
      notes: null,
    },
    access: {
      status: 'verified_free',
      free_tier_verified: true,
      registration_required: false,
      notes: null,
    },
    commercial_use: {
      status: 'verified_allowed',
      notes: null,
    },
    redistribution: {
      status: 'allowed',
      notes: null,
    },
    rate_limits: {
      documented: false,
      requests_per_second: null,
      requests_per_minute: null,
      requests_per_hour: null,
      requests_per_day: null,
      monthly_quota: null,
      concurrency_limit: null,
      notes: null,
    },
    data_characteristics: {
      freshness: 'daily',
      geographic_scope: ['US'],
      historical_data: true,
      realtime: false,
      data_format: 'json',
      notes: null,
    },
    sunrey: {
      domain: ['world', 'grow', 'financial_agent'],
      canonical_provider_interface: 'MacroDataProvider',
      priority: 'high',
      launch_tier: 'production_candidate',
      authority_class: 'authoritative_official',
      integration_state: 'adapter_implemented',
      existing_adapter: null,
    },
    verification: {
      status: 'verified',
      verified_against_official_docs: true,
      last_verified: '2026-08-30',
      notes: 'Wave 2 Prompt 8 macro subset.',
    },
    ...overrides,
  };
  return Object.freeze(base);
}

export const MACRO_CATALOG_PROVIDER_IDS = [
  'fred',
  'world-bank',
  'econdb',
  'us-treasury-fiscaldata',
  'data-usa',
  'census-gov',
  'saudi-open-data',
  'usaspending',
  'federal-register',
] as const;

export type MacroCatalogProviderId = (typeof MACRO_CATALOG_PROVIDER_IDS)[number];

export const MACRO_CATALOG_ENTRIES: readonly CatalogProviderEntry[] = Object.freeze([
  macroProvider({
    provider_id: 'fred',
    name: 'Federal Reserve Economic Data (FRED)',
    short_name: 'FRED',
    description:
      'Official U.S. macroeconomic time series from the Federal Reserve Bank of St. Louis including GDP, CPI, unemployment, and interest rates.',
    capabilities: [
      'macroeconomic_indicators',
      'economic_indicators',
      'inflation',
      'employment',
      'interest_rates',
      'gdp',
    ],
    endpoints: {
      base_url: 'https://api.stlouisfed.org/fred',
      api_version: 'v1',
      documentation_url: 'https://fred.stlouisfed.org/docs/api/fred/',
      status_url: 'https://fred.stlouisfed.org/',
    },
    authentication: {
      type: 'api_key',
      required: true,
      registration_required: true,
      environment_variable: 'FRED_API_KEY',
      notes: 'Free API key from FRED account registration.',
    },
    rate_limits: {
      documented: true,
      requests_per_second: null,
      requests_per_minute: null,
      requests_per_hour: null,
      requests_per_day: null,
      monthly_quota: null,
      concurrency_limit: null,
      notes: 'Documented rate limits apply per FRED API key.',
    },
    data_characteristics: {
      freshness: 'daily',
      geographic_scope: ['US'],
      historical_data: true,
      realtime: false,
      data_format: 'json',
      notes: 'Series update frequency varies by indicator.',
    },
    sunrey: {
      domain: ['world', 'grow', 'financial_agent', 'economic_graph'],
      canonical_provider_interface: 'MacroDataProvider',
      priority: 'critical',
      launch_tier: 'production_candidate',
      authority_class: 'authoritative_official',
      integration_state: 'adapter_implemented',
      existing_adapter: 'packages/sunrey-chain/src/macro/adapters/fred.ts',
    },
  }),
  macroProvider({
    provider_id: 'world-bank',
    name: 'World Bank Open Data API',
    short_name: 'World Bank',
    description:
      'Global development indicators including GDP, population, employment, and fiscal statistics across countries.',
    capabilities: [
      'macroeconomic_indicators',
      'economic_indicators',
      'gdp',
      'employment',
      'government_statistics',
    ],
    primary_category: 'macroeconomics',
    endpoints: {
      base_url: 'https://api.worldbank.org',
      api_version: 'v2',
      documentation_url: 'https://datahelpdesk.worldbank.org/knowledgebase/articles/889392',
      status_url: 'https://data.worldbank.org/',
    },
    authentication: {
      type: 'none',
      required: false,
      registration_required: false,
      environment_variable: null,
      notes: null,
    },
    data_characteristics: {
      freshness: 'historical',
      geographic_scope: ['GLOBAL'],
      historical_data: true,
      realtime: false,
      data_format: 'json',
      notes: 'Most indicators are annual or quarterly.',
    },
    sunrey: {
      domain: ['world', 'grow', 'financial_agent'],
      canonical_provider_interface: 'MacroDataProvider',
      priority: 'critical',
      launch_tier: 'production_candidate',
      authority_class: 'authoritative_official',
      integration_state: 'adapter_implemented',
      existing_adapter: 'packages/sunrey-chain/src/macro/adapters/world-bank.ts',
    },
  }),
  macroProvider({
    provider_id: 'econdb',
    name: 'Econdb',
    short_name: 'Econdb',
    description: 'Aggregated macroeconomic indicators from multiple official sources.',
    capabilities: ['macroeconomic_indicators', 'economic_indicators', 'inflation', 'gdp'],
    primary_category: 'macroeconomics',
    endpoints: {
      base_url: 'https://www.econdb.com/api',
      api_version: 'v1',
      documentation_url: 'https://www.econdb.com/api/docs/',
      status_url: null,
    },
    authentication: {
      type: 'api_key',
      required: true,
      registration_required: true,
      environment_variable: 'ECONDB_API_KEY',
      notes: 'API key required for most endpoints.',
    },
    commercial_use: {
      status: 'unclear',
      notes: 'Commercial terms require review before production activation.',
    },
    data_characteristics: {
      freshness: 'daily',
      geographic_scope: ['GLOBAL'],
      historical_data: true,
      realtime: false,
      data_format: 'json',
      notes: 'Aggregator; authority class is derived_data.',
    },
    sunrey: {
      domain: ['world', 'grow'],
      canonical_provider_interface: 'MacroDataProvider',
      priority: 'medium',
      launch_tier: 'secondary_source',
      authority_class: 'derived_data',
      integration_state: 'adapter_implemented',
      existing_adapter: 'packages/sunrey-chain/src/macro/adapters/econdb.ts',
    },
    verification: {
      status: 'partially_verified',
      verified_against_official_docs: false,
      last_verified: '2026-08-30',
      notes: 'Commercial use unclear; production activation blocked pending review.',
    },
  }),
  macroProvider({
    provider_id: 'us-treasury-fiscaldata',
    name: 'U.S. Treasury FiscalData',
    short_name: 'Treasury FiscalData',
    description: 'U.S. Treasury fiscal data including debt, interest rates, and government spending.',
    capabilities: ['macroeconomic_indicators', 'interest_rates', 'treasury_data', 'fiscal_data'],
    endpoints: {
      base_url: 'https://api.fiscaldata.treasury.gov',
      api_version: 'v1',
      documentation_url: 'https://fiscaldata.treasury.gov/api-documentation/',
      status_url: 'https://fiscaldata.treasury.gov/',
    },
    authentication: {
      type: 'none',
      required: false,
      registration_required: false,
      environment_variable: null,
      notes: null,
    },
    data_characteristics: {
      freshness: 'daily',
      geographic_scope: ['US'],
      historical_data: true,
      realtime: false,
      data_format: 'json',
      notes: 'Treasury yield and debt series update daily.',
    },
    sunrey: {
      domain: ['world', 'grow', 'financial_agent'],
      canonical_provider_interface: 'MacroDataProvider',
      priority: 'high',
      launch_tier: 'production_candidate',
      authority_class: 'authoritative_official',
      integration_state: 'adapter_implemented',
      existing_adapter: 'packages/sunrey-chain/src/macro/adapters/us-treasury-fiscaldata.ts',
    },
  }),
  macroProvider({
    provider_id: 'data-usa',
    name: 'Data USA',
    short_name: 'Data USA',
    description: 'U.S. government open data aggregator for demographics and economic indicators.',
    capabilities: ['macroeconomic_indicators', 'economic_indicators', 'government_statistics'],
    primary_category: 'government_open_data',
    endpoints: {
      base_url: 'https://datausa.io/api',
      api_version: null,
      documentation_url: 'https://datausa.io/about/api/',
      status_url: null,
    },
    authentication: {
      type: 'none',
      required: false,
      registration_required: false,
      environment_variable: null,
      notes: null,
    },
    data_characteristics: {
      freshness: 'historical',
      geographic_scope: ['US'],
      historical_data: true,
      realtime: false,
      data_format: 'json',
      notes: null,
    },
    sunrey: {
      domain: ['world', 'grow'],
      canonical_provider_interface: 'MacroDataProvider',
      priority: 'medium',
      launch_tier: 'secondary_source',
      authority_class: 'derived_data',
      integration_state: 'adapter_implemented',
      existing_adapter: 'packages/sunrey-chain/src/macro/adapters/data-usa.ts',
    },
  }),
  macroProvider({
    provider_id: 'census-gov',
    name: 'U.S. Census Bureau API',
    short_name: 'Census',
    description: 'U.S. Census demographic and economic statistics including population and household data.',
    capabilities: ['macroeconomic_indicators', 'government_statistics', 'economic_indicators'],
    primary_category: 'government_open_data',
    endpoints: {
      base_url: 'https://api.census.gov/data',
      api_version: null,
      documentation_url: 'https://www.census.gov/data/developers/data-sets.html',
      status_url: null,
    },
    authentication: {
      type: 'api_key',
      required: true,
      registration_required: true,
      environment_variable: 'CENSUS_API_KEY',
      notes: 'Free API key from Census developer registration.',
    },
    data_characteristics: {
      freshness: 'historical',
      geographic_scope: ['US'],
      historical_data: true,
      realtime: false,
      data_format: 'json',
      notes: 'Population and demographic series.',
    },
    sunrey: {
      domain: ['world', 'grow', 'economic_graph'],
      canonical_provider_interface: 'MacroDataProvider',
      priority: 'high',
      launch_tier: 'production_candidate',
      authority_class: 'authoritative_official',
      integration_state: 'adapter_implemented',
      existing_adapter: 'packages/sunrey-chain/src/macro/adapters/census-gov.ts',
    },
  }),
  macroProvider({
    provider_id: 'saudi-open-data',
    name: 'Saudi Open Data Portal',
    short_name: 'Saudi Open Data',
    description: 'Saudi Arabia government open datasets including economic and demographic indicators.',
    capabilities: ['macroeconomic_indicators', 'government_statistics', 'economic_indicators'],
    primary_category: 'government_open_data',
    endpoints: {
      base_url: 'https://data.gov.sa',
      api_version: null,
      documentation_url: 'https://data.gov.sa/en/About',
      status_url: null,
    },
    authentication: {
      type: 'none',
      required: false,
      registration_required: false,
      environment_variable: null,
      notes: null,
    },
    data_characteristics: {
      freshness: 'historical',
      geographic_scope: ['SA'],
      historical_data: true,
      realtime: false,
      data_format: 'json',
      notes: 'Saudi Arabia ISO 3166-1 alpha-2: SA.',
    },
    sunrey: {
      domain: ['world', 'grow'],
      canonical_provider_interface: 'MacroDataProvider',
      priority: 'medium',
      launch_tier: 'secondary_source',
      authority_class: 'authoritative_official',
      integration_state: 'adapter_implemented',
      existing_adapter: 'packages/sunrey-chain/src/macro/adapters/saudi-open-data.ts',
    },
    verification: {
      status: 'partially_verified',
      verified_against_official_docs: false,
      last_verified: '2026-08-30',
      notes: 'API surface partially verified; some datasets may require portal registration.',
    },
  }),
  macroProvider({
    provider_id: 'usaspending',
    name: 'USAspending.gov',
    short_name: 'USAspending',
    description: 'U.S. federal spending, awards, and fiscal transparency data.',
    capabilities: ['fiscal_data', 'public_spending', 'government_statistics'],
    primary_category: 'government_open_data',
    endpoints: {
      base_url: 'https://api.usaspending.gov',
      api_version: null,
      documentation_url: 'https://api.usaspending.gov/docs/',
      status_url: 'https://www.usaspending.gov/',
    },
    authentication: {
      type: 'none',
      required: false,
      registration_required: false,
      environment_variable: null,
      notes: null,
    },
    data_characteristics: {
      freshness: 'daily',
      geographic_scope: ['US'],
      historical_data: true,
      realtime: false,
      data_format: 'json',
      notes: 'Federal spending and obligation data.',
    },
    sunrey: {
      domain: ['world', 'grow', 'research'],
      canonical_provider_interface: 'MacroDataProvider',
      priority: 'medium',
      launch_tier: 'production_candidate',
      authority_class: 'authoritative_official',
      integration_state: 'adapter_implemented',
      existing_adapter: 'packages/sunrey-chain/src/macro/adapters/usaspending.ts',
    },
  }),
  macroProvider({
    provider_id: 'federal-register',
    name: 'Federal Register API',
    short_name: 'Federal Register',
    description: 'U.S. federal regulatory documents including economic policy notices and rules.',
    capabilities: ['government_statistics', 'fiscal_data'],
    primary_category: 'government_open_data',
    endpoints: {
      base_url: 'https://www.federalregister.gov/api/v1',
      api_version: 'v1',
      documentation_url: 'https://www.federalregister.gov/reader-aids/developer-resources/rest-api',
      status_url: null,
    },
    authentication: {
      type: 'none',
      required: false,
      registration_required: false,
      environment_variable: null,
      notes: null,
    },
    data_characteristics: {
      freshness: 'daily',
      geographic_scope: ['US'],
      historical_data: true,
      realtime: false,
      data_format: 'json',
      notes: 'Regulatory documents; economically relevant policy notices.',
    },
    sunrey: {
      domain: ['world', 'research', 'financial_agent'],
      canonical_provider_interface: 'MacroDataProvider',
      priority: 'low',
      launch_tier: 'fallback_source',
      authority_class: 'authoritative_official',
      integration_state: 'adapter_implemented',
      existing_adapter: 'packages/sunrey-chain/src/macro/adapters/federal-register.ts',
    },
  }),
]);
