/**
 * Refresh schedule entries for macro provider capabilities.
 */

import type { RefreshScheduleEntry } from '../../../sunrey-chain/src/provider-runtime/data-delivery/types.ts';
import { CANONICAL_INDICATORS } from './indicator-mapping.ts';

export const MACRO_REFRESH_SCHEDULES: readonly RefreshScheduleEntry[] = Object.freeze([
  Object.freeze({
    scheduleId: 'macro-fred-cpi-daily',
    providerId: 'fred',
    capability: 'macroeconomic_indicators',
    resourceId: CANONICAL_INDICATORS.US_CPI,
    intervalMs: 86_400_000,
    jitterMs: 120_000,
    priority: 5,
    enabled: true,
    maxRuntimeMs: 120_000,
  }),
  Object.freeze({
    scheduleId: 'macro-fred-gdp-weekly',
    providerId: 'fred',
    capability: 'gdp',
    resourceId: CANONICAL_INDICATORS.US_GDP,
    intervalMs: 604_800_000,
    jitterMs: 180_000,
    priority: 8,
    enabled: true,
    maxRuntimeMs: 180_000,
  }),
  Object.freeze({
    scheduleId: 'macro-world-bank-gdp-weekly',
    providerId: 'world-bank',
    capability: 'macroeconomic_indicators',
    resourceId: CANONICAL_INDICATORS.GLOBAL_GDP,
    intervalMs: 604_800_000,
    jitterMs: 240_000,
    priority: 10,
    enabled: true,
    maxRuntimeMs: 180_000,
  }),
  Object.freeze({
    scheduleId: 'macro-treasury-yields-daily',
    providerId: 'us-treasury-fiscaldata',
    capability: 'interest_rates',
    resourceId: CANONICAL_INDICATORS.US_TREASURY_10Y,
    intervalMs: 86_400_000,
    jitterMs: 90_000,
    priority: 6,
    enabled: true,
    maxRuntimeMs: 90_000,
  }),
  Object.freeze({
    scheduleId: 'macro-econdb-cpi-daily',
    providerId: 'econdb',
    capability: 'inflation',
    resourceId: CANONICAL_INDICATORS.US_CPI,
    intervalMs: 86_400_000,
    jitterMs: 120_000,
    priority: 20,
    enabled: true,
    maxRuntimeMs: 120_000,
  }),
  Object.freeze({
    scheduleId: 'macro-census-population-weekly',
    providerId: 'census-gov',
    capability: 'government_statistics',
    resourceId: CANONICAL_INDICATORS.US_POPULATION,
    intervalMs: 604_800_000,
    jitterMs: 300_000,
    priority: 15,
    enabled: true,
    maxRuntimeMs: 180_000,
  }),
  Object.freeze({
    scheduleId: 'macro-saudi-gdp-weekly',
    providerId: 'saudi-open-data',
    capability: 'macroeconomic_indicators',
    resourceId: CANONICAL_INDICATORS.SA_GDP,
    intervalMs: 604_800_000,
    jitterMs: 300_000,
    priority: 25,
    enabled: true,
    maxRuntimeMs: 180_000,
  }),
  Object.freeze({
    scheduleId: 'macro-usaspending-daily',
    providerId: 'usaspending',
    capability: 'fiscal_data',
    resourceId: CANONICAL_INDICATORS.US_FEDERAL_SPENDING,
    intervalMs: 86_400_000,
    jitterMs: 120_000,
    priority: 18,
    enabled: true,
    maxRuntimeMs: 120_000,
  }),
  Object.freeze({
    scheduleId: 'macro-federal-register-daily',
    providerId: 'federal-register',
    capability: 'government_statistics',
    resourceId: 'economic_policy_documents',
    intervalMs: 86_400_000,
    jitterMs: 180_000,
    priority: 30,
    enabled: false,
    maxRuntimeMs: 90_000,
  }),
]);
