export type ValuationFailureCode =
  | 'FORBIDDEN_VALUATION_METHOD'
  | 'CLASS_METHOD_NOT_ELIGIBLE'
  | 'FORBIDDEN_VALUATION_INPUT'
  | 'PROTECTED_TRAIT_INPUT_FORBIDDEN'
  | 'PEVE_INPUT_FORBIDDEN'
  | 'HUMAN_WORTH_INPUT_FORBIDDEN'
  | 'PERSON_RANK_INPUT_FORBIDDEN'
  | 'WEALTH_MULTIPLIER_FORBIDDEN'
  | 'AI_SUBJECTIVE_SCORE_FORBIDDEN'
  | 'PERSON_LEVEL_MULTIPLIER_FORBIDDEN'
  | 'FORBIDDEN_VALUATION_FACTOR'
  | 'INPUT_NOT_TRACEABLE'
  | 'FLOAT_MONETARY_MATH_FORBIDDEN'
  | 'SUNREY_QUANTITY_FORBIDDEN'
  | 'MINT_AUTHORIZATION_FORBIDDEN'
  | 'EXECUTION_AUTHORIZATION_FORBIDDEN'
  | 'PRODUCTION_POLICY_UNAVAILABLE'
  | 'PRODUCTION_ACTIVATION_FORBIDDEN'
  | 'DUPLICATE_POLICY_VERSION'
  | 'POLICY_NOT_FOUND'
  | 'HISTORICAL_POLICY_IMMUTABLE'
  | 'INVALID_POLICY'
  | 'VALUATION_REVIEW_REQUIRED'
  | 'NO_ACTIVE_SIMULATION_POLICY'
  | 'AI_AUTHORITY_FORBIDDEN'
  | 'TAXONOMY_DOES_NOT_GRANT_ELIGIBILITY'
  | 'REFERENCE_CONFLICT';

export type ValuationFailure = {
  readonly code: ValuationFailureCode;
  readonly message: string;
};

export function valuationFailure(code: ValuationFailureCode, message: string): ValuationFailure {
  return Object.freeze({ code, message });
}
