export const OPPORTUNITY_CATEGORIES = [
  'CASH_OPTIMIZATION',
  'EMERGENCY_RESERVE',
  'RECURRING_SAVING',
  'INVESTMENT_ALLOCATION',
  'PORTFOLIO_REBALANCE',
  'DIVERSIFICATION',
  'CURRENCY_OPTIMIZATION',
  'DEBT_OPTIMIZATION',
  'GOAL_FUNDING',
  'EXPENSE_OPTIMIZATION',
  'INCOME_ALLOCATION',
] as const;

export type OpportunityCategory = (typeof OPPORTUNITY_CATEGORIES)[number];

export const OPPORTUNITY_DETECTORS = [
  'EXCESS_IDLE_CASH',
  'INSUFFICIENT_RESERVE',
  'RECURRING_SURPLUS',
  'GOAL_FUNDING_GAP',
  'PORTFOLIO_CONCENTRATION',
  'PORTFOLIO_DRIFT',
  'UNINVESTED_INVESTMENT_CASH',
  'CURRENCY_CONCENTRATION',
  'HIGH_FEES',
  'MISMATCHED_LIQUIDITY',
] as const;

export type OpportunityDetectorKind = (typeof OPPORTUNITY_DETECTORS)[number];

export const OPPORTUNITY_STATUSES = [
  'DETECTED',
  'ELIGIBLE',
  'INELIGIBLE',
  'PRESENTED',
  'DISMISSED',
  'ACCEPTED_FOR_PROPOSAL',
  'EXPIRED',
  'SUPERSEDED',
  'COMPLETED',
] as const;

export type OpportunityStatus = (typeof OPPORTUNITY_STATUSES)[number];

export const OPPORTUNITY_SOURCES = [
  'PEG',
  'LEDGER_POSITION',
  'MANDATE_GOAL',
  'PORTFOLIO_FACTS',
  'PRODUCT_CATALOG',
  'RATE_CATALOG',
] as const;

export type OpportunitySource = (typeof OPPORTUNITY_SOURCES)[number];

export const IMPACT_KINDS = [
  'KNOWN_FINANCIAL_EFFECT',
  'ESTIMATED_RANGE',
  'SCENARIO_RANGE',
  'NON_QUANTIFIED_BENEFIT',
] as const;

export type ImpactKind = (typeof IMPACT_KINDS)[number];

export const OPPORTUNITY_RISK_LEVELS = ['LOW', 'MODERATE', 'HIGH', 'UNCERTAIN_MARKET'] as const;
export type OpportunityRiskLevel = (typeof OPPORTUNITY_RISK_LEVELS)[number];

export const TIME_HORIZONS = ['IMMEDIATE', 'NEAR_TERM', 'MEDIUM_TERM', 'LONG_TERM', 'UNSPECIFIED'] as const;
export type OpportunityTimeHorizon = (typeof TIME_HORIZONS)[number];

export const LIQUIDITY_IMPACTS = ['INCREASES', 'DECREASES', 'NEUTRAL', 'UNKNOWN'] as const;
export type LiquidityImpactKind = (typeof LIQUIDITY_IMPACTS)[number];

export const OPPORTUNITY_FEED_CARDS = [
  'BUILD_EMERGENCY_RESERVE',
  'PUT_IDLE_CASH_TO_WORK',
  'PORTFOLIO_CONCENTRATED',
  'GOAL_ON_TRACK',
  'GOAL_BEHIND',
  'RECURRING_SURPLUS_DETECTED',
  'REVIEW_FEES',
  'CURRENCY_CONCENTRATION',
  'UNINVESTED_INVESTMENT_CASH',
  'MISMATCHED_LIQUIDITY',
] as const;

export type OpportunityFeedCardKind = (typeof OPPORTUNITY_FEED_CARDS)[number];

export const RANKING_VERSION = 'OPPORTUNITY_RANKING_V1' as const;

export const DETECTOR_TO_CATEGORY: Readonly<Record<OpportunityDetectorKind, OpportunityCategory>> = {
  EXCESS_IDLE_CASH: 'CASH_OPTIMIZATION',
  INSUFFICIENT_RESERVE: 'EMERGENCY_RESERVE',
  RECURRING_SURPLUS: 'RECURRING_SAVING',
  GOAL_FUNDING_GAP: 'GOAL_FUNDING',
  PORTFOLIO_CONCENTRATION: 'DIVERSIFICATION',
  PORTFOLIO_DRIFT: 'PORTFOLIO_REBALANCE',
  UNINVESTED_INVESTMENT_CASH: 'INVESTMENT_ALLOCATION',
  CURRENCY_CONCENTRATION: 'CURRENCY_OPTIMIZATION',
  HIGH_FEES: 'EXPENSE_OPTIMIZATION',
  MISMATCHED_LIQUIDITY: 'CASH_OPTIMIZATION',
};

export const DETECTOR_TO_CARD: Readonly<Record<OpportunityDetectorKind, OpportunityFeedCardKind>> = {
  EXCESS_IDLE_CASH: 'PUT_IDLE_CASH_TO_WORK',
  INSUFFICIENT_RESERVE: 'BUILD_EMERGENCY_RESERVE',
  RECURRING_SURPLUS: 'RECURRING_SURPLUS_DETECTED',
  GOAL_FUNDING_GAP: 'GOAL_BEHIND',
  PORTFOLIO_CONCENTRATION: 'PORTFOLIO_CONCENTRATED',
  PORTFOLIO_DRIFT: 'PORTFOLIO_CONCENTRATED',
  UNINVESTED_INVESTMENT_CASH: 'UNINVESTED_INVESTMENT_CASH',
  CURRENCY_CONCENTRATION: 'CURRENCY_CONCENTRATION',
  HIGH_FEES: 'REVIEW_FEES',
  MISMATCHED_LIQUIDITY: 'MISMATCHED_LIQUIDITY',
};
