export {
  DEFAULT_M11_CONFIG,
  DEFAULT_M11_FAST_MA_PERIODS,
  DEFAULT_M11_MAX_ADVERSE_EXCURSION_BPS,
  DEFAULT_M11_MAX_HOLDING_PERIOD_HOURS,
  DEFAULT_M11_MAX_OBSERVATION_AGE_MS,
  DEFAULT_M11_MAX_REALIZED_VOLATILITY_BPS,
  DEFAULT_M11_MAX_SPREAD_BPS,
  DEFAULT_M11_MIN_HISTORY_BARS,
  DEFAULT_M11_MIN_LIQUIDITY_SCORE,
  DEFAULT_M11_MIN_REALIZED_VOLATILITY_BPS,
  DEFAULT_M11_MIN_ROC_BPS,
  DEFAULT_M11_RECOMMENDED_EXPOSURE_UNITS,
  DEFAULT_M11_SLOW_MA_PERIODS,
  DEFAULT_M11_TRAILING_STOP_VOL_MULTIPLIER,
  HELIOS_M11_CAPSULE_ID,
  HELIOS_M11_FAMILY_ID,
  HELIOS_M11_RULE_ID,
  HELIOS_M11_RULE_VERSION,
  HELIOS_MULTI_ASSET_M11_COMMODITY_TREND_QUALIFIED,
  type CommodityTrendFollowingConfig,
} from './constants.ts';
export {
  evaluateCommodityTrendFollowingRule,
  HELIOS_M11_COMMODITY_TREND_FOLLOWING_V1,
  isContinuousResearchInstrument,
  isExecutableInstrumentKind,
} from './rule.ts';
export type {
  CommodityBreakoutState,
  CommodityFreshnessStatus,
  CommodityInstrumentKind,
  CommodityMarketStateLabel,
  CommodityPositionSide,
  CommodityProviderHealth,
  CommodityRollState,
  CommoditySessionState,
  CommodityTrendBar,
  CommodityTrendDecision,
  CommodityTrendDecisionAction,
  CommodityTrendDirection,
  CommodityTrendEvaluateInput,
  CommodityTrendForcedExit,
  CommodityTrendGovernance,
  CommodityTrendMarketState,
  CommodityTrendPosition,
} from './types.ts';
export {
  M11_FIXTURE_DEFAULTS,
  VALID_GOVERNANCE,
  VALID_GOVERNANCE_LONG_ONLY,
  baseGoldBar,
  baseWtiBar,
  commodityTrendEvaluationManifest,
  computeSimpleMovingAveragePriorBars,
  flatPosition,
  openLongPosition,
  openShortPosition,
  validGoldDowntrendMarket,
  validGoldUptrendMarket,
  validWtiDowntrendMarket,
  validWtiUptrendMarket,
} from './fixtures.ts';
